### ISSUE TITLE
Polish netboot so it can be used on more than minimal systems

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1026]
For Lubuntu, we want to have a live system which keeps a default install, but if a certain netboot item is selected, it should **remove** packages instead of add them.

Also, it would be good to have the selections stored in a global variable.

Lastly, it would be good to be able to specify whether the values should be checkboxes or radio buttons. For Lubuntu, we'd have the latter enabled by default.

I really don't want to have to keep and maintain a custom distro patch for this downstream, but I also wanted to seek feedback on whether I should fork netinstall upstream and make it into what I'm visioning, or if these things could be contributed (and enabled **optionally**) in the existing module.

**Comment by adriaandegroot** [comment]
The *packages* module is used to do the actual changes to the system. It supports *remove* operations, so that part is ready for you. The trick is to get the netinstall job to do the right thing.

For upstreaming, I'd split this into two PR's: one that handles the UI parts -- changing to radio buttons to handle exclusive groups, for instance -- and one that changes how packages are injected into global storage. The global storage already has a key *packageOperations* which can contain anything that the `package.conf` can contain (e.g. also supports remove operations).

**Comment by demmm** [comment]
Seems the packagechooser module does what you are looking for, you can let users select for a minimal install there.

**Comment by adriaandegroot** [comment]
Closed with "feedback timeout", though I'm pretty sure it does what was originally asked now.
