### ISSUE TITLE
Unable to install rpms from local repository using dnf from "packages" module

### ISSUE THREAD

**Issue by Akspatole** [calamares/calamares#1027]
I am using Calamares 3.2.1 for creating customized installer for a project. I have configured "dnf" as a package manager in "packages" module of Calamares.  
I am trying to install local rpms from calamares process. I have configured dnf with the local rpm repository in ISO file.  Created a bootable USB of it. 
I have booted from USB and able to install local rpm packages using "dnf -y install xxx.rpm" command through command line. But "dnf -y install xxx.rpm" command is getting failed when executed from "packages" module of calamares.

Here is the debug log of calamares,

```
10:16:06 [1]: ERROR: Installation failed: 
10:16:06 [6]: - message: "Boost.Python error in job \"packages\"." 
10:16:06 [6]: - details: "<div><strong>Command 'dnf -y install myrpm' returned non-zero exit status 1</strong></div><div>Config error: File exists: '/var/log'</div><div><br/>Traceback:</div><div><pre>File &quot;/usr/local/lib/calamares/modules/packages/main.py&quot;, line 514, in run\n    run_operations(pkgman, entry)\n\n  File &quot;/usr/local/lib/calamares/modules/packages/main.py&quot;, line 426, in run_operations\n    pkgman.install(package_list)\n\n  File &quot;/usr/local/lib/calamares/modules/packages/main.py&quot;, line 201, in install\n    check_target_env_call([&quot;dnf&quot;, &quot;-y&quot;, &quot;install&quot;] + pkgs)\n\n  File &quot;&lt;string&gt;&quot;, line 4, in &lt;module&gt;</pre></div>" 
```

Also, I tried to execute "dnf list installed" command from "shellprocess" module then also it is failing.

I observed that if "dont-chroot" is true in settings.conf of calamares then "dnf -y install myrpm" command is successful. But due to this change, grub-install command is impacted.

```
06:49:09 [6]: Target cmd: ("grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=GRUB", "--force") 
06:49:09 [6]: Target output:
Installing for x86_64-efi platform.
grub-install: error: failed to get canonical path of `/boot/efi'
```
The exec sequence in settings.conf is,
- exec
  - partition
  - mount
  - unpackfs
  - packages
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services
  - bootloader
  - umount

Am I missing any configuration change for executing "dnf" commands from "packages" module ?

**Comment by adriaandegroot** [comment]
When *dontChroot* is false (the default), then Calamares behaves as an installer -- it's working on a new disk image somewhere, generally off of a live CD. When `dontChroot` is true it's intended to be running **inside** an already installed system -- as a post-install configurator. What you need to figure out is if `dnf` is installed and actually works inside the target image after unpackfs (personally, I'd move the packages module after locale and localecfg, so that you have at least machineid, fstab and locale set up). You can use the interactiveterminal module to "pause" and mess around inside the target system.

Note that the target system does not have direct access to the live image -- so running a package manager and trying to install from the live-CD is going to be difficult.

**Comment by Akspatole** [comment]
Thanks @adriaandegroot for the information. That helped me. 

My issue is resolved. I am able to install rpms using _dnf_ from _calamares_. In my live USB, `/var/log` was linked to `/var/volatile/log` and `/var/volatile/log` was mounted as `tmpfs`. Thus _packages_ module of calamares was unable to execute _dnf_ commands in _chroot_ mode and showed `config error`. Unlinking `/var/log` fixed dnf commands execution issue.
