### ISSUE TITLE
Let user choose between linux and linux-lts package during installation

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#1029]
During calamares setup could you make a choice for users to choose either linux or linux-lts.

I am working on an  Arch Linux based distro called ArcoLinux.

Is this feature already present? 
If not can it be considered to add in future releases. 
Just these two choices can already help a few people.
The linux kernel is likely to support lesser old hardware in the future is my guess.

**Comment by philmmanjaro** [comment]
Well, this feature is distro specific. On Manjaro, for example, you can choose from more than two kernel series. Currently the feature is not present. Also you have some tools present to have more than one kernel on the ISO and select-able from the get go.

**Comment by erikdubois** [comment]
"some tools present"  - can you point me in the right direction please

**Comment by philmmanjaro** [comment]
Does your ISO already support multiple kernels to boot from or do you want to install the kernels as extra option in post-install?

**Comment by erikdubois** [comment]
If you mean, did I change anything in calamares to have these options, I think neither but I am not (yet) a calamares specialist.
Here is our config.
https://github.com/arcolinux/arcolinux-calamares

**Comment by erikdubois** [comment]
this may not be the best medium to discuss this - I really would like the users to have the possibility to choose. - any link you can provide so I can analyze

**Comment by adriaandegroot** [comment]
This kind of ties in with the (new) issue #1036, asking for a UI to make this kind of choices that don't fit in the *netinstall* view of the world.

In any case, you want to provide the user with two choices:
 - Linux
 - Linux-LTS

Then, depending on their choice, you want to do .. *something*. I don't know what that *something* is, since it depends on your distro (which you are creating). Any one or more of these items might apply:
 - Installing a package (either one or the other) which will include the kernel, update grub, etc.
 - Running a script (you can do this already with contextualprocess, but there's no UI to get the choices **in** there in the first place)
 - Doing something in Python

One good way to approach this is not to think about the UI for a moment (that's the *view step* part of this), and instead think about the *job* part: what needs to happen **specifically** for each of the choices the user can make here. As Philip points out, you need all kinds of other preparations (e.g. having Linux and Linux-LTS available somehow) even before you get to the Calamares parts.

(As for communications channels: there's IRC: `#calamares` on Freenode is where we can chat, and GitHub issues. Calamares doesn't have a mailing list or discussion forum -- I suppose you **could** try to do something via the Wiki, but that hardly seems more commuinicative than this issue).

**Comment by iqingyuan** [comment]
pacstrap linux-lts without ever installing 'linux' package
https://bbs.archlinux.org/viewtopic.php?id=170660
pacman -Sy
pacstrap /mnt $(pacman -Sqg base | sed 's/^linux$/&-lts/')

**Comment by arcolinuxz** [comment]
Can we reopen this one?
I created successfully an ArcoLinux with linux-lts.
I used the package modules to install linux-lts and lateron let mkinitcpio do its thing
This results in what I want.

Linux kernel on usb/dvd but after reboot linux-lts.

Some people actually require it to be able to work on their computers.

So the job part I get now.
But the UI part is where I will need help. 
I would like to get an extra installation page where we can add things

- different kernels to choose from (just one out of a series)
- nvidia choices to install  nvidia  nvidia-390

If user selects things on the page then do the steps in the job part.

Is there documentation, other distro's, a template I can start with?

**Comment by abucodonosor** [comment]
Why don't you use Netinstall modules for that?

**Comment by erikdubois** [comment]
Can you elaborate on that or send me a link?

**Comment by abucodonosor** [comment]
What link?

Just look at the netinstall example.

You have to create a yaml file with packages and offer it on top of the package modules.

**Comment by arcolinuxz** [comment]
Gotcha. I will take at those possibilities.

**Comment by abucodonosor** [comment]
FYI the Neinstall menu can look like this:

http://homebox.tk/cala.png

( if you wish I can give you a link to that yaml file.. so you get some idea )

Another thing is you could use it to install local packages, not over net by
having a local repository ( however that requires changes to your iso )

**Comment by arcolinuxz** [comment]
Thanks for helping out.

So this is how far I got in 4 hours.

![netinstall](https://user-images.githubusercontent.com/36679406/60389641-76919d00-9ac5-11e9-93ce-6a901df7c27d.png)



Question 1: 
Can you make it so that users can only select one kernel?

Question 2:
Can this kernel come from the iso - local_install?
People with no internet will be in trouble?

Question 3:
Can we conditionally add packages?
Like libreoffice - users will complain if it is not in French, Russian etc. so we need to add more packages to it ONLY IF they choose to install it.
I can install all languages on the iso... but that seems somewhat over the top.

**Comment by abucodonosor** [comment]
```
Question 1:
Can you make it so that users can only select one kernel?

```
No, you can't.

```
Question 2:
Can this kernel come from the iso - local_install?
People with no internet will be in trouble?

```

Yes, you can do that, with a local repository.

```
Question 3:
Can we conditionally add packages?`

```

No, that is not possible with these modules.

Packages or contextual modules could do that ( at least with languages )

```
Question 4 :
Are there distro's that use netinstall in order to compare notes?
```

No idea about other distributions.

```
Frugalware was a good example but they stopped developing.

```

Says, who?.

We didn't stop anything we just never released anything based on calamares,
that only exists on the development ISO's.

Frugalware iso won't help you much since we do _not_ use rsync ( copy of the live cd over)
at all ). We do use netinstall and install everything from packages for various reasons.

**Comment by kkofler** [comment]
Conditionally dragging in stuff is really something that should be handled by the underlying package management system. The Calamares netinstall configuration should just list a metapackage that conditionally requires other packages. But I suspect that `pacman` does not support that at this time.

**Comment by arcolinuxz** [comment]
@abucodonosor Frugalware is marked dormant on distrowatch. No iso's in the last two or more years seems to be their criteria.

**Comment by arcolinuxz** [comment]
Can we also add group installation?

Like the displaymanagers

- lightdm

- sddm

Let the user choose but behind this choice are 4-5 installation packages that will be used. The users does not need to know these packages. Just choose the displaymanager.

Is that possible?

**Comment by abucodonosor** [comment]
> @abucodonosor Frugalware is marked dormant on distrowatch. No iso's in the last two or more years seems to be their criteria.

What they say and what reality is are different things.

**Comment by abucodonosor** [comment]
Yes, you ćan have hidden ǵroup...

```
- name: "Something"
  description: "some description"
  hidden: false
  selected: true
  critical: false
  subgroups:
  - name: "some DM"
    description: "Some description"
    hidden: false
    selected: true
    critical: false
    packages:
        - something
  - name: "Always install these when that group is selected"
    description: "something"
    hidden: true
    selected: true
    critical: true
    packages:
        -  pkg1
        -  pkg2

```

**Comment by abucodonosor** [comment]
@kkofler 

pacman does support installing groups, virtual groups or package aliases.

**Comment by kkofler** [comment]
But do any of those have conditionals (e.g.: "in the langpacks-de group, if libreoffice is installed, install libreoffice-langpack-de")?

**Comment by abucodonosor** [comment]
@kkofler 

I don't think it can handle conditionals. I think only rpm can do that.

**Comment by kkofler** [comment]
The interesting thing is actually that `comps` groups (the group system Fedora uses on top of RPM) already supported conditionals years before RPM itself got support for them.

**Comment by erikdubois** [comment]
We have solved this one with netinstall.

and yes you can use language packs  @kkofler @abucodonosor 
![office-language](https://user-images.githubusercontent.com/10594806/72383442-c52e1e00-371b-11ea-99c8-93736fe5110b.png)
![libreoffice-french](https://user-images.githubusercontent.com/10594806/72383461-cbbc9580-371b-11ea-8fee-23361a87ae73.jpg)
