### ISSUE TITLE
calamares garbagge

### ISSUE THREAD

**Issue by netstat2** [calamares/calamares#1033]
-  calamares is the only installer ,that dont see my disk or partitions during installation
- I TRIED TO INSTALL GECKO and when i get to manual partitioning it shows a questionmark as  disk type and no options.  
- My disk has windows 10 alongside with 3 linux partitions installed  
- The same issue when i tried to install manjaro
 - I wonder if there is a way to change installer during installatiom
- Gparted recognised my partitions at once and all other installers i have used
- I DOWNGRADED calamares during installation with yast and it only gave disk formatting option or install to  entire disk and thats it
- calamares the plague of arch distros

**Comment by philmmanjaro** [comment]
@netstat2: seems English is not your native language. Can you be more specific what you try to achieve with this post?

**Comment by adriaandegroot** [comment]
Closing this as "not a useful bug report". Either GeckoLinux or Manjaro, downstream, should be involved first.

**Generally** when Calamares offers no devices to install to, that's because it can't figure out what could possibly be used. That occurs when partitions are mounted from the target drive, or swap is in use, or the drive is so fragmented that it can't find enough space. An explanation can be found in the `calamares.log` then. It's definitely an issue that you can even **get** to the partitioning page when there's going to be nothing selectable there -- but there is issue for it already (I think #774).
