### ISSUE TITLE
Radio Buttons For Use In Starting Menu (Lubuntu)

### ISSUE THREAD

**Issue by SBanya** [calamares/calamares#1036]
This issue is regarding radio buttons in the Calamares module, and I am asking on behalf of the Lubuntu project.

What module within the current Calamares module allows you to create radio buttons for a menu: 

i.e. Create radio buttons to allow an installation with different web browsers included based on a user's preference

Is this possible through Calamares's module, or is this only able to implemented via qt (i.e. C++ with qt, or PyQt)?

**Comment by adriaandegroot** [comment]
This question uses "module" in a way that I don't really understand.

In Calamares, a *module* is a unit of code that provides a unit of functionality. The functionality can be a *job* (doing something during installation) or a *view step* (something the user interacts with). View steps also provide jobs, to do the thing that their UI was for.

There is no "module" that provides radio buttons. Having radio buttons isn't a useful thing in and of itself -- it's a means to an end. So you seem to want to provide a "preferences" module, which would allow the user to select some software to install (e.g. a preference for one browser, or another). That would be a *view step* module, with a UI, and then a job that does the actual installation.

Currently, the netinstall module provides a UI for doing something **like** what you want. I say "like" because it doesn't sound like it matches the UI you're thinking of. It works together with the packages module to do the actual work. The example files with the netinstall module can be used to see what it's capable of.

To do a view module yourself, you'll need to use Qt; either in C++ or via PythonQt. There are various examples available, in Calamares as well as the Calamares examples repository. Personally I'd suggest C++, since that keeps  the dependency footprint of Calamares manageable. **If** you do a module yourself, do try to upstream it into the Calamares examples repository.  **If** you do a module yourself, try to get a good visual design first that is extensible enough to be usable by others.

**Comment by adriaandegroot** [comment]
Two additional thoughts:
 - a QML view step wouldn't be half bad (pro: easy to do UI; low dependencies. con: tying it together with Calamares proper will require new technologies)
 - a sufficiently-generic module might have a config file as below:

```
# Each entry corresponds to one choice. The UI displays *title*
# atop each group-box for that choice. Within the group-box,
# a radio button is shown for each item, with corresponding text
# and icon. If selected, the named package is added to the
# global packaging list (to be passed on to the packages module).
#
- title: Web Browser
  - item: firefox
    package: firefox-extra-fluffy
    icon: /usr/loca/share/ff.png
    name: Firefox
  - item: falkon
    package: falkon
    icon: /usr/local/share/falkon.png
    name: Falkon
- title: Shell
  - item: bash
  - item: ksh93
  - item: tcsh
```

**Comment by adriaandegroot** [comment]
Following up on that sketch of a config-file design:

For compatibility with *contextualprocess* each *title* block could optionally have a *variable* entry, which is set to the value of the *item* which is selected by the user. Then you can go via *packages* jobs or *contextualprocess* jobs for the actual choice.

**Comment by SBanya** [comment]
Thanks a lot for the reply! I super appreciate this. I have only coded in Python and JS so far (with HTML + CSS for webpages), so I'm a bit new to using qt, and C++ is a refresher from high school for me haha. Literally, I have been learning qt with C++ with a guide this week, so its definitely interesting how qt ideas can be applied in this situation.

I really appreciate the in-depth reply, and the Lubuntu team will definitely find this handy. Thanks so much, I'll let you know how things go, and if we can possibly provide you guys more Calamares examples, or if we truly fork it.

**Comment by adriaandegroot** [comment]
(also @wxl @tsimonq2 ) closing this one as "still unclear what's actually being asked". Elsewhere I'm mentoring someone towards producing a QML interface based on the generic configuration I've talked about.
