### ISSUE TITLE
Supper 32-bit EFI also with a 64-bit OS installer

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1039]
The EFI may be 32-bit while the system itself is 64-bit capable (e.g. Bay Trail Intel Atom machines). Calamares doesn't know that, and just installs the (single) configured EFI support. This leaves those machines unbootable after installation (Ubiquity apparently does the right thing).

Related to #971

- [ ] Find list of affected hardware
- [ ] Find out if it's possible to simulate this in VirtualBox
- [ ] Detect 32-bit EFI reliably
- [ ] Adapt `bootloader/main.py`

**Comment by wxl** [comment]
We ran into this issue in Lubuntu. By looking at /sys/firmware/efi/fw_platform_size, we could figure out the right EFI package (for us grub-efi-amd64-signed or grub-efi-ia32) package.

**Comment by mirh** [comment]
(just for the very records, fedora is also providing signed ia32 shim as of the last bunch of months)

**Comment by kkofler** [comment]
As far as I can tell, this has been supported for a long while already, see `def efi_word_size():` in `bootloader/main.py`.

**Comment by geckolinux** [comment]
Hi there, what's the current status of this feature?

I have determined that for the base OS that I use for my spin (openSUSE Leap 15.2 and Tumbleweed) there is a package that supports 32-bit UEFI, called [grub2-i386-efi](https://software.opensuse.org/package/grub2-i386-efi), and [here](https://nwrickert2.wordpress.com/2018/12/05/opensuse-tumbleweed-and-32-bit-efi/) an advanced user explains how to configure it manually for openSUSE.

Does Calamares detect this automatically and use the correct UEFI for the hardware? Or would it require creating a separate ISO specifically for 32-bit EFI systems?

**Comment by Tuxman2** [comment]
Hi,

I made the installation of Manjaro 64bit on an usb key with an uefi 32bit hardware. I used "--no-nvram" option and "--removable" option to avoid bootloader installation error.  But it required grubia32.efi who is not available during the installation of bootloader. If the grubia32.efi is not available, the installation failed. I found a way to make it possible and I can make the installation without problems. The problem come when the system is rebooted. I've got a grub error and have the following error : "No such partition. grub rescue".

**Comment by mirh** [comment]
https://archived.forum.manjaro.org/t/how-to-install-manjaro-on-the-asus-t100ta-32bit-uefi-64bit-cpu/144744
This did it for me.

**Comment by geckolinux** [comment]
Related:
https://github.com/geckolinux/geckolinux-project/issues/129

**Comment by Tuxman2** [comment]
I followed all the tutorials available in the Manjaro forum to make an usb bootable key of Manjaro 64bit for uefi 32bit. Including this one. In my case, the problem occurs during installation. And precisely when the installer tries to install the bootloader. First, if I don't modify the main.py file in /modules/bootloader/ of calamares directory available in the live-usb, I can't make the whole installation. So, I've got these errors as in the picture available here. If I add "no-nvram" and "--removable" to install Manjaro on an removable usb key to try Manjaro system, there is no problem, but another error appears during the installation of bootloader (93%), the message error is: "/boot/efi/EFI/Manjaro/grubia32.efi directory or file missing". And the installation is stoped. I found a workaround for that. I launch the installer, and then I go to /tmp directory. There, the installer creates a calamares@rootxxxx directory or something similar. I opened it with "open as root" through nautilus (I try to install Manjaro Gnome 20.2) and create the /boot/efi/EFI/Manjaro directory and I copied a grubia32.efi file in it. Like that, the installation can be done until the end. But when I restart the system, I've got the grub rescue screen with the message error: "no such partition. Grub rescue". There is something strange because I can boot on the removable usb key and launch the system if I use the live usb of Manjaro and I choose "detect efi bootloader" and launch (hd1,gptx) /boot/grub.efi. Perhaps in my case, I must install the bootloader on esp and not in /boot/efi directory ?

Sorry for this long message.

**Comment by mirh** [comment]
Mhh.. I can't really remember if I didn't have to do some extra fiddling with grub, anyhow at worst you should just have to run `grub-install`
https://wiki.archlinux.org/index.php/GRUB#Installation_2

**Comment by demmm** [comment]
This feature request is now well over 4 years old, numerous tutorials and workarounds linked, never a PR submitted, time to close.

**Comment by mirh** [comment]
Unclear how 47 months are "well over" 4 years, anyhow if this neighbourhood and "no PR" were to be the criteria for cleanup, then you could as well nuke half of the issues in this tracker.
