### ISSUE TITLE
Extending services-systemd module functionality to disable .socket systemd files

### ISSUE THREAD

**Issue by Akspatole** [calamares/calamares#1045]
Currently, we can disable `.service` and `.target` systemd files from `services-systemd` module. 
It will be great if we extend `services-systemd` module functionality to disable `.socket` systemd files.

Would like to contribute if this new feature is approved by calamares community. Please let me know your comments.

**Comment by philmmanjaro** [comment]
We should then also enable sockets to make this complete.

**Comment by Akspatole** [comment]
Yes. That will be required in cases where user needs to enable some user defined `.socket` files.
In my case, I was trying to disable `.socket` files which were not required.

**Comment by philmmanjaro** [comment]
If you add a new feature, always add it both ways, even you won't may use it yourself.

**Comment by adriaandegroot** [comment]
What @philmmanjaro says: if you add a *disable-sockets* feature, also add an enabling feature (er .. given the way the current config-file looks, I'd call it *sockets*). Any PR should also add documentation and an example to the config file. Since the module has been refactored extensively, the actual code-change to do this feature is minimal (e.g. calling `systemctl()` with relevant arguments.

**Comment by adriaandegroot** [comment]
So, closing this issue with "yes, that's a good PR to submit".
