### ISSUE TITLE
webview crashes calamares

### ISSUE THREAD

**Issue by damianatorrpm** [calamares/calamares#1051]
**Describe the bug**
Running `sudo calamares` crashes as soon as the "webview" step is reached with:
ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**To Reproduce**
Have a webview in settings.conf

**Expected behavior**
Webview shown

**Comment by adriaandegroot** [comment]
Link to crbug is not viewable. If WebEngine is being used, you might switch to WebKit instead.

Which Qt, WebEngine, and underlying Chromium version are you seeing this with, anyway?

**Comment by kkofler** [comment]
Looks like this is a new issue with QtWebEngine 5.11: https://bugreports.qt.io/browse/QTBUG-66641
A workaround is `export QTWEBENGINE_DISABLE_SANDBOX=1`. (The "fix" in that bug report was just to add that workaround to some CI configurations that are running QtWebEngine as root.)
This is the upstream commit that introduced the error: https://chromium.googlesource.com/chromium/src.git/+/aa99e0990143359527b93a52c69dc2ec1a939fb3%5E%21/
It says the error was introduced because otherwise it would just crash. What this does not tell us is why this worked in earlier versions. Something must have changed in the way the sandbox works. It is unfortunate that they make you disable the entire sandbox, **especially** in a process running as root.

**Comment by demmm** [comment]
For many, this bug can now be avoided.  QML support for modules makes using the webview module no longer needed in most cases, notesQML can do the job for webview and does not rely on QtWebengine or webkit.

**Comment by demmm** [comment]
No longer relevant since https://github.com/calamares/calamares/commit/010ab083844ec2ea4d3257b752e010610319a369
