### ISSUE TITLE
Calamares 3.2.1requires suddenly qt5-xmlpatterns

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1060]
On Arch Linux the new qt version came from testing to stable v5.12.0-1 like yesterday or so.

Yesterday I build calamares again with this [pkgbuild](https://github.com/arcolinux/arcolinux-pkgbuild-3party/blob/master/calamares-3.2.1/PKGBUILD).

I am working not with the last version but 3.2.1.

Calamares did not start and when debugging it declared it needed qt5-xmlpatterns to run.

I have added this package now to my list of packages and Calamares works again.

My question is 
1. are you aware (important for build instructions)
2. are there other packages that we now need?
3. I wonder if there is a list available of all packages needed for Calamares to work on ArchLinux?

**Comment by adriaandegroot** [comment]
>     1. are you aware (important for build instructions)

No. Nothing in Calamares specifically asks for xmlpatterns, but I do see it installed in my *Manjaro* and *KDE neon* systems. On Manjaro, Calamares links to xmlpatterns; on neon, it does not. Some digging on Manjaro shows that it's the PythonQt libraries that link to XmlPatterns.

>     2. are there other packages that we now need?

CMake will tell you if there is something optional that is missing (or required and missing). Since PythonQt isn't used except for a demo, and is optional, it shouldn't trigger anything.

>     3. I wonder if there is a list available of all packages needed for Calamares to work on ArchLinux?

No. Arch Linux derivatives should provide that themselves (e.g. through a PR to the wiki, one which will be kept up-to-date, or to `deploycala.py` which is a best-effort script to install the build-requirements for Calamares).

**Comment by arcolinuxz** [comment]
Thanks for the swift response.
