### ISSUE TITLE
Make window frame size not expand on "summary" module

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares#1062]
While the main window stays the same tsize while cycling through the module sections, when it comes to the summary section it suddenly expands in size , which makes the follow up slideshow during installation look weird.

Expected:
Instead have a right side scrollbar if summary doesnt fit on the available screen estate.

**Comment by adriaandegroot** [comment]
You're right, on resizing the slideshow gets weird.

The reason it grows, rather than providing a scrollbar, is that I spent a few days way back in september trying to get a recognizable scrollbar and got nothing. After discussion with @apachelogger we settled on this. The discussion is in #778.

I'll take another stab at re-doing scrolling in the summary widget.

**Comment by philmmanjaro** [comment]
@star-buck: Similar to #1038

**Comment by star-buck** [comment]
Fullscreen would also be awesome.

**Comment by philmmanjaro** [comment]
@star-buck: is already in the [making](https://github.com/calamares/calamares/tree/resize-control) ...

**Comment by philmmanjaro** [comment]
See here for the upcoming setting options: https://github.com/calamares/calamares/commit/2bb7a5f6869d4af44efb3ac1f188249f92ee0f07

**Comment by philmmanjaro** [comment]
@adriaandegroot: merging **resize-control** at current state creates a segmentation fault.
