### ISSUE TITLE
Booting fails with encrypted / and separate /boot

### ISSUE THREAD

**Issue by eirism** [calamares/calamares#1073]
**Describe the bug**
After installing Manjaro xfce 18.0.2 with an encrypted / partition and either encrypted and unencrypted /boot, it fails to boot.
In the case of unencrypted /boot the initramfs cannot find the decrypted root partition, and in the case of encrypted /boot the /boot partition is mounted as /new_root.

Tested in Virtualbox with 64 bit OS and BIOS.

**To Reproduce**
1. Install Manjaro with one partition for /boot (either encrypted or unencrypted) and one encrypted partition for /.
2. Boot the installation
3. See that the boot fails after GRUB.

**Expected behavior**
The installation should boot correctly.

**Additional context**
It seems that #1022 broke this, as it works Kannolo distro which was released before that change. Reverting that change in Manjaro also fixes booting.
The correct fix to #1022 might be to not set `GRUB_ENABLE_CRYPTODISK=y` if /boot is unencrypted. From what I can understand that option makes GRUB able to decrypt LUKS partitions, so removing it will make GRUB unable to try to decrypt /.

**Comment by philmmanjaro** [comment]
@eirism: please post the working `grub.cfg` and broken one. Also check `/etc/default/grub`.

**Comment by eirism** [comment]
Files are from install with unencrypted /boot and encrypted /.

Working, reverted changes done by d775cee before install:
GRUB asks for password for /. "Fancy"/(Manjaro themed) GRUB menu.
[unencrypted-boot-blkid.txt](https://github.com/calamares/calamares/files/2769942/unencrypted-boot-blkid.txt)
[unencrypted-boot-grub.cfg.txt](https://github.com/calamares/calamares/files/2769943/unencrypted-boot-grub.cfg.txt)
[unencrypted-boot-grub-default.txt](https://github.com/calamares/calamares/files/2769944/unencrypted-boot-grub-default.txt)

Not working:
GRUB does not ask for password. Plain/default GRUB menu.
[unencrypted-noboot-blkid.txt](https://github.com/calamares/calamares/files/2769947/unencrypted-noboot-blkid.txt)
[unencrypted-noboot-grub.cfg.txt](https://github.com/calamares/calamares/files/2769948/unencrypted-noboot-grub.cfg.txt)
[unencrypted-noboot-grub-default.txt](https://github.com/calamares/calamares/files/2769949/unencrypted-noboot-grub-default.txt)

**Comment by philmmanjaro** [comment]
@eirism: seems you found a regression. We should revisit this one.

**Comment by adriaandegroot** [comment]
Thanks @eirism for providing a good description of the error scenario. I'll be revisiting this this week, and have poked @ximion who provided the original patch as well.

**Comment by abucodonosor** [comment]
I didn't looked closer but if we change grub* / boot* modules that way we need change all luks* ones
and checkall  initramfs modules to to match.

I don't think the luks* key generators actually cares about /boot vs non /boot

**Comment by teacher4711** [comment]
Perhaps this is a solution.
My system: ArcoLinux

Problem:
The first boot fails if the root partition or a single /home partition is encrypted

Solution:
What makes the first boot fail is that the /crypto_keybile.bin is not present.
The line in /etc/crypttab, which specifies that there is a /crypto_keyfile.bin, has to be altered.

If you replace /crypto_keyfile.bin with 'none', the boot process does not show any errors and you have to enter a password to decrypt the encrypted partition.

I've noticed, however, that the crypto_keyfile.bin, which holds the encryption key, does not work the way it is supposed to.
When I setup Arch Linux and install a crypto_keyfile.bin, I am not asked for my password during the boot process and the crypto_keyfile handles disk encryption. With a calamares install, I have always been asked for a password during the boot process, which I shouldn't be if everything had been setup correctly by calamares.

Hope this helps.
Michael

**Comment by kkofler** [comment]
If the system can unencrypt the partitions without ever prompting you for a passphrase, this means the encrypted partitions can be unlocked with an unencrypted passphrase, which means the disk encryption is essentially worthless. Any attacker can trivially decrypt your data, they just need to boot your system, or to manually decrypt the encrypted partitions using the unencrypted keyfile. (The only advantage of that setup over completely unencrypted partitions is that it is easier to make the data unreadable because only the keyfile must be securely deleted and not the entire data. But in all other use cases, the disk may as well be entirely unencrypted, the encryption adds no security whatsoever.)

A keyfile **must** be stored on an encrypted partition that **must** be unlocked with a passphrase for the encryption to be secure.

**Comment by teacher4711** [comment]
I totally agree and I'm aware of that. However, I follow the arch wiki and follow its precautions: "Use an embedded keyfile only if you have some form of authentication mechanism beforehand that protects the keyfile sufficiently." (https://wiki.archlinux.org/index.php/dm-crypt/Device_encryption)

That was NOT my point, however.
Calamares writes in /etc/crypttab that there is a crypto_keyfile.bin but does not generate one, which is why the system fails to boot. I get the message: [FAILED] Failed to start Cryptography Setup for luks-894...

Solution: remove /crypto_keyfile.bin from /etc/crypttab and replace it with none -> cf.: https://wiki.archlinux.org/index.php/dm-crypt/System_configuration#crypttab

My OS: ArcoLinux latest
