### ISSUE TITLE
Flatpak integration

### ISSUE THREAD

**Issue by nintyfan** [calamares/calamares#1082]
**Not way to handle cross-distro packages in installer**
Currently, LiveCD distros don't allow us to select additional packages and each distribution could use different package format.

**Use flatpak**
Flatpak provide mechanism to create use stick with software currently installed on system. Someone could order to pack flatpaked version of LibreOffice onto usb stick, went onto another computer and install LibreOffice on it without network access! Why don't use this mechanism or create similar? Distros could integrate flatpaked version of programs on LiveCD and Calamares could asks, which program to move into installed system.
So:
1. User could still use LiveCD session
2. User could select, which program He/She requiring on destination system
3. Flatpak will get (possibly) new packages and will popularize

**Comment by abucodonosor** [comment]
No .. either calamares itself can be a flatpak package see https://github.com/calamares/calamares/issues/999
or will it intergate such thing.

That is _distro_ issue .. calamares is not an package manager but an installer and all this flatpak , appimage , snapd or whatever else containerISH does not belong to calamares.

If your Distribution allows you to install flataks like from a repo then ask them to implement some modules.
99% of all Distributions won't allow you that

**Comment by kkofler** [comment]
I think this RFE can either be implemented as part of the `packages` module or as a separate, similar module. Support can then be added to the `netinstall` module or, again, a separate, modified version of it. (Since `netinstall` uses `packages` to do the actual package installation, the first part is needed first.)

I think this RFE is actually more realistic than #999 (turning Calamares itself into a Flatpak).

**Comment by abucodonosor** [comment]
@kkofler 

While it can be done some hackISH way .. there is not a generic solution for these.

Unlikely Distribution packages the ISO is made for, flapak can be random , not even implemented in that Distribution , or implemented different , not there by default and so on.

If you look closer the request is more about ' I boot some random iso' and I download 
on the live ISO some random flatpak .. which then calmamares 'should inject' into
the final installed system. .. Calamares is not an package manager , is it ?

This kind things doesn't belong to calamares.

A sort : flatpak modules could be implemented but not that way and for sure cannot be to generic.

**Comment by adriaandegroot** [comment]
The package manager for flatpak is called `flatpak` (see http://docs.flatpak.org/en/latest/using-flatpak.html) which looks like it can be run just like any other package manager in the target system. Adding it as a subclass of *PackageManager* in the *packages* module should be straightforward. Since we just use package names in the config, it's straightforward to put the name of a flatpak in there.

The netinstall module can be used as a UI if the flatpaks are to be user-selectable; otherwise it's going to pull in whatever the latest flatpak is for the given name. This might be useful (eh, doubt it) for a try-this-application kind of distro that promises to set up a testing install for a given application through flatpak.

It's likely, though, that installing an existing flatpak through the filesystem / unsquash and then updating it through the regular update mechanisms post-install, would be a better way to do this (speeds up install & reboot, defers  network traffic).

**If** this kind of package-manager subclass shows up, we might end up with a bit of a UI and execution issue: the user might end up asking for one set of distro packages to install, and then (extra!) some flatpaks. One UI, or two? And how to tell the *packages* module in the *exec* step which bunches of packages to pull out of global storage? We might end up with a "after running packages to install things as listed in globalstorage, clear that list" kind of flag.

In any case, @nintyfan , this awaits a PR.

**Comment by nintyfan** [comment]
I suppose, flatpak isn't only one package manager for flatpaks. There exist some library for handle flatpaks and Discover, Gnome-Software, flatpak, etc.

What means PR? I'm programmer with rather beginner skills and never work in bigger group of people.

**Comment by kkofler** [comment]
The `flatpak` command-line interface is what Calamares would use though. It should be straightforward to add it to the set of supported package managers in the `packages` module.

PR is short for [pull request](https://help.github.com/articles/about-pull-requests/).

**Comment by nintyfan** [comment]
Thank you! I have Python and C knowledge, so when I found a little spare of time, I can develop module. But... I never developed anything for Calamares, so be patient.

**Comment by adriaandegroot** [comment]
I'm going to encourage you, @nintyfan , to contribute to Calamares. It's a good way to learn things and make things better all over the place. In principle the Calamares developer's guide should be enough to get you on your way (in the Calamares wiki). If it's not, submit fixes or file issues against it to get it cleared up.

You'll need, most likely, a VM with a liveCD image running in it, and an (empty) virtual HDD attached to it. Pick a distro, any distro, for the liveCD and boot it and run `deploycala.py` to get stuff set up. That should *just work* (tm). Do **not** run that script in a real machine or an installed system, it is a rather rude script.

The relevant code is in Calamares `src/modules/packages/main.py`. I think the Python code is pretty straightforward; just create a new subclass for running the flatpak executable. You can test by running the installer with a suitable configuration in `packages.conf`.

Take note that the package manager is run as root in the target system; you'll probably want to run flatpak so that it installs the flatpaks globally rather than only for the single user. And then once you've got some code, do a pull request (thanks @kkofler for linky) to get it integrated. Remember to include documentation and an entry for the CHANGES file.

**Comment by nintyfan** [comment]
Sorry for asking you, but I have problem.
Calamares doesn't compile on my system - missing QtConcurence library
Could I modify a stable branch rather than master?

**Comment by philmmanjaro** [comment]
@nintyfan: what kind of live-cd do you use? Normally we are all maintainers or developers and create install medias as needed. Therefore packaging Calamares and its dependencies is one part of the process. Please be more specific with your issue integrating Calamares into your live-cd.

**Comment by nintyfan** [comment]
I modify Calamares source code not in VM, but in my real system. Should I download LiveCD, create VM, install Calamares and make a snapshot? Also I will use shared folder / NFS?

**Comment by adriaandegroot** [comment]
@nintyfan There's more than one way to Have a Lot of Fun.

If QtConcurrent isn't being found -- I guess it is complaining at CMake time? Then you will need to chase whatever package provides the **development** headers for QtConcurrent on openSUSE. Then mention it here, so I can update the list-of-packages in `deploycala.py`.

As for developing in your *real* system vs in a *VM*, that's up to you. Once you have the build-dependencies installed it's generally fine; getting a real system to a state where you can build Calamares is under-documented though, and the script `deploycala.py` is written **explicitly** for the live-VM case where you don't care about any of the configuration in the machine.

**Comment by kkofler** [comment]
The package is apparently called `libQt5Concurrent-devel` on OpenSUSE.

**Comment by nintyfan** [comment]
Thanks. Will it be better if cmake detects this errors during configure? Shouldn't it? I don't know much about cmake. If my sentence was true, then can I report bug?

**Comment by adriaandegroot** [comment]
@nintyfan yes, its better if CMake complains beforehand. It does now. Thanks for reporting that.

(Leaving this issue open while you get Calamares building and start on the flatpak-as-package-manager parts)

**Comment by nintyfan** [comment]
Hi.

I start working. My question is where does Calamares mount source filesystem inside chroot environment?

**Comment by adriaandegroot** [comment]
What do you mean by "source filesystem" here?

Calamares runs in a live system -- the host system. The hosts's filesystem is whatever has been booted, and it is mounted however the host system sets things up. When doing an installation, Calamares creates `/tmp/calamares-<random>` as a mountpoint and then mounts the target filesystems -- after partitioning, etc. -- there. The host's filesystems are not available in the target at all (not by default; I'm sure you can bind-mount yourself into loops).

**Comment by nintyfan** [comment]
Ok. I have some matter here and here not related to your code base. I will search how to copy program/runtime from flatpak installation. If I use create-usb and next install --sideload-repo, flatpak will try to download from internet. I try to use some tricks with ostree and this also not working.
Sorry you must wait.

**Comment by adriaandegroot** [comment]
Timed out. Would still need a PR and a re-consideration of how to do it, since the *packages* module now supports a lot more things than it did when the issue was filed.
