### ISSUE TITLE
Segfaults adding second partition (UI bug) [3.2.4]

### ISSUE THREAD

**Issue by domohawk** [calamares/calamares#1097]
Manjaro Version: 18.03 stable
Calamares: 3.2.4

1. Go to Manual Partitioning
2. Click on the free space, which enables "Create" button and add a partition
3. Now "Free space" is not selected, but "Create" button is still enabled
4. Click "Create" and calamares seg faults

The easy fix is probably to disable "Create" button after adding a partition, but really if you click Create and "Free space" is not selected it would be best to show an error (or disable Create and ignore click)

**Comment by philmmanjaro** [comment]
I can confirm the issue. So we should disable `Create` when nothing is selected.

**Comment by abucodonosor** [comment]
Guys these Majnaro versions does not matter here. But the used calamares version does.

**Comment by philmmanjaro** [comment]
@abucodonosor: I updated the issue.

**Comment by abucodonosor** [comment]
@adriaandegroot 

we woke up some dragons , well LVM code did already we just didn't noticed in time :-)

This is caused by the workaround for the race crash..

Something like this may fix it:

```
diff --git a/src/modules/partition/gui/PartitionPage.cpp b/src/modules/partition/gui/PartitionPage.cpp
index a2f2eab60..4a6343a1d 100644
--- a/src/modules/partition/gui/PartitionPage.cpp
+++ b/src/modules/partition/gui/PartitionPage.cpp
@@ -386,6 +386,7 @@ PartitionPage::onCreateClicked()
     {
         Partition* newPart = dlg->createPartition();
         m_core->createPartition( model->device(), newPart, dlg->newFlags() );
+        updateButtons();
     }
     delete dlg;
 }
```

However with the bt I get now it shows the race old race from https://github.com/calamares/calamares/issues/1061 is between:

https://github.com/calamares/calamares/blob/master/src/modules/partition/gui/PartitionPage.cpp#L572-L576

and 

https://github.com/calamares/calamares/blob/master/src/modules/partition/gui/PartitionPage.cpp#L584

If you comment now comment L575 and uncomment L584 nothing seems to sefgault but updateButtons()
does not really work right.
