### ISSUE TITLE
Information about the new stylesheet.qss

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1149]
We are ready to try out the possibilities to "style" calamares.

Can you provide us with links or examples how to achieve thinks like
Font family
Font size

What parts of calamares can we address?
How can we know?
Is there more to define than this?
`/* Main application window.

#mainApp { }
#logoApp { }
#sidebarApp { }
#sidebarMenuApp { }
*/

/* Partitioning module.

#bootInfoIcon { }
#bootInfoLable { }
#deviceInfoIcon { }
#defineInfoLabel { }
#scrollAreaWidgetContents { }
#partitionBarView { }
*/

/* Licensing module.

#licenseItem {  }
#licenseItemFullText {  }
*/`

ready to be a beta-tester

**Comment by abucodonosor** [comment]
Then have a look:
https://doc.qt.io/qt-5/stylesheet-examples.html

**Comment by adriaandegroot** [comment]
There are two parts to this question:
 - what styling options are supported by Qt?
 - how to find out what widgets in Calamares can be styled?

The stylesheet examples that @abucodonosor links to answers a lot of the first question. That page talks about styling in general and you **can** use QWidget class names as described there. For instance, you can put this in your stylesheet:
```
QComboBox { background: green; }
QComboBox QAbstractItemView { background: lightgreen; }
```
.. and you will get green comboboxes all through Calamares. This ticket, and the Calamares documentation, isn't the right place to deal with all the details of using CSS for Qt styling. There's a lot of details needed to get it just right, though (e.g. changing the combobox to green also needs a better foreground color, and colors for the selection, and handling inactive comboboxes, and ...).

The second question is **partly** answered above: you can style  QWidget classes, and so deal with all the buttons, labels, comboboxes at once if you like. However, you may want to style **specific** elements differently from the rest. For instance, the *support* button in the welcome page. To do that -- style a specific widget -- you need to know the widget's *ObjectName* (note also that names are not necessarily unique). Now, I know that that particular button has the name *supportButton*. So I can style it by using the name as selector-id in the CSS:
```
#supportButton { font-style: italic; }
```

You can see that that particular name is **not** mentioned in the example stylesheet. So how can you find out the names, so that you can style specific elements? The most important names are already listed. I don't think it would be useful to extend the example list with all the names that there are -- because there are many, they can change with the code, and the list depends on the modules in use anyway. I know the name of that particular button because I looked in the source code (it's in `WelcomePage.ui`). That's not a useful kind of answer, though.

To find the object names in a **running** application, use a Qt object inspector. There's Qt-Inspector, and FrogLogic's Squish will do as well, but the tool I've actually used is GammaRay, by KDAB. It's packaged for Debian, at least.

 - Start Calamares (it is probably not useful to run it as root at this point)
 - Start GammaRay
 - Pick the Calamares process and wait for the process-specific GammaRay window to come up.
 - Switch to the *Widgets* view in the left-hand pane of GammaRay.
 - Here you'll see a *mainApp* widget, which you can expand; that contains more widgets .. this is the entire widget tree of the application. Some widgets have names, some don't. If a widget that you would legitimately style **individually** (e.g. not the QStackedWidget inside the main window, that doesn't make sense to me) does not have a name, that's a bug and you should file an issue for it (or better yet, a PR to fix it).
 - Continue exploring the widget tree until you find the widget named *WelcomePage*, which contains a QPushButton named *supportButton*. Feel free to wonder about the inconsistencies in naming of widgets. If you click on  *supportButton* in the GammaRay's widget tree, it will be highlighted in the running application. That way you can double-check the name.

    ![Screenshot_20190521_111004](https://user-images.githubusercontent.com/19431457/58083321-0e43c780-7bb9-11e9-8c01-6af43c972dd0.png)
 - Now that you know the name of the individual widget, you can style it with an appropriate selector, like this
   ```
   #supportButton { font-style: italic; }
   #supportButton:pressed { border: 2px solid red; background-color: pink; }
   ```

**Comment by arcolinuxz** [comment]
Thanks for your time to write this.
Now I can start theming Calamares like I theme my wordpress websites via
css, id's and classes.

**Comment by adriaandegroot** [comment]
After writing all that realised that it would be useful to have a "reload stylesheet" (so you can live-test it) button. Find it in the debugging window (which, if you are running in debug mode, has a button in the lower-right of the window even if you can't see it very well) in the *tools* tab. There is also a *widget tree* button, which dumps widget names, so you don't need to use GammaRay after all. Lots of widgets have no names, though, so you might still want to use GammaRay to find out what arts there are -- the widget tree from Calamares just lists those as "".

This has also been added to the wiki.
