### ISSUE TITLE
Let Branding default to values from os-release

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1150]
http://manpages.ubuntu.com/manpages/disco/man5/os-release.5.html

**Is your feature request related to a problem? Please describe.**
At KDE neon we have just about 100% duplication going on between os-release and our branding.desc and maintaining the same information in multiple places is really annoying. Specifically for neon there isn't a single string in the `strings` hash that is not already present in os-release.

**Describe the solution you'd like**
Branding class should pick default values from os-release file. If the data is the same a distro can stop setting the same values again in branding.desc. If a distro wants to override os-release they can set the strings in the desc file.

**Describe alternatives you've considered**
An equally useful solution that might fit better into the existing system is allowing the use of place holders in the values of branding.desc. So we still have to maintain branding.descs, but the actually values are resolved out of os-release's data at run time.

```
strings:
 productName: @OS_RELEASE_NAME@
 version: @OS_RELEASE_VERSION@
 bootloaderEntryName: '@OS_RELEASE_ID@ @OS_RELEASE_VERSION_ID@ @OS_RELEASE_VARIANT@'
 ...
```

This may be cleaner over all and also more dynamic.
bootloaderEntryName is a prime example of why this may in fact be the better approach. Depending on the specific content of os-release any number of fields may be best for constructing the loader entry.

**Additional context**

At a glance the existing branding strings map to os-release like so:

- productName :arrow_right: NAME
- shortProductName :arrow_right: NAME (maybe ID, unclear what this is used for)
- version :arrow_right: VERSION
- shortVersion :arrow_right: VERSION (maybe VERSION_ID, unclear what this is used for)
- versionedName :arrow_right: PRETTY_NAME
- shortVersionedName :arrow_right: PRETTY_NAME (again, unclear, maybe concat ID and VERSION_ID?)
- bootloaderEntryName :arrow_right: ID/NAME/PRETTY_NAME/+VARIANT
- productUrl :arrow_right: HOME_URL
- supportUrl :arrow_right: SUPPORT_URL
- knownIssuesUrl has no representation and would need setting in branding as it is ISO/release specific
- releaseNotesUrl same as knownIssuesUrl

Additionally the images values:

- productLogo :arrow_right: LOGO
- productIcon :arrow_right: LOGO
- productWelcome :arrow_right: LOGO

**Comment by kkofler** [comment]
In the Fedora packaging (in order to support Fedora Remixes out of the box), I do the following:
https://src.fedoraproject.org/rpms/calamares/blob/master/f/calamares.spec#_252

**Comment by adriaandegroot** [comment]
So there's a precedent for re-using /etc/os-release informations already. Good show.

The *short<foo>* entries can easily be set to the same value as their long counterparts. The versioned names are supposed to also carry version information. The difference is *Kannolo* vs *Kannolo (Fedora Remix)* vs *Kannolo 30*, basically, and it shows up subtly in different messages in Calamares:

 - *Welcome to the Calamares installer for **versionedName**.* (title in welcome)
 - * **shortProductName** support* (button text in welcome)
 - * **productName** installer" (window title)

I'd be happy with a PR that reduces the number of strings there down to, say, two. But that's not what this issue is about.

I quite like the idea of supporting per-field replacements from /etc/os-release.

**Comment by kkofler** [comment]
Well, all those string settings were added deliberately because people complained about the existing entries not being suitable for that particular context. I would rather not merge any of those.
