### ISSUE TITLE
Exec before show adds an install sequence

### ISSUE THREAD

**Issue by jstnlth** [calamares/calamares#1157]
**Describe the LOW PRIORITY bug**
Mixing exec sequences with show sequences adds multiple install instances and (assuming prompt-install: true) it prompts for early user approval.

**To Reproduce**
sequence:
- exec:
  - interactiveterminal
- show:
  - welcome
...results in a script/install/welcome sequence with a user approval prompt

**Expected behavior**
I guess I don't expect to see an install sequence until after the summary screen (although summary is not mandatory...)

***Additional Context***
I was investigating an early script job before Welcome to verify that unpackfs's source file is valid as a mandatory item.

![interactiveterminal](https://user-images.githubusercontent.com/8320822/58166474-934edf80-7c92-11e9-88ef-eb1897b8084d.png)

**Comment by adriaandegroot** [comment]
You are getting surprising results here because *interactiveterminal* is a viewmodule (with a UI) and you're putting it in the *exec* part without first putting it in a *show* section. So Calamares fills in a potentially bogus *show* section for you, so you're effectively ending up with this sequence:

```
- show:
  - interactiveterminal
- exec:
  - interactiveterminal
```

Calamares inserts an *install* sequence between each transition from *show* to *exec*, which is why you get exactly this. You probably want to put the terminal inside the *show* section. Then you'll get a visible terminal **and** no virtual *exec* section **and** no spurious *install* sequence.
