### ISSUE TITLE
add some margins around logo and/or let branding.desc control margins

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1159]
**Is your feature request related to a problem? Please describe.**
Currently the logo artwork in the sidebar has no margins and gets its personal space invaded by both the top of the window and the first step in the list.

**Describe the solution you'd like**
Introduce sound empty margins along all sides of the logo and/or let branding.desc control margins. At the very least there need to be some pixels between the logo and the first entry.

**Additional context**
![space](https://user-images.githubusercontent.com/809987/58242226-b2ab4280-7d4e-11e9-8389-8b6701211e2f.png)

**Comment by adriaandegroot** [comment]
This is what the branding stylesheet is for. Create a `stylesheet.qss` in your branding directory, alongside `branding.desc`. Add this:

```
#logoApp { margin-top: 20px; margin-bottom: 20px; }
```

Of course since the logo's size is fixed at exactly 80x80 pixels, the margin will take away from the image size (in this example you'd want to re-do your logo PNG to use only the 40 middle pixels). That's far from optimal, looks like it needs some extra trickery.

**Comment by adriaandegroot** [comment]
The issue with the CSS line I mentioned is that the logo has no CSS-defined size (it's in `setFixedSize()`) so you need to help it:

```
#logoApp { min-height: 80px; margin-bottom: 30px; }
```

It's a *little* peculiar in that increasing the margin setting there also moves it from the top, so you'll need to do a little tweaking. I recommend the *reload stylesheet* feature just added in master (from the debug window).
