### ISSUE TITLE
partitioning capabilities not detected without welcome page

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1169]
**Describe the bug**
When using a sequence without welcome page the partitioning page does not actually detect capabilities.

```
sequence:
  - show:
    - partition
  - exec:
    - partition
```

**To Reproduce**
1. have pre-existing partitions, e.g. do a complete installation first
1. install with short sequence as shown above
2. part page only has erase and manual options
3. close cala
4. add welcome page as first show page in the seqeucne
5. start install again
6. part page now has install alongside, replace, erase, manual options

**Expected behavior**
Partition page should work on its own.

**Comment by adriaandegroot** [comment]
The issue here is that it is the **welcome** page that sets up *requiredStorage* (it's in the requirements section) and if that is not set, we can't tell if a partition can be replaced or resized to a suitable size. So then those options disappear.

**Comment by adriaandegroot** [comment]
There's a branch issue-1169 for this, which starts with only commits cleaning up the relevant code so that you would get useful debugging information, instead of just vanished buttons. In the rewrite-partiton  branch the buttons should (once the UI is re-done) remain visible, with a tooltip explanation why they are disabled.

Solutions for this specific case:
 - regard a missing configuration entry as "not a problem" and carry on as if it was set to 0
 - allow specifying the configuration entries in `partition.conf` as well
