### ISSUE TITLE
Proprietary driver installation page and/or tickbox somewhere

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1172]
**Is your feature request related to a problem? Please describe.**
Some distributions install free software exclusively by default. The user may still wish to opt into proprietary software (e.g. bcmwl or nvidia drivers).

**Describe the solution you'd like**
A new page or perhaps a checkbox on an existing page (I don't think there really is a fitting one though?) to enable the user to opt into installing proprietary drivers. Backend-wise this could be as simple as a command that gets run if the  checkbox was ticked.

**Additional context**
On ubuntu-ish distributions this would essentially act as frontend for the command `ubuntu-drivers install` which takes care of determining what drivers need installing and executes on that.

This may also need to have a network check as distributions may not have (all) drivers on their ISO.

**Comment by demmm** [comment]
In case helpful, KaOS has used a python module for this since 2014:
https://github.com/KaOSx/calamares/blob/master/src/modules/nonfree_drivers/main.py
On the license page the use will have to accept to the appropriate license, otherwise the module won't run.
To select non-free drivers though, KaOS uses menu options at the start of the Live session, which then carries on to be used by the installer.

**Comment by adriaandegroot** [comment]
The netinstall / packages page might help here as well, as the user can then choose to install specific software (e.g. the proprietary drivers). This isn't **really** convenient though, because then the user needs to pick them specifically, rather than accept a generic "install whatever proprietary stuff is needed" .. although that in turn has licensing issues written all over it.

Probably best is to make the license acceptance more granular, and then to be able to use contextualProcess to DTRT.
