### ISSUE TITLE
Improve the sliders timing when the filesystem is copied over to the harddisk

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1176]
I realize this is a strange request.

We have been getting this response from our users for like months.
And I never dared to ask it since it is not important at all.

So any calamares version applies.

When you install the system on the harddisk  the slider and the percentage do not change for like minutes and people assume it is broken or crashed.

Could you make it so that the slider does not jump from 22% to 50 % but give people the impression that it is still installing by showing more progress in the slider and the percentages - unsquash process
![slider](https://user-images.githubusercontent.com/36679406/59561594-9aafa180-9022-11e9-863d-4bd5bc09134f.png)

**Comment by adriaandegroot** [comment]
Not a strange request at all: the **appearance** of progress is important, even if it slows the actual progress down :) The unpackfs module is supposed to report progress as it happens, so I guess there's something wrong there (might be that it only reports proper progress with one of the source options, though).

**Comment by d3signr** [comment]
It appears the unpackfs module is designed to only update progress every 100 files, maybe this vale could be reduced in order to update the progress more frequently?

**Comment by adriaandegroot** [comment]
**wow**, that's a beautiful distro during installation. Shame Calamares is ugly :( .. there's probably a lot to gain in the desktop-integration and theming part of the story.

Anyway, I see Calamares reporting progress like **mad** during unpack operations. There's about 500k files to read, and progress goes from 0 to 1 (0 to 100%) as it grinds through them, but that only translates into going from 25% to 26% as it chugs along. So the issue is scaling in the overall progress, **or** as @d3signr points out, a per-module progress could help as well.

**Comment by adriaandegroot** [comment]
I hear @bill-auger has something along these lines, so I'm going to park this issue for a bit and wait for a PR.

**Comment by bill-auger** [comment]
yep, ill show it soon - i need to refresh my memory a bit from
about 18 months ago so i can untangle it for a merge request

my solution adds an m_jobWeight instance var and getter to the
Job class, allowing each sub-class to define a weighted share of
the total 100% progress, against which the jobPercent as passed
into the JobThread::emitProgress() handler is compared, and added
to all previous job weights, rather than the current linear
calculation (m_jobIndex / jobPercent)

for any sub-class not implementing the m_jobWeight getter, the
default value will reproduce the original current behavior as
1/n_jobs

the caveat for the implementer, is that it requires the long
running command to be run in its own thread; so that 'emit
progress' can be pumped in fine grained intervals - and of
course there needs to be some way to determine what is the
current progress from the outside Job subclass, while waiting for
the long-running thread to exit

im not sure if that suits the needs of the OP; but thats how i
handled it

**Comment by arcolinuxz** [comment]
I am now building 17 iso's for ArcoLinux and it came to my attention that the slider is not changed yet. The unpack module does  not really show a gradual progress. Rather it jumps from 22 to 50%.
Calamares used is 3.2.15. I saw here the label **merged** hence the feed-back.

**Comment by bill-auger** [comment]
the patch above adds support for fine-grained progress-bar
updates; but none of the standard calamares modules take
advantage of it yet - the un-squash module is probably the best
candidate though, if you would like to implement it

**Comment by arcolinuxz** [comment]
if this could be revisited - I just thought my system hung on an older pc but that was not the case. You do not see the slider move for like minutes.

**Comment by bill-auger** [comment]
this was just suggested again on IRC; so i looked into it - all the plumbing necessary for fine-grained control over the progress-bar is in place now, for anyone to make use of in any module

the module that people are complaining about, i presume is 'unpackfs' - that module actually does use that mechanism already; but it updates the progressbar only once per 100 files ( see https://github.com/calamares/calamares/blob/master/src/modules/unpackfs/main.py#L160 ) - simply removing that conditional on LOC 160 may be all that is needed for the 'unpackfs' module to satisfy this request

i could show some boilerplate to accomplish the same in C modules, if any similar requests are made for other modules

upon searching the tickets, i noticed that #1200 and #1262 are requesting essentially the same thing

**Comment by kkofler** [comment]
As I wrote on IRC:

That conditional is actually buggy. It only works if `rsync` actually reports an exact multiple of 100 files. I guess it should be something like
```python3
if num_files_copied-last_num_files_copied >= 100:
```
I think changing that would magically make unpackfs progress reporting more reliable.

That said, files have very different sizes, so the progress based on file count alone might still get stuck on some huge file.

**Comment by adriaandegroot** [comment]
This was special-cased (giving more weight to *unpackfs*, so it occupies more of the linear scale of progress) and the progress messages were expanded to indicate how many files have been copied.

I know the commit refers to it as "an ugly hack" but ..

Adding it to the milestone because it may be "simple" to do some things from `settings.conf`.

**Comment by adriaandegroot** [comment]
This needs #1473, so that every instance (both custom and not-custom) has an instance descriptor. Then `Module* moduleFromDescriptor()` can take a ModuleSystem::Descriptor (e.g. information from `module.desc`) and an InstanceDescriptor (information from `settings.conf`) and load from that.

In particular, a module can then be assigned a weight. If the instance sets a weight, use that; otherwise if the module descriptor sets a weight, use that; otherwise use 1. When adding the jobs from a module to the job queue in `ExecutionViewStep::onActivate()`, "spread" the module's weight over the jobs. Jobs can still report a weight, which should be used to distribute the module's weight.

- [ ] change `Job::getJobWeight` to return int
- [ ] remove special case for unpackfs job from the Python infrastructure
- [ ] set the module weight for unpackfs to 12
- [ ] in `JobQueue::enqueue` add the module that created the job as parameter; calculate the weight-spread over the job or jobs right there
- [ ] change m_jobs to carry both job pointers and weights
- [ ] change JobThread to use the calculated weights rather than asking the jobs

**kind** of needs #1474 as well, although I suppose doing `descriptor["weight"].toInt()` is acceptable for now.

Taking this **off** the milestone and onto the next one, since this one is overdue and there's a fair amount of internals-work needed for this ticket (and related ones).

**Comment by adriaandegroot** [comment]
Plenty of internals changed, but the setup by @bill-auger is largely intact: jobs can have weights. However, at a higher level modules have weights, and module instances have weights, and jobs from a single module contribute together to the weight of their module. Job-weights are only configurable at the source level (and then, only really for C++ modules).

For modules with a single job, configure the module weight instead (e.g. all the Python modules); modules with multiple jobs can do some tweaking with job weights if there are light and heavy jobs from the same module.

In general, tweaking module weights should now be done in the *instances* section in `settings.conf`, although *unpackfs* specifically has the module configured with weight 12 (like it was previously, hackishly, done in job weights).

Thanks to bill for getting this started (like a year ago or more)
