### ISSUE TITLE
Feature request : button to send calamares log file to pastebin.com or other services

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1182]
During conversations on discord we discovered the need in the ArcoLinuxD iso (which does not contain any browser at all) to have the ability to put logs online in order to investigate issues with calamares.

I came up with the application pastebinit on Arch Linux as a solution to put documents online on pastebin.com.

Then it occurred to us that having a way to share issues/information about calamares in Calamares could be in everyone's interest.

What if  there was a button to quickly send over all the data of the installation?
What if you would have a battery of logs to analyze issues?
How many times does this error occurr etc. A way to prioritize.
Just brainstorming out loud.

Keep at it people.

**Comment by adriaandegroot** [comment]
That's an intriguing idea. Long ago (?) I think Calamares had a log-upload-on-crash, which went to calamares.io. That went away with the switch to KCrash and when the heavyweight calamares.io site was phased out.

A common (?) XML-RPC interface for pastebins is documented at http://paste.debian.net/rpc-interface.html .. so an implementation of that in C++ is possible. OTOH, `pastebinit` is **also** common, supports lots of bins and is already widely configurable, so calling that as an external process is probably much, much easier. Main issue then is getting the pastebin URL back to the user so they can report it.

**Comment by kkofler** [comment]
I guess a C++/Qt client library for paste services would be a candidate for KDE Frameworks. I can imagine, e.g., DrKonqi getting support for it.

**Comment by adriaandegroot** [comment]
KF5Purpose **might** be the thing to do this; it's hard to tell (it has a generic HTTPPost job).

But I'm told that @bill-auger already has this , so I'll just wait from input from that side.

**Comment by bill-auger** [comment]
yes, its dead simple with termbin.com - and that has the extra
advantage of the back-end (fiche) being freely licensed and
easy to self host, if one wants the posts to be private, for example

**Comment by arcolinuxz** [comment]
I had an idea you might incorporate easily in the debug part of calamares.
In one of the tabs at the end you have buttons. An extra button to send the log text to pastebin.com?
I use **pastebinit** to send code of installations. Maybe this can be implemented.
The url can be written down and later you can make an issue about it.

**Comment by JoelStienlet** [comment]
Is there also support planned for connections through "socks" proxy servers? I'm pretty sure no liveCD has proxychains4 installed by default.

**Comment by bill-auger** [comment]
JoelStienlet - if that is unrelated to paste uploads, it would be best to open a specific ticket about it

**Comment by JoelStienlet** [comment]
> JoelStienlet - if that is unrelated to paste uploads, it would be best to open a specific ticket about it

It is related to any operation that requires a working internet connection, and as I understand the different posts here, this new feature (sending logfiles to pastebin or similar) is still in discussion, so I thought it may be desirable to take this requirement into account at an early stage, so that it can later work nicely on most corporate networks. Not all client libraries may have support for socks (and socks5h where DNS is also resolved through socks), so this could be one more selection criterion.

**Comment by bill-auger** [comment]
the paste feature is not still under discussion though - it is
already fully implemented and usable - this feature request is
asking for two very specific extensions to functionality that
calamares already has

a global proxy would be an entirely new feature with a broad
scope and implications; so it should have it's own dedicated
ticket, in order to keep both of them on track

the first thing i would add to that ticket though, is that
network access in not at all in the early stages - calamares
already accesses the network in several different ways, including
shelling out to the system package manager - a global proxy
would probably require normalizing all network access, which may
not be feasible

**Comment by adriaandegroot** [comment]
@arcolinuxz having a "send install log" on the finished page sounds like a useful **developer** feature (like when testing ISO's), probably not something to put on a final product. That, plus the security/safety of pastebins and the contents of the logfiles would probably need to be double-checked.

But for developers, sure.

**Comment by adriaandegroot** [comment]
@JoelStienlet As @bill-auger (and Phil) point out, the feature is implemented. It uses QNetworkAccessManager for communications; there's **some** infrastructure code in Calamares for normalizing network connections, but mostly we rely on whatever Qt can do. Perhaps your request is related also to network-setup; Calamares doesn't do that itself, but relies on the surrounding DE to provide a network-setup mechanism (like Plasma NetworkManager applet).

**Comment by adriaandegroot** [comment]
Hacktoberfest 2020 has not yet started, but this is a good kind of issue to do for it.

## Procedural
- [ ] Make sure you can compile Calamares locally (see https://github.com/calamares/calamares/blob/calamares/CONTRIBUTING.md, which will point you onwards to the wiki)
- [ ] Make sure the *finished* module is enabled in your Calamares build (by default it is compiled, and also enabled in `settings.conf`: check the CMake output to see that it will be compiled, and check the `settings.conf` in your build directory to make the module show up). To speed up testing you might cut down the sequence to just show *welcome* and *finished* with nothing else.
- [ ] Some relevant  sources are in https://github.com/calamares/calamares/tree/calamares/src/libcalamaresui/utils/Paste.h ; make a branch, add your copyright statement to one of the .cpp files and add your name to top-level CHANGES, then start a PR with WIP in the title

## Functional

- [ ] Find a good place to configure this; I suspect that **branding** might be suitable, since that has distro-specific flavoring that can also vary by remix. You'll want to have URL + port at the very least. But you could stick to the *finished* module, too.
- [ ] Look into the ViewManager class; it can (does!) upload crash logs and there are some UI things that probably need work; to test installation failures you can use *shellprocess* and run `false` in there.
- [ ] Load the configuration and make sure it gets to the ViewManager; if it's in branding that might be easy, otherwise it will take some wrangling (e.g. get the *finished* module to put it in GlobalStorage)
- [ ] Make the configuration available to the *finished* module as well.
- [ ] Show a suitable UI (checkbox?) in the FinishedPage. Hook that up to *sendLogToPastebin()*.


## Extras

At this point, it would be good to get sidetracked into a separate PR, to Config-ify the finished module. This untangles the configuration of a module from its UI and the ViewStep and puts it in a config object. In other ViewSteps this lives in `Config.h` and `Config.cpp`; imitate that structure, though the configuration for the *finished* module is quite simple.

Do a QML version of the *finished* module, using the Config object.

## Post-Procedural

Feel free to push to the PR branch regularly; this shows how your progress is and allows early comments. Please stick to the commit-message style used in the rest of Calamares; do write out what-and-why with commits. It's OK to leave fixme's around for later in the branch and we can coordinate force-pushes if need be.

**Comment by adriaandegroot** [comment]
(It's on 3.2.37 milestone, but that's because we're re-using that one for 3.2.38)

**Comment by adriaandegroot** [comment]
The send-log-on-click is now implemented:
- it's configurable
- current implementation supports only fiche servers

Any other servers would need to send in an API description, preferably a PR, against:
   - `src/libcalamaresui/utils/Paste.cpp` (for the implementation of upload) and
   - `src/libcalamaresui/utils/Branding.h` (to add an enum value for the new kind of server to *UploadServerType*) and
   - `src/libcalamaresui/utils/Branding.cpp` (to add enum value to the table in *uploadServerFromMap()*)
