### ISSUE TITLE
Unsafe generation of initramfs during FDE

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1191]
[Downstream bug](https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1835095), [IRC logs from the user who reported it](https://irclogs.ubuntu.com/2019/07/02/%23lubuntu.html#t10:26).

The tl;dr is:

"The initramfs images that are generated by mkinitramfs will have the user:group set to root:root, but their access flags will be 644 (-rw-r--r--). This means that any user or even a script that has read access to the file system can read and extract the secret keyfile from an initramfs image."

initramfs needs to be ran with a different umask here.

**Comment by teward** [comment]
This issue has been assigned the CVE ID of CVE-2019-13179 by MITRE.

**Comment by Ofirnir123** [comment]
Hi! according to Mitre all the versions up to 3.2.4 are vulnerable.
Can you relate if this issue was already fixed and from which version ?

Kind regards :D

**Comment by adriaandegroot** [comment]
MITRE is wrong, it's all versions up to 3.2.10 and it isn't fixed yet. There's **probably** a fix for this specific issue in master, though.

**Comment by teward** [comment]
@adriaandegroot I'll submit the update to MITRE for both CVEs - the CVEs were submitted with 'discovered in...' - and there was a note attached to it indicating "Not Fixed".  That info doesn't get added to the CVE its kept internally.  I will ask them to update.

**Comment by adriaandegroot** [comment]
For Ubuntu-derivatives, which use the *initramfs* module, this should now be fixed. But there are other ways of generating the initramfs (mkinitcpio, for instance), and those have the same problem.

So I'm not closing this yet.

**Comment by kkofler** [comment]
Please note, however, that `dracut` is **not** affected: Dracut does not require the caller (Calamares in this case) to set the umask, it already does this automatically, and has been doing so since 2012 (since 2016 for one special case). See CVE-2012-4453 (https://github.com/dracutdevs/dracut/commit/e1b48995c26c4f06d1a718539cb1bd5b0179af91) and CVE-2016-8637 (https://github.com/dracutdevs/dracut/commit/0db98910a11c12a454eac4c8e86dc7a7bbc764a4).

Issue #1190 (CVE-2019-13178) affects all distributions regardless of initramfs generator though.

**Comment by kkofler** [comment]
Since the `initramfs` module was fixed and the `dracut` module is not affected, only the `initcpio` module remains to be fixed in upstream Calamares. If distributions have downstream modules for other initramfs generators, those may or may not be affected by this issue, depending on what the initramfs generator does.

**Comment by adriaandegroot** [comment]
![Screenshot_20190705_004330](https://user-images.githubusercontent.com/19431457/60689463-f486e700-9ebd-11e9-8118-b066d4f5e3fa.png)

I just installed lubuntu (using Calamares) and the initrd was readable by world, **even** from the *more-permissions* branch of Calamares, which does more work to keep the initrd readable only by root **and** sets `umask 077` before calling the update script. But at this point I don't think it's actually a Calamares issue:

 - in the **installed** system, I logged in, switched to a root bash
 - In `/boot`, make the initrd file 0600 and set `umask 077`
 - checked that the initrd had the right permissions and generated a new one
 - in **spite** of the umask, the generated initrd has world-readable permissions

So the (re)generation process is ignoring umask anyway. 

I was going to say "and the cryptfile isn't in there anyway, since `cpio -i -t < /boot/initrd` doesn't list it", but `unmkinitramfs` does something different, and does extract the key file.

**Comment by adriaandegroot** [comment]
The initramfs is multiple cpio archives, concatenated, so that's why a simple cpio-command won't read them all. The update-initramfs script does not mess with umask. It calls *mkinitramfs* (in /usr/sbin) which in turn creates an initrd with suffix *.new*. **That** file has insecure permissions, and is then moved over top of the existing initrd.

This really isn't a Calamares problem at all.

**Comment by adriaandegroot** [comment]
Line 3 of `/usr/sbin/mkinitramfs` in an installed lubuntu system reads

```
umask 0022
```

**Comment by adriaandegroot** [comment]
What Calamares **could** do (and I guess it must, but really this is a setting that should be applied at the Debian level) is append UMASK=0077 to `/etc/initramfs.conf` when LUKS is used, or perhaps always, as a security measure.

**Comment by adriaandegroot** [comment]
(that's `/etc/initramfs-tools/initramfs.conf`)

**Comment by adriaandegroot** [comment]
Suggestion from Tom Reyn (mentioned in downstream bug) **and** from Jonathan Carter **and** from Alf Gaida **and** from Kevin Kofler -- so fairly widely supported -- is the following:

 - distro's should fix up their configurations for initramfs to be more secure anyway, referring to CVE-2012-4453 as well (pointed out by Kevin).
 - Calamares can drop a configuration snippet in /etc/initramfs-tools/conf.d to do the actual work.

One issue is package updates (e.g. of initramfs-tools itself), but by using a configuration snippet -- separate file -- we avoid those because the snippets should be left alone.
