### ISSUE TITLE
Net install mode with feedback

### ISSUE THREAD

**Issue by jmrcpn** [calamares/calamares#1200]
During the install process (partition, set file system, etc.. ) the calamares page give 
real-time feed back and it is good.

This stop in case of installing package from net,  where you have a static message
stating (from memory) "installing package"

It would be nice to have a better feed back, describing packages which are uploaded
and installed.
For now  we have "92% completed, installing packages", and that for a rather long period
if the number of packages to install is substantial.

We are using Calamares within our distribution (Osukiss) and this a comment we are
hearing often.

**Comment by kkofler** [comment]
The issue there is, every distribution uses a different tool to install packages, which formats progress output differently, if it outputs it at all. There is already a lot of distro-specific code in the `packages` module to even just handle the different command syntaxes, see the lines starting at:
https://github.com/calamares/calamares/blob/36fe3ed188fbc4436eaa0719b1f292de340be870/src/modules/packages/main.py#L160
(and no, `pkcon` is not typically going to work in a chroot environment, so we usually need to use the native command, as per one of the classes below). Handling progress output too is going to make this even worse, and it has to be implemented and tested separately for each distribution. And if the tool does not output anything that allows estimating the overall progress, we are stuck anyway.

**Comment by jmrcpn** [comment]
Agree, it is not an easy task. I fully understand the constraint using "native" tools as 
as yum, zypper (we have select zypper), which give or not feed back, which are difficult 
to display on the calamares page.
Lets try to thinks out of the box....
Let say package install are space consuming, reporting available space on system,
(on each partition?, globally?), will give a feed back about "something is in progress" ....
That could be handle by a fully independent task started at same time as the
 Package manager task and stopped when install is reported completed...
In the mid time, it take control about the calamares screen and report about current available space....
make sense? possible??

**Comment by adriaandegroot** [comment]
This is **partly** addressed by the job-weights patches, which will give lengthy operations more "space" in the progress bar to play with. What it would need next is some way of getting information from the package manager; you could patch up the **one** class for your own package manager if you know how it works. That would be analogous to how unpackfs works: it runs rsync and reads stdout from rsync to report progress to Calamares.

**Comment by jmrcpn** [comment]
On 08/01/2019 09:55 AM, Adriaan de Groot wrote:
> This is *partly* addressed by the job-weights patches, which will give
> lengthy operations more "space" in the progress bar to play with. What
> it would need next is some way of getting information from the package
> manager; you could patch up the *one* class for your own package manager
> if you know how it works. That would be analogous to how unpackfs works:
> it runs rsync and reads stdout from rsync to report progress to Calamares.
>

Not sure I understand your proposal.
My guess is you propose to extract current "install" information from
the package manager (zypper in my case).

I checked python code
modules/packages/main.py
and it seems to me calamares designers made some
provision to have a kind of package install feedback.

;---------------------------------------------------------------------------- 

total_packages = 0  # For the entire job
completed_packages = 0  # Done so far for this job
group_packages = 0  # One group of packages from an -install or -remove 
entry
...
...
def pretty_name():
     if not group_packages:
         if (total_packages > 0):
             # Outside the context of an operation
             s = _("Processing packages (%(count)d / %(total)d)")
         else:
             s = _("Install packages.")
;-----------------------------------------------------------------------------

If this code is(|should be) working, then the problem is
to extract the current number (count) of package installed
(lets say, from an rpm count) and the expected (total)
packages to be installed. (May be I missed the link to feed
information within the package.conf file).

IMHO, we do not need a very accurate feedback, as long
the displayed is refreshing to show some kind of progress....
so having
"Processing packages xxx/yyy"
updated every 2 or 3 seconds is very good enough.

For now it stay "stuck" with 93% displayed while a (long)
network install is done.

-- 
seen "Linux from scratch" and looking for ISO files
www.osukiss.org

**Comment by adriaandegroot** [comment]
This is requested again in #1310.

There are three aspects to this request:
 - Making the installation phase have "enough space" in the progress bar for progress to be visible. This is where job-weights come in; current configuration is such that *unpackfs* has weight 12 and everything else (including netinstall / packages) has weight 1. That will become configurable at some point to support installers that do a lot of netinstall work.
 - Making the *packages* module produce better installation messages, preferably mentioning what package is being installed.
 - Obtaining progress information from the package-installation commands (e.g. `zypper` lists package names and *n/m* progress) as they run, and using that for progress reporting.

**Comment by adriaandegroot** [comment]
Adding this to the next milestone because it's related to progress reporting and job weights, but this **won't** necessarily solve the problem that the packages module needs to report progress, for there to be progress to report (that's a tautology; however, people who maintain the packages backends will have to handle package-manager output). It's likely that I'll implement progress for **some** package manager, because I'll be using neon or Manjaro and can futz with that.

**Comment by adriaandegroot** [comment]
So I've looked at this more closely and it's yucky, simply because the API offered to the Python modules is limited; or the Python module could do its own chroot calls and handle stdout and everything -- that's part of the **problem** with the Python modules that there's more than one way to do things and therefore they're done inconsistently. It also gets in the way of eventual no-root, because you have to chase down all the inconsistent ways of starting an application in the chroot.

So, ideally:
 - [ ] Port to C++
 - [ ] Expand API in System class to allow async use (maybe just a slot to call)
 - [ ] Use the async API to read stdout from zypper

**Comment by adriaandegroot** [comment]
The **infrastructure** is now there, in the form of the new function exposed to Python modules, `libcalamares.utils.target_env_process_output()` which calls a callback function for lines received from the command it runs. That can be used to update progress information during package installation. However, actually **doing** that work is up to the individual package-manager maintainers (if I'm feeling charitable, I may do something for ArcoLinux, since they heavily use netinstall and have quick testing turn-around)
