### ISSUE TITLE
Allow command substitutions for GRUB_DISTRIBUTOR

### ISSUE THREAD

**Issue by apt-ghetto** [calamares/calamares#1201]
**Is your feature request related to a problem? Please describe.**
In _branding.desc_ or _bootloader.conf_, the distributor can set the value for the `GRUB_DISTRIBUTOR` variable in /etc/default/grub.

Unfortunately, it looks like it is currently not possible to use command substitutions.
For example, Ubuntu sets the value to
```
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
```
or Fedora:
```
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
```

**Describe the solution you'd like**
I prefer a solution, where the value for `GRUB_DISTRIBUTOR` is set character by character (without newline?) as it is defined in `bootloaderEntryName`.

**Additional context**
The variable GRUB_DISTRIBUTOR is not only used to set the label in the Grub menu, but it is also used, when you (re-)install Grub on an ESP. This leads to problems, if the values of `efibootloaderId` and `bootloaderEntryName` differ.

**Comment by kkofler** [comment]
To clarify the situation on Fedora: The `efiBootloaderId` is **always** `fedora` on Fedora and any Fedora Remix. This is hardcoded directly in the `grub2` package (it installs files to that directory), so if you want to change the `efiBootloaderId` setting in Calamares, you have to rebuild `grub2`. `grub2-install` is never run on UEFI systems in Fedora. Instead, the package installs the files directly to the location in the ESP expected by `shim`, and `shim` is what gets installed (using `efibootmgr`). That is also why the directory is hardcoded. Thus, `GRUB_DISTRIBUTOR` is used only for display purposes in the menu. (We run `grub2-mkconfig`, but not `grub2-install`.) Hence, it is perfectly fine to have the `bootloaderEntryName`/`GRUB_DISTRIBUTOR` differ from the `efiBootloaderId`. It will be the same on a system installed with Anaconda, where the above `sed` is used for `GRUB_DISTRIBUTOR` (resulting in essentially the same value that my Calamares package sets `bootloaderEntryName` to; in my package, it just happens at the Calamares package install time rather than at each system boot, but that should not really matter), but the EFI bootloader ID is always `fedora` (as explained above).

The situation on Fedora is actually the whole reason why I introduced a separate `efiBootloaderId` setting to begin with, as opposed to always using `bootloaderEntryName`.

**Comment by apt-ghetto** [comment]
@kkofler Thank you for the interesting explanation.

The background for my "Additional context" is [Launchpad bug 1833490](https://bugs.launchpad.net/ubuntu/+source/calamares-settings-ubuntu/+bug/1833490).

After digging a bit in the code, I don't see a reason, why `GRUB_DISTRIBUTOR` is changed, when the key `overwrite`in _grubcfg.conf_ is set to `false`.
This led me to this, maybe not beautiful, but short workaround/improvement/idea to change [grubcfg main.py](https://github.com/calamares/calamares/blob/master/src/modules/grubcfg/main.py#L173) as follows:
``` python3
            elif (lines[i].startswith("#GRUB_DISTRIBUTOR")
                   or lines[i].startswith("GRUB_DISTRIBUTOR")):
                if "doNotOverwrite" != distributor:
                    lines[i] = distributor_line
                have_distributor_line = True
```

This works, if `bootloaderEntryName: doNotOverwrite` is set.

**Comment by kkofler** [comment]
FYI, this new `keepDistributor` setting will not be of any use on Fedora because on Fedora, it is the installer's task to create `grub.cfg` from scratch, which is why I implemented support for creating `grub.cfg` from scratch 5 years ago. (See issue #128 and commit 1499963920f96c8871bb5680648c0055134cbb7c.) But if it helps other distributions, I have no objections to having this setting. (Fedora works fine with `keepDistributor: false` anyway, even if the implementation is not identical to how Anaconda does it, see my comment above.)

**Comment by adriaandegroot** [comment]
There are two "modes", if you will, for this module:

 - create (or overwrite) the file `grub.cfg`
 - edit an existing file `grub.cfg`

Fedora is in the first group. That's fine. It doesn't need any help. It doesn't need a weird *GRUB_DISTRIBUTOR* setting. Frankly I don't see why anyone else would need a weird dynamic setting for that, but I guess that's when you update from *Grubby Gopher* to *Hazardous Hamster* that the grub settings follow. I don't really care.

The second group, which OP is apparently in, want more control of how Calamares edits grub.cfg. It is already careful about kernel settings, and disk-encryption is finicky so Calamares needs to be in full control there. But the distribution line? Whatever. If it's already set, you can ask Calamares to leave it alone.

Note that OP's modification requires a specific setting in `branding.desc` that might be surprising in other contexts (you'd need to specify an extra setting in `bootloader.conf` to avoid silly EFI boot-menu entries).
