### ISSUE TITLE
grub-pc has no installation candidate

### ISSUE THREAD

**Issue by makorne** [calamares/calamares#1207]
**Describe the bug**
grub-pc has no installation candidate
Installation with encryption fail.

**To Reproduce**
    Get current debian-live-testing-amd64-cinnamon.iso
    Use default settings and choose encryption
    Try to install

**Expected behavior**
Complete installation

**Screenshots and Logs**

![Screenshot_2019-07-29_18-48-11](https://user-images.githubusercontent.com/26540498/62076340-f9c62000-b236-11e9-9f66-c0b9f82b3ee7.png)

**Comment by kkofler** [comment]
This is really a downstream Debian bug and should be reported there.

**Comment by adriaandegroot** [comment]
@highvoltage is this something you can look at?

**Comment by highvoltage** [comment]
I've tested this before and haven't had this problem before.

Can you please share as much information as possible?

- How much RAM you have
- Disk space and partition layout
- Confirm whether you booted EFI or legacy and which installation method you used
- Check that the checksum of your iso your downloaded matches the one on the website

grub-pc is available on the installation media so it should have no problem installing, so something odd is definitely happening in that specific case.

**Comment by adriaandegroot** [comment]
Closing with feedback-timeout.

**Comment by Loggus66** [comment]
Yup, same for me. Also a live CD of Debian 11. I believe the error happens because Calamares chroots into the mounted target partition and tries to install grub-pc via apt or apt-get, in that case there will be the "grub-pc has no installation candidate" error. However, if I run "apt-get update" and _then_ "apt-get install grub-pc" inside the chroot manually, it installs fine.
8G RAM
Layout for the target disk is 500M /boot, ~118G /
Legacy boot, installing on MBR
sha256sum matches the one provided for debian-live-11.0.0-amd64-kde.iso

**Comment by highvoltage** [comment]
@Loggus66 Hmm, this bug was fixed quite some time ago, it's odd that you saw it on a Debian 11 ISO because I tested them just a few weeks ago and they were still fine then, but I'll look into this again and also specifically do another check with encryption enabled.

**Comment by highvoltage** [comment]
@Loggus66 Are you able to re-test without a seperate /boot? I remember we used to have a release not about not adding a seperate /boot when using full-disk encryption with calamares (since it uses GRUB itself to unlock, so /boot can (and should) be on / directly). I suppose a reminder of that within calamares would also be helpful.

**Comment by kkofler** [comment]
The Calamares full disk encryption setup is **supposed** to work with a separate `/boot` (though it may or may not be broken on Debian). The way it is intended to work is that GRUB unlocks `/boot`, which contains a keyfile, which is then used to unlock `/` without a second passphrase prompt.

**Comment by kkofler** [comment]
(but the setup without a separate `/boot` **should** also work these days!)

**Comment by Loggus66** [comment]
Tested it, same result.
Took some time to fix it, but there's a file called /usr/sbin/bootloader-config which belongs to the calamares-settings-debian package. I had to insert the line for apt-get update, so now it looks like
```shell
if [ -d /sys/firmware/efi/efivars ]; then
    echo " * Installing grub-efi (uefi)..."
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get update
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get -y install grub-efi-amd64 cryptsetup keyutils
else
    echo " * install grub... (bios)"
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get update
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get -y install grub-pc cryptsetup keyutils
fi
```
Maybe it's not the most elegant way to fix it by executing two chroot commands but it works.
Corresponding file is likely [there](https://salsa.debian.org/live-team/calamares-settings-debian/-/blob/master/scripts/bootloader-config) but since it prompts to login, I'll just leave my comment here.

**Comment by highvoltage** [comment]
Interesting that that apt-get update would fix it because it's supposed to already happen in the sources-media script. Will check that out.

**Comment by rosoau** [comment]
Hoping that this may help somebody. Installing Ubuntu Jammy Mod on an older BIOS PC
Since I was able to manually install grub-pc and then proceed with calamares;
I found that leaving out the "chroot $CHROOT" finally did the job.
grub-pc needs to be installed on our Live media.
So it does not need the chroot bit.
/usr/sbin/bootloader-config; a section of the file:
--------------------------------------------------------------
if [ -d /sys/firmware/efi/efivars ]; then
    echo " * Installing grub-efi (uefi)..."
    DEBIAN_FRONTEND=noninteractive  apt-get update
    DEBIAN_FRONTEND=noninteractive  apt-get -y install grub-efi-amd64 cryptsetup keyutils
else
    echo " * install grub... (bios)"
    DEBIAN_FRONTEND=noninteractive  apt-get update
    DEBIAN_FRONTEND=noninteractive  apt-get -y install grub-pc cryptsetup keyutils
fi
-------------------------------------------------------------
By default we already have grub-efi-amd64 installed,
which then would also be on the target system from the squashfs. There we also have:
grub-common grub-efi grub-efi-amd64 grub-efi-amd64-bin grub-pc-bin grub2-common
Updating grub works via: "update-grub" (/usr/sbin/update-grub), which is part of grub2-common
If one needs to re-install grub on the target system, yes, then it would need grub-pc installed
Mostly the usage would be to update grub and that is covered with grub2-common
PS PinguyBuilder removes apt and then reinstalls it on firstboot (consequence?)

**Comment by kkofler** [comment]
`grub-pc` should be present on the installed system, so that it can be reinstalled by the user when needed.

The issue that GRUB-PC (BIOS) and GRUB-(U)EFI conflict (cannot be installed together) is a Debian/Ubuntu-specific packaging issue. On any other distribution, they can coexist just fine. As I already wrote 3 years ago, this needs to be fixed in the downstream GRUB packaging. There is no valid reason for the packages to conflict.

**Comment by highvoltage** [comment]
Yep no bug here really.

On Debian media, we ship both debian-installer (d-i) and calamares, since d-i is a really tiny core system, it needs to install nearly everything from packages (including grub), so when we have a calamares that co-exists with d-i on media, we also install the grub packages afterwards like d-i does. If you're on media that doesn't have d-i and just has calamares, then you can just skip that module alltogether and ship the packages in your squashfs, that's quite easy for any derivative to do in their calamares-settings package.
