### ISSUE TITLE
[Support Question] How to customized desktop for newly created user?

### ISSUE THREAD

**Issue by kevinsmia1939** [calamares/calamares#1255]
Hello,

So I have been using KIWI (software that create distros from opensuse) to make live ISO and use Calamares to install the live ISO.

The problem is that, I can set username (banana, for example) and password for the live ISO on KIWI and put config files for customization (changing desktop background, themes, etc) which the config files is under banana user. 

But when installing live ISO with Calamares, new user is created. Which while does not delete banana user data, it replace it, removing all customization when boot up. 

Can I have Calamares create new user but copy or replace, banana user name keeping all the config files like desktop background, themes, etc.

Thanks

**Comment by abucodonosor** [comment]
That is not calamares businesses but your one in packaging.

A new user will have files copied over from /etc/skel , meaning if you want all newly created
user to have the same configurations for desktop's, and your distribution defaults you have to provide 
files into /etc/skel, and that is a packaging thing, not a calamares one.

Adding support to copy live home should be easy but that won't help you in any way and here is why:

1) You have 'fix' those files in .config or .local for everything may be associated with USERNAME or 
    $HOME path ( not an easy task and if you mess that up your new user has broken desktop)
2)  Any newly created user on the installed system won't have the same configuration, resulting in
    what you see right now.

**Comment by agaida** [comment]
@abucodonosor - one don't need calamares upstream to do this job. it would be more or less a simple script. Second thought: Customization at user level is fundamentally broken by design - just create another user as Linux is a system that can handle more than one user well :smile:

**Comment by abucodonosor** [comment]
@agaida 

sure you can use XDG, scripts, first-boot apps, write your own-sw etc but still, the way to have it painless and consistent for any newly created user is the usage of /etc/skel, especially if you are not a programmer or a developer.

**Comment by kevinsmia1939** [comment]
Thanks, will try copy config to etc/skel

**Comment by adriaandegroot** [comment]
There's a couple of things here:

 - creating a new user in the target system (that uses /etc/skel)
 - setting look-and-feel for the user in the target system, whatever that user is
 - (possibly? I can't make it out from the problem report) user settings copied into the target system are being replaced

For setting look-and-feel you *might* also use the plasmalnf module (plasma-only, of course) but that probably won't fill up everything you want.

I can imagine using unpackfs to extract a "skeleton" image to the user's home-dir. That would require some special coding for "extract-to-user" (but avoids setting up /etc/skel so that a particular lnf is set for *every* user ever added to the system).

**Comment by peter-kl** [comment]
Yes like @abucodonosor said,  put your configs for new users at /etc/skel , working opensuse here too and it works.
