### ISSUE TITLE
[Request] Configuration tools for Calamares with the Modern Kernels with chroot refinement/improvement

### ISSUE THREAD

**Issue by blackcrack** [calamares/calamares#1264]
**Is your feature request related to a problem? Please describe.**
[..] I Install the System and i can not fully configuring the System like i want ..

**Describe the solution you'd like**
behind the installation, directly chroot and start Configurationplugins directly in the "Install" Service
and behind the System pull on Hardisk, should start the Configuration-Plug/snapins : 

* I want have a possible for Configuring for Users (more as one), 
* smbd (for my basement for WinNT Clients like Reactos) to be able by create users PAM, directly configurate smbd.ini and need configfiles for the users of PAM with UID and GID on the FS, 
* Apache configuration(an Configurator for Userweb ~%USER% an Grafikal configurator for php.ini as example and a Subdomain creator in easy way),
* exports, nfs including-configurator, so an Configurator as NFS-Client and a an Configurator as NFS-Server. 
* Configurator for a sendmail Mailserver or other Mailpossibility (this is at the same time a check that it functions behind the install and reboot as with the other points)
* enabling different Services and adjusting the FW directly
* and so on, all what it should be setting up before it first boot

**Additional context**
With the Modern Kernels it's now possible to have a -full- chroot and be in able directly 
manipulating configurations files and start a installing Xserver/wayland because it is
possible to chroot the installed system and directly use the installed system

* Install the Kernel of the Install System
* use/reread the Kernel of the installed chrooted System
=> chroot to the installed system,
=> configure the OS directly in the Installer (Here Calamares)
=> restart/reread the modern Kernel from the chrooted System and set up the / path
=> restart/reread the Services from the chrooted System and set up the / path
=> restart the chrooted XServer/Wayland from the chrooted Path /
and use the chroot space directly as Systemspace "/ "
=> work directly in the chrooted System (no reboot need anymore)
is this possible ? (normally yes, with the modern refinement chroot Kernel)
=> and remove the Install Disk/Volume/Media without boot

Root/Admins have the possibility for configuring the installed System directly further and install extra packet's (deb/rpm) on the "chroot '/ ' " without one boot at start of the boot up to a running system..
no boot imho needed .. with modern kernels and the improved possibility's of chroot in the kernel.

therewith it is also directly possibility for let run the Firewall and AV by chrooted System directly 
behind the running/started the chroot system.. reread kernel, restart systemd, restart the X-Server
and no fully warm boot more needed. Only.. by Software .

best regards
Blacky

**Comment by abucodonosor** [comment]
Other than  "I want have a possible for Configuring for Users (more as one),"
nothing you request here belong to calamares.

You can develop some OEM/first boot tool doing these adjustments to your system

**Comment by blackcrack** [comment]
Hi @abucodonosor and this decide you.. alone ? Why want you not speak this in Group, if this be a possibility or not, for a better Calamares .. there be 49 Contributors and One Chairman @adriaandegroot , is maybe this not better to let this decide in Group ?.. 
best regards
Blacky

**Comment by abucodonosor** [comment]
@blackcrack 

See I know these requests already from OpenMandriva :-)

I don't decide anything alone, everyone is free to add his comment.

Configuring 'packages' is not the job of calamares itself.
Moreover, what you request here are GUI configuration tools for
apache, nfs, samba, the kernel, mail servers, chroots and whatever else.

Write these GUI tools and we can add some first boot server tool to run these,
if found or configured on your distribution.

**Comment by adriaandegroot** [comment]
This should be a bunch of separate issues, if anything. In general: PRs are welcome. It may take some wrangling t make things general, but non-general things can end up in other repositories (either downstream forks with extra modules, or the calamares-extensions repo).

 - Add multiple users has an issue, #526, and a PR that no longer merges (it was old already two years ago). I don't see it as a really important one for the most-common "install for one user" scenario, and you can always add users once the target system is up (e.g. via KDE's User Management tool).
 - For other configuration tasks, it's not clear to me if there are existing GUI tools to do that work.
 - Services configuration already has a module (in Python, unfortunately). Making that a ViewModule with a checkbox-like UI shouldn't be that hard to do.

Developing a UI for the later configuration tasks seems out-of-scope for Calamares. It could be an interesting exercise in UI sharing, to build such a tool though.

An "easy" way of leveraging GUI configuration tools installed into the target system is using shellprocess and running the GUI there. It may take some doing to export DISPLAY properly and get permissions right, so that would be a bit of an experiment. Until I have a more concrete use-case I do not see where this is headed.

Now, the *no reboot* approach **is** intriguing. After setting up the target system, restart system into the target -- and possibly run Calamares again there, in OEM (post-install) mode for setup. Bear in mind that OEM mode is kind of incomplete, and needs lots of work (there's various issues for that). I can imagine introducing a different *finished* module to handle that (or wrangling the existing module with more options), but that too should be a separate issue **and** really come with a PR.

Closing as "Should be filed as separate issues, preferably with PRs attached".
