### ISSUE TITLE
Feature request : netinstall configuration

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1269]
This is how it starts up now.

![netmodule ](https://user-images.githubusercontent.com/36679406/68539992-a910a800-038b-11ea-83f7-695d0a4f5dbb.png)

This is how we would like to have it.
Group is opened by default.

![netmodule-right](https://user-images.githubusercontent.com/36679406/68540004-ce051b00-038b-11ea-8300-eba7e9b954d2.png)

Can we add text to the bottom of this page?
Can we change the font - bold - size - just here
Can we make the selection window height smaller so we can get text under there?
Can we have a nice big capital text at the top?  In our case - choose your kernel - if you do not choose anything you will get the linux kernel

And what is most important. Thanks to make it work technically.
Lets make it awesome now.

**Comment by abucodonosor** [comment]
To make it awesome, it has to be re-written.

**Comment by abucodonosor** [comment]
But what we can do ( I don't know whatever this is already supported ) is to allow customize
the TreeView. See an example there:

https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtreeview

Expanding everything by default is a bad idea since you can have sub-items and
it will look horrible with a lot of groups.

**Comment by arcolinuxz** [comment]
Not expanding everything by default - all groups. But expanding per group. Just need the one.

**Comment by adriaandegroot** [comment]
Titles and labels were already done, this adds `expanding` to the keys a group can understand.
