### ISSUE TITLE
Feature request : netinstall - just one choice in group selection

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1270]
Calamares 3.2.16
Is it possible to tell to this group that you can select only one of them?

![nvidia-choice](https://user-images.githubusercontent.com/36679406/68540245-d90d7a80-038e-11ea-9c8a-fb4ad65b64e0.png)

**Comment by abucodonosor** [comment]
No is not possible

**Comment by arcolinuxz** [comment]
would be a great asset.

**Comment by adriaandegroot** [comment]
That's more a thing for the *packagechooser* module, which tries to have a nice UI on top of much more limited package selection. Packagechooser supports this workflow. I see the netinstall module now as a more low-level tool rather than something you really want to show the user.

**Comment by demmm** [comment]
Closing with won't implement, since it already is working as asked in the package chooser module.  In case not clear, here is an image of the package chooser GUI with several (unique) options:
![Screenshot_20200207_202805](https://user-images.githubusercontent.com/5360485/74087471-e1a84680-4a8c-11ea-987b-aba7345e1f75.png)
