### ISSUE TITLE
If you select license module and then unselect - next button is grayed out

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1271]
There is no way to continue if you first accept the license and then change your mind and unselect the license again.

Next button is gray. 

![unselect-nvidia](https://user-images.githubusercontent.com/36679406/68544163-96649600-03c0-11ea-933f-8b0204570af3.png)

**Comment by adriaandegroot** [comment]
Can't reproduce with master; I'll need more information or an image where this actually happens.

**Comment by arcolinuxz** [comment]
I will make a video

**Comment by arcolinuxz** [comment]
IF you select the button nvidia - the nvidia packages will be installed lateron.
Once you selected and moved on, you can not go back and unselect anymore.
Calamers button is gray and you are stuck.

https://vimeo.com/373426706

Password:  calamares

**Comment by BradHeff** [comment]
i can confirm this issue, clicking back button then proceeding forward makes the button enabled again.

**Comment by adriaandegroot** [comment]
With the video, confirmed.

Scenario:
 - have just one license item that is not required
 - start calamares, go through to the license page
 - because it's not required, note:
   - you can leave the license-accept box unticked, and continue
   - or tick it, and continue
 - from the next page, go **back** and untick the box if you ticked it previously
 - the *next* button is greyed out even though the license is optional.

**Comment by adriaandegroot** [comment]
Thanks for reporting with such a clear video, that really helped to track this down and reproduce the problem.
