### ISSUE TITLE
default partitioning option

### ISSUE THREAD

**Issue by wxl** [calamares/calamares#1297]
**Is your feature request related to a problem? Please describe.**
You know what I love about Calamares? How darn fast it is. It's so easy to get a system to install. I can practically just keep clicking next and call it good. The one thing I wish I didn't have to select was the radio button for the partitioning option. There's one I almost always pick and it would be nice if it were selected for me.

**Describe the solution you'd like**
Allow for a default option in the partitioning module.

**Describe alternatives you've considered**
Not necessarily alternatives, but some thoughts about where this "simple" solution might go wrong:
 * Let's say we wanted "Erase" to be default but it just so happened that a swap was automounted (ugh) so it didn't appear. In this case, I think it would need to default to the current state of affairs: no default.
 * There's the concern about whether or not the user will pay attention long enough to actually make an appropriate selection. That could equally apply to the keyboard layout or location, though, so it's probably a moot point. Plus, given the fact that deployer would be making an informed choice for the user, this is not likely to be an issue.

**Comment by kkofler** [comment]
The problem is, what should the default be? I think it is not a good idea to erase a disk by default without an explicit user request.

**Comment by wxl** [comment]
Sorry for not making myself clear. The request is for an optional default which can be selected by the deployer. A config might look like:

```
# Default partioning option
#
# Calamares shows all available partitioning
# layouts by default, but none are selected.
# To set a default, set to true and select the
# default. If the default is not available, it will
# revert back to having none selected. 
defaultPartitioning: false
# 
# Options include:
#  * erase
#  * replace
#  * alongside
#  * manual (if enabled)
#  * custom (if defined): use name field
#defaultLayout: none
```

**Comment by adriaandegroot** [comment]
This is mostly a matter of untangling bits (see branch issue-1297) where the ChoicePage is initialized with `NoChoice` .. we can pass that in via the Config object.

**Comment by adriaandegroot** [comment]
I picked this interpretation of the issue:

> Make it configurable which of the four buttons is selected when the user arrives on the partitioning choice page.
> If the configured button which should be selected, is disabled / hidden for some reason, then select none of them (like right now, none is selected on arrival).

Spent half a day on it and got mostly nowhere. I'm going to drop it from the milestone, because it's a want-to-have feature and it's turning into a big time sink.

Part of the problem is that the UI *is* the configuration, and there are a lot of asynchronous moving parts that mix UI manipulation with configuration bits. Hiding a radio button disables an option, but only if other code takes the visibility of the UI into account. Various changes to the internal data structures -- like changing which device to install on -- will reset the visibility of the radio buttons multiple times, and I can't find a place to safely say "select this option if it is visible". Again, because selecting an option can reset all kinds of internals that are closely tied to the UI.

So, backburner.

While working on this, I've also been thinking about what Keving said: which selections here actually make sense? Erase is dangerous. Replace and Alongside still need you to select a partition to use, and Manual needs you to click to continue to the manual partitioning page. All-in-all it seems like a lot of work to save one click. (Note that in **general**, work on refactoring business logic out of the UI and into the Config class for a module is welcome and necessary: we don't want to be stuck with this specific UI forever)

**Comment by adriaandegroot** [comment]
```
b518ef7dfe (Adriaan de Groot 2020-09-28 15:32:47 +0200  93) initialPartitioningChoice: none
```

It looks like this was implemented (and not mentioned in the release notes) a long time back.
