### ISSUE TITLE
netinstall module: support "local"

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1319]
It's a bit silly to only support external files for netinstall, when we already have a YAML file at hand, namely the configuration file itself. Let's add a totally-bogus *local* scheme, or case where we set the URL to that specific string, and then load the packages from the `.conf` file instead of externally. For netinstall-used-as-a-package-selection this speeds things up.

## Sub-steps

 - [x] Remove superfluous ItemData from PackageTreeItem
 - [x] Add constructor for PTI from pre-script, package, post-script
 - [x] Add constructor for PTI from QVariant
 - [x] Rationalize PackageModel::setupModelData() to use constructors, build from QVariant
 - [ ] Untangle data-processing in NetInstallPage
 - [x] Distinguish URL scheme in NetInstallViewStep:SetConfigurationMap

**Comment by kkofler** [comment]
Why is `file:` with a separate local file not good enough?

And also, how can we then ensure that users only get shown the netinstall when their Internet connection is working? Using a `http`(`s`) URL ensures that by design (which is the main reason why I ended up using that for Kannolo rather than `file` as originally intended, though having the option to update the list even for already released ISOs, especially if the repository contents change, which can happen in Fedora, was a nice bonus of the online approach too).

**Comment by adriaandegroot** [comment]
`file:` is good enough, but this is *more convenient*: one single file to configure the netinstall module, rather than two. The code is also a tangle of building-models and parsing-data and doing-UI, which those sub-steps do some part in untangling.

**Comment by killajoe** [comment]
Take a look what EndeavourOS is doing:
We do create different configuration for offline and online install, so that you can manually choose before calamares starts.
