### ISSUE TITLE
Adding additional translations strings for Distro Specific additions

### ISSUE THREAD

**Issue by samurailostinjapan** [calamares/calamares#1367]
Distro: Arcolinux
Calamares Version 3.2.20

As you guys may already know Erik has been adding some additional modules to Calamares to better group the packages and as a result, they do not have the related the translations. As this is very distro-specific; is there a way we can add the translations or would we need to send them back to you guys to add them for the next release? If this is possible for us to do, can you please provide the necessary steps that we would need to follow to add the translations.
![Calamares-Japanese](https://user-images.githubusercontent.com/10843832/78456123-d82e0a00-76dc-11ea-903a-542f3e8d4a6b.png)

Thanks,
John

**Comment by erikdubois** [comment]
Would be great if other distros can reuse words for translation in their distro?

**Comment by abucodonosor** [comment]
Custom modules translations are not upstream businesses.

**Comment by erikdubois** [comment]
but names like these are used by everyone - if people want to assist in translations would that not benefit Calamares a a whole

**Comment by adriaandegroot** [comment]
The *netinstall* module already contains a table of what-I-guessed-would-be-common-names for the packages, so that the translations can help. A PR expanding that table -- within reason -- would be be acceptable.

Note that the whole setup of the netinstall module *supports* translations outside of Calamares itself: you need some infrastructure to deal with the YAML bits, but you can use `title[jp]` and `sidebar[jp]` keys in `netinstall.conf` to set translations.

**Comment by adriaandegroot** [comment]
https://github.com/calamares/calamares/blob/master/src/modules/netinstall/netinstall.conf#L50

That commented-out line shows how you would add translations for the label for an arbitrary netinstall instance.
