### ISSUE TITLE
Fakaofo Geoip map wrong timezone

### ISSUE THREAD

**Issue by FLVAL** [calamares/calamares#1374]
Hi _!_ 
I noticed that when I click on Fakaofo which belongs to New Zealand, it's showing **calamares/src/modules/locale/images/timezone_10.0.png** where if I'm not wrong it should show (+13)  **calamares/src/modules/locale/images/timezone_-11.0.png**

If you confirm it and you need the pictures to be modified, I could prepare them.
It asks to modify the **timezone_10.0.png** in removing Fakaofo then modify **timezone_-11.0.png** in adding Fakaofo.

Tested on Endeavouros and works.

1. Go to 'Locale page'
2. Click on 'Geoip Map on Fakaofo'
3. See error timezone displayed

**Expected behavior**
Show **calamares/src/modules/locale/images/timezone_-11.0.png** when click on Fakaofo

**Screenshots and Logs**
![fakaofo_01](https://user-images.githubusercontent.com/56921008/79085562-5c196f00-7d39-11ea-92eb-ceffdc3b2be4.png)

![fakaofo_02](https://user-images.githubusercontent.com/56921008/79085565-5de33280-7d39-11ea-8ba5-27d407ceab3e.png)

**Additional context**
Maybe 5 or 6 timezone pictures in Geoip are indexed where it's not necessary to work.

Thanks for your great work on Calamares.

FLVAL EndeavourOS

**Comment by adriaandegroot** [comment]
Can confirm (at least, that clicking Fakaofo shows the wrong zone).

If you build Calamares with option *DEBUG_TIMEZONES* (in master since just now; older versions need you to fiddle around with `_enable_debug_flags` in the top-level CMakeLists.txt) then when you click on a zone it tells you where it finds the zone.

Here's a log with that flag enabled:

```
11:24:59 [6]: void TimeZoneWidget::setCurrentLocation(const CalamaresUtils::Locale::TZZone *)
    Setting location "Pacific" "Enderbury" ( "KI" @ -3.13333 N -171.083 E ) 
11:24:59 [6]:  ..  pixel x 770 pixel y 218 
11:24:59 [6]:  ..  First zone found 37 "-11.0" 
11:24:59 [6]: void TimeZoneWidget::setCurrentLocation(const CalamaresUtils::Locale::TZZone *)
    Setting location "Pacific" "Fakaofo" ( "TK" @ -9.36667 N -171.233 E ) 
11:24:59 [6]:  ..  pixel x 770 pixel y 231 
11:24:59 [6]:  ..  First zone found 16 "10.0" 
11:24:59 [6]:  ..  Also in zone 37 "-11.0" 
```

So you can see that the pixel is in two different zone-images. To fix, edit the PNGs, putting a transparent, I think, pixel at that spot (x,y are shown in the log) in the zone where you **don't** want it to show up.

See also commits 4bacafb41102252321dbcb30235131fca0e5b8b0 and e0988a5e1970691a5d487fb248a6f1c9a196fca5 where I did something similar.

For background: originally these were sharply-defined images; then sometime in the past the images were resized when the Calamares UI changed, and that made them "fuzzy" and some pixels overlap.

**Comment by adriaandegroot** [comment]
I finally sat down to write a test that highlights these items. If you build Calamares from git master, you can run the *localetest* test by hand: cd into the build directory, then run the executable `localetest` you find there.

It will spit out the test results, and especially log the zones with problems: a problem here means "location is claimed by more than one zone". Here's part of the output, for part of the Pacific (there are 97 problems in all).

```
16:24:44 [6]: void LocaleTests::testTZImages()
    Region "Pacific" zones # 38 
16:24:44 [6]:  ..  Zone "Chatham" QPoint(758,303) 
16:24:44 [6]:  ..  First zone found 20 "12.0" 
16:24:44 [6]:  ..  Also in zone 21 "12.75" 
16:24:44 [6]:  ..  Zone "Easter" QPoint(124,268) 
16:24:44 [6]:  ..  First zone found 31 "-6.0" 
16:24:44 [6]:  ..  Also in zone 32 "-7.0" 
16:24:44 [6]:  ..  Zone "Fakaofo" QPoint(770,231) 
16:24:44 [6]:  ..  First zone found 16 "10.0" 
16:24:44 [6]:  ..  Also in zone 37 "-11.0" 
```

The last item is Fakaofo, which you originally noticed; I don't know where Easter Island and Chatham Island are supposed to be located, but for both there is *potentially* a problem.

If you edit the PNG in the source directory, then you can re-run the test to see if you've fixed it.

**Comment by adriaandegroot** [comment]
So, @FLVAL , I'm gently putting this on your plate, if you would be so kind as to chase that test and the timezone images. Not all over the overlaps have to be a problem for the user -- Calamares just grabs the first zone it finds, so if the zone images happen to be loaded in a different order then you wouldn't notice this as a user.

**Comment by FLVAL** [comment]
Great, thanks a lot for your explanation, I will try to test the _localetest_ it's interesting the possibilities, and would be very helpful to find the wrong pixel on map.

The 2 zones you found here correspond exactly for Kafaofo. To get it works I had to remove pixels from **timezone_10.0.png**.

> Zone "Fakaofo" QPoint(770,231) 
> First zone found 16 "**10.0**" 
> Also in zone 37 "**-11.0**"

Calamares bring already what we need on Geoip, I found this Kafaofo just because I was creating each timezone on EndeavourOS way to understand how it works. I'm really not sure that one day someone from Fakaofo would install it ! but let's say it could be...

I will send you .png for Kafaofo for update on Calamares like I saw they did on existing issue you showed me. Then if I found others pixels interesting to change on timezone for EndeavourOS I will directly do it for Calamares in the same time, now that my settings are working well on Gimp for it.

Thanks again for your great work.

**Comment by adriaandegroot** [comment]
Thanks, I'll look forward to your image patches (you can PR them, or email the images directly to me if you like).

Now that I look closely, it's not "just" distant locations. Dublin is one of the problem locations highlighted by the test:

```
14:31:40 [6]: void LocaleTests::testTZImages()
    Region "Europe" zones # 60 
14:31:40 [6]:  ..  Zone "Dublin" QPoint(347,110) 
14:31:40 [6]:  ..  First zone found 0 "0.0" 
14:31:40 [6]:  ..  Also in zone 23 "-1.0" 
14:31:40 [6]:  ..  Zone "Gibraltar" QPoint(349,144) 
14:31:40 [6]:  ..  First zone found 0 "0.0" 
14:31:40 [6]:  ..  Also in zone 1 "1.0" 
14:31:40 [6]:  ..  Zone "Guernsey" QPoint(355,118) 
14:31:40 [6]:  ..  First zone found 0 "0.0" 
14:31:40 [6]:  ..  Also in zone 1 "1.0" 
14:31:40 [6]:  ..  Zone "Jersey" QPoint(356,118) 
14:31:40 [6]:  ..  First zone found 0 "0.0" 
14:31:40 [6]:  ..  Also in zone 1 "1.0" 
14:31:40 [6]:  ..  Zone "Lisbon" QPoint(341,139) 
14:31:40 [6]:  ..  First zone found 0 "0.0" 
14:31:40 [6]:  ..  Also in zone 23 "-1.0" 
14:31:40 [6]:  ..  Zone "Vilnius" QPoint(415,105) 
14:31:40 [6]:  ..  First zone found 1 "1.0" 
14:31:40 [6]:  ..  Also in zone 2 "2.0" 
```

In Dublin's case, though, it is really in GMT (0.0) so Calamares picks the right zone for it; that pixel should be pulled out of the -1 zone image to avoid the possibility of confusion.

 - Dublin is in 0 (-1 needs editing)
 - Gibraltar should be 1.0 (0 needs editing)
 - Guernsey and Jersey are in 0 (1.0 needs editing)
 - Lisbon is in 0 (-1 needs editing)
 - Vilnius should be in 2 (1 needs editing)

**Comment by FLVAL** [comment]
Sorry Adriaan de Groot for the time answer ! I looked yesterday night and tested with localetest but it returns me only 0 everywhere, no detection !

I'm not an expert still in PKGBUILD, but @fernandomaroto is helping me right now so will give you a feedback very soon...

In waiting here are the 2 pictures about Kafaofo for Calamares, I removed the pixels on **timezone_10.0.png** then I added pixels on **timezone_-11.0.png**, let me know if your pixel detection tool accepts them as good ?

**Comment by FLVAL** [comment]
Adriaan, @fernandomaroto helped me to test your detection tool then it worked.
We obtains like you 97 in all : 

```
23:28:27 [6]:  ..  Zone "Norfolk" QPoint(725,272) 
23:28:27 [6]:  ..  First zone found 18 "11.0" 
23:28:27 [6]:  ..  Also in zone 19 "11.5" 
23:28:27 [6]:  ..  Zone "Pohnpei" QPoint(703,199) 
23:28:27 [6]:  ..  First zone found 16 "10.0" 
23:28:27 [6]:  ..  Also in zone 18 "11.0" 
23:28:27 [6]:  ..  Zone "Rarotonga" QPoint(14,256) 
23:28:27 [6]:  ..  First zone found 36 "-10.0" 
23:28:27 [6]:  ..  Also in zone 37 "-11.0" 
FAIL!  : LocaleTests::testTZImages() Compared values are not the same
   Actual   (overlapcount): 97
   Expected (0)           : 0
```

So I will make these corrections now : 

    Dublin is in 0 (-1 needs editing)
    Gibraltar should be 1.0 (0 needs editing)
    Guernsey and Jersey are in 0 (1.0 needs editing)
    Lisbon is in 0 (-1 needs editing)
    Vilnius should be in 2 (1 needs editing)

**Comment by adriaandegroot** [comment]
I've merged your PR, thanks! Now Vilnius is in the right spot. I couldn't find Gibraltar on the map, it's either pixel-perfect clicking needed or it overlaps with Ceuta.

I'd like a PR that reduces the size of the pin a bit -- it *does* look very large on the map.

**Comment by FLVAL** [comment]
The mask needs to fit perfectly to not overlap mostly on small country size, I will check the Gilbratar to correct it to not overlap with Cueta, then I will PR the same pin size that we have on EndeavourOS but on Calamares colors, and I forgot to PR You the Kafaofo !!

**Comment by kkofler** [comment]
Gibraltar is supposed to be on the Spanish side (but belongs to Great Britain). Ceuta is supposed to be on the Moroccan side (but belongs to Spain). They should not overlap.

**Comment by kkofler** [comment]
(There should be a sea inbetween, even if it's a straight at that longitude.)

**Comment by FLVAL** [comment]
Thanks for the geo info, maybe we are wrong on the red point actual position is about (349, 144) from : 
23:28:27 [6]:  ..  Zone "Gibraltar" QPoint(349,144)
23:28:27 [6]:  ..  Zone "Ceuta" QPoint(349,144) 

New Pixel position  : 
- blue (353,147)
- Yellow (353,149)

Adriaan let me know which positions I have to keep ?

![gibraltar](https://user-images.githubusercontent.com/56921008/79478832-2cee5080-800c-11ea-9de6-5caac4c19330.png)

**Comment by adriaandegroot** [comment]
I'm just discovering that as well :( The map is weirdly-scaled, and was resized at some point in the past -- and as you notice, Gibraltar is put in the wrong spot. Lisbon is out to sea. Dublin is inland. I can start adjusting the scaling of map pixels to lat/long again, but then exactly your work is broken again (because places move to adjacent pixels).

At this point my feeling is: use the red pixel, because that's where Calamares thinks that Gibraltar is -- totally wrong. Let's not waste too much time on this, and do two things:
 - think about getting a new map drawing with proper scaling
 - using a real map widget, like the localeq module can

**Comment by FLVAL** [comment]
Yep I will use the red pixel for Gibraltar, but what for Cueta could I use another position than the red pixel to make it work ?

**Comment by adriaandegroot** [comment]
Gibraltar and Ceuta are in the same zone (CET / CEST) so let's not worry about it; they have the same pixel coordinate (the red one)

**Comment by adriaandegroot** [comment]
See also #967 for one of the previous times we noticed things wrong.

**Comment by FLVAL** [comment]
Adriaan, I tested the new Deepin V20 Beta that appeared on 15/04/2020 and when I saw the geoip map, I thought was interesting to share it with You on how they managed the dual or trial same pixel zone country to click on map !

In fact, when the mouse cursor is closed to 2 or 3 countries it's showing these 2 or 3 countries in a small list popup to choose ! very interesting. Then when you are exactly on the pixel country dedicated, you have only 1 country showed. This would be useful in our example for Gibraltar/Cueta that has the same pixel zone and others places on the same way. You will notice they removed timezone and keep only the map and pin only.

If you have a chance to test it, try it it's interesting to see.

![deepin_map2](https://user-images.githubusercontent.com/56921008/79659566-0d922780-81b4-11ea-96a7-675ff450b68a.png)

![deepin_map3](https://user-images.githubusercontent.com/56921008/79659601-108d1800-81b4-11ea-9819-83c43c147a7b.png)

![deepin_map](https://user-images.githubusercontent.com/56921008/79659520-0a973700-81b4-11ea-8503-a4d71880e94a.png)

**Comment by demmm** [comment]
@FLVAL Work is ongoing for exactly this, PR is not ready for use in Calamares yet, but localeq will have what you mention here.  Zooming in to street level will be possible.
https://github.com/calamares/calamares/pull/1371

**Comment by FLVAL** [comment]
Thanks for your answer @demmm like the dem file !

A real ArcGIS system to zoom in and out.
It will be connected outside Calamares to display the enterly system map or not ?

**Comment by demmm** [comment]
>Would it be connected outside Calamares to display the enterly system map or not ?

Not clear what you are asking here. If it is about the map, it now renders from the web (ESRI map), not clear yet if localeq will require internet connection from now on, or will render from a local (has to be large).
If it is about zoom level, demos show zoom level '6', can be set to show the whole world map (1).

**Comment by FLVAL** [comment]
> not clear yet if localeq will require internet connection from now on, or will render from a local (has to be large).

It was my question, you answered it as well. I'm wondering which database you would use for it then if the list countries would correspond to it ?

I think for the use on Calamares, to set the whole global map at start is faster to reach.

**Comment by demmm** [comment]
>database you would use for it then if the list countries would correspond to it ?
There is a ~400 Mb ESRI world database available that includes all points & info (coordinates, city, country, timezone and so on), thus requiring an internet connection makes more sense imo.

>whole global map at start is faster to reach
That is not true for the majority of the installs, since the map will use your Geoip (IP) info to point to your approximate location.

**Comment by kkofler** [comment]
IMHO, neither requiring an Internet connection nor requiring a 400 MB database (under what license?) is acceptable. Such a zoomable map is simply way overkill for timezone and language selection.

The map currently used in the C++ module is buggy, and that is an issue, but it ought to be possible to produce a map that is just as compact but actually works. E.g., the projection needs to be known and not tampered with so that geographic coordinates can be mapped exactly to pixel coordinates and back with the projection's formulas, rather than the fudged approximations currently used in the C++ module's C++ code.

**Comment by demmm** [comment]
Looks like that is the general consensus, so I will withdraw my PR and make it a distro specific module.

**Comment by adriaandegroot** [comment]
Most of the discussion here has no bearing on the actual problem reported by @FLVAL and that is being fixed by them.

- The **existing**, widgets-based, timezone selection thing uses a world map divided into timezone images. Some pixels in those images are assigned to the wrong timezone.
- Deepin uses something entirely different, but very cool (and the overlapping-zones popup seems like a good addition to Calamares's existing timezone selection widget).
- QML-based view steps are coming; these are **optional** and configurable just like the widgets steps. You can switch them on in `settings.conf` like any other module.
- Distro's have *way* more flexibility through the QML modules, and you *can* do neat stuff with other QML / Qt components. That relies entirely on 1. using the QML modules and 2. using distro-chosen QML that uses those extra components. For widgets uses (that is, distro's not interested in the fancy QML) this has exactly zero impact.

So this issue remains open because `localetest` still lists a bunch of problems, and I hope @FLVAL will send in more fixed images that apply **to the current widget**. When the images are fixed then this issue will be closed (I hope for the next Calamares release, that's why it's on the milestone).

**Comment by FLVAL** [comment]
Hi Adriaan, sorry for the late answer, I'm on the way to pass an exam which was normally end of may even if Covid19 would change this, I'm enterley on it...so I don't have time until june to change all the map !  I could make the most important pixels errors in a first step...

If you see a list of what you want first, which continent you would prefer, let me know if you have an order. Or simply I could go in the order list presented in the localetest ??

Yesterday I tested localetest I saw some new information appears about pixels errors at the end which is great. Are you able to rebring the total erros at the end of the localetest like it was first ?
Wuld be a good mark for me in the advance of work...

**Comment by FLVAL** [comment]
Another test with ASMARA timezone overlap where I need an answer to understand what to do with ?

I started on Africa zone, first on the list overlap. The localtest gives me : 
```
Region "Africa" zones # 52 
14:25:19 [6]:  ..  Zone "Asmara" QPoint(445,183) 
14:25:19 [6]:  ..  First zone found 2 "2.0" 
14:25:19 [6]:  ..  Also in zone 3 "3.0" 
```
After check, **Asmara should be 3.0 (2.0 needs editing also)** : 

![asmara_2 0](https://user-images.githubusercontent.com/56921008/81068283-66fe9400-8ee0-11ea-9061-858b15b6c9ff.png)

![asmara_2 0_3 0](https://user-images.githubusercontent.com/56921008/81068287-682fc100-8ee0-11ea-8516-8b769596dd2c.png)

Like you see, I fixed the both timezone files, and I updated them into **calamares/src/modules/locale/images/**. Then now localtest doesn't show anymore the error on Asmara which makes sense but when I check on Calamares, the click on Asmara still showing timezone_2.0 ?? 

Is it necessary to recompile the new fixed timezone pictures to see it work on Calamares ? or What I'm doing wrong ? Need your help to continue...

**Comment by adriaandegroot** [comment]
@FLVAL 

> Is it necessary to recompile the new fixed timezone pictures to see it work on Calamares ? or What I'm doing wrong ? Need your help to continue...

Yes. The **tests** read directly from the source-directories, but Calamares compiiles the images into the locale module. So to test in Calamares itself, you will need to recompile Calamares (and then run `calamares -d`, for instance, to try out the version of Calamares you just built).

**Comment by adriaandegroot** [comment]
(It's also OK to just PR updated images when the tests pass, and I can double-check them in Calamares)

**Comment by FLVAL** [comment]
Thanks Adriaan, I will PR you directly when the locatest past correctly. I just PR Asmara.
I will wait your update to test it on map.

**Comment by adriaandegroot** [comment]
There's another batch just landed, thanks. If you're feeling ambitious, keep in mind Kevin's comment from earlier that it would be **better** if we had a good new map with known projections, but that strays into GIS territory and map-making.

**Comment by kkofler** [comment]
For the "twin capital" issue, e.g., Kinshasa vs. Brazzaville, I guess it would make sense to fudge the coordinates of the capitals inward into their respective country, to make them distinct pixels. I mean, living in a sorta twin capital myself (though not **that** close), if I click and get Bratislava, I'll retry clicking a few pixel westwards (deeper into Austria and away from Slovakia) and hopefully get Vienna then.

**Comment by adriaandegroot** [comment]
Dropping this IRC message here, because it connects to my blog post https://euroquis.nl/kde/2020/05/31/timezones.html and possible improvements to the widgets version of the timezone selector

```
<vkrause[m]> [ade]: reading your blog, I just recently removed coordinate to pixel code (see https://invent.kde.org/pim/kitinerary/-/commit/a80599e0903086f0500545e8d181cfeb206044e7#6a683daa5503ed9b947dc78180b7578d47a70b2e_211_99 and https://invent.kde.org/pim/kitinerary/-/commit/a80599e0903086f0500545e8d181cfeb206044e7#6a683daa5503ed9b947dc78180b7578d47a70b2e_61_32), not really complex, the key for high precision coming from QGIS
<vkrause[m]> renderings is https://en.wikipedia.org/wiki/World_file though
```

**Comment by adriaandegroot** [comment]
I'm going to close this one, after spending another hour on fixing up the graphics.

There's a lot of issues in this map, and it really comes down to "needs a re-do" rather than anything else. I did put Norfolk Island in the right zone (zone +11.5 stopped existing in 2015), but Kirimitati is still in -11 rather than +14 where it belongs .. Calamares doesn't have such a zone).

Note that all this is about the drawing on the map of the various zones, not the eventual timezone that gets attached to any given name: that's done correctly.
