### ISSUE TITLE
Debian repositories after installation 

### ISSUE THREAD

**Issue by prp-e** [calamares/calamares#1405]
I made a distribution and the distribution is not a Debian _remaster_ anymore, we worked on our own repositories and when I install the final image using Calamares, repos turn back to debian buster repositories. 
For example, my preferred repository is : 

```
deb http://apt.mylinuxdistro.com/apt release main contrib non-free
``` 

But what I get after the installation is: 

```
deb http://deb.debian.org/debian buster main
``` 
Which module is for repositories?

**Comment by abucodonosor** [comment]
There isn't such a module.

**Comment by kkofler** [comment]
The trick is that you need to configure the repositories directly in the base image of your live image, i.e., the one that you let Calamares install. So you need to make sure the proper repository configuration file is included when you generate the live image. If you edit the repositories at runtime in some live-only init script or systemd unit, the changes will only be written to the transient read-write overlay and not to the read-only base image.

**Comment by prp-e** [comment]
> The trick is that you need to configure the repositories directly in the base image of your live image, i.e., the one that you let Calamares install. So you need to make sure the proper repository configuration file is included when you generate the live image. If you edit the repositories at runtime in some live-only init script or systemd unit, the changes will only be written to the transient read-write overlay and not to the read-only base image.

Oh I see. Can you show me an example of a systemd unit for that? Thanks.

**Comment by adriaandegroot** [comment]
[[ Is there any relation between your distro, and the big update to the Farsi translation for Calamares I got yesterday? If not, maybe there should be. ]]

Calamares just copies to the target system what you ask it to; generally this is whatever squashfs you're writing from the *unpackfs* module. If your **live** ISO image has configurations that aren't in the squashfs (e.g. Kevin thinks they might be in a FS overlay or handled by a systemd unit on your live ISO) then those won't get written to your target system.

 - For debugging, the *interactiveterminal* module is actually really useful, because it can drop you to a shell prompt in the target system (once there's a filesystem and a shell in it, anyway) and you can poke around during the install. So give that a shot.
- For configuring things once the system is installed, Calamares has a whole bunch of different modules. If you have a systemd unit (probably not, or you wouldn't be asking about them here above) then the *services-systemd* module might help. If you need to configure specific repositories then you could use shellprocess to run whatever apt-repo-modification commands are needed to add your distro repo. If it's just a matter of getting the right file onto the target, you could even configure the *unpackfs* module to copy that one file after doing the usual unsquash work.

It would be easiest to suggest something if I had your ISO image, feel free to mail me a link if you like.

**Comment by prp-e** [comment]
> 
> 
> [[ Is there any relation between your distro, and the big update to the Farsi translation for Calamares I got yesterday? If not, maybe there should be. ]]
> 
> Calamares just copies to the target system what you ask it to; generally this is whatever squashfs you're writing from the _unpackfs_ module. If your **live** ISO image has configurations that aren't in the squashfs (e.g. Kevin thinks they might be in a FS overlay or handled by a systemd unit on your live ISO) then those won't get written to your target system.
> 
>     * For debugging, the _interactiveterminal_ module is actually really useful, because it can drop you to a shell prompt in the target system (once there's a filesystem and a shell in it, anyway) and you can poke around during the install. So give that a shot.
> 
>     * For configuring things once the system is installed, Calamares has a whole bunch of different modules. If you have a systemd unit (probably not, or you wouldn't be asking about them here above) then the _services-systemd_ module might help. If you need to configure specific repositories then you could use shellprocess to run whatever apt-repo-modification commands are needed to add your distro repo. If it's just a matter of getting the right file onto the target, you could even configure the _unpackfs_ module to copy that one file after doing the usual unsquash work.
> 
> 
> It would be easiest to suggest something if I had your ISO image, feel free to mail me a link if you like.

Thanks for your kind reply. 
About the Farsi translation, the answer is yes and no at the same time. I work for the company that makes the distro for the Iranian people and the whole interface is in Farsi. My colleague asked about the process of contribution. I think his issue is still here in github. 
By the way, I will give you a link to my personal project soon. I may make a release as soon as possible. 
And again, thanks for your kind reply.

**Comment by highvoltage** [comment]
In Debian we just run a simple shell script from a calamares module that takes care of the final sources.list:

https://salsa.debian.org/live-team/calamares-settings-debian/-/blob/master/calamares-modules/sources-final/module.desc

https://salsa.debian.org/live-team/calamares-settings-debian/-/blob/master/scripts/sources-final

If you forked calamares-settings-debian for your distribution, then those are the files you want to change.

**Comment by prp-e** [comment]
> 
> 
> In Debian we just run a simple shell script from a calamares module that takes care of the final sources.list:
> 
> https://salsa.debian.org/live-team/calamares-settings-debian/-/blob/master/calamares-modules/sources-final/module.desc
> 
> https://salsa.debian.org/live-team/calamares-settings-debian/-/blob/master/scripts/sources-final
> 
> If you forked calamares-settings-debian for your distribution, then those are the files you want to change.

I see. What I did was just simply write a script myself, then I added the script to `shellprocess.conf` and it worked very well!
