### ISSUE TITLE
-s|--simulate opation ?

### ISSUE THREAD

**Issue by otyugh** [calamares/calamares#1412]
**Is your feature request related to a problem? Please describe.**
When I tweak calamares, more precisely when I'm trying stuff for the slideshow, I need to launch the installation process to checkout if thing goes well - which is a bother.

**Describe the solution you'd like**
A simulate option, which would allow to "launch calamares process as if" but at the end it wouldn't install anything (just making a false progresse waiting for ~20sec ?). That would be great.

**Comment by demmm** [comment]
If it is just the QML slideshow you are tweaking, no need to run in Calamares, you can test & tweak just fine using qmlscene (part of QtDeclarative).

**Comment by adriaandegroot** [comment]
This is a useful suggestion; it will land in the **test** application, so you can run `./loadmodule --slideshow` (or `-s`) from the build directory. Alternatively you can edit your `settings.conf` so that there are fewer modules, and just set up a dummycpp module for "installation". But having a `-s` will be simpler.

**Comment by philmmanjaro** [comment]
Having simulate function would be a plus for tests. Maybe make the actions it would execute a little verbose

**Comment by adriaandegroot** [comment]
Testing for individual modules can be done through `./loadmodule` and now `./loadmodule -s` can run the slideshow with a fake job load, so you can tweak the slideshow without modifying Calamares at all; I'm not a big fan of having an actual `-s` or `--dry-run` in Calamares itself, since the same effect can be achieved through a suitable *exec* section (with dummycpp) for the rare cases you need a full Calamares UI but no actual work done.

For slideshow development, and for module UI tweaking, `./loadmodule` ought (otyugh?) to be enough.

See also https://github.com/calamares/calamares/wiki/Test-Guide#standalone-slide-show-tests
