### ISSUE TITLE
Localeq blockers for deployment

### ISSUE THREAD

**Issue by demmm** [calamares/calamares#1426]
Commit https://github.com/calamares/calamares/commit/34e7b06cc9d6a6518f87254f08780e8a65d3cb14 mentions what is implemented for localeq and what is still missing.

To better track this, have a bug report open for this new module.
To summarize what is still needed:
* get hasInternet status, it is briefly mentioned in https://github.com/calamares/calamares/blob/master/src/modules/locale/LocaleViewStep.cpp#L232 not usable outside of the locale module
* fill the fine-tune 181n.qml with proper locale & language data, this is probably possible already, just not clear what model/globalstorage holds the data
* connect the obtained timezone to globalstorage

Clarification is also needed how to set settings.conf.  If the view module is set to localeq and exec to locale you will get the view module for locale showing after the copying of files is completed.  Exec needs to be set to localeq too?

**Comment by adriaandegroot** [comment]
For a QML module -- and for regular ViewSteps, too if we want to be consistent and clean about things -- all the **module** configuration should happen in, and through, a Config object. If something needs to go in Global storage, then it's still the Config object that handles that, though a slot or property.

The *hasInternet* value that shows up in global storage comes from requirements checking in the welcome module. That is there for mostly-historical reasons and because the Python API is a bit limited. For code with closer ties to C++ (including QML code) there are global objects that can be used for global information. In this case, I added the *Network* object to `io.calamares.core`, and it exposes a *hasInternet* property. More importantly, this is *always* available and is updated by Calamares core, rather than by the welcome module (which runs just once!).

- The i18n module now grabs the *supportedLocales* list from the Config object
- The i18n module now sets *currentLanguageCode* and *currentLCCode*  in the Config object -- which then does all the rest, updating string statuses and writing to global storage
- The map writes the timezone (from clicks) into the Config object via the `setCurrentLocation()` slot, so TZ and locale information updates with the map now.

**Comment by demmm** [comment]
@adriaandegroot If you don't mind I'd like to re-open this issue, since it is not at a stage yet as ready for deployment.
In my tests (build with all the latest commits), hasInternet is still not used:
```
qrc:/localeq.qml:41: ReferenceError: Network is not defined
```
Setting line 41 to explicitly load Map.qml results in fully working map, clicking sets the new location in Globalstorage as should.

Using i18m.qml is not working, it either sets unrelated locales or crashes Calamares, I will try to get better backtraces to see why.

**Comment by adriaandegroot** [comment]
The *Network* component is registered into io.calamares.core in `Qml.cpp` (function `registerQmlModels`) so there's no real way for it to be missing.

I can reproduce the crash in `i18n.qml`, though.

**Comment by demmm** [comment]
>The Network component is registered into io.calamares.core in Qml.cpp (function registerQmlModels) so there's no real way for it to be missing.

I presume this is a local issue only, since you cannot reproduce. Hopefully some other distros can confirm either way, until then, I will set networks as requirement (thus offline not needed).
