### ISSUE TITLE
Welcomeq needs geoip connection

### ISSUE THREAD

**Issue by demmm** [calamares/calamares#1427]
Since the CHANGES include a note for the new welcomeq module:
https://github.com/calamares/calamares/blob/master/CHANGES#L28
It would be good to address the one missing component.  It now always sets American English for locale, since there is no connection to geoip.

Requirements.qml is buggy on a Qt 5.15 system.  When RAM requirements are not met for example, only text shown is:
https://github.com/calamares/calamares/blob/master/src/modules/welcomeq/Requirements.qml#L47

The Listview does not show data from config.requirementsModel, it does however show data if there is also no internet connection.  Not clear if this is Qt 5.15 only, or an issue with `mandatory`.

**Comment by adriaandegroot** [comment]
Can't reproduce the GeoIP issue: in my log I get

```
06:50:51 [6]: setGeoIP(Config*, const QVariantMap&)::<lambda()>
    GeoIP result for welcome= "NL" 
06:50:51 [6]: void Config::setLocaleIndex(int)
    Index 34 Selected locale QLocale(Dutch, Latin, Netherlands) 
```

Note that you actually have to configure GeoIP: the example `welcomeq.conf` doesn't contain a *geoIP* section, nor does it mention the possibility. You can copy the example configuration from the *welcome* module, or do, say

```
geoip:
    style:    "fixed"
    url:      "http://example.com/"  # Bogus
    selector: "DE"  # Country code
```

(`fixed` is a special kind of GeoIP, intended for testing) Bear in mind that you need to set the *selector* to get country codes -- otherwise you'll see some kind of "unusable country code" in the log.

**Comment by adriaandegroot** [comment]
I can confirm, though, that the requirements-checking doesn't come up: this is with Qt 5.14.

A side-effect of QML is that it's harder to tell if the problem is in the Calamares framework (e.g. missing signals / property notifications) or in the QML itself (which is the responsibility of downstream designers, except for the example QML included in Calamares). :S

**Comment by adriaandegroot** [comment]
(note that the example *geoIP* configuration you just added, **explicitly** says *none* for style, so it's the same as leaving it out.)

**Comment by demmm** [comment]
It is a copy of the default in welcome.conf, so imo, should be consistent with settings there.

**Comment by demmm** [comment]
>problem is in the Calamares framework (e.g. missing signals / property notifications) or in the QML itself

I'll further check the QML, but only difference with Recommended.qml is `mandatory`.  Recommended.qml works as should.

**Comment by adriaandegroot** [comment]
As an example of shooting oneself in the foot: I had a stray `welcomeq.qml` file lying around, so I was looking at something completely different :(

**Comment by adriaandegroot** [comment]
Note that *mandatory* means "is this requirement mandatory?" It's totally independent of *satisfied*, which means "is this requirement satisfied?". A single requirement can be mandatory and satisfied, or mandatory and unsatisfied .. only the latter should be shown as "something is wrong".

So the logic in `Requirements.qml` is wrong: it uses *mandatory* to pick colors and icons, when it should be using *satisfied* instead.

I'd use the following table:
 - *satisfied*: green
 - not *satisfied*, not *mandatory*: yellow
 - not *satisfied*, *mandatory*: red

**Comment by demmm** [comment]
Then this bug report can be closed imo, no issues in the Calamares framework. Geoip connections work here now too with the proper settings in welcomeq.conf.

**Comment by adriaandegroot** [comment]
Also, the model's *satisfiedRequirements* and *satisfiedMandatory* are not independent: if not all the mandatory requirements are satisfied, then (by definition) not all the requirements are satisfied, either.

I think the whole `Requirements.qml` can be removed, with one delegate that does the colors right, and only a switch to set the right text in `Recommended.qml`
