### ISSUE TITLE
mount module attempts to run chcon even on non-selinux systems

### ISSUE THREAD

**Issue by ollieparanoid** [calamares/calamares#1429]
**Describe the bug**
The mount module fails here, if `chcon` is not installed:
https://github.com/calamares/calamares/blob/73eb718c08395cdac05ecfeabcbf01e441ded6da/src/modules/mount/main.py#L52-L56

**Expected behavior**
A boolean for selinux in settings.conf, that prevents mount from trying to run chcon.

**Additional context**
Version 3.2.25

**Comment by abucodonosor** [comment]
This was done on purpose like this since it won't do any bad by running chcon with or without selinux.

Yes, and it will fail on gazillion other things when not installed.

OFC we could add a check for chcon, a settings option is not needed. @kkofler what do you think?

**Comment by kkofler** [comment]
`chcon` is part of `coreutils`, so I am surprised you can have it not installed.

If `chcon` is installed, the module definitely does not fail, even without SELinux enabled, or even with a kernel with no SELinux support at all. You get only a warning/error message from `chcon`, which is harmless because Calamares ignores the return code.

And how exactly is the installation failing for you? Do you get a Python backtrace proving that it is failing on the call to `chcon`? Or could it be that it is actually crashing somewhere else and you are just seeing the `chcon` error as a red herring?

**Comment by ollieparanoid** [comment]
> `chcon` is part of `coreutils`, so I am surprised you can have it not installed.

I'm working on postmarketOS, which is based on Alpine Linux, and it comes without GNU coreutils by default (though that can be installed). It's using busybox instead. If coreutils is considered a dependency of calamares, then this can be closed.

> And how exactly is the installation failing for you? Do you get a Python backtrace proving that it is failing on the call to `chcon`?

Yes, and if I link it to /bin/true as workaround, the installation succeeds.

Thanks for the quick responses!

**Comment by kkofler** [comment]
Well, the current code kinda assumes that `coreutils` is present. Busybox provides most of its tools though. I suppose that we should simply catch the Python exception when `chcon` is not found. (Can you post the backtrace so we know what error type to catch?)

(It would really help if the Python API documentation actually documented what exceptions a method can actually throw… Just one more annoyance with Python. I hope we can eventually get all modules ported to C++.)

**Comment by kkofler** [comment]
(I would have expected `subprocess.call` to never throw and only `subprocess.check_call` to throw, but things are more subtle, it seems, i.e., it looks like the special exit code for a non-existent command is actually special-cased, which is not documented anywhere.)

**Comment by abucodonosor** [comment]
@kkofler 

maybe do it the old weird way? Like we look for dracut and other stuff?

**Comment by kkofler** [comment]
This tool needs to run outside of the `chroot`, because we need to fix a context while we are still mounting things, so the methods from `libcalamares` that run within the `chroot` do not work.

The fix should be straightforward, just a `try` around the `subprocess.call`. All we need to know is what to put in the `except`.

**Comment by adriaandegroot** [comment]
All of the Python modules are terrible for running arbitrary commands in all kinds of different ways. This is **also** one of the reasons I want to port the Python modules to C++ -- then there's a clear API (`System::runCommand()`, ultimately) for running arbitrary commands with suitable flags for in-host, in-target, etc.

The **right** fix here (aside from porting to C++) is giving the `libcalamares` Python bindings a better run-this API and then applying that consistently.

Here's variants I can quickly find:
 - `os.system`
 - `subprocess.run`
 - `subprocess.call`
 - `subprocess.check_call`
 - `subprocess.check_output`

Note also that each and every one of those calls is a blocker for "rootless Calamares", because there's no auth / privilege escalation possible there through a suitable API.

**Comment by adriaandegroot** [comment]
`subprocess.call()` raises `OSError` if the named command does not exist, so we could catch that; if the command exists then everything else that can be raised is `CalledProcessError`.
