### ISSUE TITLE
Calamares on BSD's, is it possible?

### ISSUE THREAD

**Issue by prp-e** [calamares/calamares#1434]
Yesterday at work, while working on a project with my co-workers, we saw some files related to BSD in Calamares source code. 
So, I have some questions and I ask them here. And I'm thankful for your kind replies. 

1. Will Calamares be available as a BSD installer as well? (anytime soon?)
2. Which BSD variant has the higher priority? (and I ask from another friend, will it support OpenBSD?)
3. Will Calamares support ZFS? 
4. Which mechanism will be used in Calamares if it becomes available on BSD? I mean will it be depending on SquashFS or it just walk on BSD ways to find some traball archives and extract them in place? 
And last but not the least, Has Calamares ever been tested on any BSD variant? was the test successful?

**Comment by abucodonosor** [comment]
Calamares doesn't work on BSD, right now.

**Comment by adriaandegroot** [comment]
Almost all Calamares development is done on FreeBSD -- there are two parts that are not natively available on FreeBSD, and those are:
 - KPMCore (partitioning tool)
 - the actual installation bit

1. Someone needs to sit down and do a full configuration of Calamares for this purpose. You'll find that there's a handful of places that need work, for instance any call to useradd (or is it adduser?), and without partitioning you will need another way to select a disk to install to.

   In the -extensions repo I added a useless stub module called *freebsddisk*. The idea there is to pick a disk and select UFS or root-on-ZFS. (Picking a disk probably means "do `geom disk list` and parse that") It's just a start, though, and is more of an example than a real project.
2. FreeBSD, because that's the one I have. Anything that works for FreeBSD is likely to work -- in terms of making UFS FS and untarring stuff to it and calling adduser at least. The same policy that applies to Linux distro's would apply to the BSD variants: support is welcome, probably untested by me, please file PRs and upstream things.
3. Yes. It's also **not** going to support fancy ZFS setups (see Linux LVM for what a mess that becomes -- you really need a full-on partitioning tool there, which Calamares doesn't provide). Just to get started I'd go for "pick a disk and that's your 1-disk striped /zroot".
4. There would either be a custom module or *unpackfs* should learn to deal with the usual tarballs. A measure of success would be if you can run Calamares from a booted regular FreeBSD install ISO (the one with the tarballs on-disk) and get a working system from there. I don't think that **also** changing the delivery mechanism is a good thing (unpackfs is a mess and should be ported to C++, but that applies to nearly all the "slightly complicated" Python modules).
5. It runs. I've never tried to actually *do* anything with it, since that's pretty low-priority. A good start would actually be OEM-mode: fix up the adduser job to do the right thing on FreeBSD.

One experiment I did was running Calamares with Qt in the FreeBSD framebuffer, so without X. That displays things, but moused messes up the screen on mouse movement, and there's no input possible to the application -- so for screenbuffer Qt apps to work there's a bunch of work to be done lower in the stack.

**Comment by prp-e** [comment]
I actually know the answer to 1. It's `adduser` and also `bsdinstall` uses that script to add new users to the system. And about partitioning, there's a `pc-sysinstall` which is a backend to GhostBSD installer, I think it uses `parted` as the partitioning tool. 
BTW, is there any ports or packages I can test on FreeBSD (or a FreeBSD based OS)?

**Comment by adriaandegroot** [comment]
I just added `data/FreeBSD` to the Calamares repo. It's a ports subdirectory: copy it to your ports tree, under `sysutils/calamares` (recommended) and you can build Calamares with poudriere (recommended) or portmaster or just plain `make`.

The port doesn't install any config-files, so running `/usr/local/bin/calamares -D6` will just get you an error message on the console, but .. it's a start. You could put together a normal collection of configuration files in `/usr/local/etc/calamares` and see how far that gets you.

```
[adridg@beastie ~]$ uname -a
FreeBSD beastie.example.com 12.1-STABLE FreeBSD 12.1-STABLE GENERIC  amd64
[adridg@beastie ~]$ calamares
00:34:13 [1]: static Calamares::Settings *Calamares::Settings::init(bool)
    ERROR:Cowardly refusing to continue startup without settings. 
     "/usr/local/etc/calamares/settings.conf" 
     "/usr/local/share/calamares/settings.conf" 
00:34:13 [1]: static Calamares::Settings *Calamares::Settings::init(bool)
    ERROR:FATAL: none of the expected configuration file paths exist. 
```

**Comment by adriaandegroot** [comment]
Especially, I'm encouraging you (or IRBUG) to experiment a little and push things forward; issues can be fixed, but giant milestones like "support BSD installs" outside of my normal priorities are unlikely to get done.
