### ISSUE TITLE
Upstreaming mobile-friendly modules from postmarketOS

### ISSUE THREAD

**Issue by ollieparanoid** [calamares/calamares#1451]
I've been working on [postmarketos-ondev](https://gitlab.com/postmarketOS/postmarketos-ondev/), the on-device installer of postmarketOS. This repository contains custom Calamares configurations and touch-friendly QML modules. I'd like to streamline the modules some more and then upstream them into Calamares, so other Linux distributions targeting phones can use them as well (there are quite a few out there by now). Here are some related thoughts to kick off the upstreaming discussion.

Notable differences to existing modules:
* The QT virtualkeyboard is integrated into each module to provide an on-screen keyboard.
* Instead of having one dialog with all sorts of inputs for one topic (e.g. Calamares' "users" module asks for username, password, hostname IIRC), the user gets shown multiple screens within a module, with few inputs at a time.
  * For example, the user is asked if they want to enable full disk encryption, or not, on one screen. A big "enable" button leads to a screen where the password can be typed in, "disable" leads to loading the next module.
  * No sidebar or navigation, the navigation elements are done in QML. There is a header bar with a title and a back button, and the back button will either go back to a previous screen in the same module, or go to the previous module ([code](https://gitlab.com/postmarketOS/postmarketos-ondev/-/blob/7cad72e2f5c578220d05afdaad3376dff68ded67/calamares/modules/partitionq/partitionq.qml#L138-157)).
* Full disk encryption:
  * The partition is not encrypted with a key that gets embedded into an initramfs, which is encrypted in GRUB2. This would not work, we don't use GRUB2 (it's not that simple to use it on phones anyway), and even if we did, it would need an on-screen keyboard to enter the password etc.
  * So instead, the root partition is directly encrypted with the password, not with a keyfile.
* User configuration:
  * The user password is numeric, because that's what mobile-friendly user interfaces Plasma Mobile and Phosh require
  * This would be a bad choice for SSH of course, and SSH is quite important for development on these phones. So SSH access is disabled for the default user. And the installer asks if the user wants to set up a second user, dedicated for SSH access (with a proper password, and recommendation to switch to SSH keys after install).
* Partition selection:
  * Not implemented yet, but I imagine it makes more sense for mobile devices to ask, if they want to install on SD card or on internal storage - not displaying a full partitioning assistant.
  * Right now, it is installing into a "reserved space" partition that gets flashed together with the installer partition to the target device / to the SD card ([details](https://wiki.postmarketos.org/wiki/On-device_installer#How_it_works)).

Naming of the modules:
* I went with the "q" suffix initially ("partitionq", "usersq"), since that's what seems to be used in upstream Calamares modules for QML. However, by now there are the differences above to the existing modules, so I intend to [give them a "-mobile" suffix](https://gitlab.com/postmarketOS/postmarketos-ondev/-/issues/20).
 * I'm not sure I understand the intention of the existing QML modules, was the idea to slowly rewrite everything in QML to make it more customizable?
* Is this "-mobile" suffix suitable for upstreaming?

Some photos of how it looks like currently (0.2.0):
* [welcome](https://gitlab.com/postmarketOS/pmaports/uploads/ad8de9ee7b910243758a56f6d53fdfb4/ondev-welcome.jpg)
* [lockscreen-pin](https://gitlab.com/postmarketOS/pmaports/uploads/9b34f0bbdf715fece0759f9af7c091d6/ondev-lockscreen-pin.jpg)
* [ssh-credentials](https://gitlab.com/postmarketOS/pmaports/uploads/ee80283bd13afcc84598fb4d0a70013e/ssh-credentials.jpg)
* [fde-optional](https://gitlab.com/postmarketOS/pmaports/uploads/8f0a7f14e31a3f72bfde8af696f1de77/fde-optional.jpg)

Open issues are [here](https://gitlab.com/postmarketOS/postmarketos-ondev/-/issues). Let me know if you have any suggestions, pointers or questions.

CC: @PureTryOut

**Comment by adriaandegroot** [comment]
There is a long and winding road behind -- and ahead -- of the *q* modules. 

- Originally it was an experiment to see if QML could work at all for the UI,
- Then there was a concerted effort to the UI for all existing modules **also** in QML. Because there was much code-wranging, they got forked to *q* modules as the infrastructure gelled for QML-based UI modules.
- Now we've got shared code (the `Config` objects in each module) shared between the *q* and non-*q* (Widgets) version of the module. In principle the config should be connected to the UI, receive all the updates from the UI, and be the "source of truth" for information for that instance of the module.

There's a fair bit of work in the Config class each time to clean things up, make them QML-friendly and Widgets-compatible and especially untangle the Widgets UI code from configuration -- older Widgets modules often have the confguration stored in the UI, so there's a big chunk of refactoring right there.

QML is not the goal: however, it should be possible to do a Widgets-only, QML-only, or mixed UI in Calamares. That's why there are modules for both, and the config code is being untangled from Widgets, and there's a `WITH_QML` build-time option, and a `qmlSearch` configuration entry in the config files. Longer-term, since the config object is where all the real configuration lives, the idea is to re-merge the modules and have the UI selectable at runtime through the module's config-file (e.g. adding `qmlSearch: no` would select the widgets UI). Again: tons of refactoring needed.

I don't know directly if the Calamares, or the Calamares-extensions repo would be the right target for these modules; I kind of think that new / different modules should be done in extensions and that the existing set of "core" Calamares modules should just be enough (and the tracking module should move to -extensions).

That said, *-mobile* seems like a reasonable suffix for the modules. Note that if you upstream them to the main Calamares repo, you may run into conflicts with the USE_ mechanism in Calamares's CMakeLists.txt (easy enough to test though).

I'm most curious about any changes you've needed to do to the welcome module, because that's most-likely-useful to be upstreamed.

And I should stress over-and-over: the QML modules API and infrastructure isn't all settled yet. There's obvious deficiencies (no base class for Config objects, too much boilerplate in the view-step, and the long-term-plan to merge UIs again).

**Comment by ollieparanoid** [comment]
As discussed in #calamares, we'll try the `calamares-extensions.git` route. I've started to remove the pmOS specific branding from `postmarketos-ondev.git` (WIP, not published yet), will make some further tweaks (more stuff needs to be configurable) and will make a merge request based on that as next step.

**Comment by ollieparanoid** [comment]
Here it is: https://github.com/calamares/calamares-extensions/pull/3
