### ISSUE TITLE
Need an option to skip the Bootloader installation - essential for expert users

### ISSUE THREAD

**Issue by informer2016** [calamares/calamares#1456]
If you're trying to do a full disk encryption using a method like [**Artix Linux** _(great Arch with OpenRC or runit/s6 instead of SystemD)_ - **Full Disk Encryption for a new install**](https://forum.artixlinux.org/index.php/topic,1541.0.html) - creating/mounting the partitions encrypted with the custom flags and then pointing a Calamares to them - there's a high chance of running into this installation error:
```
Installation Failed

Boost.Python error in job "bootloader".

Command 'grub-install --target=i386-pc --recheck --force /dev/sda' returned non-zero exit status 1.
Installing for i386-pc platform.
File descriptor 7 (/root/.cache/calamares/session.log) leaked on vgs invocation.
Parent PID 7025: grub-install File descriptor 17 (/dev/mapper/control) leaked on vgs invocation.
Parent PID 7025: grub-install WARNING: Failed to connect to lvmetad. Falling back to device scanning.
File descriptor 7 (/root/.cache/calamares/session.log) leaked on vgs invocation.
Parent PID 7025: grub-install File descriptor 17 (/dev/mapper/control) leaked on vgs invocation.
Parent PID 7025: grub-install WARNING: Failed to connect to lvmetad. Falling back to device scanning.
grub-install: error: attempt to install to encrypted disk without cryptodisk enabled. Set `GRUB_ENABLE_CRYPTODISK=y' in file `/etc/default/grub'.

Traceback:

File "/usr/lib/calamares/modules/bootloader/main.py", line 465, in run
    prepare_bootloader(fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 437, in prepare_bootloader
    install_grub(efi_directory, fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 344, in install_grub
    check_target_env_call([libcalamares.job.configuration["grubInstall"],

  File "<string>", line 11, in <module>
```
There should be an option to **not to do** a GRUB installation, just in case a user needs to do it later _(after completing a Calamares install)_ in a custom way, or doesn't want to overwrite the existing bootloader which may be not a GRUB. Currently, the only way to skip a GRUB installation is to manually edit a `/usr/lib/calamares/modules/bootloader/main.py` 
and comment out this line near the end of file at "def run()" function:
```
prepare_bootloader(fw_type)
```
--->
```
# prepare_bootloader(fw_type)
```
To make it more user-friendly, please add this option to UI

**Comment by apt-ghetto** [comment]
For installations in BIOS mode, it is possible to install without a bootloader. According to your output, you should be able to skip the bootloader installation.

For installations in UEFI mode, it does always install a bootloader. See also #517.

And the grub-install error looks like a downstream bug, because the grub configuration _/etc/default/grub_ is not set up properly.

**Comment by JeffRockatansky** [comment]
Looking forward to this feature. It might be very useful for power users. What are the odds for it to be implemented?

**Comment by abucodonosor** [comment]
Probably if some do a PR, otherwise low.

**Comment by apt-ghetto** [comment]
Prior to the PR, it might be worth to discuss, how Secure Boot should be handled in this case?

**Comment by JeffRockatansky** [comment]
@apt-ghetto 
> Prior to the PR, it might be worth to discuss, how Secure Boot should be handled in this case?

I think it would be wise to consider user generated keys (PK, KEK) and DBs (DB, DBX) for SecureBoot. There are tools to perform generation (`openssl`, `efitools`, `sbsigntool`) and replacement (`keytool.efi`) manually, but a user-friendly UI with all the required info and instructions or even a semi-automated process (it still requires a password input for key generation I guess) would be perfect.

**Comment by deprov447** [comment]
I would like to start working on this issue. A small how-to or some reference/help ( if possible ) would be appreciated.

**Comment by adriaandegroot** [comment]
On the UI front, there are two cases:
 - BIOS partitioning
 - GPT partitioning
I have not looked lately whether the *boot loader location* drop-down shows up in EFI mode. The choices provided here don't make sense for EFI except for "Do not install", which seems to be the original problem.

To test the UI part, start a VM, preferably with 8GB RAM or so and a virtual disk; boot it from an ISO. Build Calamares in the VM. Then you have a most-recent Calamares, in a system ready for install. We're going to try to **not** reboot this one, so that the built-Calamares-plus-disks can be used, tested, and updated. Zero the first part of the virtual disk, then create a BIOS partition table on it, or a GPT table (use KDE partitionmanager, or command-line tools). *Then* start Calamares, so that you end up on the partitioning page with one (or the other) of the cases already chosen.

**Comment by adriaandegroot** [comment]
Looking at the **original** traceback in this issue, though, it looks more like "bootloader installation does not understand all possible encryption setups" rather than "bootloader should not be installed". That's probably a separate issue entirely once we make it possible to get through installation with the kind of setups that need specialized grub configurations.

**Comment by adriaandegroot** [comment]
On the logic front, the *bootloader* module obeys a global storage setting `bootloader`, like this:

```
    if (libcalamares.globalstorage.value("bootLoader") is None and fw_type != "efi"):
        libcalamares.utils.warning( "Non-EFI system, and no bootloader is set." )
        return None
```

(I don't know why that is a warning: it is a legitimate user choice, even if it is unusual). In the EFI case, though, this `if` is not triggered, and we end up in `prepare_bootloader()` (as shown in the original backtrace), and then the `efiBootLoader` configuration takes precedence, which is set in the job configuration: it ignores the `bootloader` global setting -- which is not strange, since there's nothing that would even set that GS value because the UI does not expose it.

**Comment by adriaandegroot** [comment]
Relevant code is `bootloader/main.py` (functions `run()` L455 and `prepare_bootloader()` L431) and `partition/gui/ChoicePage.cpp` (function `updateActionChoicePreview()` L920)
