### ISSUE TITLE
Choosing "root" username cause installation to fail

### ISSUE THREAD

**Issue by Dizirgee** [calamares/calamares#1462]
As per suggestion in #526 I'm logging this as new issue.

**Describe the bug**
Installer on user creation page should prohibit to enter "root" as username because if it is chosen than installation fails at the end as "root" user obviously already exists (so useradd cmd fails to add another root user)

I found this on Endeavour and also Manjaro latest installs which both uses calamares (v3.2.26 on End and 3.2.24.2-1 on manjaro
), so it looks not to be related to distro(s)

**To Reproduce**
1. Start Installation from livecd
2. On "Users" page of installer, type "root" 
3. Proceed with installation, at the end of install you get error

**Expected behavior**
Probably disallow to choose root as username (with some hint text like its default user which will be created etc) , or make "useradd" towards end of install not to execute again for existing user(s)

**Screenshots and Logs**
[root@archiso ~]# tail /root/.cache/calamares/session.log
    ERROR:Installation failed: 
2020-07-21 - 20:35:47 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    - message: "External command finished with errors." 
2020-07-21 - 20:35:47 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    - details: "Command <i>useradd -m -U -s /bin/bash -c root root</i> finished with exit code 9.\nOutput:\nuseradd: user 'root' already exists" 
2020-07-21 - 20:35:47 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    Calamares will quit when the dialog closes. 
2020-07-21 - 20:35:47 [8]: QML Component (default slideshow) deactivated
2020-07-21 - 20:35:47 [6]: void FinishedPage::setUpRestart()
    FinishedPage::setUpRestart(), Quit button setup= "never" command= "systemctl -i reboot" 

**Additional context**
![calamares_bug_root](https://user-images.githubusercontent.com/11375021/88095286-29331280-cb95-11ea-966c-c71e50c3a4ef.PNG)
![calamares_bug_root_error](https://user-images.githubusercontent.com/11375021/88098929-d0667880-cb9a-11ea-8e4c-7f3b10eca892.PNG)

**Comment by adriaandegroot** [comment]
I'm going to merge this so the issue is closed, at least.

I'm not convinced it needs to do case-insensitive checking here, because the **previous** check in the if-chain stops non-lowercase letters already. That's a bit nit-picky though.

What I don't like -- and this has nothing to do with your code, and is why there's an issue-1462 branch -- is that there's all this business logic and checking in the Widgets UI. We're slowly trying to get **away** from that, with Config objects for business logic and the actual configuration from a step, and a UI that connects to that Config object. So I'll merge your check into that branch once I get to the untangling-username-validity-checks-from-the-textboxes part of the branch.

**Comment by adriaandegroot** [comment]
(Comment was addressed to @apt-ghetto , who wrote the straightforward patch to do this check. Thanks, @apt-ghetto , for contributing to Calamares)

**Comment by abucodonosor** [comment]
@adriaandegroot that is only a partial fix for such a problem.

There are a lot of other system users names should not be used.
Probably the solution for that is to have a configuration option so distros could have a user name list is not allowed to be created.

**Comment by demmm** [comment]
Old PR has a commit for this:
https://github.com/calamares/calamares/pull/280/commits/bf252b1e27291c7e408fdf7317e1effeb8ed0787

**Comment by abucodonosor** [comment]
@demmm 

right forgot about this one :).

The old PR has still some hardcoded names, we should probably add some config option.

**Comment by adriaandegroot** [comment]
See `Config::forbiddenUserNames()` and `Config::forbiddenHostNames()`. These are currently static, but an obvious extension is to make them configurable by
- adding a configuration key in the config file
- add that configuration key to the config schema
- handle that configuration key in `Config::setConfigurationMap()`
- change `Config::forbiddentUserNames()` to non-static

Since @shainer did the work of collecting a typical list of forbidden user names, the configuration could be "smart" as well:
- config unset, or "none", or invalid: use the list `{"root"}`
- config value "typical": use the list @shainer put together
- config value is a list: use the list
It might be tricky to express that in the YAML schema, but it'd be a good setup for "these usernames are in use" and offer a **next** extension of distinguishing "typical" from "typicalbsd" or whatever.
