### ISSUE TITLE
reiserfs wrongly written as reiser to /etc/fstab (EndeavourOS) 

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1479]
--> This issue seems to be affecting the Installer application that both EndeavourOS and Artix Linux use

**Describe the bug**

**To Reproduce**
1. choosing reiserfs as the format for manual partition
2. install fails if chosen reiserfs for / (ROOT), and write format as reiser (not reiserfs) to /etc/fstab (archbased install)

**Screenshots and Logs**
BUG reported here:
https://forum.endeavouros.com/t/install-bug-reiser-in-fstab-instead-of-reiserfs/
(i do verify this in vm installs (EFI) )

**calamares install logs:** 
* http://ix.io/2tbv (/ (root) as reiserfs)
` Target cmd: ("mount", "-t", "reiser", "/dev/sda2", "/tmp/calamares-root-rkvbzw88/") output:
 mount: /tmp/calamares-root-rkvbzw88: unknown filesystem type 'reiser'.`
install failed

* http://ix.io/2tbV (/ (root) ext4 :: /var reiserfs)
install works, but wrong /etc/fstab entry for /var with reiser instead of reiserfs:
`13:43:09 [6]:  ..  mapping for "/dev/sda3" "/dev/sda3" 
     partlabel :   "" 
     partuuid :   "3C9E3EA7-BA74-B345-A55F-DFAC2159D3F6" 
     mountPoint: :   "/var" 
     fs: :   "reiser" 
     fsName :   "reiser" 
     uuid :   "d4e63e28-6939-4d84-b7a5-2c4655eeb6bf" 
     claimed :   "false" `
![wrong fstab entry](https://i.imgur.com/nVm5dGq.png)

* latest EndeavourOS ISO [endeavouros-2020.07.15-x86_64.iso](https://endeavouros.com/latest-release/)
* calamares version: 3.2.26-1 and same with calamares 3.2.27
* kpm-core 4.1.0-1
* reiserfsprogs 3.6.37-3
* progreiserfs 0.3.0.5-10
* parted 3.3-2

**Comment by adriaandegroot** [comment]
Relevant bits of the log (you've pointed to the most important one, though):

```
12:50:26 [6]:  ..  mapping for "/dev/sda2" "/dev/sda2" 
     partlabel :   "" 
     partuuid :   "4FE12E77-D6F6-5648-BB78-1766D4DA369D" 
     mountPoint: :   "/" 
     fs: :   "reiser" 
     fsName :   "reiser" 
     uuid :   "b63b160d-8727-4f91-90ac-45718fb32b9e" 
     claimed :   "false" 
12:50:42 [6]: virtual void Calamares::JobThread::run()
    Starting job "Format partition /dev/sda2 (file system: reiser, size: 19967 MiB) on QEMU HARDDISK."  (there are 32  left) 
12:50:50 [6]: static CalamaresUtils::ProcessResult CalamaresUtils::System::runCommand(CalamaresUtils::System::RunLocation, const QStringList&, const QString&, const QString&, std::chrono::seconds)
    Running "env" ("mount", "-t", "reiser", "/dev/sda2", "/tmp/calamares-root-rkvbzw88/") 
```

We see that the *fsName* and *fs* are both "reiser". This can be traced back to code in `FillGlobalStorageJob`:

```
    map[ "fsName" ] = userVisibleFS( partition->fileSystem() );
    map[ "fs" ] = untranslatedFS( partition->fileSystem() );
```

Which calls into KPMCore here:

```
static inline QString
untranslatedFS( FileSystem& fs )
{
    return fs.name( { QStringLiteral( "C" ) } );
}
```

I went to double-check the name of the filesystem:

```
adridg@saskatoon:~/src/calamares> sudo modprobe reiserfs
adridg@saskatoon:~/src/calamares> cat /proc/filesystems 
...
nodev   fusectl
        reiserfs
```

Looking then into KPMCore source, I find

```
static const KLocalizedString* typeNames()
{
    static const KLocalizedString s[] = {
...        kxi18nc("@item filesystem name", "reiser"),
        kxi18nc("@item filesystem name", "reiser4"),
        kxi18nc("@item filesystem name", "xfs"),
```

which is where Calamares gets the idea that the FS is called reiser, rather than reiserfs. Long story. I originally wanted to say "this is KPMCore's fault" @stikonas , but it's not -- it's Calamares assuming more about filesystems than is justified. Of course, just plain `mount` without the `-t` option would also work. But that leaves the fstab, which also uses the fs name directly.

I think the right thing to do is to munge the fs in the partition module, since the name "reiser" needs to be **used** as "reiserfs" everywhere Calamares needs it. I think.

**Comment by stikonas** [comment]
It might be good to fix name in kpmcore too. KPMcore can also write to fstab. I'll try to check when I'm not on the phone.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by killajoe** [comment]
great ! thanks for the details!
looks like an easy fix now ;)
