### ISSUE TITLE
as of late users can create empty passwords

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1499]
**Describe the bug**
neon sets no password requirements and instead lets calamares' defaults decide what requirements a password has. this previously was at least requiring nonempty. Nonempty is still the default communicated through users.conf :|

**To Reproduce**
install any neon

![Screenshot_20200826_104453](https://user-images.githubusercontent.com/809987/91283833-69387700-e78b-11ea-9611-05cb88daa02a.png)
![Screenshot_20200826_104503](https://user-images.githubusercontent.com/809987/91283838-69d10d80-e78b-11ea-8342-6d3affc2eaa1.png)

**Expected behavior**
don't accept empty passwords same as before

**Comment by apachelogger** [comment]
```
---
doAutologin: false
setRootPassword: false
sudoersGroup: sudo
defaultGroups:
    - adm
    - cdrom
    - dip
    - lpadmin
    - plugdev
    - sambashare
    - sudo
# Explicitly set the shell instead of defering to calamares. We have a platform
# expectation derived from ubuntu here.
userShell: /bin/bash
```

current users.conf because I'm about to change it

**Comment by adriaandegroot** [comment]
With **this** `users.conf`, also older Calamares (at least 3.2.27 and 3.2.26) also accept an empty password. The checkmark was recently made more "in-your-face" -- previously it was a kind of subdued grey -- so maybe that's why you notice it now.

After some back-and-forth it seems that the behavior changed between 3.2.8 and 3.2.16 or so. Before then, an empty password was not acceptable even without explicit settings.

Note that password requirements can be set in `users.conf`, notably:

```
passwordRequirements:
    nonempty: true
```

**Comment by adriaandegroot** [comment]
It's in the [Calamares 3.2.17 release notes](http://calamares.io/calamares-3.2.17-is-out/), see also the [CHANGES](/calamares/calamares/blob/calamares/CHANGES) entry for 3.2.17.
