### ISSUE TITLE
How do I disable the ability to install the bootloader?

### ISSUE THREAD

**Issue by Joe23232** [calamares/calamares#1510]
If I am creating a new partition table, then calamares allows me to not install the bootloader, but if I have a pre-existing partition table then I have no choice but to install the bootloader.

![image](https://user-images.githubusercontent.com/34926497/92343611-86fcc900-f107-11ea-854b-ae83e49a0f8d.png)

is it possible in anyway to disable the installation of a bootloader?

This seems to happen on any OS that uses the calamares installer.

**Comment by killajoe** [comment]
You simply need to set mount points first to have the options for bootloader working, befor eit show default value.
![2020-09-07_10-55](https://user-images.githubusercontent.com/16797647/92369167-ef907980-f0f8-11ea-9bd5-bdfba8f26c14.png)

**Comment by Joe23232** [comment]
Ah I see, I didn't realise this, thanks :)

**Comment by killajoe** [comment]
Can you close the issue then, seems solved then ;)
Also if you have an issue with our version of Calamares better fill a BUG at the Forum first so that we can check if the issue is on our side, we have some changes and modifications on calamares, devs here do not know about.
https://forum.endeavouros.com/c/Arch-based-related-questions/bug-reports/64

**Comment by Joe23232** [comment]
> Can you close the issue then, seems solved then ;)

Sure mate :)

> Also if you have an issue with our version of Calamares better fill a BUG at the Forum first so that we can check if the issue is on our side, we have some changes and modifications on calamares, devs here do not know about.

Sure I will keep that in mind for next time :)
