### ISSUE TITLE
Pick timezone from /etc/timezone

### ISSUE THREAD

**Issue by jo-so** [calamares/calamares#1517]
The value of */etc/timezone* might have been set by the live environment. So, it would be useful to pick the initial setting from */etc/timezone*, if it's set.

**Comment by adriaandegroot** [comment]
- What OS , what distro?
- What kind of value is set there?

Making me guess these things makes it much harder to do anything about an issue.

**Comment by adriaandegroot** [comment]
.. since I have a Manjaro VM open just right now, for the record:

- A regular recent Manjaro install has an `/etc/timezone` file
- The file is a regular file
- The content of the file is the name of the selected timezone, e.g. `Europe/Amsterdam` followed by a newline
- In a Manjaro KDE Plasma installation, neither the *Time & Date* nor the *Date and Time* configuration modules change the content of `/etc/timezone`, while they **do** change the standard `/etc/localtime` link

I'm going to mark this issue up as a hacktoberfest one, because it's straightforward to implement (even if I doubt that it is useful; `/etc/timezone` is sufficiently non-standard that `QTimeZone::systemTimeZoneId()` is not going to consult it either)

**Comment by kkofler** [comment]
My Fedora installation does not have an `/etc/timezone` file at all.

**Comment by adriaandegroot** [comment]
Hacktoberfest 2020 will start soon, and this is a good kind of issue to do for it.

## Procedural

- [ ] Check that your Linux distro has a `/etc/timezone`. (Fedora and FreeBSD do not; Manjaro does; I have an older Netrunner Debian that does too). If this is interesting for a live CD, check that the live CD carries such a file or creates one.
- [ ] Make sure you can compile Calamares locally (see https://github.com/calamares/calamares/blob/calamares/CONTRIBUTING.md, which will point you onwards to the wiki)
- [ ] Make sure the locale module is enabled in your Calamares build (by default it is compiled, and in settings.conf: check the CMake output to see that it will be compiled, and then double-check that locale is listed in the show section of the sequence in settings.conf)
- [ ] Module sources are in https://github.com/calamares/calamares/tree/calamares/src/modules/locale ; make a branch, add your copyright statement to one of the .cpp files and add your name to top-level CHANGES, then start a PR with WIP in the title

## Functional

- [ ] Calamares picks up the default timezone (to be pre-selected in the *locale* module) just once, in `src/modules/locale/Config.cpp` in the function *getStartingTimezone()*, where the *region* and *zone* and *useSystemTimezone* are read from the configuration.
- [ ] Introduce a new configuration key, e.g. *defaultTimezoneSource* with suitable values for fixed, Qt-default, and `/etc/timezone`; document it in `locale.conf` and how it will fall back
- [ ] Document *useSystemTimezone* as deprecated, that it means "use Qt-default" in the other key
- [ ] In *getStartingTimezone()* determine which methods to try and in which order, then do them; complain about legacy configurations (e.g. with *useSystemTimezone*), but accept them
- [ ] Keep the first good timezone found

## Extras

I can't think of anything extra for this request.

## Post-Procedural

Feel free to push to the PR branch regularly; this shows how your progress is and allows early comments. Please stick to the commit-message style used in the rest of Calamares; do write out what-and-why with commits. It's OK to leave fixme's around for later in the branch and we can coordinate force-pushes if need be.

Note that FreeBSD has a patch to Qt itself, that reads a timezone from `/var/db/zoneinfo`; that's **part** of the necessary functionality (except for the filename). This is because FreeBSD sometimes doesn't have a symlink as `/etc/localtime` and Qt's system-timezone function would return the wrong thing.

**Comment by anoopmsivadas** [comment]
@adriaandegroot Hi, can i work on this issue?.

**Comment by kkofler** [comment]
I think that, if your distro uses `/etc/timezone`, support for writing this file is actually more important than support for reading the time zone to which the GUI should default from it.

**Comment by adriaandegroot** [comment]
So the idea is that the live CD environment does something magical during startup to populate `/etc/timezone`, and it **might** carry over into Qt's default system timezone and it might not, but if it doesn't then configuring Calamares to read the magic file and use that as the starting timezone -- rather than doing GeoIP or whatever all over again, and rather than relying on Qt's default timezone which might not be set correctly to the value in `/etc/timezone` -- is low-effort: basically a `QFile f; f.open(); auto z = f.readline().strip();`

**Comment by kkofler** [comment]
But if the user changes the time zone in the UI, and if we don't write to `/etc/timezone`, then the installed system will have a wrong time zone in `/etc/timezone` (the distro default rather than what the user selected). I think this is a more serious issue than not showing the correct default in the UI (which most users will change anyway).

**Comment by adriaandegroot** [comment]
After some more investigation:
 - Manjaro has the file, but only by accident
 - The only real (?) users of `/etc/timezone` may be **Debian** (and derivatives: I have a KDE neon user edition, 2020-08, which has the file)

See for instance [here (arch)](https://unix.stackexchange.com/questions/452559/what-is-etc-timezone-used-for) and [here (flatpak)](https://github.com/flatpak/flatpak/issues/2190) for mentions.

In KDE neon, adjusting the date and time timezone via the KCM also modifies `/etc/timezone` (in the live system). As does running `timedatectl set-timezone`, which is also the command that Calamares uses to set the timezone. If, in KDE neon, I set *useSystemTimezone* to true and use the system tools to set the timezone (e.g. to *Europe/Madrid*) then Calamares obediently starts with that timezone.

So, overall -- and after testing some bits and pieces -- I think there is **nothing to do** for this: in systems that support the file, it is already part of the system source of timezone information, and in Manjaro and some other systems where the file exists but only by accident and really shouldn't exist, we don't want to read the file anyway.

So I'm going to close this as "in retrospect, not needed" .. @jo-so if there's a specific system where this **would** have an impact, please re-open or file a new issue.
