### ISSUE TITLE
Netinstall module : change number when package is installed

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1582]
Is it possible to change the text at the bottom left to show that Calamares is 'busy' installing packages.

If you select 30 packages to install the slider will stay there and not move nor will the numbers change for quite a while.

Then people think calamares hangs and reboot. If you have a slow internet connection and a slow harddisk ... users abandon the installation.

If we were able to use a **counter** that decreases after each installation you would see the progress even if the slider stays the same.

**Comment by adriaandegroot** [comment]
This sounds like a dup with the other progress-during-package-installation issues. The primary problem is that **during** a package operation (e.g. installing a whole bunch of packages) we have no feedback. This is because:
- the module is in Python, and doesn't have nice hooks to the usual progress-reporting that a C++ module would have
- the package managers don't provide usefull progress output when run

A useful initial PR here would be to (say) read the output of *pacman* while it is being run, and just debug-logging progress. Then we know it would be *possible*, and that building more extensive progress-reporting is useful.

For *try_install* packages, the package manager is called once per package; regular *install* packages (and the ones that come from *netinstall*, unless marked non-critical) do one call to the package manager. What might be nice is at least **stubbing** (1/n) progress (that's the start of "more-extensive-progress-reporting"). The loops for *try_install* can then count up by one each time.

And a final idea is to report the total count as well.

**Comment by kkofler** [comment]
> the package managers don't provide usefull progress output when run

That needs to be relativated: **some** package managers do provide suitable progress report, either by default or with suitable flags. E.g., `dnf` is pretty good at reporting progress. The problem is that the output format differs vastly between the different package managers, and some do not provide any progress reports at all. So scraping the progress in a portable way is very hard.

**Comment by kkofler** [comment]
One alternative would be to always call the package manager once per package (though it would still not solve the issue for dependencies and transitive dependencies that the package drags in). The drawback is that this makes the overall progress even slower because the initialization phase can be quite time-consuming. (Some package managers will even refetch metadata each time. Most are smart enough not to do that (or require an explicit refresh, e.g., `apt-get`), but still spend a lot of time computing each transaction.)
