### ISSUE TITLE
Username is not named correctly during installation

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1591]
Calamares 3.2.35
Os : ArcoLinux

While installing the os we get information in the bottom left. 
There seems to be a typo or wrong code when the name of the user is created.

![ArcoLinux_2020-12-04_21-46-48](https://user-images.githubusercontent.com/36679406/101213295-70b8c780-367a-11eb-90c8-9425b54e0f76.png)

**Comment by philmmanjaro** [comment]
Most likely [this](https://github.com/calamares/calamares/blob/calamares/lang/calamares_en.ts#L1043) ...

**Comment by adriaandegroot** [comment]
These show up sometimes in the data that comes from Transifex, and I don't know why. I went through all the translations that had a stray `{1?}` and removed it, then modified the sources so that there was one string less -- it *seems* to happen when two strings differ only by a single character or something like that.

Updated translations / sources have been committed.

**Comment by arcolinuxz** [comment]
Solved in 3.2.35.1
