### ISSUE TITLE
Command line argument to remove UUIDs from the log

### ISSUE THREAD

**Issue by superbonaci** [calamares/calamares#1593]
Add command line option inside OPTIONS:
````
       -n, --nouuids
              Replaces partuuid and uuid with PARTUUID[NUMBER] and UUID[NUMBER].
````

EXAMPLE
```
    Building partition information map 
    ..  partitions on "/dev/nvme0n1" 
    ..  mapping for "/dev/nvme0n1p1" "/dev/nvme0n1p1" 
    ..  mapping for "/dev/nvme1n1p4" "/dev/nvme1n1p4" 
     partlabel :   "" 
     partuuid :   "928CA954-8FC4-F390-3467-C353864C13F4" 
     parttype :   "" 
     partattrs :   "" 
     mountPoint: :   "" 
     fs: :   "ntfs" 
     fsName :   "ntfs" 
     uuid :   "9030750C970FDBB3" 
     claimed :   "false" 
    ..  partitions on "/dev/sda" 
    ..  mapping for "/dev/sda1" "/dev/sda1" 
     partlabel :   "" 
     partuuid :   "B2BE9C80-8413-4FDB-A562-6CA072385C02" 
     parttype :   "" 
     partattrs :   "" 
     mountPoint: :   "" 
     fs: :   "BitLocker" 
     fsName :   "BitLocker" 
     uuid :   "" 
     claimed :   "false" 
```
with 

```
    Building partition information map 
    ..  partitions on "/dev/nvme0n1" 
    ..  mapping for "/dev/nvme0n1p1" "/dev/nvme0n1p1" 
    ..  mapping for "/dev/nvme1n1p4" "/dev/nvme1n1p4" 
     partlabel :   "" 
     partuuid :  PARTUUID[1]
     parttype :   "" 
     partattrs :   "" 
     mountPoint: :   "" 
     fs: :   "ntfs" 
     fsName :   "ntfs" 
     uuid :   UUID[1] 
     claimed :   "false" 
    ..  partitions on "/dev/sda" 
    ..  mapping for "/dev/sda1" "/dev/sda1" 
     partlabel :   "" 
     partuuid :   PARTUUID[2]
     parttype :   "" 
     partattrs :   "" 
     mountPoint: :   "" 
     fs: :   "BitLocker" 
     fsName :   "BitLocker" 
     uuid :   UUID[2] 
     claimed :   "false"
```

In case `PTUUID` exists do it as well.

**Comment by abucodonosor** [comment]
Why?

**Comment by adriaandegroot** [comment]
@abucodonosor because UUIDs can, I suppose, leak personal information. Calamares redacts some things in the log already, it could redact UUIDs as well (or just not log them ..). It will need some figuring out to ensure that logfiles remain useful to match up various things (partitions, mountpoints) and not all UUIDs are sensitive (the GPT partition IDs for instance).

**Comment by apt-ghetto** [comment]
> because UUIDs can, I suppose, leak personal information.

Can you explain this? Which UUID contains personal information?

**Comment by superbonaci** [comment]
UUIDs themselves, but if you don't want to make the change it's ok, I'll write a python script to do it myself.

**Comment by superbonaci** [comment]
Thanks a lot.

**Comment by adriaandegroot** [comment]
There's no command-line argument, it "just happens". I looked at your log file, where you had removed things, and applied a redaction there. There are probably more places, but those are simple PRs now (add a `RedactedName( "some context", ... )` around the `...` that is being logged, to get it logged as *some context$hex-identifier* -- the logging consistently uses the same hex-identifier for a given name within one run of Calamares, but this is salted randomly each run).

So in my log, instead of *VBOX HARD DISK* as a name, I now see e.g. *DevName$deadbeef* (the hex-identifier varies per run, but all *DevName$deadbeef* are the same name). It will no longer leak *MY SHAMEFUL OPENSOLARIS DISK* as a name.
