### ISSUE TITLE
JobResult::error doesn't result in message box

### ISSUE THREAD

**Issue by ollieparanoid** [calamares/calamares#1600]
I would have expected that returning `JobResult::error` in a job's `exec()` opens a message box and shows the error to the user. However, with this job I wrote:

https://github.com/calamares/calamares-extensions/blob/0d057478b026de73aaa5be2df9ea4a01231818ab/modules/mobile/PartitionJob.cpp#L110

...the error is written to the log, but _not shown_ to the user. Calamares then continues with the next job, mount in my case, and this one fails here and _does show_ a message box to the user:

https://github.com/calamares/calamares/blob/2ccd5a2043003024a801e3d41f4604cd3a60ebf0/src/modules/mount/main.py#L128

The first error message would have been much more useful, the second is rather irritating because that's not the original error.

So I'm wondering, is it possible to make my job show a message box, just like the (python) mount job? Is this a bug in my code or in calamares?

Thanks!

**Comment by adriaandegroot** [comment]
The problem is that you're running the job (partitioning) the moment you leave the page. And you log the error result, and then carry on as if nothing is the matter. Normal processing runs jobs in the *exec* phase, and Calamares knows all about handling errors from jobs in the *exec* phase. That's where the pop-up comes from, as well as emergency shut-down support and all the rest.

**Comment by adriaandegroot** [comment]
The ViewManager does have a method for this, though: `onInstallationFailed()` so you could do something like:

```
ViewManager::instance()->onInstallationFailed( res.message(), res.details() );
```

This kind of fatal error will exit the installer, though.

**Comment by ollieparanoid** [comment]
Aaah, that makes sense. Thanks for the detailed answers!

I'll close this then, not a problem in Calamares.
