### ISSUE TITLE
Make "finished" module usable for mobile

### ISSUE THREAD

**Issue by ollieparanoid** [calamares/calamares#1601]
I'm implementing the use case for [mobile](https://github.com/calamares/calamares-extensions/tree/calamares/modules/mobile) right now, that will allow installing from SD card to eMMC. I considered using Calamares' "finished" module at the end to let the user know that they need to remove the SD card before powering the device again (so it doesn't boot into the installer OS again, but into the installed system).

But there are several things that would need to be implemented first:
* Override/extend the message to be displayed from global storage
  * @adriaandegroot wrote in #calamares:
    > medium term it might make sense for there to be an API in libcalamares for adding messages to the finished module (I'd put it there as an "it is understood that a finished-module will look in global storage under these keys"), and then make finished read out GS to add extra messages.
  * I think override is easier than just extending the message. Because right now it talks about that you could continue to use the live environment and has the word "PC" and not "phone" or "device".
  * I'd need this in global storage, so I can display different messages depending on the installation target chosen by the user during installation (SD to eMMC or not).
* Add an option to global storage, so it can optionally show "poweroff" instead of "reboot".
* Actually show the reboot / poweroff button in the UI, because the mobile module expects the navigation to be hidden. (put that in finished.conf?)

Nice to have:
* global storage option to automatically reboot / poweroff after a given timeout.
  * I'd set this to 10s by default in mobile, unless the user needs to eject the SD card after poweroff, then I would disable the timeout.

I wrote this down for the record, and so we can discuss if the ideas could be implemented that way.

Regarding mobile, for now I'll just display the "remove SD card" information in the last screen before the installation starts, and automatically reboot or poweroff with the "shellprocess" module.

**Comment by adriaandegroot** [comment]
You might be interested in XeroLinux. The *finished* module that they use, has buttons "reboot" and "quit" in the page itself, rather than a checkbox and the navigation panel. I believe the buttons are hard-wired to execute specific shell scripts.

For just showing something else -- without collecting messages across different modules -- you could use the *finishedq* module instead. That gives you all the freedom of design and wording that you like. You may need to write some (QML / JS) code to check global storage to find out the type of installation. You could hook up to the `onActivated` signal (er .. might be called something different, check the QML-modules documentation) and start a timer if you want a timed auto-reboot.

I can do a bit of messing-about with the *finishedq* module and see if I can come up with something that resembles your list-of-wishes; you could hand that off to a real designer afterwards.

**Comment by adriaandegroot** [comment]
Basically @demmm had done all the work already; I just added a countdown timer. You can fiddle with the phrasing of the texts in the QML if you like. To use this, rename or copy the `finishedq@mobile.qml` to `finishedq.qml` in your branding directory, or copy it with the name unchanged and set the module-id to *mobile* in `settings.conf` -- you can watch the search for QML happening in the logfile.

It's not clear to me if poweroff vs reboot is a thing that should be selected **during** installation, or that depends on the device being installed on; similarly for SD vs eMMC. You can easily check GS in the `onActivate()` function and set relevant texts then.

**Comment by ollieparanoid** [comment]
Thanks a lot for getting back to this. I'm a bit overloaded with tasks right now, but making a note to try this out in the future. (and unpackfsc from calamares-extensions also looks promising, if I remember right this could help getting rid of python in our install image and save 60 or 80 mb or something.)
