### ISSUE TITLE
Can not find DNS in WiFi connections after installation via Calamares due to copied /etc/resolv.conf

### ISSUE THREAD

**Issue by embar-** [calamares/calamares#1630]
Since https://github.com/calamares/calamares/commit/a45f78e9ac01c93cb4c178722fda54697e0fe050#diff-5960a6e192d1804ed3e3b84905264cff37275564879d6d87d0668369b495c21b Calamares writes `/etc/resolv.conf` file. However at least in _openSUSE_ it is just symlink into `/var/run/netconfig/resolv.conf` . Later after installation, as this file already exist, openSUSE Linux fails to properly open any regular internet address, i.e. it shows errors "could not resolve host", due to wrong DNS as it came hardcoded during installation.
Some distribution, like Debian, already intentionally disabled this Calamares functionality: 
https://git.parrotsec.org/packages/installer/calamares/-/blob/master/debian/patches/disable-resolvconf-creation.patch 
I recommend to remove lines about copying of /etc/resolv.conf file upstream.

**Comment by embar-** [comment]
Or, if we need internet in chroot, please at least dont't forget to remove /etc/resolv.conf at the end of installation

**Comment by kkofler** [comment]
Basically, there are 3 ways `/etc/resolv.conf` can be handled:
* manually written (or generated by the installer and potentially manually edited),
* automatically generated by NetworkManager,
* handled by `systemd-resolved`.

We need to make sure that we do the right thing in all cases. If `/etc/resolv.conf` is a symlink, overwriting it with a regular file is not a good idea.

**Comment by kkofler** [comment]
There may be additional ways (which Calamares also needs to work with), but the 3 above are those that can easily be used on Fedora, the distro I am running. See also: https://fedoraproject.org/wiki/Changes/systemd-resolved

**Comment by kkofler** [comment]
My `/etc/resolv.conf` is currently managed by NetworkManager, and it is a symlink to `/var/run/NetworkManager/resolv.conf`.

**Comment by adriaandegroot** [comment]
The code has been there since Calamares 3.1, so it's a bit weird to have issues with it now (or I wish Debian would have reported it in a meaningful way). There's not much explanation *why* in the original commit. To me the whole code looks like something that assumes that the ISO (host system)  configures networking in such a way that that also applies in the target system.

But .. now I'm wondering why copying NetworkManager configurations is needed (e.g. in Debian) but the other bit is not.

Anyway, plan-of-attack would be:

- [ ] refactor this into separate steps: `copy_networkmanager_config()` and `copy_resolv_config()` so it is easier to test and to document
- [ ] figure out if configuration options make sense for this module
- [ ] if so, write them, add a schema file, etc.

A fourth item I'd like to add here if there are options and the whole thing is tidied up and covers the different cases Kevin describes above, is porting the module to C++; it's a fairly straightforward module for doing that.

**Comment by embar-** [comment]
Seems at least in older openSUSE (2 years old [Tumbleweed](https://lists.opensuse.org/opensuse-factory/2019-02/msg00088.html) or [Leap 15.0](https://forums.opensuse.org/showthread.php/536569-change-resolv-conf)) `/etc/resolv.conf` was a regular file, thus previously Calamares behavior did not caused problems. However recent openSUSE versions (from [Leap 15.1](https://forums.opensuse.org/showthread.php/536569-change-resolv-conf)) it use symlink.

Maybe at least we could check whether `/etc/resolv.conf` is symlink in main system (host): if so, then Calamares could avoid touching `/etc/resolv.conf`; but if it is a regular file, then it could copy file as it do now.

**Comment by adriaandegroot** [comment]
The fix from @raurodse seems to do the trick: if the source is a symlink, it remains a symlink in the target (with the same path, absolute or relative).
