### ISSUE TITLE
Variant locations for lightdm.conf

### ISSUE THREAD

**Issue by grafiksinc** [calamares/calamares#1638]
**Describe the bug**
This is a 64bit Debian Bullseye base.....lightdm does not autologin after install when adding a check in the box during install.
The problem is.... debian bullseye does not use the default location  **/etc/lightdm/lightdm.conf**  to configure lightdm.
It uses **usr/share/lightdm/lightdm.conf.d/01_debian.conf**

Could Calamares be adjusted to allow different locations, for configuring lightdm rather than just the default **/etc/lightdm/lightdm.conf**

The current 01_debian.conf has this code:
```
# Debian specific defaults
#
# - use lightdm-greeter session greeter, points to the etc-alternatives managed
# greeter
# - hide users list by default, we don't want to expose them
# - use Debian specific session wrapper, to gain support for
# /etc/X11/Xsession.d scripts

[Seat:*]
greeter-session=lightdm-greeter
greeter-hide-users=true
session-wrapper=/etc/X11/Xsession
```
What we see is (a) the path is different and (b) there's no #autologin-user= line in there either.

Even  if I were to add the autologin-user line I don't think calamares will even  see the setting because it is a different path altogether.

I am sure other Debian based OS's could benefit from a built in work around. if possible to Calamares.
--Thank you - Tommy

**Comment by adriaandegroot** [comment]
I installed the Debian-based OS in question, and it's kind-of-weird (in the installed system):

- There **is** a `/etc/lightdm/lightdm.conf`, and it has a commented-out *autologin-user* line. This is weird because Calamares would normally edit exactly that file and set autologin.
- There **is** a `/usr/share/lightdm/lightdm.conf.d/01_debian.conf` which doesn't have an *autologin-user* entry. That's on the distro, for not putting such a line in there, and on Calamares which doesn't know about the file and won't edit it anyway.
- The config file for Calamares only configures *slim*, not lightdm -- and slim isn't even on the system!

I edited the start-calamares script to add `-D6` to the command-line arguments: then you get a nice detailed log in `~/.cache/calamares/session.log` (where ~ is for root). This shows lots of debugging, but nothing really *useful* for the displaymanager module.

**Comment by adriaandegroot** [comment]
So I added *lightdm* to the list of display managers to configure for Calamares, editing `/etc/calamares/modules/displaymanager.conf`, and ran the otherwise-unchanged install again. This time it *did* edit `/etc/lightdm/lightdm.conf`, adding the correct autologin user, and after installation and reboot .. it auto-logged me in. Note that LightDM itself documents that the config file in `/etc/` is read (and Calamares code comments say "is read **last**") so I think all-in-all this does not need any work except maybe that we should detect situations where the DM configuration is insufficient.

**Comment by adriaandegroot** [comment]
@grafiksinc so to sum up:
- slim (the display manager) is installed on the ISO **and** installed on the target system
- slim is **not** the active display manager, either on the ISO or in the installed system
- lightdm is installed on both, and is the active display manager on both
- the calamares configuration in `/etc/calamares/modules/displaymanager.conf` on the ISO is set up to configure *slim* only, not *lightdm*.

Modifying the Calamares configuration on the ISO makes the problem go away: then lightdm is properly configured for autologin on the target system. So I'm going to close this as "fix the configuration, no code changes needed."
