### ISSUE TITLE
Add an option to include more than one keyboard layout and an option to set keys for switching keyb layouts.

### ISSUE THREAD

**Issue by panospolychronis** [calamares/calamares#1642]
When you're installing a distro with calamares you're able to choose only one keyboard layout.
I'd like to see the option to include more layouts and an option to set keys for keyboard layouts switching
For instance, in my case if i'll select Greek layout, i cannot set a username with latin characters in the next steps of the installer. It would be better to set to "US,GR " and set e.g. Shift-Alt to switch between those layouts.

**Comment by adriaandegroot** [comment]
There is a table of non-ascii layouts that get this treatment in `src/modules/keyboard/`, so this is pretty straightforward.

**Comment by adriaandegroot** [comment]
You'll need to test this in some future version of your distro (or rebuild Calamares with this change). It *should* add the alt-shift as switcher when you select Greek as a keyboard layout. καλισπερα! (Although since I started Calamares in English, I needed to alt-shift to test the keyboard in Greek)

**Comment by panospolychronis** [comment]
Ok then i'll check again later... thanks! :)
