### ISSUE TITLE
[Question] Is it possible to change the display manager and bootloader in the installation?

### ISSUE THREAD

**Issue by Toadfield** [calamares/calamares#1663]
I never saw any distro do that.
So does that work at all?

**Comment by demmm** [comment]
Distributions can adjust what will be used for both, but I presume you mean for the end user, as a GUI option?

**Comment by Toadfield** [comment]
yes,I mean if it is possible to choose from the user in the package selection section.

**Comment by kkofler** [comment]
Calamares does not currently include any modules that do this. It is possible to implement custom modules, but the existing ones won't do the job at this time.

**Comment by adriaandegroot** [comment]
I imagine that *displaymanager* selection **is** possible, though it is something you would have to put together from several modules and test carefully (and then, hopefully, submit to the Calamares wiki so it's available for others):
- use *netinstall* or *packagechooser* to select a DM (*packagechooser* would be better because you can configure it to "pick exactly one", but it doesn't integrate with the *packages* module as yet)
- use *packages* to install that DM in the target system
- use *displaymanager* to configure the DM on the target system

So it's a matter of getting the modules in the right order.

**Comment by adriaandegroot** [comment]
(This is possible because the *displaymanager* module goes through a list of potentially-installed DMs and configures the ones it finds)

**Comment by adriaandegroot** [comment]
The *bootloader* module (which currently supports grub (on BIOS) and a choice of grub, sb-shim and systemd (on EFI) does not have anything to set the bootloader from "outside" the module. It just reads the config file and uses the configuration from there.

That said, it might be an interesting point of extension -- one that also could introduce rEFInd, and LILO -- but I suspect there's a lot of refactoring needed in the module to give it (a) some kind of consistent approach to installing the various bootloaders (b) useful configuration parameters for all of them. A different approach would be to have separate bootloader modules and enable one or the other of them.

**Comment by deprov447** [comment]
> I never saw any distro do that.
> So does that work at all?

[EndeavourOS](https://endeavouros.com/docs/installation/calamares-offline-installer-tips/) uses calamares to choose between DEs. https://github.com/endeavouros-team

**Comment by killajoe** [comment]
yes we offer choosing DE with netinstall module and some script we run after install from calamares is finished (cleaner_script) this is not hard to setup.

**Comment by Toadfield** [comment]
> > I never saw any distro do that.
> > So does that work at all?
> 
> [EndeavourOS](https://endeavouros.com/docs/installation/calamares-offline-installer-tips/) uses calamares to choose between DEs. https://github.com/endeavouros-team

I know that that is possible,but I asked if it's possible to choose which display manager and bootloader gets installed.

**Comment by philmmanjaro** [comment]
@Toadfield be more specific what you expect. Let me guess here: An installer on which you can specify the bootloader, display manager and maybe other packages of your choosing to be installed. Most distributions have predefined what to ship per edition. Some offer you to select some packages or get all packages on the fly during installation.

Calamares as an installer framework can be used to achieve that, but for now I don't see any given distribution which uses Calamares fully doing that ...

**Comment by petsam** [comment]
> I know that that is possible,

Then your question is answered.

What you may confuse is that Calamares provides the tools/framework and the (already created and provided from some distribution developers) installer on the ISO provides the chosen features to the users. So, I suppose that your complete question 

> if it's possible to choose which display manager and bootloader gets installed

should be asked to each **distribution you are interested in installing**. (because they might not want to provide such feature...).

**Comment by demmm** [comment]
>A different approach would be to have separate bootloader modules and enable one or the other of them.

Is it possible to adjust settings.conf after Calamares has loaded? Not clear how this would be implemented otherwise.
I am working on such an option (splitting bootloader, adding rEFInd and creating a GUI/using packagechooser to offer a bootloader selection page).

**Comment by adriaandegroot** [comment]
@demmm there is, at this point, no way to change "the flow" of operations. What's in *sequence* in `settings.conf`, the steps for show, exec, show, whatever .. those are fixed once Calamares has started. I can imagine having some way of influencing it -- but you can fudge this as follows:

- have the packagechooser set a GS key to some value
- have the modules check the GS key to see if they should run, and just skip if they should not
- load all the modules that handle that GS key .. only one will run, based on that GS key

I suppose we could make a generic way of expressing that, rather than coding it into each individual module.

**Comment by demmm** [comment]
>I suppose we could make a generic way of expressing that, rather than coding it into each individual module.

I'll start with `per module` (since I already have a few that load that way, as is, don't run on `if`)
If I get 2-3 bootloader options working that way, it will be time enough to work on a generic way.

**Comment by kkofler** [comment]
> there is, at this point, no way to change "the flow" of operations.

And that, along with the fact that the choice of bootloader is only for UEFI whereas we only support GRUB (more precisely, GRUB 2) for BIOS, is exactly why the unified `bootloader` module was created, a change that you now apparently want to undo. There was just no better way to avoid duplicating the BIOS GRUB code for the several UEFI bootloaders.

IMHO, the easiest way to implement user bootloader selection would be to simply extend the unified `bootloader` module to read the `efiBootloader` option from global storage before falling back to reading it from the config file.

As for `rEFInd` support, that could, and IMHO should, be added to the existing unified `bootloader` module.

**Comment by kkofler** [comment]
Sorry, but I think you misunderstand my point: What I wish to discuss is not so much the history of the `bootloader` module (which I only brought up to explain why the code is structured the way it is), but its future. And, as I have already written on IRC, I think the way to go for the future would be to have a unified `bootloader` module in C++, where the bootloader to use is normally chosen by a config file entry (as in the current Python `bootloader` module), but can be overruled by a global storage entry (to make it user-selectable). The same configurability could also apply to the BIOS bootloader if there is any interest in supporting anything other than GRUB 2. (To be future-safe, we could also support a configuration setting there, with `grub` as the only currently supported option.)

I do **not** object to your GUI option, I am only unhappy with the way you implemented it. But in the end, it is @adriaandegroot who has to decide anyway.

**Comment by adriaandegroot** [comment]
I'm closing this one since the original question / issue has been answered:

**Yes**, you can change the display manager during installation, because the *displaymanager* module looks for whatever is installed, and you can configure Calamares to install a chosen DM.

**Eventually Yes**, you could change the bootloader during installation, even if it is currently not supported. A PR for that would add a check in the *bootloader* module that looks at a specific GS key to override the config-file-choice. Then you can configure Calamares to set that GS key via a user choice (e.g. via the *packagechooser* module).

**Comment by demmm** [comment]
>Eventually Yes, you could change the bootloader during installation

Just to add that it is quite doable, this is implemented downstream (very easy to do in the packagechooser(q) module), but so far no interest shown from other distributions to adjust it so that it is distro agnostic (needed for a PR).
