### ISSUE TITLE
Calamares does not recognize the SSD

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1670]
Reported on behalf of the user.

Here is the report : https://arcolinuxforum.com/viewtopic.php?f=120&t=2575&p=10427#p10427

Hightlights:
ArcoLinuxD v21.03.11
Calamares 32.2.39.1

SSD KINGSTON RBUSNS8154P3256GJ1

User tried Endeavour Os as well - same issue - we can rule out an ArcoLinux configuration issue.

User is willing to give us more info if required.

Probe url with all the possible technical specs : https://linux-hardware.org/?probe=97c81f4b56

Asking now if he checked the motherboard settings?

**Comment by abucodonosor** [comment]
Seriously, why is THIS a calamares issue?

```
...  neither GParted or lsblk find my internal laptop ssd that my Windows 10 is installed on.

```

So why do you think this is a calamares problem?

Ask the user for dmesg's and figure what is wrong.

**Comment by adriaandegroot** [comment]
More a hardware issue on the user's end (or a general Linux problem; none of the logs provided show that there **is** an SSD in the machine).

**Comment by arcolinuxz** [comment]
And is precise his issue.

**Comment by abucodonosor** [comment]
I don't know of any BIOS settings to hide an NVME device for the OS.
The only mistake you could do in BIOS ( with some weird BIOSes ) is to set
the controller to AHCI, while having NVME as your boot device. A sane BIOS 
won't allow that but...

The problem may be the NVME device itself, having broken settings in the firmware,
missing filds, broken/missing ASPM handling. Linux will pretty much kill off such a driver,
for different reasons. However, there are boot options and upstream code to work around such problems,
once the problem is identified. The best thing you can do is to as the user for a full dmesg and look for
nvme errors.

**Comment by arcolinuxz** [comment]
After changing RAID to AHCI, my SSD is now recognized by GParted and Calamares.

Lets keep that in mind to tell our users.
He fixed my changing the setting of his motherboard

**Comment by erikdubois** [comment]
I wonder if Calamares can give more output in the log file

https://termbin.com/db97

Gparted gave more info on what is going on. (NTFS at least 9 bad sectors)

https://arcolinuxforum.com/viewtopic.php?p=10445#p10445
