### ISSUE TITLE
No Documentation explaining packages.conf and backends

### ISSUE THREAD

**Issue by jcfrosty** [calamares/calamares#1676]
**Is your feature request related to a problem? Please describe.**
I'd like to see some documentation on package management backends for Calamares. I can see packages.conf files with a "backend: pacman" line, but I cannot find where backends are stored, what the code looks like, how I would write my own backed, etc.

**Describe the solution you'd like**
I'd like clear instructions on how to create a backend for calamares packages.conf. We're developing a new package manager for prebuilt packages based on funtoo/gentoo.

**Comment by kkofler** [comment]
The backends are Python classes in https://github.com/calamares/calamares/blob/calamares/src/modules/packages/main.py . You will have to add such a class for your package manager. It is fairly simple Python code. Mostly, the only trick is to figure out the correct commands to use, and in particular, whether additional switches are required or not. (Some package managers have more installer-friendly defaults than others. E.g., DNF requires passing `--disablerepo=* -C` to allow removing packages without Internet connectivity, and it also returns an error exit code if the package did not exist to begin with. But since you folks are also developing your package manager, you should be able to avoid such design pitfalls to begin with.)
