### ISSUE TITLE
button not translated on system requirements dialog

### ISSUE THREAD

**Issue by linlinger** [calamares/calamares#1688]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.
Make sure you can't pass installation check like you don't have enough disk space. and the installer language can't be English
**To Reproduce**
1.Open calamares 
2. Click on Details...
3. See error

**Expected behavior**
The close button should be translated to system language
**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.
![截图_2021-05-10_13-16-30](https://user-images.githubusercontent.com/32541118/117609126-03154800-b192-11eb-81d4-241dc9b08128.png)

**Additional context**

**Comment by demmm** [comment]
This most probably means that particular string is not translated to zh_CN in Transifex, not a bug in the installer.  Have you checked Transifex, or are you able to help to get zh_CN more completely translated?

**Comment by adriaandegroot** [comment]
"Close" and such are special, in the sense that they are strings **also** used in Qt for standard UI elements. When I run `LANG=zh_CN.UTF-8 ./calamares  -d` (the `-d` is for "development mode" since I'm not working from a live-ISO), I get this:

![image](https://user-images.githubusercontent.com/19431457/117651543-57b8c300-b192-11eb-93b1-cea8ebb96a1b.png)

You can see that "Close" **is** translated. You can also see that my fonts are incomplete, because the window title is missing one character, and that I'm running it as myself and not as root -- that **may** be a cause, that translations for Qt-UI-elements aren't loaded in root.

@linlinger Which Calamares and Qt version are you using? This looks like a beautifully-themed distro, is it available somewhere?

**Comment by linlinger** [comment]
![截图_2021-05-10_19-33-55](https://user-images.githubusercontent.com/32541118/117653221-b6982f80-b1c6-11eb-8d47-9ff37e4e0247.png)

I don't know what is going on with qt. I always have problems with buttons in qt applications
@adriaandegroot . It's SpanningTree Linux . A distro based on Arch Linux. It's still under development

**Comment by kkofler** [comment]
Make sure that your Qt is compiled with ICU support, it is basically required on *nix, though as far as I know, you can build a Qt with limited to no localization support without it.

**Comment by linlinger** [comment]
I download the built  binaries from Arch Linux . I don't know how to make sure qt has icu support . I know that I installed a package named icu

**Comment by linlinger** [comment]
btw, the translation should be simplified Chinese. People in China mainland use this and traditional Chinese is mainly  used by people in Hong Kong , Taiwan province and Marco .
You should correct this.

**Comment by adriaandegroot** [comment]
I can reproduce the problem -- pretty closely, in any case -- with an ArcoLinux install ISO, where starting the installer with Chinese also does not get me translated OK and Close buttons.

For the translations themselves, I must admit that I know far too little (about) Chinese to say something useful about the translations. There are *three* Chinese translations in Transifex (here, named by LANG code): zh_CN, zh_TW and zh. The last of the three was requested recently, by someone who did not answer my question about **why** another translation is needed. That is a discussion to be had within the translator teams, though.

**Comment by linlinger** [comment]
The code of Chinese has three when using UTF-8. zh_CN (简体中文中国大陆) ,zh_HK (繁体中文中国香港) and zh_TW.(繁体中文中国台湾) The translation should has three different. Btw how to join calamares translation team. I would like to translate this application

**Comment by adriaandegroot** [comment]
(Sorry, I was distracted and forgot there was also an open-right-now question in this issue) @linlinger Join Calamares translations by following the [translation guide](https://github.com/calamares/calamares/wiki/Translate-Guide), which is basically:
- register with [Transifex ](https://www.transifex.com/)
- join one of the teams, e.g. [zh_CN](https://www.transifex.com/calamares/teams/20061/zh_CN/) .. I think you can join teams without asking.
- there are 3 translations for Calamares right now (zh, zh_CN, zh_TW). I don't really know what the *zh* one is supposed to be for -- it also has no translations yet.

**Comment by linlinger** [comment]
zh？ Just ignore this，No locale named zh

**Comment by adriaandegroot** [comment]
So, as a background:

- starting Calamares in a particular (system) locale loads the translations for Qt-internal bits in that locale: `LANG=zh_CN calamares` makes it run in Simplified Chinese (leaving out LANG starts it in whatever locale the system defaults to)
- on the welcome page, click "About"; the About dialog uses Qt-internal "OK" button
- this button is not changed if you change the language Calamares runs in from the welcome-page drop-down

For me this is easiest to see and test by running Calamares and changing it between English, Chinese and Russian. It demonstrates that Qt **has** the translations for the OK button, but we're not changing them in the right way. After a day of looking, I couldn't find a way to change it effectively, so I gave up and now we use Calamares texts rather than Qt-internals.

**Comment by linlinger** [comment]
Yes. And I figured it out. At that time I generated  system locales by using a systemd service. It will be done on system. So I think this could be my fault. And I changed the way generate system locale . It's done on build time and no more systemd service. It won't happen again even if  I change language. The way  I set language by adding LANG=zh_CN.UTF-8 in ~/.dmrc
