### ISSUE TITLE
Boost.python error in job "package"

### ISSUE THREAD

**Issue by azharrafif5** [calamares/calamares#1694]
I getting this error

![VirtualBox_Cala Test Ubuntu_15_05_2021_14_19_55](https://user-images.githubusercontent.com/75826509/118352012-48b68400-b589-11eb-8f1b-10db62dc1b39.png)

help meeeeeeee

**Comment by erikdubois** [comment]
Calamares (apt) can not find two packages. Do these packages exist?

Op za 15 mei 2021 om 09:25 schreef azharrafif5 ***@***.***>:

**Comment by adriaandegroot** [comment]
It's a bug in the *packages* module, in the sense that removing a non-existent package **should** not fail, in my opinion. At least one *packages* backend has a comment about that, but the *apt* backend there does fail if the program it calls returns a non-zero exit code.

@azharrafif5 , there are three things you can do:
- Repair the list of packages that you are passing to the packages module, set for removal. Take out the packages (two of them) that do not exist in the target system after a normal installation.
- Figue out how to call `apt` or `apt-get` to remove a package, so that it returns a 0 (zero) exit code **even if** the package doesn't exist. I would have guessed that `-q -y` would do it, but no. Then patch the two calls in the `remove()` method. Maybe use `apt` instead of `apt-get` or whatever.
- Fix the code to ignore failures on removal, e.g. in this chunk:
  ```
    def remove(self, pkgs):
        check_target_env_call(["apt-get", "--purge", "-q", "-y",
                               "remove"] + pkgs)
        check_target_env_call(["apt-get", "--purge", "-q", "-y",
                               "autoremove"])
   ```
   Replace the two calls to `check_target_env_call()` by `target_env_call()`.

**Comment by demmm** [comment]
>It's a bug in the packages module, in the sense that removing a non-existent package should not fail

The packages.conf specifically states the install will abort in such cases:
https://github.com/calamares/calamares/blob/calamares/src/modules/packages/packages.conf#L93

So unless instructions change, it is not a bug, but expected behavior.

**Comment by adriaandegroot** [comment]
@demmm oh, good point. I hadn't looked into the rest of the code. TBH I'm not sure what the point of failing-if-the-package-isn't-there is, and the *dnf* backend even explicitly ignores the return code (taking option 3, above).

@azharrafif5 so the fourth option is to use *try_remove* instead of *remove* with your package list.

**Comment by kkofler** [comment]
It really depends on the underlying package manager how it treats removing a non-existent package. For the old `yum`, this was not an error. For `dnf`, this is actually an error, which broke Calamares testing on images which do not include it out of the box for me (because the `calamares` RPM is then only installed on the overlay and not on the image that gets installed, so when Calamares tries to remove it from the chroot, `dnf` would error), which is why I made that workaround. I suppose we could do the same for other package managers that behave that way, or you could try to get the package manager fixed so that it either never treats this as an error or at least offers some flag that Calamares can pass to get it to not report this as an error. Or I suppose you could just use the `try_remove` command instead of the `remove` command.
