### ISSUE TITLE
Install On arch Linux

### ISSUE THREAD

**Issue by azharrafif5** [calamares/calamares#1697]
how to install calamares in arch linux

i use command: pacman -S calamares
but
output: error: target not found: calamares

**Comment by adriaandegroot** [comment]
There is no package *calamares* for Arch. The Arch User Repository (? AUR) does [not have one](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=calamares&outdated=&SB=n&SO=a&PP=50&do_Search=Go) either. Not all software is packaged for each distro.

There are Arch-**derived** distributions, like Manjaro, ArcoLinux, .. that **do** have Calamares packages. You may be able to add a package from one of those distro's, by adding their repo's, but from what I know about Arch and package stability, that is probably difficult: the Calamares packages will expect other versions of just-about-everything than what's in the rest of AUR. You could try, but that's outside the scope of the Calamares issue tracker.

**Comment by adriaandegroot** [comment]
I'll follow up with some general comments, which echo some things that @demmm said in a different issue. You've opened a bunch of issues recently. It seems you are trying to make a distro -- based on Ubuntu, maybe, or now Arch in this issue. As a general guide, it's **easiest** to start from a place where some parts are already done. For instance, a Lubuntu ISO, or a KDE neon ISO -- those are Ubuntu derivatives that use Calamares. Or a Manjaro ISO, or ArcoLinux -- those are Arch derivatives that use Calamares.

[ArcoLinux](https://www.arcolinux.info/) is especially interesting because it has documentation about how to shape the ISO-building process.

Distro-building, and ISO-building, is outside the scope of the Calamares issue tracker. It **is** on-topic for the IRC channel for Calamares, where there are representatives from a dozen or more Linux distro's. It is not a very active channel, but it makes more sense to talk about ISO-building there, than in the Calamares issue tracker. I myself know next to nothing about ISO-building: that's a downstream (distro) activity.

An advantage of using an existing distro / ISO to work from is that you have a working Calamares configuration to start with. There are many configuration files. All of them have documentation, in the form of comments, in the source repository (this one). It is not always obvious how the modules interact or what order they need to be in: we welcome improvements through pull requests (PRs) for the documentation, always.
