### ISSUE TITLE
BootToRAM new archiso option

### ISSUE THREAD

**Issue by TechXero** [calamares/calamares#1713]
**Is your feature request related to a problem? Please describe.**

Today Arch introduced a new boot option called "copytoram". With that it introduces something I have no idea how to do with Calamares modules...

The _airootfs.sfs_ file when booted with copy to ram is in _/run/archiso/copytoram/airootfs.sys_
The _unpackfs.conf_ specifies a different location since the _airootfs.sys_ is normally at: _/run/archiso/bootmnt/arch/x86_64/_

The trouble is going to be to tell Calamares to use a different unpackfs.conf file depending on whether the user boots with copy to ram or not.

**Describe the solution you'd like**

If a user selects a normal boot, Calamares needs a normal unpackfs.conf. If the user selects boot to ram, it needs a different config file. We need to make Calamares smart enough to know which is which.

**Describe alternatives you've considered**

I have considered shellscripts but still confuses Calamares. At least way I do it.. I am no dev so no idea what am doing...

**Comment by adriaandegroot** [comment]
Labeling as "help wanted" in this case to mean "I'm not going to do this, but I'll write out some various approaches." Overall, "yeah, cool, Arch community gets to pitch in as well".

## Allow unpack to fail

To enable "try unpacking this", extend the configuration for *unpackfs* items with a *required* key, boolean, defaults to `true`. If an entry is **not** marked required, then it's ok for the source to be absent, and the item will be skipped.

- needs change in `unpackfs.schema.yaml` (for documentation / verification purposes)
- needs change in `unpackfs.conf` (documenting and explaining)
- needs change in `unpackfs/main.py` :
  * check if *required* is `false` .. if so, the check that the source exists can be skipped (around line 456)
  * if required is false and the source does not exist, don't add an operation (around line 483)

This approach will need a new Calamares release to roll it out (or local patches in packaging).

## Multiple configuration directories + launcher script

Calamares can use the `-c` flag to point to different configuration directories. Make one for a RAM boot, one for a non-RAM boot, e.g. `/etc/calamares-ram` and `/etc/calamares`. You can use symlinks to share the qml and branding that needs to be in the configuration directory, and leave only the module-configurations.

The launcher script then detects which set of configurations should be used, and passes in the appropriate `-c` flag to Calamares.

## Live-edit configs + launcher script

You can live with just one configuration directory, if you don't mind running `sed` or something like that on the configuration files before starting Calamares. I think EndeavourOS does that -- checks some system state, then modifies the config files, then runs Calamares.

## Symlinks + launcher script

Configure *unpackfs* to use, say, `/tmp/thething.sfs` and symlink that to the real location of the file, then run Calamares. I'm not entirely sure this will work, since it's going to (loopback) mount the source image and that might not be symlink-compatible.

**Comment by adriaandegroot** [comment]
## Allow alternative sources

Change the *source* key for an unpackfs entry to accept a list, as well as a single string. The unpackfs module looks for the first entry in the list that exists, and uses that. If none exist, it is an error.

- needs change in schema, conf and code (like *Allow unpack to fail* approach, but from a different angle)

**Comment by adriaandegroot** [comment]
Closing as "needs to be solved elsewhere".
