### ISSUE TITLE
Hidding encryption if the processor doesn't support it

### ISSUE THREAD

**Issue by es20490446e** [calamares/calamares#1725]
Some processors don't support [AES instructions](https://en.wikipedia.org/wiki/AES_instruction_set), and encrypting the storage renders the system quite slow. The user won't notice that the slowness is because of this.

Calamares could check if the processor supports AES, and if the kernel is compiled with an encryption that isn't intensive, like [ChaCha](https://www.cryptopp.com/wiki/ChaCha20).

If neither of the above is true, it could disable encryption.

**Comment by kkofler** [comment]
I do not think hiding software encryption makes sense. It had been all we had for ages, and with slower CPUs than nowadays. People still used encryption when they wanted or needed it. Any Turing-complete CPU "supports" AES, the instructions just make it faster.

**Comment by adriaandegroot** [comment]
You're talking about the checkbox *encrypt system* on the partitioning page, right? I don't think **disallowing** encryption is a good idea, since it might be an important consideration for a specific user, regardless of the performance considerations. A warning icon or such -- "This system does not seem to support fast encryption, which would be needed for encrypted filesystems. System performance may suffer." -- could be used.

Anyway, this issue won't go anywhere without an example implementation (preferably in C++ that returns a `bool` saying "probably suitable", but a shell script that has exit code 0 would do as well -- that can be translated to C++ easily enough).

**Comment by es20490446e** [comment]
To test the difference I had an Intel Core 2 Quad processor, a brand new SDD as system storage, and a 3GiB folder. I tested deleting the folder while the SDD was encrypted, and while it wasn't encrypted.

While encrypted it took a second, while not encrypted it took over a minute (notice that the file manager goes over each single file for deleting the folder).

Also while encrypted, if I downloaded something from the Internet under a connection of 300Mbs the computer started to become unresponsive. Same if I opened three tabs on Firefox with each one having a different twitch.com stream.

So having encryption in such system won't be suitable under any circumstance. Either the kernel supports a less intensive cypher, or it is a no go road.

I would grey out the option, and mention that "the kernel doesn't support a cypher compatible with your processor".

**Comment by es20490446e** [comment]
Checking if the processor supports AES can be done with:
> grep aes "/proc/cpuinfo"

**Comment by es20490446e** [comment]
The list of supported cyphers is under:
> /lib/modules/[KERNEL]/kernel/crypto

Now, if encryption can use one of those alternative cyphers I don't know.

**Comment by kkofler** [comment]
Deleting a folder with lots of files is not necessarily something one does often, and not all users even have a 300 Mbps Internet connection, there are countries where the Internet connections are still much slower than software encryption (56 kbps and even 33 kbps connections still exist!).

It is not the job of the installer to overrule or forbid what the user wants or needs. Warning that the performance will be junk makes sense, graying out the option outright does not.

And to check CPU flags from C++ code, the right way is really to use the `cpuid` instruction directly instead of scraping `/proc/cpuinfo`.

`cryptsetup benchmark` will tell you what ciphers are available on your system and how they perform in RAM (no disk I/O included).

**Comment by es20490446e** [comment]
That allowing the user to make choices that will render their system barely usable, I don't agree with.

**Comment by kkofler** [comment]
On my system (CPU with AES-NI instructions), I get that AES, Serpent, and Twofish are supported, and AES is clearly the fastest (unsurprisingly, given that it is hardware-accelerated and the others are not).

What is also interesting are the key derivation functions: the legacy PBKDF2 does more than a million iterations per second with the various SHA algorithms (SHA1, SHA-256, SHA-512), and a few hundred thousand iterations per second with RIPE-MD-160 or Whirlpool, whereas Argon2i and Argon2id manage only three (!) iterations per second (6 iterations in 2000ms)!

**Comment by es20490446e** [comment]
**BENCHMARK**

Command:
openssl speed -elapsed -evp aes-128-cbc

Reference block size:
16384 bytes (the highest)

---

**RESULTS**

Intel Core 2 Quad Q6600 (high end 2008):
72641.19k

Intel i5 2410M (mid end 2010) (non EVP):
171524.10k

Intel i5 2410M (mid end 2010):
569409.54k

---

**GRAPH**

![comparison](https://user-images.githubusercontent.com/9594332/122565797-2bbd1700-d047-11eb-9679-d4740391cd76.png)

**Comment by kkofler** [comment]
That is a factor 8 speed difference and does not explain the factor 60+ (a second vs. over a minute) you claim you got for the real-world disk I/O. Are you sure that it is all due to the encryption?

**Comment by es20490446e** [comment]
Probably gvfs does more than just copying the file, and the overhead composes.

**Comment by kkofler** [comment]
It would still scale proportionally if encryption were the only factor.

**Comment by es20490446e** [comment]
Even if you found out the root of the overhead, and you were able to persuade their developers to fix it, storage operations would still be 800% slower.

If you don't see why 800% is unacceptable, I simply conclude you don't listen.

By the way we already know that is also GLib/GVFS, and that GNOME won't fix it. [Here](https://github.com/lxqt/pcmanfm-qt/issues/1375).

**Comment by abucodonosor** [comment]
@es20490446e like @kkofler already told you it is not the job of the installer to disallow you something like this.

> By the way we already know that it's also GLib/GVFS, and that GNOME won't fix it.

LOL!. Surely not because of GNOME... If they refuse to fix that use a different DE or bug them to hell to fix their bugs.

IOW, if you know you use that buggy GNOME on your old machine simply don't enable encryption.

> If you don't see why 800% is unacceptable, I simply conclude you don't listen.

No, your arguments are bogus. Is NOT like we FORCE encryption, YOU enable it.

**Comment by abucodonosor** [comment]
> You're talking about the checkbox _encrypt system_ on the partitioning page, right? I don't think **disallowing** encryption is a good idea, since it might be an important consideration for a specific user, regardless of the performance considerations. A warning icon or such -- "This system does not seem to support fast encryption, which would be needed for encrypted filesystems. System performance may suffer." -- could be used.
> 
> Anyway, this issue won't go anywhere without an example implementation (preferably in C++ that returns a `bool` saying "probably suitable", but a shell script that has exit code 0 would do as well -- that can be translated to C++ easily enough).

@adriaandegroot yes it anything a friendly warning.

One could use such a machine as a secure backup server/archive server or anything else, where performance doesn't matter.

**Comment by es20490446e** [comment]
This is pretty bad design.

**Comment by es20490446e** [comment]
Very poor technical criteria.

**Comment by kkofler** [comment]
Once again: software disk encryption had been a thing long before AES-NI was invented. If installers had refused to support software disk encryption back then, nobody would have used it and AES-NI would probably never have been invented to begin with.

**Comment by es20490446e** [comment]
Then why is this so slow compared with back then? 🤔

Perhaps the nature of the storage, being it SDD?

**Comment by kkofler** [comment]
Well yes, if your storage is fast (SSD), then the overhead from slow software encryption, compression or the like will be much more noticeable than if the slowness of the storage itself (HDD) makes it negligible in comparison.

**Comment by adriaandegroot** [comment]
I've deleted a whole bunch of comments going back-and-forth on things not directly relevant to this issue.

There's a request:
- detect if the system is likely to support encrypted media with acceptable performance
- if not, put a warning there if the user choses encrypted media.

We're not going to disable the checkbox: for each user with a Pinebook that doesn't want encryption because of performance, there's a user with a Pinebook who absolutely needs it for security. That is to say, there is no question of "my use-case trumps your use-case in all situations". People are allowed to shoot themselves in the foot.

The request is going to sit here with the help-wanted label (which always also means "PRs welcome"). An implementation of the first bullet point above might check for the availability of AES in the CPU; I consider it likely that "magic" is the only way to do it right, though.

**Comment by es20490446e** [comment]
What about:
> Your processor doesn't support encryption instructions. Performance will be notably slower.
