### ISSUE TITLE
Getting error while building

### ISSUE THREAD

**Issue by BeyondDevy** [calamares/calamares#1729]
Getting error while building 
```
[ 25%] Linking CXX executable ../../loadmodule
/usr/bin/ld: CMakeFiles/loadmodule.dir/testmain.cpp.o: in function `main':
testmain.cpp:(.text+0x36f2): undefined reference to `Calamares::PythonJob::setInjectedPreScript(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/calamares/CMakeFiles/loadmodule.dir/build.make:111: loadmodule] Error 1
make[1]: *** [CMakeFiles/Makefile2:4378: src/calamares/CMakeFiles/loadmodule.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by demmm** [comment]
What version? Building from release tar or latest git? Care to share settings/modules used? New build issue or first time trying to build Calamares?

**Comment by adriaandegroot** [comment]
It's possible, I suppose, that @BeyondDevy is compiling without Python module support -- then the module loader will return `nullptr` for Python modules, but the test-application is trying to call Python API anyway.

**Comment by BeyondDevy** [comment]
@adriaandegroot well but which module

**Comment by BeyondDevy** [comment]
> What version? Building from release tar or latest git? Care to share settings/modules used? New build issue or first time trying to build Calamares?
 latest git

**Comment by kkofler** [comment]
> @adriaandegroot well but which module

All Python modules. "Python module support" means that Calamares is linked with Python and Boost::Python so that modules written in Python work. This is currently basically required for a working installer anyway, as there are still essential modules that are written in Python. So, even if @adriaandegroot fixes this bug, you will still want to make support for Python modules work in your Calamares build.

You need Python 3 and a Boost::Python compiled against Python 3 (called boost-python3 in some distributions). Python 2 is not supported (never was, because it was already deprecated when Calamares was started). You also need development headers for Python and Boost::Python, as for any other library you want to compile C/C++ code against.

**Comment by BeyondDevy** [comment]
oh thanks, I have Python 3 but I don't have Boost::Python

**Comment by BeyondDevy** [comment]
I'm using Arch Linux and I'm unable to find boost-python3

**Comment by demmm** [comment]
Since the issue is already closed, I will leave my usual comment here.
This is NOT a help channel, Calamares issues are not for teaching you about your distro. Use the Wiki pages written for any would-be distro dev to learn how to implement Calamares.  If you have questions AFTER thoroughly reading the Wiki, use IRC to ask questions.
https://calamares.io/
https://calamares.io/about/
