### ISSUE TITLE
issue with using netinstall module after update to calamares 3.2.40

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1739]
using calamares latest release 3.2.40 netinstall usage is completely broken for EndeavourOS.
Configs in use: https://github.com/endeavouros-team/calamares_config_next/tree/master/calamares
We do use netinstall.yaml setting to `critical true` but it seems it fails the same when set to `critical false`
ISO with that version in use:
https://github.com/endeavouros-team/ISO/releases/download/0-EndeavourOS-development-ISO-releases/endeavouros-broken-cal40-2021.07.25-x86_64.iso
(to start installer use the icons on panel first one for online install, as welcome app is not configured to use latest calamares)
![Bildschirmfoto_2021-07-25_19-59-06](https://user-images.githubusercontent.com/16797647/126908671-19d37cbc-1350-4d4a-b848-727dc5b62e5f.png)

It gives error that it can not resolve host on all mirrors.. and also if i try to run a shellprocess in that state of install with a simple ping commad it fails to get connection to internet/DNS ? it is a very strange issue.. indeed 
here is the install log:

https://clbin.com/gAacT

- network is working fine as installing packages with pacstrap module ( https://github.com/endeavouros-team/Calamares_current/tree/master/src/modules/pacstrap ) is working without issue.

- Same configuration is working fine with calamares 3.2.39. 

![2021-07-25_19-44](https://user-images.githubusercontent.com/16797647/126908563-7d023be2-5d05-48d9-80ad-d6cdbc300535.png)

**Comment by killajoe** [comment]
another finding is that if i select a very little number of package sinside netinstall it does not fail.. i test this with 7 packages.. 
testing if pacmen features causing the issue do not show any evidence, like disable parallel downloads result in the same error.

**Comment by adriaandegroot** [comment]
Booting up that ISO now. Judging from the screenshot you showed elsewhere: are you sure none of the packages are resetting the network configuration in the target system? Because that would (well .. *might*) explain how the mirrors suddenly become unavailable in DNS.

FWIW, I booted the ISO, the live desktop comes up, I can do DNS lookups in the **host** (e.g. live) system and use `curl` to fetch things from the net, but using the *Start the Installer* > *Online* version waits for some time, then pops up a "No Internet!" dialog and the install does not work.

**Comment by adriaandegroot** [comment]
But whatever `settings.conf` is there on the ISO, `pkexec calamares -D6` does the trick with sufficient debug-logging on the terminal. I picked "KDE minimal" and that .. failed as well. But not right away! The first round of package installation goes well, I can see everything being parallel downloaded (very fancy!), and then a second round falls over. In the **target** system I can see that `/etc/resolv.conf` links to a systemd thingy that does not (yet) exist. In the chroot I can't do DNS lookups, because it's misconfigured. I don't know how the configuration is before.

**Comment by killajoe** [comment]
devel ISO needs to start installer from panel buttons.. 
 >>In the target system I can see that /etc/resolv.conf links to a systemd thingy that does not (yet) exist. In the chroot I can't do DNS lookups, because it's misconfigured

So this could be the issue.. strange that it does not have the issue still with 3.2.39 and the same ISO ..

**Comment by killajoe** [comment]
on the archiso `/etc/resolve.conf`is a symlink to `/run/systemd/resolve/stub-resolv.conf` what is dynamicly created:
https://wiki.archlinux.org/title/Systemd-resolved#DNS

**Comment by adriaandegroot** [comment]
At the point that pacman fails (running in the **target**), the symlink is there, but systemd isn't running **in** in the target (yet) and the file pointed-to (`stub-resolv.conf`) doesn't exist. So name lookups done in the target fail.

**Comment by killajoe** [comment]
Using NetworkManager does not need to use the symlink to `/run/systemd/resolve/stub-resolv.conf` as NetworkManager will create a "real" resolv.conf .. seems inside chroot on calamares running the DNS resolution is getting confused now... because we still have the symlink on host but not inside target.
Removing the symlink on host and restarting NetworkManager is solving this issue for me.. in do just build a new ISO to validate, if the symlink was causing the issue.

**Comment by killajoe** [comment]
i just research and we have the symlink since the beginning of EndeavourOS on the ISO.. never causing such issue.. and we do used NetworkManager from beginning too..  and again with calamares 3.2.39 and versions before it never had any issue with DNS resolution.. but good to have it working again and removing the symlink feels good ;) I was fighting with this way to long .. 

Thank you a lot @adriaandegroot !
