### ISSUE TITLE
Support for external callbacks, e.g. for package installing

### ISSUE THREAD

**Issue by manuel-192** [calamares/calamares#1740]
Hello, I'm one of the EndeavourOS devs, working with @killajoe.

**Is your feature request related to a problem? Please describe.**
When installing packages we've had issues when a mirror fails and calamares in conjunction  with pacman seems to fail too. The expected behavior would be to use another mirror and carry on. We are using the "**critical: true**" with package installing.

**Describe the solution you'd like**
We have been thinking that we could use our own script or command to do the installing of packages. That way we would be free to handle potential problems with pacman. Naturally our command would need to co-operate with calamares to achieve this goal.

For this purpose we are thinking about being able to install a _callback_ command (an external replacment routine for installing packages) into calamares. Then calamares would, instead of using its current methods of installing packages, call this installed callback with the package list as a parameter. The command would be a normal, plain linux command, written in any programming language.
If calamares wants any feedback from the callback command, it could return a status code, e.g. 0=success or 1=failure (and more if needed).

The callback command name or path could be given to calamares via e.g. some config file.

In general, callback support also for other features than installing packages might be quite useful, but for now I'm interested in having a callback for installing packages.

**Describe alternatives you've considered**
I'm not very familiar with calamares itself, so maybe support for this kind of feature already exists?

**Comment by kkofler** [comment]
IMHO, the proper fix would really be to fix `pacman` to fall back in a more robust way instead of requiring a wrapper like the one you propose, or failing that, to add your wrapper as an alternative package manager to the `packages` module.

**Comment by manuel-192** [comment]
Thanks for your comment!
While I agree that a package management fix in calamares would solve the problem, I assume implementing the fix takes much more time than implementing a callback feature.
In addition, the callback techniques could be used for *extensions* in other areas as well, like I mentioned in my first post.

**Comment by adriaandegroot** [comment]
Part of the problem is that the handling of "do these packages" is not under the control of the package manager. It is the driver logic that decides what or how to call into the low-level package-management functions. I have a branch to move that around, so that the PM can decide itself how to handle critical or non-critical packages (with default implementation as it is now: non-criticals are installed one at a time, with failures ignored).

**Comment by manuel-192** [comment]
Thanks!
As I don't know the inner structure of calamares, I don't know what the "driver logic" actually is.

I can understand that calamares has a high level structure for operations like installing packages. And it seems that there are many lower level package manager implementations that calamares eventually can run, depending on the configuration.
What I don't know is why calamares seems to stop installing if one pacman mirror is not responding. Normally pacman would simply use the next mirror (after waiting max 10 seconds) and continue. What causes calamares to stop installing?

I don't have a debugging environment that I could use to find the actual reason. But I assume calamares devs have such an environment.

**Comment by kkofler** [comment]
I think fixing the specific issue here (in the specific `packages` module) is actually much much easier than adding a general callback feature that would basically have to be implemented in every single module in Calamares. And you want to not only add a callback, but also disable the command that the `packages` module would normally run.

**Comment by adriaandegroot** [comment]
I realise I have closed the wrong issue, because focusing on "callbacks".

I'm still going to leave it closed: if you want to do some kind of "try this, then that" for installing packages, there are enough hooks in the *packages* module to do it right now:
- the `operation_*()` methods in base class `PackageManager` can be reimplemented to use other logic when handing off groups of packages to the package manager
- the usual implementation functions `install()`, `remove()`, ... can also be reimplemented

If you need to fall back in some way, then handle error codes from the package manager in one of those functions and implement your own try-again mechanism.

The commits that closed this **do** have a purpose around package management, because it's now much easier to read output from the package manager during installation -- for e.g. progress reporting, or to detect specific errors.
