### ISSUE TITLE
usr/local/bin/slowloris no such a file or directory

### ISSUE THREAD

**Issue by kazi-sifat-plus9a** [calamares/calamares#1742]
Sorry for annoying
My own Arch calamare iso was installing at the last time it gave me this message

Installation Failed
External command finished with errors
command usr/local/bin/slowloris finished with error code 172
Output bin/sh : line one : usr/local/bin/slowloris no such a file or directory
I downloaded github.com/calamares/calamares/realise that zip file version :- 3.2.35 and i removed a line to fix that problem
.src/modules/shellprocess/shellprocess.conf

-command "usr/local/bin/slowloris"
Now how can i make this directory to .tar.zst 😞
Can you please give me you repo link to fix it Thanks for reading

**Comment by erikdubois** [comment]
I believe that is just an example name. It does not exist.
You are supposed to change it to something you would want.

**Comment by kazi-sifat-plus9a** [comment]
How to make tar.zst from cmake ,can you show me a path

**Comment by adriaandegroot** [comment]
For slowloris specifically:

- The Calamares repository contains a the Calamares source code, modules source code for 50-or-so modules, and **example** configuration files for those modules. Those example configuration files are, e.g. `shellprocess.conf` in the repository. There is also an example `settings.conf` for the overall Calamares configuration.
- The examples are supposed to be sort-of-useful, but also explain all the options that are available. There is a CMake-time option `INSTALL_CONFIG` which defaults to off: in **general** there is no point in installing the example configs, since you should have configuration files suitable for **your** distro.
- The shellprocess example, in particular, is totally bogus. Unless you **really** want to create `/tmp/thingy` and run slowloris in the target system during install, it is not something you want to do.

Changing configuration files doesn't require a rebuild: in any case you should probably be building with INSTALL_CONFIG turned off, and creating / installing the configuration files from a separate repository.

Anyway, none of that is answering the question you were actually asking in the original issue.

**Comment by adriaandegroot** [comment]
Issues are not a support channel. For support, join the IRC channel (you need to hang around) or the Matrix channel (persistent).

**Comment by adriaandegroot** [comment]
What is a tar.zst, why would you want one, and why do you think that cmake or make should be able to create one? What's it for?

As a not-particularly-helpful kind of answer: to create a tar.zst file, use the `tar(1)` command, like so: `tar czaf cala.zst CHANGES` . This creates a file `cala.zst` which contains, in the archive, the single file `CHANGES`. May require BSD tar. I suspect you mean something else with tar.zst, though.

**Comment by kazi-sifat-plus9a** [comment]
Thanks a lot for your long answer ..but What actually i should do to fill something on usr/local/bin/slowloris

**Comment by kazi-sifat-plus9a** [comment]
https://www.dropbox.com/s/k23r83qsmcy8lwv/img_20210730_080319.jpg?dl=0

**Comment by kazi-sifat-plus9a** [comment]
https://www.dropbox.com/s/wv9o45hyl1jf3pl/IMG_20210730_003814.jpg?dl=0

**Comment by abucodonosor** [comment]
> Thanks a lot for your long answer ..but What actually i should do to fill something on usr/local/bin/slowloris
> 
> slowloris is a hacking tools ? Why my distro needed it.

Nothing.
Again, those are *example* configuration files.

What you should do is writing configuration files for your distribution.

**Comment by kazi-sifat-plus9a** [comment]
I3 window manager..

**Comment by abucodonosor** [comment]
> I3 window manager.. installation faileding bcz, its searching something on their. What if i try to make fool (echo "skip")
> Does is will solve it.

Please read docs and write configuration files, if you have questions left join the IRC/Matrix channel and ask.

This is no a bug, closing.

**Comment by adriaandegroot** [comment]
So, to repeat one more time: *shellprocess* is a module, to run shell commands, during install. Which shell commands? I don't know, whatever makes sense for **your distro**. It could be anything, but the only person who knows is you, the distro-creator. The example file for *shellprocess* contains things that do **not** make sense, anywhere, any time. Change the configuration file `shellprocess.conf` if you need to run different commands. Or better yet, if you do not need to run shell commands during installation, don't list *shellprocess* in the `exec` phase of `settings.conf` at all.

**Comment by killajoe** [comment]
> building with INSTALL_CONFIG turned off,

off the topic.. but this will then not install the sample configs under /usr/share/calamares ?

**Comment by kazi-sifat-plus9a** [comment]
Yes solved ,sorry + thanks a lot .. I become very fastrated .. i am working for it about 4-5 days
