### ISSUE TITLE
Deepin Desktop Bug (I Think its A Bug)

### ISSUE THREAD

**Issue by carbon-ui** [calamares/calamares#1756]
> Hi i am a manintainer of carbonui a new arch based distro
**Describe the bug**
BIOS - Virtualbox x86_64
This is a deepin only error on other desktops this error is not seen

**Expected behavior**
the installation must go on but it stops

**Screenshots and Logs**
[session.log](https://github.com/calamares/calamares/files/7012906/session.log)

**Additional context**
this only happens in deepin desktop

i can give you the pkgbuild
https://raw.githubusercontent.com/carbon-ui/PKGBUILD/master/calamares/PKGBUILD
this has to do nothing with desktop but i think its a calamares bug

and this version of calamares also has this bug which is seen in all desktops
the update-db=true if we put then it says package manager could not prepare updates
in the previous versions this bug was not seen
ISO
https://sourceforge.net/projects/carbonui/files/Testing/

**Comment by demmm** [comment]
Which versions of kpmcore is in use?

**Comment by carbon-ui** [comment]
We Are Using 21.08 Version of kpmcore

**Comment by adriaandegroot** [comment]
From the log, relevant parts are:

```
2021-08-19 - 13:45:03 [6]: virtual void Calamares::JobThread::run()
    Starting job "Create new 46841MiB partition on /dev/sda (VBOX HARDDISK) with file system ext4." ( 5 / 37 ) 
2021-08-19 - 13:45:06 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    ERROR: Installation failed: "The installer failed to create partition on disk 'VBOX HARDDISK'." 
2021-08-19 - 13:45:06 [6]:     ..  - message: "The installer failed to create partition on disk 'VBOX HARDDISK'." 
2021-08-19 - 13:45:06 [6]:     ..  - details: ==========================================================================================
Create a new partition (45.74 GiB, ext4) on ‘/dev/sda’
```

I can't tell from the kpmcore output **which** command, or sub-step, actually failed. It **might** be the "set label" step -- try filling in something for the root filesystem label. But you say this only happens with deepin (not when the live ISO uses a different DE?) .. this **may** be that deepin is being very agressive about auto-mounting new partitions when they appear. Then subsequent changes to the partitioning fail. If that is the case, we need to know how to tell deepin to not automount for a while.

**Comment by carbon-ui** [comment]
ok sir i did as you told
first i set the filesystem label to it as disk
and then i unmounted it via gparted
and then i started calamares
so first time it crashed (segmentation fault)
i restarted it in debugging mode but the same issue

**Comment by carbon-ui** [comment]
sir so here something wierd happened
i did sudo -E calamares -d
it is not able to create a partition
but it can format its partition and install on it
when i did manuel partitioning formated the ext4 drive
it worked
it instlled
but when coming to installer it is unable to create a partition

**Comment by carbon-ui** [comment]
@adriaandegroot
please see to it that it gets solved (please)

**Comment by adriaandegroot** [comment]
You're right that this is a (Deepin) bug. It automounts disks when they are created. So Calamares creates a partition table, creates a partition, makes a filesystem -- **bam** that filesystem gets mounted --, checks the filesystem -- **bam** that fails, because it's mounted. Who instructed  the filesystem to be mounted?

KDE Plasma has a known DBus interface for turning off (or on) automount. Tell me how to turn off automount (programmatically) in Deeping and we can implement that.

**Comment by adriaandegroot** [comment]
Here is a workaround:

- open file manager
- go to *settings* (hamburger menu)
- under *advanced*, pick the *mount* page
- uncheck *automount*

Now close the file manager and do the installation. TODO: do that programmatically.

**Comment by carbon-ui** [comment]
@adriaandegroot WIll Close This Issue Now TQ Sir

**Comment by adriaandegroot** [comment]
For reference, some other possible workarounds:
- put a no-automount configuration file into the live-user directory (I think this is what Manjaro did, some time ago)
- add a password (?) so that automounting isn't automatic

The best thing to do would be do have a way to turn off the automounting programmatically (perhaps writing the config file, then restarting the file-manager -- that's a last restort) but it will need someone who cares about Deepin to sort that out.
