### ISSUE TITLE
Configurable SDDM config file

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1757]
Calamares 3.2.41.1
ArcoLinux v21.09.10
Plasma and our 21 other desktops.

When Plasma saves its sddm theme, autologin user and autologin session it creates two files
/etc/sddm.d.conf and /etc/sddm.conf.

Could we add a variabele so we can choose either /etc/sddm.conf or /etc/sddm.conf.d/kde_settings.conf?
Calamares uses it to set the autologin.
https://github.com/calamares/calamares/blob/bf677df6ca67e6119c16c0b7a0e577002ab614ad/src/modules/displaymanager/main.py#L794

![sddm-variable](https://user-images.githubusercontent.com/36679406/130118823-09827691-00da-439d-8017-a5b798fc74fd.jpg)

For now I completely overwrite the file with my own settings.

**Comment by adriaandegroot** [comment]
> Writing this up as a Hacktoberfest issue

Calamares Python modules are relatively easy to test as part of a whole install:
- get an ISO (e.g. ArcoLinux) that uses the Python module
- modify the Python code in-place on the ISO
- do the install and do **not** reboot afterwards
- mount the target system and check if things worked out OK
- if so, copy the modified Python somewhere "safe" outside of the live system
- submit modifications.

## Procedural

- [ ] ensure you can do an installation with Calamares, from a live ISO (see above)
- [ ] if you want to do Hacktoberfest, ensure you're registered there
- [ ] say "I'm on this" in the comments of this issue; that's not so much to "claim" the issue, as to try to avoid duplicate work
- [ ] do the technical bits (see below)
- [ ] make a PR. Keep the [Contribution Guide](/CONTRIBUTING.md) in mind! In particular:
  - do use `[displaymanager] description-of-commit` as commit messages
  - do use multiple commits; it's fine to have each technical step as a separate commit if you like
  - don't litter the commit sequence with `revert` kinds of commits
  - do rebase before submitting the PR, to fix up spelling in commit messages, to fixup reverts, and squash multiples that together form one logical commit
  - do add yourself to the contributors list in the CHANGES file

## Technical

- [ ] add an entry into the `displaymanager.conf` file where you will put the configuration value. Since there might be custom configurations per-DM, and some might have multiple customizations, I'd suggest something like
     ```
     sddm:
         configurationFile: /etc/sddm.conf
     ```
     This groups all the sddm settings into one spot, and allows space for more customizations if needed. Remember to include suitable documentation!
- [ ] add an entry to the YAML schema, in `displaymanager.schema.yaml`. Following the suggestion above, key *sddm* should be optional and *configurationFile* optional as well. If you pick a different naming scheme, do something sensible. Test the example configuration file against the modified schema by running `ci/configvalidator.py`.
- [ ] update the code in the `main.py` file in the module. Modify the `set_autologin()` method of the `DMsddm` class to look for configuration values. The complete job configuration is available as a Python dictionary `libcalamares.job.configuration`. See the `run()` function in the module for an example of reading the job configuration. Check for the existence of keys and read them (or don't check and rely on exception-handling to set default values, either style of Python code is acceptable). Don't forget to fall back on a sensible value as default (`/etc/sddm.conf`) if nothing is set!
- [ ] use the value (default or from configuration) in that one line of code that sets the path variable (the path refers to a location inside the mounted target-system).
- [ ] do at least one installation with the default configuration `displaymanager.conf` from the distro you are using, and one with a modified `displaymanager.conf`. If you're on ArcoLinux you may have to fight the patches that the distro already applies.

> Have fun!

**Comment by arcolinuxz** [comment]
I see @demmm cleaning up issues. You can close this one too.
I just change the python code via pkgbuild.
Lets keep the important ones alive.

**Comment by demmm** [comment]
Let's not re-open feature requests that clearly no-one has an interest in implementing, OP already has a solution/work-around. If re-opened because of some vague `not resolved yet` from another report, first make sure what issue they actually imply.

**Comment by eeickmeyer** [comment]
@demmm I discussed this directly with @adriaandegroot (literally standing next to him) and he agreed this is a valid concern. In the Ubuntu and Debian land, we don't have the luxury of manipulating the python code via pkgbuild that arcolinux does, so their workaround does not apply to us.

If you read https://bugs.launchpad.net/ubuntu/+source/calamares-settings-ubuntu/+bug/1984136, this needs to be configured as, at least in our distribution, the sddm configuration is done differently. Therefore, this is perfectly valid.
