### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [calamares/calamares#1758]
Would you like to [wrap any pointer data members](https://github.com/calamares/calamares/blob/db51e813fbf0f0d286aaa429df157deb7834462e/src/libcalamaresui/viewpages/Slideshow.cpp#L201 "Update candidate: SlideshowPictures class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by adriaandegroot** [comment]
This seems less like an issue and more like a "are you interested in receiving PRs that do this?" There's a fair bit of `std::unique_ptr` use already, but more -- where relevant -- is welcome. Keep in mind, though, that QObject ownership semantics play a role as well: in the slideshow, the two `delete` statements are superfluous because QObject would take care of that through the parent-child mechanism.

Anyway: yes, PRs are welcome (take a look at `CONTRIBUTING.md`, try to keep each commit self-contained with a useful commit message, PR early and PR often).

**Comment by adriaandegroot** [comment]
I'm going to close this one, not because it's "fixed", but because it's an overall code-quality thing that can be PR'ed as time goes on. New code ought to use `unique_ptr` (or Qt's ownership mechanism), but there's nothing directly "to fix".
