### ISSUE TITLE
Using a Btrfs root partition breaks systemd-boot

### ISSUE THREAD

**Issue by chloecormier** [calamares/calamares#1773]
**Describe the bug**
If Calamares uses Btrfs as the root filesystem and systemd-boot as the bootloader, the installation finishes with no apparent errors but the installed system fails to boot, due to being unable to mount the root filesystem. This, of course, only applies to EFI installations. This was tested with Calamares 3.2.41.1.

**To Reproduce**
1. Set defaultFileSystemType in partition.conf to "btrfs"
2. Set efiBootloader in bootloader.conf to "systemd-boot"
3. Go through the installer as normal, using automatic partitioning.
4. Attempt to boot the installed system.

**Expected behavior**
When systemd-boot is in use, it should detect whether the root filesystem is Btrfs, and if so, add an appropriate kernel option (e.g., "rootflags=subvol=@") to the options list inside the boot entry configuration file.

**Additional context**
Deepest apologies if this issue is invalid, or if there's something I've missed. I'm still very new to configuring Calamares.

**Comment by demmm** [comment]
These 2 lines need to be added (79 & 80):
https://github.com/KaOSx/calamares/blob/master/src/modules/bootldr/main.py#L79
That has been tested for years for systemd-boot & BTRFS.

**Comment by adriaandegroot** [comment]
Hi @chloecormier , thanks for the report. As @demmm points out, this is solveable, **but** KaOS uses a different module (*bootldr*) which isn't the same as the upstream module (*bootloader*). That makes applying the changes from KaOS .. straightforward, since @demmm describes them well (and explained on Matrix to me as well).

There's a branch, *issue-1773* with a single commit in it right now; you might try applying that one commit to your copy of Calamares to see if it helps.

**Comment by chloecormier** [comment]
Thanks for the rapid response! I've tested that commit and can confirm it works great now.

**Comment by kkofler** [comment]
I really wish KaOS would finally switch to the unified upstream `bootloader` module (merger of `bootloader` and `grub`, because all the BIOS GRUB support was copied&pasted between the 2 modules) that @philmmanjaro and I have worked on a few years ago and that has been part of upstream Calamares ever since instead of sticking to the forked old version without GRUB-EFI support that KaOS has renamed to `bootldr`. I have never seen any report of a concrete issue that prevents the switch, and I am sure that if there is such an issue, it can be fixed pretty easily, just like this bug. It is just a waste of everyone's time to keep having to merge fixes (such as the 2 lines quotes in this bug) from one module to the other, and I see no benefit whatsoever in keeping the downstream `bootldr` around.
