### ISSUE TITLE
Auto-Partitioner Bug

### ISSUE THREAD

**Issue by LJB018** [calamares/calamares#1780]
**Describe the bug**

Calamares does not create EFI boot partition during (in my case) ArcoLinux installation.

-----------------------------------------------------------------------------------------------------------------------------------------

My system specifications:

CPU: AMD Ryzen 5 3600

GPU: NVIDIA GeForce 1050 Ti

Memory: 16 GB 3200 MHz

Storage Device (The device Calamares attempted to partition) : Kingston SSDNow A400 120GB

Firmware: UEFI

-----------------------------------------------------------------------------------------------------------------------------------------

**To Reproduce**
1. Select "Erase Disk".
2. Wait for Calamaries to install ArcoLinux.
3. Reboot.
4. System does not boot because Calamaries did not create EFI Boot Partition.

-----------------------------------------------------------------------------------------------------------------------------------------

**Expected behavior**
Calamaries should create EFI Partition during installation.

**Comment by erikdubois** [comment]
Is it possible to provide the log file Calamares produces?

**Comment by carbon-ui** [comment]
@LJB018 provide us some more info such as log file and arcolinux version and iso version

**Comment by LJB018** [comment]
@carbon-ui @erikdubois

The ISO file is "arcolinuxl-v21.09.8-x86_64.iso".

I didn't read or save the log file during the installation, however I could try again in a Virtual Machine to see if this happens again then I will give the log file.

**Comment by demmm** [comment]
Please follow the instructions added for you to help with posting useful bug reports:
https://calamares.io/issues/
And for end users, make sure to follow:
https://calamares.io/issues/#end-users

Might be best to start with opening a report with your distribution, and work with them (since they know their setup of Calamares best) to decide if this is a bug, distro specific setting or user error.
Closing issue now, since nothing can be done with it at this time, feel free to re-open if after working with your distro it is decided to be a general Calamares issue.
