### ISSUE TITLE
Installer doesn't detect disk on Alpine

### ISSUE THREAD

**Issue by computermouth** [calamares/calamares#1804]
64-bit Gnome Boxes VM
BIOS mode

I've followed Alpine's instructions to get a desktop environment set up. Part of this includes switching from mdev to udev, and that all seems to be working fine.

I'm able to:
1. see the device in fdisk
2. see the device in udevadm
3. see the device, create a partition table and partition, in gparted
4. manually mount the device, write files to it, etc.

I get the following output from the UI and from the debug mode output in the terminal
```
There are no partitions to install on.
  [X] has at least one disk device available

Requirements not satisfied:
  0 "partitions" set? false req? true
  1 "storage" set? true req? false

void PartitionCoreModule::doInit()
  LIST OF DEVICES:
  node  capacity  name  prettyName
  ..  0 devices detected.
```

I'm using a very bare-minimum settings.conf, mostly copied from debian's, with most modules removed to just get to installation for a proof of concept.

I know this can very easily devolve into a "what's wrong with my alpine rootfs", but I figured I'd just ask in case someone had a suggestion on how I could get more verbose output, or get some details on how the drives are detected.

Also, saw another similar issue here: https://github.com/calamares/calamares/issues/1105
Which seems to have never arrived at a conclusion.

EDIT: I've also tried installing via the Debian live image in the same VM, so I can at least rule out an issue with the VM or qemu.

Thanks,
  -- Ben

**Comment by MohammadHisham** [comment]
@computermouth hey
sorry for late reply
use Virtualbox
if possible
send the log file

**Comment by adriaandegroot** [comment]
This needs a closer reading of the log file. Please run Calamares with the `-D6` flags to make sure you get a full log, and then take a closer look around the *Requirements not satisfied* part of the log. The referenced issue ended up with "oh, Calamares thinks your HDDs are CD-ROMS, because some tool says they are .. figure that out first." Something similar needs to happen here: **why** is the disk not considered suitable?

As for running Calamares with `-D6`, if you are starting it from the command-line, just use `calamares -D6` -- and if you need pkexec or sudo, prepend those; if you are launching it in a desktop environment, edit the *.desktop* file, find the *Exec* line and add `-D6` to the end of the command there.

**Comment by computermouth** [comment]
`calamares -D6`

Ah excellent! This looks like just what I was looking for, thanks so much. Will report back soon

**Comment by computermouth** [comment]
I believe this is about all that's relevant here:

```
03:54:18 [6]: QList<Device*> PartUtils::getDevices(PartUtils::DeviceType)
    Removing unsuitable devices: 0 candidates. 
03:54:18 [6]: void PartitionCoreModule::doInit()
    LIST OF DETECTED DEVICES: 
03:54:18 [6]: void PartitionCoreModule::doInit()
    node	capacity	name	prettyName 
    ..  0 devices detected. 
03:54:18 [6]: OsproberEntryList PartUtils::runOsprober(DeviceModel*)
    os-prober gave no output. 
    ..  Loading "/usr/share/calamares/branding/default/show.qml" 
03:54:18 [6]: void CalamaresApplication::initViewSteps()
    STARTUP: loadModules for all modules done 
03:54:18 [6]: void Calamares::ModuleManager::checkRequirements()
    Checking module requirements .. 
03:54:18 [6]: void CalamaresApplication::initViewSteps()
    STARTUP: Window now visible and ProgressTreeView populated 
    ..  8 view steps loaded. 
03:54:18 [6]: void Calamares::RequirementsChecker::addCheckedRequirements(Calamares::Module*)
    Got 1 requirement results from "partition" 
03:54:18 [6]: Calamares::RequirementsList GeneralRequirements::checkRequirements()
    GeneralRequirements output: 
     storage :   5905580032 
     enoughStorage :   true 
     RAM :   1073741824 
     enoughRam :   true 
     hasPower :   true 
     hasInternet :   true 
     isRoot :   true 
03:54:18 [6]: void Calamares::RequirementsChecker::addCheckedRequirements(Calamares::Module*)
    Got 6 requirement results from "welcome" 
03:54:18 [6]: void Calamares::RequirementsChecker::finished()
    All requirements have been checked. 
03:54:18 [6]: void Calamares::RequirementsModel::describe() const
    Requirements model has 7 items 
    ..  requirement 0 "partitions" satisfied? false mandatory? true 
    ..  requirement 1 "storage" satisfied? true mandatory? false 
    ..  requirement 2 "ram" satisfied? true mandatory? true 
    ..  requirement 3 "power" satisfied? true mandatory? false 
    ..  requirement 4 "internet" satisfied? true mandatory? false 
    ..  requirement 5 "root" satisfied? true mandatory? false 
    ..  requirement 6 "screen" satisfied? true mandatory? false 
03:54:18 [6]: void CheckerContainer::requirementsComplete(bool)
    Requirements not satisfied 7 entries: 
    ..  0 "partitions" set? false req? true 
    ..  1 "storage" set? true req? false 
    ..  2 "ram" set? true req? true 
    ..  3 "power" set? true req? false 
    ..  4 "internet" set? true req? false 
    ..  5 "root" set? true req? false 
    ..  6 "screen" set? true req? false 
```

But here's the full log: https://pastebin.com/dnLVuvgK

**Comment by adriaandegroot** [comment]
Yes, that's about it. So we have the situation
- there **is** a disk (at least one), but KPMCore can't find it
- so we have an empty list of disks to work with

What do **you** think the name of the disk is? How do you call, say, fdisk? Are you running Calamares through `pkexec` or `sudo`? (That I can answer: yes, Calamares is running as root, which you can see from the `5 "root"` line in the requirements checker)

I think this is one for @stikonas , but in the meantime: @computermouth you've mentioned a bunch of tools that **do** work, but have you tried KDE Partition Manager? Since KPMCore is the library underlying that application, and Calamares uses the same library, it might be useful to see if the application **can** find the disk. And if installing the application pulls in any dependencies in the live session, then try Calamares again -- it might be a packaging issue.

**Comment by stikonas** [comment]
KPMcore runs the following command to scan for disks:
```
lsblk --nodeps --paths --sort name --json --output type,name
```
It's worth trying to run it manually and see what it reports.

**Comment by computermouth** [comment]
Output for the above questions here: https://pastebin.com/BH8bMbbH

I fell down a couple rabbit holes here with the output from these programs, but ultimately, it seems that installing lsblk was actually what solved the detection!

So it seems this issue is resolved, it is indeed a dependency problem with alpine's package. I'm onto another issue here: http://termbin.com/g1bs but I'll do some more testing and create a new issue if necessary.

Upstream change here: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/27085

**Comment by adriaandegroot** [comment]
.. regarding the issue you hit after that, unfortunately there's no useful output telling **why** `mkfs` failed there. You might want to jump to a later Calamares release; the one we just did last week has a number of partitioning-related improvements.
