### ISSUE TITLE
Allow changing filesystem type in the guided partitioning step

### ISSUE THREAD

**Issue by shmerl** [calamares/calamares#1819]
I tried using Calamares with from the Debian recent live image and was struggling to set up partitions the way I need it. Options were complete manual setup or guided one without ability to tweak it in any way.

What I needed is EFI setup with root set to XFS. There was no easy way to do it. I.e. guided one picked ext4 and didn't give any way to change FS type. It would be nice to provide an ability to tweak at least FS type without changing the rest of the settings. Which wouldn't require going into full manual step.

On a side note, for some reason XFS was even completely missing in the fileystems list in the manual option. But may be that requires opening a separate bug? Or it could be Debian live image just missing some XFS packages.

**Comment by adriaandegroot** [comment]
There isn't a "guided" approach. Do you mean one of *erase disk*, *replace* or *alongside*?

- Erase has a default; a distro can **choose** to offer a drop-down of available filesystems, otherwise there is a specific one configured (which in turn defaults to ext4). Relevant configuration options are *defaultFileSystemType* and *availableFileSystemTypes*.
- Replace preserves the fillesystem it is replacing.
- Alongside uses *defaultFileSystemType*. I suppose a drop-down here might be in order, if the distro configures it to have more than one option.

Debian is special -- at least the 11.0 Live ISO I have here -- in that it doesn't provide a configuration file for the partitioning module at all. So you get the defaultest of defaults. It also uses Calamares 3.2.36, which dates from before the addition of the filesystem-dropdown. And it ships without the XFS tools; `sudo apt install xfsprogs` makes XFS accessible from manual partitioning.

So except for "alongside should allow FS choice if that is configured", this comes down to distro-choices and -configuration.

**Comment by shmerl** [comment]
I mean Erase one, yes.

I figured I need to install xfsprogs, yeah (no idea why it's not included by default, I filed a bug for Debian for that). I mostly figured out how to do it all in manual sure.

**Comment by demmm** [comment]
>I can file another bug to improve the config.

As pointed out in the first reply, this is implemented in current Calamares, you will have to go to your distro and ask them to use current AND set the option to select a filesystem in guided, not something Calamares forces on any distro (Calamares gives options, up to the distro to decide which options to present to the user).

So, seems this issue can be closed, since it is an issue/question for Debian.

**Comment by shmerl** [comment]
Yes, I meant I can file a bug for Debian for improving provided configs.
