### ISSUE TITLE
using grub creates the same grub-id if install the same OS alongside on the same partition (UEFI dualboot)

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1820]
Just got a use case where we test installing EndeavourOS using the alongside option on partition slide:
1. install EOS on UEFI system using automatic partition using grub a s bootloader
2. install EOS using alongside option in partition slide
3. reboot
Grub shows only the second installed system and seems to have overwritten the boot entry from first installed system because we use the same grub-id on grub-install command. dir-name is the same as it uses grub-id naming inside /boot/efi (ESP)

I can fix it by chrooting into the first installed system and reinstall grub files using a different grub-id, which will generate an entry for both installed EOS systems. 

using current calamares 3.2.45 and latest EOS calamares configs:
https://github.com/endeavouros-team/EndeavourOS-calamares

**Comment by demmm** [comment]
From the link I don't see that the option to set bootloaderID is used:
https://github.com/calamares/calamares/blob/calamares/src/modules/bootloader/bootloader.conf#L38
If you just set a name without any versioning/ID, not celar how this could be a Calmares bug:
https://github.com/endeavouros-team/EndeavourOS-calamares/blob/main/calamares/modules/bootloader.conf#L14

The option is available right now in Calamares to set versioned name/ID, seems that is what you are looking for, so each ISO will have a unique GRUB ID.

**Comment by killajoe** [comment]
i see we use `bootloaderEntryName:` instead of  `efiBootloaderId:` so it will use the `bootloaderEntryName` from branding.desc  but i do not see any option describing that we can use versioning there.

So could you hint me on:
_**The option is available right now in Calamares to set versioned name/ID**_

**Comment by killajoe** [comment]
![grub-efi-fix-path](https://user-images.githubusercontent.com/16797647/141687569-18475b53-cbab-4080-9d6c-7939b26aabca.png)
we solved that by adding randomized postfix to the pathname:
`   # change bootloaderEntryName in bootloader.conf:
    sed -i $cfolder/modules/bootloader.conf \
        -e "s|^bootloaderEntryName:.*|bootloaderEntryName: \"endeavouros-$(shuf -i 1000-9999 -n1)\"|" `

**Comment by apt-ghetto** [comment]
What is the use case to have the same binaries more then once on the ESP?

If Grub doesn't show the other system, then the used grub.cfg is wrong.

**Comment by killajoe** [comment]
> What is the use case to have the same binaries more then once on the ESP?

Also the images will be mostly the same on fresh install you may want to change the configuration or include different modules related to the usecase of the different install instances, but indeed it is also an issue with grub, but aside from that.
On testing it looks also like os-prober is having an issue with BTRF and subvol setups. 
As if you install BTFS with subvol first and try to install second alongside OS the first installation will not get detected at all.

**Comment by apt-ghetto** [comment]
Speaking from the Ubuntu point of view (I assume, it is the same for Fedora): It is the expected behaviour, that all Ubuntu flavours use the same bootloader location. If you install Kubuntu 21.10 and Lubuntu 21.10, there will be exactly one bootloader (well, two: `shim` and `grub`). The second system will overwrite the identical binaries from the first system and will point to the grub.cfg of the second system.
Best practice is to remove the bootloader packages from the secondary system, so that you have a main system, which "controls" the bootloader on the ESP.

Arch Linux does not really have an installer, so it is expected, that the user is able to install Grub. And if I remember correctly, `pacman` does not have a hook to install the bootloader in case a newer Grub is available via the repos. So the Arch Linux user needs to install the bootloader again manually.
It is possible to install the bootloader with different bootloader identifiers. But the user has to remember the "correct" bootloader identifier for the current system, otherwise the bootloader will be installed on a new location or is overwriting the "wrong" bootloader. In the worst case, the bootloader on the ESP location \EFI\...\grubx64.efi will never see a newer version and might be vulnerable.
I have no idea, how this is handled by Endeavour OS.


And regarding the BtrFs setup: I think, that os-prober takes only the default subvolume into account and is not looking for further subvolumes. If the second installation changes the default subvolume, then it will consider only the second system.

**Comment by kkofler** [comment]
> Speaking from the Ubuntu point of view (I assume, it is the same for Fedora): It is the expected behaviour, that all Ubuntu flavours use the same bootloader location.

Yes, but on Fedora, it is actually even stricter: EFI installation will only work at all if you use `/boot/efi/EFI/fedora` as is, because files are installed directly to that location by the `grub2-efi-x64` package, `grub2-install` is not used. This is also why, a few years ago, I introduced the `bootloaderEntryName` setting in `bootloader.cfg`, which can differ from the short name of the distro: that way, Fedora Remix distributions can use a different short name in other places, but still have the required `bootloaderEntryName: fedora`. So anything messing with `bootloaderEntryName` by adding any kind of unique suffix will completely break bootloader installation on Fedora.
