### ISSUE TITLE
Documentation for global variables in contextualprocess?

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1853]
Hi there, I'm trying to figure out a way to run some commands on the target system with `contextualprocess` based on what the target root filesystem is (specifically, if it's Btrfs). But I can't find any documentation for what the global variable names are and what their possible values could be. I tried this, but no luck:

```
filesystem_use:
    btrfs:
        -   "-touch /btrfs-used.txt"
```

Or would it have to be `"-touch @@ROOT@@btrfs-used.txt"` ?

And as a general feature request, could documentation be created for this? Thanks a lot!

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/EndeavourOS-calamares/blob/main/calamares/modules/contextualprocess.conf
Is what we use IDs coming from packagechooser module here:
https://github.com/endeavouros-team/EndeavourOS-calamares/blob/main/calamares/modules/packagechooser.conf
but global known IDs should work i think.
And `@@ROOT@@` would be needed if you run _dontChroot true_  only.

**Comment by killajoe** [comment]
> documentation for what the global variable names are

i do not know that or simply currently forget if there was such..

**Comment by geckolinux** [comment]
Thanks @killajoe ! I ended up with this, which seems to work:

```
btrfsSubvolumes:
    "*":
        -   "-touch /this-is-btrfs-root"
```

It doesn't technically make sure that the actual rootfs is Btrfs, for example somebody could use the manual partitioner to create an XFS `/` with `Btrfs` for `/home` , but that wouldn't be a subvolume so it would still be a valid test... I think?

**Comment by adriaandegroot** [comment]
There are two separate questions here:
- how to tell if the root FS is btrfs
- which global storage keys exist

I'll semi-answer the second one first.

### Global Storage keys

The GS keys that are used depend entirely on the modules used in the system. There is no special coordination or central registry of which keys there are. Modules that need to share information need to have an agreement -- at source-code level -- on which keys they use. There are core "services" in Calamares where there is a C++ API for manipulating some GS keys. Both packages and partitions have a "service". That's because the structure of the GS data for those keys is complex.

The debug window (run `calamares -d`, then click on the *show debug information* in the progress-sidebar) shows you which GS keys there **are**, right now, in your Calamares session. It updates when modules set new values.

Ideally, modules would document the GS keys they consume (read) or produce (write). Some do. This is an excellent opportunity for PRs or for wiki-writing. I'm not sure which; both will have the tendency to go stale as the code is updated. I think I prefer documentation "close" to code. We could decide on a conventional filename -- say, `gs.md` if we go for a textual description -- and list the keys there.

The information could be put into `module.desc` -- except C++ modules generate that at build time (that doesn't clash with having one in the source tree, most likely). Or we could come up with a `gs.yaml` to store it in a machine-readable format so it's easier to check that a given set of modules has a proper data-flow (this is headed towards over-engineering).

In the wiki, this would go in the [Deployers Guide](https://github.com/calamares/calamares/wiki/Deploy-Configuration) although I see that just links back to the configuration files in the source tree.

To find out which keys a module uses (either read or write), you can:
- for Python modules, `grep globalstorage main.py`; from the top-level of the source tree, `grep globalstorage src/modules/*/main.py` gets you 87 hits.
- for C++ modules, if's more complicated because typically the code will get a pointer to the globalstorage object, and then use the pointer under a different name. `grep -r globalStorage src/modules/` from the toplevel is demonstrative.
- for C++ services, it gets murkier because this is internals, which have different ways to get to the globalstorage object which are much less obvious (for an example, see `src/libcalamares/partition/Global.h`).

### Partition Information in GS

The partition module only fills in GS keys when it actually runs as part of the installation procedure. Some keys that it **does** set are *filesystem_use* (e.g. you can tell that there is any FS on the machine that uses btrfs) and *partitions* (which is a list-valued key, difficult to use in a *contextualprocess*). And, since recently, *btrfsSubvolumes*.

I can imagine having a *partitions_by_mount* key, though; this would be new code to add to the *partition* module, and it would be sub-keyed on the mount-point. Then your *contextualprocess* configuration could look like this:

```
"partitions_by_mount./.fs":
    "btrfs" : "- touch /this-is-btrfs-root"
```

**Comment by dalto8** [comment]
Since the installer doesn't have a way to create subvolumes outside of identifying the btrfs partition as `/`, it shouldn't be possible to have a non-btrfs `/` and any other subvolumes.  

At least as the code is written today, if the key `btrfsSubvolumes` exists, it should indicate that the root is btrfs.

**Comment by geckolinux** [comment]
@dalto8 Good point, that's what I was thinking too, thanks for confirming that.

**Comment by adriaandegroot** [comment]
There's a table in `src/modules/README.md` (started by @dalto8 , thanks!) that should give a reasonable overview.

**Comment by geckolinux** [comment]
Thank you both!
