### ISSUE TITLE
Python 3.10.1 breaks Calamares 

### ISSUE THREAD

**Issue by Neo-29** [calamares/calamares#1854]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
Python 3.10.1 breaks building and using calamares

**To Reproduce**
1. Update python 
2. Build Calamares 

**Expected behavior**
Bullding correctly 

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.

**Additional context**

**Comment by arcolinuxz** [comment]
This night Arch Linux released 168 updates - consider a big release.
One of those packages was boost and boost-libs.
Calamares builders should have the reflex to rebuild because it.
It is not always necessary but it is most likely. 
There may have been other packages.

We rebuild and done.

![ArcoLinux-2021-12-13_06-10](https://user-images.githubusercontent.com/36679406/145755887-2f838105-b1b9-49fa-aad4-2f21e12a50f8.jpg)

More knowledge at

https://youtu.be/J2mUWk3RAOc

https://youtu.be/F03I9EECQY8

https://www.arcolinuxiso.com/rebuild-calamares-if-one-of-its-dependencies-gets-an-update-boost-and-boost-libs/

This topic can be closed.

**Comment by Neo-29** [comment]
I did of course a rebuild of calamares which failed with this version of python.
It didn't with 3.9.
I'm curious to know what you did exactly to succeed.
Tks.

**Comment by demmm** [comment]
Make sure to post the build full build log.

**Comment by Neo-29** [comment]
I'll try. Is there a command or something to get it entirely easily?

**Comment by demmm** [comment]
Whenever you build Calamares, either on commandline with `cmake/make` or your distros build tool output (if this is Arch based, output of `makepkg`).

**Comment by Neo-29** [comment]
Arch indeed.
The output is quite long.
Shoud I copy paste the lines where the error occurs ?

**Comment by demmm** [comment]
No, pastebin the full output.

**Comment by Neo-29** [comment]
Believe me or not. I retried... And..... No change since yesterday....

And it works.!😃😃😃

I don't get it... Should I have rebooted yesterday?... A cache issue?
I don't know.
Tks for your support Erik and demm, I close the issue. Will re-open if needed.
Cheers.
