### ISSUE TITLE
The distributed ISO image can not be created from calamares

### ISSUE THREAD

**Issue by StrongTiger-cloud** [calamares/calamares#1858]
My purpose is to get the final distributed ISO image after the installation from calamares, but no any iso image can be created yet.

The followings are the things done from my side:
First, my enviroment(virtualbox):
outputs from "uname -a":
Linux localhost 5.10.0-9-amd64 SMP Debian 5.10.70-1(2021-09-30) x86_64 GNU/Linux

I have two virtual harddisk named as "disk_A.vdi" and  "disk_B.vdi", the disk  disk_A.vdi has 32GB and the other one has 16GB.
Then I downloaded the ISO "debian-11.1.0-amd64-netinst.iso"  from the following url:
https://www.debian.org/download

And I had installed the downloaded ISO into my both harddisks, So I have two debian system and I can boot it from any of the two disks. after I boot into the debian system from the installed disk_A.vdi, I mount the other disk disk_B.vdi.

Then I had installed calamares and it had been installed in the path /usr/bin/calamares, and I had configured the setting.conf(add the module netinstall and packages)\netinstall.conf(modify groupsUrl) and packages.conf(modify backend as apt).
when start calamares, seems no any errors in the installation except the grub has some issue, other modules especially the package manager can work correctly. 

**Expected behavior**
After the installation, one ISO image should be created.

**Additional context**
[session.log](https://github.com/calamares/calamares/files/7738635/session.log)
[the reported logs.zip](https://github.com/calamares/calamares/files/7738677/the.reported.logs.zip)

**Comment by StrongTiger-cloud** [comment]
and why I try to get a ISO image:
I will do some development work for calamares in itself, so that I can give some specific features for the installation.
So I hope that the changed calamares and other installation packages can be packed into the ISO image.

**Comment by demmm** [comment]
Not clear from the report/request how Calamares should turn into an ISO creator.

**Comment by adriaandegroot** [comment]
Calamares does not create ISO images. Your distro-tooling does that. What you **can** do with Calamares is build-and-run it in a live ISO sesstion, or build-and-run it in an already-installed system, and use it to run installs to a second hard-disk, for testing purposes.You may have to wrestle a little to get all the relevant parts of the ISO image onto the installed-system -- generally you have the filesystems, squashed or otherwise, available from the ISO so you will need to copy them over.

I do nearly all my development work from an installed system, since only rarely do I need to try the **actual** installation part. When I do need to do a full run, a VM + `deploycala.py` gets me a freshly-built Calamares in a live ISO session; one I can run the install from and do other testing.

**Comment by kkofler** [comment]
Another way to test Calamares (the way I did it, though I have not done it for quite some time now) is:

1. create/update and build a Calamares package for your distribution with the distribution packaging tools (`dpkg` in your case),
2. build an updated ISO with the updated Calamares package with your distribution's ISO building tools (probably `live-build` in your case),
3. run the ISO in a VM with at least one virtual hard disk (backed by an image file),
4. run Calamares in the VM to install the ISO to the virtual hard disk.

**Comment by adriaandegroot** [comment]
Closing with "creating a bootable ISO is not Calamares's task"; there are various approaches mentioned in the comments. I'll add one more: Penguins EGGS is a system to create a bootable ISO from an installed system (and in fact that bootable ISO uses Calamares to install itself, again!) -- https://penguins-eggs.net/ . To me, though, it sounds mostly like you need to deal with how-to-update-an-ISO-image for your own distro.
