### ISSUE TITLE
Calamares cannot find module

### ISSUE THREAD

**Issue by cdvhs** [calamares/calamares#1867]
seems like calamares cannot find the module named "neon-fs-cleanup@neon-fs-cleanup" on a KDE Neon based distro. how do I fix this?

**Comment by demmm** [comment]
Make sure to read https://calamares.io/issues/
Is this a report from an end user?  Distro creator? What distro?
This is certainly not a Calamares issue, since no such module exists. Check with your distro where they have this module/what this module is.  See the full list of Calamares shipped/maintained modules:
https://github.com/calamares/calamares/tree/calamares/src/modules
