### ISSUE TITLE
Add option to install all drivers/language packs 

### ISSUE THREAD

**Issue by ShalokShalom** [calamares/calamares#190]
That can be very help full, because each Hardware (WLAN, GPU, UMTS) works then out of the Box, even when the User/Admin assemble this Device after the Installation process. ^-^

This is also very nice, when somebody install the OS to a USB stick and/or an external hard drive, in order to use them on different computers.

One more benefit result, when someone install the OS on a hard drive and build that one then into another computer, for instance, to go around a BIOS, which can not boot from USB/DVD.

Similar arguments may be valid for the locale support, even if for somebody else than me. :)

The DrakX installer in Mageia, as an example, offer this option:

http://www.dedoimedo.com/images/computers_years/2011_2/mageia-unused-hardware.png

**Comment by demmm** [comment]
Modules referred to in this request are too distro specific.  None of these are even accepted in Calamares master.
That said, a feature to choose which modules to run, and make it configuarble by distributions will be a needed feature.
First "need" case is the option not to install a bootloader.
https://github.com/calamares/calamares/issues/62
If this could be expanded to include 4-5 modules or so that any distro makes optional to run, then a request like above can be implemented.

**Comment by teo** [comment]
This is possibly a long-term TODO. Feel free to report it to http://calamares.io/bugs/
