### ISSUE TITLE
compile error with qt

### ISSUE THREAD

**Issue by facilalinux** [calamares/calamares#1914]
![facilalinux](https://user-images.githubusercontent.com/102735854/161049805-9ef9b0eb-9efe-4a15-b29a-10405b39b05b.PNG)
i am a windows user who's developing a linux distro with a vm. it's debian based. when i ran `$cmake -DCMAKE_BUILD_TYPE=Debug ..`, i got the error in the image above. 

seems like the solution is to get qt5, but for me, it's hard to do that with the terminal, and if i don't need to get qt5 to fix this, then tell me the real solution.

**Comment by adriaandegroot** [comment]
See *Building Calamares* in https://github.com/calamares/calamares/blob/calamares/CONTRIBUTING.md : you need Qt, and you need the Qt-development headers installed. There is a script `deploycala` available -- in a VM you can use that to help install the dependencies. Otherwise, use `apt install qt5-devel` (or whatever the package name is in your linux distro) to get the dependencies. You'll probably have to go a few rounds to install the dependencies.

**Comment by facilalinux** [comment]
and now my problem is that i can't find `qt5-devel`... i am using debian, and i am modifying it into a distro that i am calling facila linux

**Comment by facilalinux** [comment]
and also, i've got a new error that says that i need qt5 linguist

**Comment by demmm** [comment]
Issues are for bug reports or feature requests:
https://calamares.io/issues/
They are not a help channel:
https://calamares.io/issues/#developers-of-distributions

If you need help with deploying Calamares for your distribution, use the appropriate channel (IRC, Matrix, see the links).
