### ISSUE TITLE
Fix the the larger territory of Bangladesh in Location menue.

### ISSUE THREAD

**Issue by rafidalhaque** [calamares/calamares#1929]
The map in the location menue shows a way larger territory for Bangladesh than it should. 

![IMG_20220421_194612.jpg](https://user-images.githubusercontent.com/68812773/164473690-4d07c78d-e6d1-4fa3-b6b9-4bf038264a66.jpg)

The territory of Bangladesh should be this: 

![bangladesh territory](http://ontheworldmap.com/bangladesh/bangladesh-location-map.jpg)

**Comment by kkofler** [comment]
That time zone was correct only for 3 months 80 years ago (in 1942).
https://en.wikipedia.org/wiki/Bangladesh_Standard_Time#History

**Comment by adriaandegroot** [comment]
For a list of timezone issues that we can identify mechanically, but don't have a fix for, build Calamares and run `localetest`. It tells you all of the problematic places. For instance, the output says:

```
    .. Zone "Kolkata" QPoint(552,169) 
    .. First zone found 8 "5.5" 
    .. Also in zone 9 "5.75" 
```

Kolkata is IST, so nobody notices because the algorithm goes from west to east and finds +5.5 (IST) before +5.75 (Nepal). For a good time (ha!), go through that list and with an image editing program (e.g. kolourpaint, with zoom turned up to 800%) make the matching pixel (given by the QPoint there) transparent in the zones where it is wrong. The files are blurry PNGs in `src/modules/images/` -- the blurriness is why this happens. See also all the **other** closed issues about timezones, and why it'd be great if someone produced a new set of pictures or switched out the timezone selector entirely (like the QML version of this module does).
