### ISSUE TITLE
Zfs boot manager needed for Calamares 

### ISSUE THREAD

**Issue by osevan** [calamares/calamares#1947]
Grub doesnt support native zfs encrypted boot possibility. 

Amd snapshot starting before os start.

Starting from different OS installed  

Here is a working solution :

https://github.com/zbm-dev/zfsbootmenu

I hope integrating in calamares is easy possible.

Thanks and 
best regards.

**Comment by demmm** [comment]
Systemd-boot has the needed support and is fully supported by Calamares. Make clear if this is a new feature request, or if you never tried systemd-boot/didn't know about it.

**Comment by adriaandegroot** [comment]
There is also a rEFInd bootloader module for Calamares in the *calamares-extensions* repository. Glancing through the *zfsbootmenu* README, it isn't a bootloader as-such, but needs to be started through rEFInd or something else.

The best thing to do -- if this is a feature request -- is to move this forward yourself by, e.g. any one of these:
- write a shellprocess configuration that does whatever is needed (copy files? do something with initramfs? you can find this in the zfsbootmenu documentation, I'm sure). This can be done for your-distro-only; you could submit it to *calamares-extensions* to share with others.
- write a Python or C++ module that does the necessary things. This could also be upstreamed to *calamares-extensions*.
- add something to the existing rEFInd module (frankly, I'm not sure if anyone uses it since it's not as visible as the Calamares core modules)
- add something to the existing bootloader module (you could open a PR to discuss this, starting with "what configuration is needed"; this sounds like something that would target 3.3 though)

**Comment by osevan** [comment]
Not working with legacy boot. 

We need grub solution or zfs bootmenu

**Comment by demmm** [comment]
>rankly, I'm not sure if anyone uses it since it's not as visible as the Calamares core modules

Yes, been in use in KaOS for quite some time, working well, so another option for this feature request.

**Comment by adriaandegroot** [comment]
Closing with "needs more information, preferably a PR".

At the very least, a list of "to get *zfsbootmenu* running, install a ZFS-based distro with Calamares and then, afterwards, you need to ... (put list of steps here).".
