### ISSUE TITLE
Next button inactive until `encrypt disk` is checked

### ISSUE THREAD

**Issue by demmm** [calamares/calamares#1953]
**Describe the bug**
With Calamares 3.2.58, on the partition page, the `next` button is disabled until encrypt disk is checked & password entered. This happens for replace & whole disk option (did not test alongside, all disks tested are XFS).
Reverting 1 commit did fix this for the erase disk option, but that had no effect on the replace option, reverted commit was https://github.com/calamares/calamares/commit/a63c474d939c915a2706968ea3b239830931850f
I did not try to revert the Luks changes from https://github.com/calamares/calamares/commit/9d6bb2ee2afca9015f7764fa2cc9d217f555c06b

**To Reproduce**
1. Update to 5.2.58
2. On the partition page select replace or erase
3. Next stays greyed out

**Expected behavior**
Use prior to 5.2.58 > once erase disk is selected, `next` is enabled

**Screenshots and Logs**
Section of the log when `Replace` is selected (see the next not enabled part because of missing passphrase, encrypt NOT selected)
```
22:36:11 [6]: bool PartUtils::canBeReplaced(Partition*, const Logger::Once&)
    Checking if "/dev/sda3" can be replaced. 
    ..  Partition "/dev/sda3" authorized for replace install. 
22:36:11 [6]: void PartitionCoreModule::dumpQueue() const
    # Queue: 
    .. ## Device: "/dev/sda" 
    .. - DeletePartitionJob 
    .. - CreatePartitionJob 
    .. ## Device: "/dev/sdb" 
22:36:11 [6]: bool ChoicePage::calculateNextEnabled() const
    No passphrase provided 
22:36:12 [6]: bool PartUtils::canBeReplaced(Partition*, const Logger::Once&)
    Checking if "/dev/sda3" can be replaced. 
    ..  Partition "/dev/sda3" authorized for replace install. 
22:36:12 [6]: bool PartUtils::canBeReplaced(Partition*, const Logger::Once&)
    Checking if "/dev/sda3" can be replaced. 
    ..  Partition "/dev/sda3" authorized for replace install.
```

**Comment by adriaandegroot** [comment]
In my testing (each time, starting Calamares through `sudo -E ./calamares -d` on my laptop where I've just built Calamares):

- click *erase disk* shows the *Encrypt system* checkbox, also *next* is enabled
- click *replace a partition*, shows *Encrypt system*, *next* is not enabled (because there is no partition to replace, selected yet).
  - click on a partition to replace (e.g. I have a hefty free space partition, click on that), *next* is not enabled and debug-log shows "No passphrase provided", as in @demmm 's report.
  - check *encrypt system*, passphrase boxes are shown and warning that the passphrase needs to be entered; *next* is not enabled.
  - **un**check *encrypt system*,passphrase boxes vanish and *next* is now enabled
