### ISSUE TITLE
Qml modules issues

### ISSUE THREAD

**Issue by abalfoort** [calamares/calamares#1985]
**Describe the bug**
I've been testing the Qml modules (calamares branch) and found some issues.

**Graphical issues**
**welcomeq**: without an internet connection the message overlaps the header text.

![Screenshot_20220607_140409](https://user-images.githubusercontent.com/63945418/172667733-e2aed0ca-0456-4ae8-818a-04043773c28d.jpeg)

**usersq**: the last two check boxes and their labels are centered instead left-aligned.

![Screenshot_20220607_123516](https://user-images.githubusercontent.com/63945418/172667927-6df7be8e-8152-455b-82ae-1f2e261cf907.jpeg)

**A general remark**: modules like welcomeq. locationq have a white background (using Page type in qml), the others haven't. Is there a way to make that white background transparent?

**Code or configuration issue**
**keyboardq**: does not load. In the log file I found this:
```
2022-06-07 - 14:12:55 [2]: void Calamares::QmlViewStep::showFailedQml()
    WARNING: QmlViewStep "keyboardq@keyboardq" loading failed. 
2022-06-07 - 14:12:55 [6]:     .. QML error: "qrc:/keyboardq.qml:282 Keyboard is not a type\n" 
```
The Keyboard type can be found [here](https://github.com/calamares/calamares/blob/9fdae8c76f87c3d1d228610a46f501427f1872ce/src/modules/keyboardq/keyboardq.qml#L282).

Do I miss a package?

**Comment by demmm** [comment]
>usersq: the last two check boxes and their labels are centered instead left-aligned.

Intended design, not a bug, left align is for headers for LineEdits (LineEdit for reuse password will be under it, if you set that box as unticked), last 2 are 2 check boxes only.  Just copy the usersq.qml (or any of the others) file to you branding directory, and create the QML as you'd like to design.
All QML modules ship with basically example QML files, the `q` modules are specifically intended to give all distros complete freedom to make the modules look like they want, defaults are a starting point/example/option.

All qml modules have the color variables in their headers, so it is easy to get started with customizing.

Keyboardq not loading not clear yet, since it loads fine here, the qml files list what they expect to have installed, not all are listed in the cmake of the module. The Keyboard.qml list this one, make sure you have it installed:
https://github.com/calamares/calamares/blob/calamares/src/modules/keyboardq/data/Keyboard.qml#L11

For future reference, please open one bug report per module, impossible to start throwing multiple modules in one.

**Comment by demmm** [comment]
Keyboardq issue is due to a missed merge of keyboard.qrc.
