### ISSUE TITLE
Keyboard preview not compatible with xkeyboard-config 2.36

### ISSUE THREAD

**Issue by demmm** [calamares/calamares#1988]
**Describe the bug**
The keyboard page shows a keyboard preview without any characters.

**To Reproduce**
Open Calamares with xkeyboard-config 2.36 installed, see image below.
Downgrade to xkeyboard-config 2.35.1, issue is gone.
Probably not a Calamares issue, but no bug reports found yet at https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues so not a clear answer yet where the change is needed to fix

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/5360485/172954567-7ed7a215-0217-49a8-984f-1a83389adc87.png)

**Comment by adriaandegroot** [comment]
The bug is upstream, and if you run `ckbcomp -model pc106 -layout default` (which is the / a command that Calamares uses to get the keyboard preview) it will print an error message. You can look up the file it is complaining about (`xkb/rules/base`). Then you can search for the error line, and you will see that it uses `/` for line-continuation instead of `\`

**Comment by adriaandegroot** [comment]
Upstream report is https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/324

**Comment by demmm** [comment]
Fixed upstream in https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/commit/8ac41c50ab0aa7cd3a7e94313074115de2a172d2

**Comment by killajoe** [comment]
https://gitlab.freedesktop.org is down currently?
