### ISSUE TITLE
Touch only installation

### ISSUE THREAD

**Issue by plata** [calamares/calamares#2024]
**Is your feature request related to a problem? Please describe.**
While the buttons can be used with touch input, a physical keyboard is needed to fill the text fields.

**Describe the solution you'd like**
Include a virtual keyboard such that the installation works with a touch screen only.

**Describe alternatives you've considered**
None.

**Additional context**
I'm not completely sure if this is a feature for Calamares or should be handled by the distribution/people who create the installer.

**Comment by kkofler** [comment]
Generally, the virtual keyboard is supposed to be provided by the (mobile) "desktop" environment, e.g., Plasma Mobile provides one, Phosh does too, etc.

Calamares, being a GUI application, normally expects to run within such an environment and not on raw X11 (or even raw framebuffer) or with a dumb Wayland compositor. If the distro insists on running it in a very minimal environment, they need to provide the virtual keyboard in that environment.

**Comment by kkofler** [comment]
Closing as a downstream distribution issue. Please take it up with whatever distribution you are using.

**Comment by demmm** [comment]
I have been looking into this some, and I presume this is for the user page, correct?  Currently there are no other modules in Calamares where the user needs to fill in text fields.
This can be deployed inside the Calamares app, working version shown below, but I only know how to implement this in the QML `usersq` module.
Current code opens the virtualkeyboard on clicking a text field.
One image (if your distro is interested in implementing this through the usersq module, I will show some more images/short video):
![Screenshot_20220722_195729](https://user-images.githubusercontent.com/5360485/180498216-2c17baba-544c-4351-8856-18e7060c1c68.png)

**Comment by adriaandegroot** [comment]
I'm with Kevin that this is something the environment should provide; typically you would get whatever input-method / touch-support is needed whenever you enter a text field. But since Calamares often runs as a separate user, the environment may end up confused. With the QML modules you can do whatever extra UI you like -- you'll still find un-editable text fields in the partition module (manual partitioning), possibly in the OEM configuration module (rarely used). You'll need to figure out how to hook up IM to applications running as different users (or push towards a rootless Calamares, which means adding some kind of elevated-permissions-helper like KPMcore has, and starting to route Calamares command-executions through that)

**Comment by demmm** [comment]
As noted here a few times, using a virtual keyboard in the "Desktop" environment is not an option for Calamares. So that leaves the option to run a virtual keyboard within the application.
For QML modules to be able to do that, the main.cpp will have `qutenv` set to the needed input module.  Since that should not be a default options, the top cmake will need to have a build option to enable.  That would make it that distributions can't just adjust some QML files to enable this feature.  Even though it does work well when set within the application.

**Comment by demmm** [comment]
Since no further response from the original submitter, I'm closing this again.
Doing a touch only install is very doable, and already implemented downstream (KaOS).
But as noted here, it is preferred to let the distributions do the implementation.

**Comment by plata** [comment]
To be honest, I wasn't aware that I should provider further response. Maybe there's also a misunderstanding. I'm not maintaining a distribution. I've only observed that e.g. in Manjaro Gnome, there's a virtual keyboard in the live system but not in Calamares (e.g. on the user page but also e.g. to test the keyboard layout).

I understand that showing the virtual keyboard as in the live system (like a naive user might expect) doesn't work.

It would probably still be nice to have some common implementation such that the virtual keyboard can be enabled easily by distributions (and if possible not for every page/module separately).

As for KaOS: I've tried it. There's a custom virtual keyboard on the keyboard layout page but I couldn't fill the user page.

**Comment by demmm** [comment]
>As for KaOS: I've tried it. There's a custom virtual keyboard on the keyboard layout page but I couldn't fill the user page.

There is no ISO or release with that feature yet, it was just implemented a few days ago.

>I've only observed that e.g. in Manjaro Gnome, there's a virtual keyboard in the live system

Can that keyboard interact with Calamares?  I would doubt so, since Calamares does not run as user, so input target of the virtual keyboard would never be Calamares, that is why the solution done in KaOS is to do the keyboard in app.

>To be honest, I wasn't aware that I should provider further response.  

See my reply https://github.com/calamares/calamares/issues/2024#issuecomment-1192819853, I asked 2 questions about what was wanted for this feature.

**Comment by plata** [comment]
> Can that keyboard interact with Calamares?

No. It doesn't open. That's why I wrote
> I understand that showing the virtual keyboard as in the live system (like a naive user might expect) doesn't work.

Questions:
> I presume this is for the user page, correct?

I thought it was a rhetorical question. Most importantly, yes. Additionally keyboard layout filed and as pointed out by @adriaandegroot 
> you'll still find un-editable text fields in the partition module (manual partitioning), possibly in the OEM configuration module (rarely used)

What's the second question?

**Comment by demmm** [comment]
>What's the second question?

`if your distro is interested in implementing this through the usersq module, I will show some more images/short video`

If there is no interest in using the QML modules, then all these replies are moot.

**Comment by plata** [comment]
I cannot answer this. Like I said, I'm not a distribution maintainer.

Does the virtual keyboard open also if a physical keyboard is attached? Can Calamares know this?

**Comment by demmm** [comment]
It is a user choice, regardless whether the install is done with a keyboard attached.  Activating is not automated, but done with a button, see image (text on mouse hover), when the virtual keyboard is in use, the edit fields will scroll up once they come in focus, that scrolling won't happen when virtual keyboard stays hidden:
![Screenshot_20220724_213200](https://user-images.githubusercontent.com/5360485/181257199-15fca541-37a5-45d0-ad25-e9306d47332c.png)

**Comment by plata** [comment]
From a user's perspective, this will get the job done.

**Comment by demmm** [comment]
[vokoscreenNG-2022-07-27_15-58-41.webm](https://user-images.githubusercontent.com/5360485/181266364-cd8fba54-98d2-4337-8143-415f7c01304a.webm)

**Comment by spikerguy** [comment]
This is good to have and I appreciate your work on adding keyboard app inside calamares. 

Are you willing to share the source or test iso, so we can test it further ?

**Comment by demmm** [comment]
@spikerguy  >Are you willing to share the source or test iso, so we can test it further ?

No need for a test ISO, it is available on the latest KaOS stable ISO
https://kaosx.us/news/2022/kaos08/
https://kaosx.us/pages/download/

**Comment by demmm** [comment]
@spikerguy 
>I did find the patches on KaOS git

You will need a lot more then just that patch to have it really functional, plus if you are running kirigami 5.97, it won't work at all with that patch, later commits moved it away from the breakage in that version of kirigami.ScrollablePage.
