### ISSUE TITLE
Translation string seems to be missing on the about button on the side navigation

### ISSUE THREAD

**Issue by codesardine** [calamares/calamares#2030]
**Describe the bug**
About button is not translated to another language, this was tested only in Portuguese language

**To Reproduce**
chose Portuguese or another non English language, the about button should still say (About)

**Expected behavior**
The about button should be translated to the respective language, as discussed in the dev channel this seems to only affect Qwidgets and not QML sidenav, seems to affect 3.2 branch and maybe 3.3 branch, I only had a chance to test on 3.2

**Comment by adriaandegroot** [comment]
You will want to look for that string in the extracted language files (e.g. `lang/calamares_en.ts`). The actual extraction is done by *lupdate*, or lupdate-called-from-`txpush.sh`. You can do it by hand:

```
lupdate src/calamares -ts check_en.ts
```

This will produce a translation file for the strings from `src/calamares` and you can look in `check_en.ts` for the string. It's not there. It looks like the code tries to re-use a translation from the main Calamares window, (that's why it's using the meta-object in the call to `::translate()`) but the string itself has gone away. It's probably easiest to fool *lupdate*; see  `ViewManager.cpp` and the define appropriately called `PRESERVE_FOR_TRANSLATION_PURPOSES` for an example. After patching the code, the *lupdate* call above should produce a translation file that does contain the relevant string, and you can PR that.

**Comment by adriaandegroot** [comment]
As an alternative, since the string was lost from translations **anyway** -- at least, I'm assuming the tooltip is also gone -- is to just replace the context with something else. Instead of using the meta-object, use `"calamares-sidebar"` if you want to share the translation context with the QML code. That will give you the existing translation of the QML "About" for free, and is probably the quickest fix.

**Comment by demmm** [comment]
I've traced it back to March 4 2021, when the debug button was adopted to add the QML option, since then the translation for the debug button & popup are gone.
Since the About button uses the same code as the debug button, logic the translation does not work.
Probably this commit:
https://github.com/calamares/calamares/commit/ab7f6abf026d5480fbf699846c8428767b6430d7

en.ts file:
https://github.com/calamares/calamares/commit/d3f84980b32c3d879d3ddb11a4dc9750ac5d244b#diff-dcb0325879aaf321a57d27baa59728c1d7d13f424735bc67f3edcfffb2738938L467

**Comment by demmm** [comment]
> As an alternative, since the string was lost from translations **anyway** -- at least, I'm assuming the tooltip is also gone -- is to just replace the context with something else. Instead of using the meta-object, use `"calamares-sidebar"` if you want to share the translation context with the QML code. That will give you the existing translation of the QML "About" for free, and is probably the quickest fix.

that was the simplest fix, and picks up all needed translations, so no work for transifex translators.
