### ISSUE TITLE
settings.conf installed in strange place

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#2075]
There is a file settings.conf which is installed into the build directory

 https://github.com/calamares/calamares/commit/8f72d2541f241ef5a1f4bc945bdc908e7dbe9fdd

https://github.com/calamares/calamares/blob/calamares/CMakeLists.txt#L589 

e.g. when I build locally it gets installed into `/home/jr/src/extras/calamares/github/calamares/build/settings.conf` instead of /usr/share/calamares or similar

What is this madness?

**Comment by kkofler** [comment]
+1, this breaks distribution workflows, see also:
https://src.fedoraproject.org/rpms/calamares/blob/rawhide/f/calamares-3.2.61-default-settings.patch

I do not see why it is not a reasonable thing to do to apply a patch to the upstream default settings adapting them to the distribution and then install them as part of the Calamares package. IMHO, that is a perfectly valid way to handle configuration files, and surely easier to maintain than having to copy the whole bunch of config files into a custom noarch package.

Please revert commit 8f72d2541f241ef5a1f4bc945bdc908e7dbe9fdd.

**Comment by dalto8** [comment]
Personally, I think this change fixes more than it breaks.  Too many people were doing the wrong thing here.

While I think the approach of patching all the config files on the distro side is sub-optimal, if that is the approach you prefer you can also patch the CMakelists to install them again or simply install them as part of your package.

**Comment by jriddell** [comment]
From the deploy guide
https://github.com/calamares/calamares/wiki/Deploy-Guide 

```
Distributions are strongly urged to package configuration files separately from Calamares itself, and to install them in /etc/calamares. It is not recommended to edit or patch the configuration files included with Calamares for production use -- they are examples.
```

That is fair enough.  I just don't understand why it's installing a file into the build directory, that's broken.

**Comment by killajoe** [comment]
this is installed by the package and something is creating the file so it will get into the package build.. 
![Screenshot_2022-12-05_17-08-00](https://user-images.githubusercontent.com/16797647/205685186-b4143293-a6ac-4b87-9022-1abd466b101a.png)

**Comment by kkofler** [comment]
How does that commit address this issue? `settings.conf` is still installed to the same weird location, just using a different CMake command at a different spot in `CMakeLists.txt`.

**Comment by adriaandegroot** [comment]
/close

The problem was, as Jon reported, that a file was being `install()`ed into the build directory. That breaks packaging whenever the packaging depends on CMake's installation logic -- in the face of `make install DESTDIR=/tmp/package` for instance, where you would get `/tmp/package/home/....src/calamares/build/settings.conf` . This has been resolved.

**Copying** `settings.conf` into the build directory is intentional: it's a developer convenience that `calamares -d` when run in the build directory picks up the settings (all of them, and updated when edited) from the source repo.

**Comment by kkofler** [comment]
I still think commit 8f72d2541f241ef5a1f4bc945bdc908e7dbe9fdd should be reverted though. Why does it hurt to have an `INSTALL_CONFIG` option that is off by default, so that distributions that want it (and that already patch the config files to do the right thing on their distribution) have to only set one CMake variable (through the CLI or a one-line patch) rather than to patch a whole bunch of files to readd code that was once there?
