### ISSUE TITLE
Bad backend error

### ISSUE THREAD

**Issue by johna23-lab** [calamares/calamares#2089]
Hi! i tried to make a custom installation for Void Linux, (uses the xbps manager) it works well, but if i use the module packages.conf with this configuration

####### Which package manager to use, options are:
  - xbps

######
backend: dummy

operations:
  - remove:
    - sane
    - vim

The installer finishes with this error
"Installation failed
Bad backend

Details:
backend="None"

**Comment by demmm** [comment]
Make sure to post the used packages.conf.
Since there is no `xbps` added/available, are you sure VOID has that option?
https://github.com/calamares/calamares/blob/calamares/src/modules/packages/packages.conf#L22
It will need a PR from VOID to add the needed backend.
Also not clear if this is an end user report, or are you a distro developer?  See https://calamares.io/issues/ and https://calamares.io/issues/#end-users
Are you using Calamares released version?  Git version? Fork?

**Comment by dalto8** [comment]
That doesn't look like a correct conf file.

You have `xbps` at the top of the file just floating there but you have the backend set to `dummy`.

The backend should probably be set to "xbps" if that is your package manager.

**Comment by demmm** [comment]
Closing with user error, wrong setting in .conf file.
