### ISSUE TITLE
Need module for unencrypted /boot

### ISSUE THREAD

**Issue by DerGrossmann** [calamares/calamares#2117]
Hello everyone!
I'm in the process of building my package to install a debian fork. Unfortunately, I'm not good at compiling and building packages, I can only change configs. I have a big request to knowledgeable people. Help me write a module that doesn't require rebuilding the calamares package. It should have functionality so that when partitions are automatically created and LUKS encryption is enabled, the /boot partition is not encrypted, but only the root is encrypted. The file system must be text4 and must be UEFI. Only manual creation of partitions helps me, but I want convenience during installation. One person gave a link to his module, but the link is not available https://github.com/calamares/calamares/issues/1311#issuecomment-1102625901 
Thank you very much in advance. If you can help me, I will consider the possibility of thanking with money. Thank you

**Comment by dalto8** [comment]
Trying to do that by creating a module is not very practical since partioning is handled by the partition module.  You would either need to implement everything the partition module does or do something terribly awkward like read the partition table, see if was encrypted then modify the partitions on the disk and the partition data structures in global storage to match.

Really, the best solution would be to add support for that to the partition module which I believe there is already an open feature request for.

As a workaround, if you are only concerned about UEFI, you could change the location of the EFI partition to `/boot` in `partition.conf`.  That would ensure that `/boot` was always unencrypted.

Lastly, this is not really a forum for soliciting people to do work for your distro.
