### ISSUE TITLE
persian keyboard problem

### ISSUE THREAD

**Issue by MrRezax85** [calamares/calamares#2132]
Hello, my keyboard is a 104-key keyboard with a large enter key.As you can see, this keyboard is incompatible with the screen keyboard in the Persian language installer. I request you to solve this problem.
![233923630-10771eba-4734-4203-934b-852b9e349b31](https://user-images.githubusercontent.com/86867247/235117551-97d2603c-9ae9-4dce-83c6-e7787cd1ba90.png)
![keyboard Green GK402](https://user-images.githubusercontent.com/86867247/235117562-2e162e9b-db98-45d6-887d-259e1f11deaf.jpg)

**Comment by kkofler** [comment]
You picked the wrong model in the Keyboard Model dropdown. What you have selected is "Generic 105-key PC". That is the German layout, which has 2 hardware differences compared to yours:
* There is an extra (105th) key next to the left Shift, which is unassigned in the Persian keyboard layout.
* The \ key (in your layout) is located next to the Enter key rather than next to the Backspace key.

XKB has a setting for a generic 104-key PC keyboard with an L-shaped Enter key. That should be what you want.

**Comment by MrRezax85** [comment]
> You picked the wrong model in the Keyboard Model dropdown. What you have selected is "Generic 105-key PC". That is the German layout, which has 2 hardware differences compared to yours:
> 
> * There is an extra (105th) key next to the left Shift, which is unassigned in the Persian keyboard layout.
> * The \ key (in your layout) is located next to the Enter key rather than next to the Backspace key.
> 
> XKB has a setting for a generic 104-key PC keyboard with an L-shaped Enter key. That should be what you want.

This image was just a preview
My choice was exactly generic 104-key PC keyboard with an L-shaped Enter key and I have the same problem again

**Comment by demmm** [comment]
Is this a Calamares only issue?  Can you set the correct preview & keyboard in your installed system/Desktop Environment?
Or is this an xkeyboard-config issue?  Checked the bug reports there?
https://gitlab.freedesktop.org/search?group_id=1240&project_id=891&repository_ref=master&scope=commits&search=persian

**Comment by demmm** [comment]
Closing, no further (needed) response from submitter.
