### ISSUE TITLE
Does Calamares support the usage of zram instead of swap?

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2152]
**Is your feature request related to a problem? Please describe.**
Does Calamares support the usage of zram instead of swap in the Partition module?

**Comment by dalto8** [comment]
Not currently. 

If you want to always use zram you could disable the swap option in partition module and enable it via a script later in the install process.

**Comment by D3vil0p3r** [comment]
> Not currently.
> 
> If you want to always use zram you could disable the swap option in partition module and enable it via a script later in the install process.

Do you mean should I set "No swap" and then implement zram as described in https://wiki.archlinux.org/title/Zram#Using_a_udev_rule ?

**Comment by dalto8** [comment]
> Do you mean should I set "No swap" and then implement zram as described in https://wiki.archlinux.org/title/Zram#Using_a_udev_rule ?

If you set the only available swap option to `none` in `partition.conf` and then setup zram in a script.

There are many ways to setup zram.  You can use whichever you prefer.  On an Arch-based distro I would probably use `zram-generator` since it doesn't require fstab changes and supports a simple config file if an end user wants to change it.

**Comment by D3vil0p3r** [comment]
Thanks for the suggestion! I hope that in the future Calamares will support also zram.
