### ISSUE TITLE
Increasing verbosity level on the Calamares GUI during installation

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2155]
Usually, when I use `shellprocess` module for running some bash script, as:
```
- command: "/usr/local/bin/myscript"
```
during the installation, when i click on **Toggle log** button for seeing the runtime logs, about the execution of `myscript` I don't get stdout output but only errors. In general the logs stuck at a log string like:
```
2023-05-29 - 23:46:33 [6]:     .. Running ("/bin/sh", "-c", "/usr/local/bin/myscript") 
```
without showing any string of execution or echo, but only error strings.

Is it possible to enable on the Calamares GUI also the verbosity level to get also the logs related to the execution of this kind of scripts run by shellprocess module?

**Comment by dalto8** [comment]
I believe those logs follow the verbosity level set when you run Calamares.  If you launch Calamares with `-D8` you should get the maximum level of logging.

**Comment by D3vil0p3r** [comment]
I run calamares by `calamares_polkit -d` that contains the following code:
```
#!/bin/bash
if [ $(which pkexec) ]; then
        sudo "/usr/bin/calamares" "$@"
else
        /usr/bin/calamares "$@"
fi
```
On `calamares -h` I read that `-d` argument `Implies -D8`. Should I try `calamares_polkit -d -D8`?

**Comment by D3vil0p3r** [comment]
I performed a further test by running `calamares_polkit -d -D8` but I still have the same log verbosity of `-d` only argument.

It could be cool if Calamares could reach a verbosity level such that, if `myscript` of the example above has inside a `pacman -S <package>`, logs will show the pacman output, so the user can check better if in general a script is hanging or not.

Currently, by `-D8`, the only output produced here that I see is only related to non-blocking errors, for example `error: package 'gdm' was not found` produced by `pacman -R gdm` command in `myscript`.

**Comment by adriaandegroot** [comment]
It's time to disentangle `-d` (*developer mode*) from `-D` (*debug level*). In developer mode, there are extra buttons, the module-loading path is different, and the debug level is automatically set to `-D8`. If you have a production ISO, setting `-d` is probably quite useless.

The debug level influences what goes to standard output and what goes to the log file. 

- Nothing passed in, defaults to debug level 2
- Level 0, nothing goes to stdout, debugging messages (and warnings and errors) go to the log file
- Level 1, errors go to stdout, debugging messages (and warnings and errors) go to the log file
- Level 2 (default), errors and warnings go to stdout, debugging messages (and warnings and errors) go to the log file
- Levels 3, 4, 5 are the same as level 2 because nothing special logs at those levels
- Level 6, debugging messages and warnings and errors go to stdout, and also to the log file
- Level 7 is the same as level 6
- Level 8, verbose messages and debugging and warnings and errors go to stdout, and also to the log file

But all that is about **logging**. Then we get the question of what the *shellprocess* module (and similar) do with the output from the things they run. You can follow the chain of classes used to run things and end up in `libcalamares/utils/Runner.h`, which is used from `System::runCommand()`.

I think that setting output processing on the *Runner* object, and connecting the *output* signal to a lambda that logs it -- probably doing this only if debug-level is 6 or 8 -- would do the trick. Bear in mind, though, that this function is used for **everything**, so it may be best to add parameters to influence this logging in `CommandList` so that only *shellprocess* gets logged. But you'll need to PR something in the C++ code regardless.

**Comment by adriaandegroot** [comment]
Here is typical *shellprocess* output (**already** like this):

```
21:56:25 [6]: virtual void Calamares::JobThread::run()
    Starting job "Running shell processes…" ( 1 / 1 ) 
    .. Running ("/bin/sh", "-c", "touch //tmp/thingy") 
21:56:25 [6]: void {anonymous}::PowerManagementInterface::inhibitDBusCallFinished(QDBusPendingCallWatcher*)
    Sleep inhibited, cookie 214 
    .. Running ("/bin/sh", "-c", "/usr/bin/true") 
    .. Running ("/bin/sh", "-c", "echo -e '\u001B[33;2mred\u001B[33;0m'") 
    .. Finished. Exit code: 0 output:
 -e red
```

Huh, I see now that the escaped strings are turned into escape codes at the YAML level, already. Anyway, the output of the shell command is already logged: it's `-e red` (and if your terminal supports it, in the color red, too).

This is different -- or less useful -- for long-running commands with multiple lines of output, because it only gets logged at the end. So what's this issue / feature request really about?

**Comment by adriaandegroot** [comment]
See branch *issue-2321* (wrong issue number, right branch though). That gets some things started, but then I realised that the logging you seem to want, is already there; or maybe it is "if the command is verbose, always log output".

**Comment by D3vil0p3r** [comment]
Yes. I mean that
