### ISSUE TITLE
Request to add Network Configuration View Module in calamare while installation.

### ISSUE THREAD

**Issue by skmdab** [calamares/calamares#2255]
Requesting to add Network Configuration View module in calamares while installation.

Like.
IP address
Netmask
Gateway
DNS

**Comment by adriaandegroot** [comment]
Is this a request from a distro, or an end-user? 

Calamares typically copies "the network configuration", whatever that may be, from the live-cd into the target system, since most live-cds already do network configuration somehow -- if there is a desktop environment, then that usually offers a networking widget of some sort. 

Just offering some input fields doesn't do enything useful on the Calamares side -- what should it write? (hm, maybe for FreeBSD I know how to output something useful in the rc files) Much more useful would be a general "embed this KDE KCM" because then you could leverage the desktop environment (well, **a** desktop environment) configuration tools from within Calamares.

Closing as under-specified.

**Comment by kkofler** [comment]
Hmmm, in principle, the default NetworkManager configuration format (`keyfile`) is well-specified and could be written by Calamares. But it would mean Calamares would become yet another NetworkManager frontend, and configuration can be quite complex for things such as WPA Enterprise or VPNs.
