### ISSUE TITLE
Installation boot to black screen

### ISSUE THREAD

**Issue by jupgithub** [calamares/calamares#2272]
Arch Linux derivation (installation on bare metal or virtualbox, but appears that some people does not have the problem [?])
Calamares 3.2.61-5

When I install it, appears to be that Calamares create /etc/sddm.conf.d/autologin.conf
with the following:

[Autologin]
Relogin=false
Session=plasma
User={live user} (I changed the specific user)

And the system boot to black screen.

I changed via TTY (terminal) with the following:

[Autologin]
Relogin=false
Session=plasma
#User={live user} (I changed the specific user)
User={my own user}

Then reboot, and it boot fine (lasted a little bit).

Maybe the problem is that the system was configured to autologin with the user <live user> that does not exist.

The solution would be to disable autologin on installation or to assign it to the new user.

I don't know if that was fixed on recent versions of Calamares.

**Comment by demmm** [comment]
Is this a report from an end user? If so, please report to your distribution first, they will know best if the issue is a distro specific setting, see:
https://calamares.io/issues/
https://calamares.io/issues/#end-users

If you are a distro developer, make sure to post your used settings and any & all info required for a proper bug report (as asked for in this issue template too):
https://calamares.io/issues/#developers-of-distributions.

Issue as is will be closed shortly.

**Comment by dalto8** [comment]
In that case, the issue should be reported to the distro.  If they determine it to be an issue in Calamares, they can report it along with all the proper details to replicate the issue.

**Comment by jupgithub** [comment]
Ok, thanks
