### ISSUE TITLE
Partition: EditExistingPartitionDialog: update Keep/Format radio with queued changes

### ISSUE THREAD

**Issue by iam-TJ** [calamares/calamares#2283]
In manual partitioning when there are existing partitions, the Keep/Format radio button  defaults to Keep even if a previous call to the Edit dialog changed it to Format (except for ZFS).

This leads one to believe the previous selection of "Format" wasn't saved so one might do this again, and again, and again... because the change doesn't seem to stick.

When one gives up and continues on the installation summary then lists multiple entries for formatting that partition!

"Keep" is the default in  `EditExistingPartitionDialog.ui`  and there are ZFS specific overrides to "Format" in `EditExistingPartitionDialog.cpp::EditExistingPartitionDialog()` constructor.

There may be two parts to a fix:
  1.  inspecting previously queued actions and updating the radio button state based on those
  2.  removing duplicate queued actions before the install summary.

**Comment by kkofler** [comment]
I would even classify this as a potential data loss bug! Just think of the use case where one accidentally selects "Format", then goes back to switch to "Keep", but the partition gets formatted anyway… bye bye data!

**Comment by adriaandegroot** [comment]
Let's be very specific about scenarios here:

- start Calamares (in a configuration that has the *partition* module enabled; recommended to have `DEBUG_PARTITION_UNSAFE` on, and `DEBUG_PARTITION_BAIL_OUT` on as well)
- click through to the *partition* module
- click *Manual partitioning*
- click *Next*
- pick an existing partition and click *Edit*
  ![image](https://github.com/calamares/calamares/assets/19431457/0a72950c-e16a-40ed-b4dc-664061052cc7)
- click the radio button *Format* and then *OK*
- pick the same partition and click *Edit* again
- notice that the *Keep* / *Format* choice is back to *Keep*

You can do this a couple of times if you like. Also, optionally, set a FS label -- it is not preserved across invocations of the edit dialog, either -- I think there is another issue already filed for this.

After a few iterations, set some partition to mount at `/` and click *Next*, and then through to the *summary* page.

![image](https://github.com/calamares/calamares/assets/19431457/310e4c41-d5e8-4372-801a-3a16717a28a8)

Notice that here, I have set the label twice, picked format three times, so the "what will we do" looks really silly. (Also the two messages at the top because of the CMake-time configuration variables I set).

**Comment by adriaandegroot** [comment]
Fixed with d7bbfd055cadba98b63e9436767b19f7ae221dd9 but I forgot to put FIXES in the commit message.
