### ISSUE TITLE
Calamares installation on Debian produce a 755 /home/$USER permissions

### ISSUE THREAD

**Issue by arpinux** [calamares/calamares#2362]
Hi,

i'm performing many installations tests of Debian 12 Bookworm (live, Cd, DVD) and noticed something strange:

while Debian classical installer produce a /home/$USER with no permissions to other to view its content (700), Calamares produce a /home/$USER available to any other user (755).

**Comment by dalto8** [comment]
Calamares doesn't set the permissions of the directory.  It calls `useradd`.  So those permissions are what is coming from your distros `useradd` command.

I would try running `useradd -m` from your ISO and see what permissions it assigns the home directory.

**Comment by arpinux** [comment]
The Debian system usually use 'adduser'. this command chmod the home dir when 'useradd' don't.
maybe Calamares should use 'adduser' to avoid permissions issue ?

**Comment by highvoltage** [comment]
@arpinux Which ISO did this happen on, the change in default changed it in calamares too, and on my latest ISO the newly created directory does have 700 permissions. The older releases had 755, in the old days the idea was that it's easier for users on the same system to share files with each other from their home directories. Obviously no one expects that anymore these days, so the default was changed to 700.

**Comment by highvoltage** [comment]
> The Debian system usually use 'adduser'. this command chmod the home dir when 'useradd' don't. maybe Calamares should use 'adduser' to avoid permissions issue ?

On the Debian 13 ISOs it sets it up with 700 permissions, not sure if the release team would consider it a big enough issue for backporting, but I'm surprised that the calamares behaviour here is different on Debian 12 where it does the right thing on the Debian 13 builds. Will look into it.

**Comment by arpinux** [comment]
@highvoltage : my first test was on debian-live-12.6-xfce. i've just tested on debian-live-12.7-gnome and same result : $HOME is on 700 after an installation via Calamares  
i didn't test the debian 13 installation

@dalto8 : if Calamares uses useradd, maybe adding a little hack at the end of the useradd call in order to check the /home/$USER permissions would be a good alternative

**Comment by adriaandegroot** [comment]
I'm going to close this because it is entirely a distro-decision. While Calamares uses (old-school) `useradd`, the newer `adduser` describes itself as a friendly wrapper around `useradd`. The differences are described below. The tools are configured differently, and Calamares happens to call the one that Debian has configured to create a permissive home-dir.

That said, I think a "set homedir-permissions" configuration item in Calamares would be useful, if only so that installation-configuration and later users can be done differently.

### useradd

This uses configuration files from `/etc/login.defs`. In Debian 12, this file specifically configures umask 022 for home directories, right under a comment saying "077 would be more secure, but that is a sysadmin decision for each installation".

### adduser

This uses configuration files from `/etc/adduser.conf`, which sets a umask of 077 in the default configuration.
