### ISSUE TITLE
Shorten Install Time Drastically for Separate Home Partition if same username is being used on reinstall.

### ISSUE THREAD

**Issue by ellertone** [calamares/calamares#2385]
**Is your feature request related to a problem? Please describe.**
In installing any new distribution the home partition can be reused. But resetting file permissions adds an extra hour or more to every install even for recovery.

**Describe the solution you'd like**
Add a single line of code, an "if statement" for checking whether the new username matches the old one for permissions and just skip over that step.

**Describe alternatives you've considered**
Make a checkbox whether to add the change permissions or not if it a reinstall.

**Additional context**
Most installs are usually just distro changes with same environment and personal files for one user. Calamares is great but the extra additional time can be skipped with a single "if statement" or a user prompt or checkbox. One hour or more is saved with just a line of code.

**Comment by dalto8** [comment]
I am not a fan of this idea for a few reasons:
* It adds user confusion since a large percentage of Calamares user's won't know what it does or how to use it properly.
* This is especially true since it has nothing to do with the fact that the username is the same.  It is the underlying UID that needs to be the same.
* You would also have to consider how to handle the GID.  Not all distros handle the default groups the same way.
* It making a material difference is an edge case to begin with.  You would need slow storage and a large number of files to have chown take a substantial amount of time.  I can't even imagine what your scenario is where it takes over an hour.

If you have this problem, it could be easily worked around by simply mounting your `/home` after install instead of trying to do it during the install.
