### ISSUE TITLE
[Debian] Needs to reconfigure key packages post-installation

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#359]
Jira issue originally created by user @teo:

Hi!
After the installation, several packages need to be reconfigured, e.g. dbus and systemd require a new unique machine-id to be generated.
Also, ping needs to be suid-root, which it isn't after squashfs-extraction (so running ping won't work). This is fixed by a setcap call in it's postinst script.
These issues can be solved by running these commands in the new system:
```
dpkg-reconfigure -f noninteractive --force dbus
dpkg-reconfigure -f noninteractive --force systemd
dpkg-reconfigure -f noninteractive --force iputils-ping
```
Not sure if that is the best solution, but it is a working solution.
Cheers,
    Matthias

**Comment by adriaandegroot** [comment]
Closing based on IRC comments; in addition, the package module can run this kind of pre- and post-scripts which probably solves the problem? This otherwise seems very close to #610, which is similar in that something-needs-to-be-done-on-a-package-level in the newly-installed system. So let's reconstruct the issue there.

**Comment by agaida** [comment]
and in debian we have such things as pre(inst,rm) and post(inst,rm) so if there is a need to do several things before or after some actions it seems to be a distribution packageing thing.
