### ISSUE TITLE
install latest package updates from archive

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#610]
Jira issue originally created by user jriddell:

a nice feature would be to offer to install the latest updates from the relevant package archive

<Kevin_Kofler> teo-, Riddell: I think installing updates is something we want to add support for to the packages module, for all the supported package managers.
<Kevin_Kofler> It can be done through the package manager's CLI just like the other operations.

**Comment by adriaandegroot** [comment]
The idea would be to check for network connectivity (?), then run an update of some sort. If that fails, I don't think it should abort the installation though -- the system is installed, just not totally updated.

It's straightforward to add a method to the package manager class and add implementations where we have one.

**Comment by kkofler** [comment]
The idea was to first implement the operation in the `packages` module, then offer a distro-independent UI (a checkbox somewhere) to allow the user to run it. The packager would be able to choose:
* whether to show the checkbox at all,
* whether to check or uncheck it by default, and also
* whether to require it to install packages in the `netinstall` module (because installing packages without updating the system first is pretty unreliable on some distributions such as Fedora/Kannolo). If this option is enabled and if the user opts out of updating, the `netinstall` module would just display a message instead of a list of packages, just as in the case where there is no Internet connection

**Comment by adriaandegroot** [comment]
Trying to figure out the configuration space here:

 - disable
 - enabled

times (relevant only if enabled)

 - required for netinstall
 - optional netinstall

times (relevant only if enabled)

 - show in UI
 - don't show in UI (so user has no control over it)

times (only relevant if show-in-UI)

 - ticked by default
 - unticked by default in the UI (this is undesired if it is required-for-netinstall)

**Comment by adriaandegroot** [comment]
The *packages* module has a configuration key *update_system* which seems to do what it wanted.
