### ISSUE TITLE
Warn when unable to set partition flags

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#622]
Jira issue originally created by user paddatrapper:

Flags can be set on a partition, however if these flags are not a valid combination for that partition, it will silently fail and the flags will be unselected if you try manage flags again.

Example:
EFI partition that was set to lba and boot. I tried to set esp without first removing lba. This failed silently. Eventually I just cancelled the install, used gparted to set up my partitions and their flags and installed again.

Expected Behaviour:
Display a dialog to the user warning them that the combination of flags is invalid

**Comment by stikonas** [comment]
These partition flags are a bit of a mess inherited from libparted.

Most of the partition flags are actually not flags but partition type. On MBR, only boot is really a flag. Everything else is really a partition type. And on GPT there isn't even boot. Everything is just partition type (so you can only select one type, it doesn't work like "flags" where you can select a few of them).

I think in the long term it would be best to allow user to choose partition type. But since we can't do this with libparted, we will first need to migrate away from libparted kpmcore backend (sfdisk backend is mostly ready now).
