### ISSUE TITLE
Please install libs out of the standard search path

### ISSUE THREAD

**Issue by agaida** [calamares/calamares#729]
it would ease packaging work a lot. Setting the linux rpath woud be needed.

**Comment by kkofler** [comment]
I don't see the point. I don't have any trouble packaging Calamares as it is now.

**Comment by philmmanjaro** [comment]
@agaida: do you have an example for us?

**Comment by agaida** [comment]
@philmmanjaro: Sure - we have a nice little tool in debian called lintian - and it is nice if lintian don't cry if one test a package with it. If i make a solid calamares package with shared libs included in the default search path lintian cries out loud:
```
evil=' lintian -EvIL +pedantic --show-overrides --no-tag-display-limit *changes'

W: calamares: package-name-doesnt-match-sonames libcalamares3.1.0 libcalamaresui3.1.0
X: calamares: shlib-calls-exit usr/lib/libcalamares.so.3.1.0
X: calamares: shlib-calls-exit usr/lib/libcalamaresui.so.3.1.0
W: calamares: non-dev-pkg-with-shlib-symlink usr/lib/libcalamaresui.so.3.1.0 usr/lib/libcalamaresui.so
W: calamares: non-dev-pkg-with-shlib-symlink usr/lib/libcalamares.so.3.1.0 usr/lib/libcalamares.so
I: calamares: no-symbols-control-file usr/lib/libcalamaresui.so.3.1.0
I: calamares: no-symbols-control-file usr/lib/libcalamares.so.3.1.0
```
X - experimental tag
W - warning
I - info

Ok, one could override these warnings - or make the libs private. I guess one  could do some packaging magic to achive this - and it would be a fine thing because one has not to argue with the debian ftp-masters or mentors who run this test too. And it would be nice to have this upstream.

**Comment by kkofler** [comment]
Or you could actually ship a `calamares-dev` package to allow building out-of-tree modules. (I have a `calamares-devel` package in my Fedora packaging.) That said, last I checked, the `CMakeLists.txt` setup was not installing all headers needed to build all kinds of out-of-tree modules. (IIRC, the `calamaresui` ones were missing.)

**Comment by philmmanjaro** [comment]
@kkofler: so by excluding the following files according to your [spec](http://pkgs.fedoraproject.org/cgit/rpms/calamares.git/tree/calamares.spec?id=ce041cbbabf85dc14c919a1ac70ad89a5f80e94a#n314) you avoid messages like @agaida has on his Debian distribution?

```
%files devel
%{_includedir}/libcalamares/
%{_libdir}/libcalamares.so
%{_libdir}/libcalamaresui.so
%{_libdir}/cmake/Calamares/
```

**Comment by kkofler** [comment]
Yes, this kind of files is what a -devel or -dev package is for.

**Comment by shadeslayer** [comment]
Lintian is a tool that merely suggests fixes. As the maintainer it's up to you to decide whether or not you want to follow the suggestions. There are multiple other packages that have lintian violations but are still in the Debian archive, therefore, you can choose to ignore violations that do not really apply to your package.

I'm not sure if having a separate dev package is a good idea since I'm not aware of whether or not Calamares is supposed to provide a stable public API. That you (want to) have a separate dev package is something that you as the package maintainer decided even though Calamares does not explicitly advertise a consumable public API.

**Comment by agaida** [comment]
@shadeslayer: i read the packaging guidelines and the nm-documents. Beside of that i've maintained one or two packages over the time. But this is not the point. The dev package is a good idea.

To be true about - in siduction i have no ftp-masters and only two supported architectures. It's like Arch Linux, we are more or less our own overlords. For debian and derivatives i see this a little bit different. The maintainer or team need someone to sponsor this (these) packages and have it go through the new queue. And one has to argue about packages that are not lintian clean - or even if  there are overrides in place - has to argue about the (non)sense of these overrides. Thats the only reason for this request: Making the life easy for the maintainer - no matter who it will be, i think @highvoltage is heavy involved in this. So feel free to ignore/close it, but if there is a chance to make this improvement with minimal changes i would suggest to change it that way.

**Comment by shadeslayer** [comment]
@agaida The dev package is a good idea only when Calamares explicitly supports a public API. Otherwise as a distributor you're placing unrealistic expectations on upstream wrt API/ABI compatibility when none is explicitly promised.

**Comment by agaida** [comment]
@shadeslayer - thats why i would like to have the libs private.

**Comment by adriaandegroot** [comment]
There is a very specific reason to have those symlinks: libcalamares is also a Python (extension) module, and the Python code uses "import libcalamares". Without the symlinks, the module is not found. So we "need" the symlinks, since the .so's a created in versioned format.

Taking a step back, though: why are the .so's versioned? There is no intention to let things link to older versions; no actual API or ABI guarantees and I don't think it's a good idea to re-use binary modules from older versions. I don't consider co-installability of Calamares versions a high priority. So another approach would be to install non-versioned .so's; that might get Debian to shut up (and gives us the "one libcalamares.so to rule them all").

**Comment by shadeslayer** [comment]
Since Calamares doesn't gurantee ABI/API stability, that sounds sensible to me.

**Comment by agaida** [comment]
+1

**Comment by adriaandegroot** [comment]
So, some bits and pieces:
 - libcalamares.so and libcalamaresui.so are installed unversioned in 3.2, as discussed above.
 - debian already suppresses the shlib-symlink warnings in Calamares

Calamares as a package could have a -dev package, I don't really care. The existing setup installs CMake and header files and everything all together, and I don't intend to spend time splitting that up. I would accept a PR that adds COMPONENTS to do so, though (as long as the default build still installs everything).
