### ISSUE TITLE
Different frontends?

### ISSUE THREAD

**Issue by polarathene** [calamares/calamares#765]
Hello, I'm not aware of any installers that are similar to the modern kind of style you see when you get a new laptop with Windows OS these days. I created a reddit thread [here](https://www.reddit.com/r/linux/comments/6ne2cc/windows_looking_system_installer/) that has some screenshot links if you're not familiar with what I'm referring to.

[From a brief glance](https://github.com/calamares/calamares/wiki/Design-Notes), Calamares is properly split into backend and frontend? So one could create a frontend similar to the current Windows OS installer instead of CLI or Windowed(live desktop) installers that are usually found with Linux?

I'm not sure what the best way would be to go about creating such a frontend, would fullscreen webview/webapp make sense? Or is GTK/Qt capable of achieving that same flat kiosk experience without windows/borders?

I'm not sure if Calamares is a good choice for this approach, though choosing an existing solution at least for the backend API seems to make sense.

---

When these OEM/preseed/kickstart #762 #508 #291 feature are supported, would a frontend need additional work or does an API to the backend properly control the frontend(eg partitions and timezone already configured, skip those and go to section for username and password input)?

**Comment by kkofler** [comment]
Your Reddit link is dead, it says the post has been removed.

**Comment by polarathene** [comment]
@kkofler Oh, thanks for mentioning that. I got no notification of it being removed, when I look at it, it's still there with no indication that it was removed. Here is the snippet about screenshots:

In case you're not aware of the installer look I was referring to, [here](http://thewirecutter.com/wp-content/uploads/2016/08/windows-setup-lowres-2357.jpg) are [some screenshots](http://thewirecutter.com/wp-content/uploads/2016/08/windows-setup-2280-1200.jpg) that [I found](https://www.liberiangeek.net/wp-content/uploads/2014/10/windows10-installation-3.png) from an [image search](https://www.windowscentral.com/sites/wpcentral.com/files/styles/large/public/field/image/2015/03/Windows-10-New-Install-Screen.jpg?itok=S8ZhOhzu). I understand if it's not your kind of thing, I'm just curious if anyone knows of an installer for Linux with this type of UI/UX or if there are limitations preventing it?

**Comment by adriaandegroot** [comment]
I'm really not sure what this issue is asking about / asking for, so I'm going to close it.

- Radically different UI? Yes, it's possible, although you'd need to replace the calamares UI library, write a new application that calls into the job and view queue mechanisms to use those back-end bits. Some steps have the UI closely tied to the resulting job, which means you might have to re-create some modules. That's pretty much outside the purview of Calamares, though.
- Post-install / first boot setup, for systems that have already been partitioned and installed, so that it is network and user setup that needs to be done without an partition + unsquash step. That's what the OEM mode issues are for. Those are not planned yet, as there are other fish to fry in the coming months (fish that are possibly necessary for OEM mode, anyway)
- Extended user configuration, like IM / social media setup. We're going to be looking into this as a better way to spend the time while the system is unsquashed during installation, but it is neither planned nor visible in GH issues.
- "Flat kiosk experience" is more a style and decoration issue, I think, than anything directly Calamares related -- see also radically different UI, above.
