### ISSUE TITLE
Mismatch between space-required check and installable devices

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#774]
It is possible for the space-required check to pass (e.g. there is 5GB available according to the space-check) while the partitioning page offers no devices to install on. This is confusing, because the user starts into an installation and is then blocked.

**Comment by Kishaihd** [comment]
I'm having this bug too, and it's really frustrating because three different Linux distros use calamares, and my only experience with calamares so far has been that it sucks hard.
It detects that there is enough space for installation, but then before or during running os-prober, it removes my hard drive /dev/sda from the list saying "it's probably a cd".

**Comment by adriaandegroot** [comment]
There are two separate things now in this ticket:
  - mismatch when partitioning isn't going to allow you to proceed because no suitable devices are found, this was fixed with the merge of requirements-checking (partitioning has a requirement that there is at least one device),
  - some users have hard disks that identify as CDs. That's not something we can fix, unless we throw out the "don't suggest installing on read-only media". See also #1105 .. there's someone else who has HDDs that identify as CDs. I don't know what causes that.

So, closing as "the technical bit is resolved with the new requirements-checking".
