### ISSUE TITLE
KDE neon Install Tracking Option

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#783]
Please add a question for the user to choose whether to enable KDE neon install tracking

Currently set in packaging
https://packaging.neon.kde.org/neon/settings.git/tree/debian/neon-settings.postinst?h=Neon/unstable

    MACHINE_ID=`cat /etc/machine-id`
    sed -i "s,URI =.*,URI = http://releases.neon.kde.org/meta-release/${MACHINE_ID}," /etc/update-manager/meta-release
    sed -i "s,URI_LTS =.*,URI_LTS = http://releases.neon.kde.org/meta-release-lts/${MACHINE_ID}," /etc/update-manager/meta-release

Can't be done in finishing step as then the installed disk is unmounted

Text something like:
KDE neon would like to count installs, this sends your machine ID along with daily update checks, do you give us permission to do this? <a href="https://neon.kde.org/install-tracking">More info</a>

**Comment by adriaandegroot** [comment]
There is a branch usertracking which is where we can do some rough UI and functional implementation of this idea.

**Comment by shadeslayer** [comment]
Wouldn't this be a KDE Neon specific module? Perhaps a more generic privacy module could be implemented upstream

**Comment by adriaandegroot** [comment]
As specifically requested by @jriddell, yes. But there are generic tracking levels you can distinguish:
 - install tracking (that distro <foo> has been installed,. possibly with hardware info)
 - machine tracking (letting distro <foo> know that a machine is up -- that's what this Neon thing does)
 - user tracking (whatever kind of opt-in telemetry you want)

What needs to happen to configure the various kinds of telemetry surely depends on the distro in question. But the generic questions can be asked for everyone. Perhaps this should end up being a viewmodule that *just* does the UI bits, dropping data into global config -- then distro's can write their own modules (possibly Python) that do the manipulation on the installed system.

(For install tracking, I envision a configurable URL endpoint, or possibly more than one, that sends a Gamma-Ray chunk somewhere, so that there's a well-documented format with a reference implementation available.)

**Comment by jriddell** [comment]
It may well be useful to make it generic and the only thing the distros need to override are the link to privacy policy and a script that gets run to turn tracking on/off.
