### ISSUE TITLE
Keep Wipes All Data and Destroys The World

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#816]
#### Submission type

  - [X ] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> git build on kde neon 3.1.0+p16.04+git20170907.0545-0

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> 1 partition with everything on it

#### What do you expect to have happen when Calamares installs?

> I marked the partition as keep so I expect it to overwrite system directories /usr, /var, /etc  but keep other ones

#### Describe the issue you encountered

> /home was wiped.  my life is destroyed. 

#### Steps to reproduce the problem

> be born. use calamares. mark / partition as keep. note that life has now ceased.

#### Include the installation.log:

> …

**Comment by adriaandegroot** [comment]
I note that my assumption that @jriddell would write a sensible (or perhaps "non-hyperbolic") bug report, has been proved false. Will need to check the semantics of *Keep* in the installer.

**Comment by abucodonosor** [comment]
@adriaandegroot 

#723 is similar .. Also I guess is about time for #725

**Comment by jriddell** [comment]
> Will need to check the semantics of Keep in the installer. 
Or just change it so it doesn't wipe the disk but rather only wipes /usr /etc etc.  This is what ubiquity does.

**Comment by adriaandegroot** [comment]
* In a VM with 2 disks attached; `/dev/sda` is my development environment, `/dev/sdb` is a second 8GB disk for this test.
* Manually fdisk `/dev/sdb`, add one linux partition, make an ext4 FS on it, create a `home/riddell/valuable` file in that filesystem. Umount the filesystem.
* Choose the disk to install on (in my case, `/dev/sdb`)
* Choose *manual* partitioning, click on `/dev/sdb1` in the list, click *edit*, dialog pops up. Click on *Format*, then *Keep*, (even though the default is *Keep*, let's make sure it has been switched on), pick / as mount point, set flag *boot*. OK.
* Choose *do not install bootloader* from the drop down.
* Click next, do user config, next.
* Summary page says *Manual partitioning* and *Install Generic in /dev/sdb1*. No mention of formatting or erasure. Click next.
* Slideshow comes up; then for me it errors out because my bogus example distro doesn't create a machineid in the target system, but the squashfs is unsquashed, and `home/riddell/valuable` still exists.

I guess this means that it might be a neon-specific, or neon-as-configured thing.

**Comment by adriaandegroot** [comment]
- Created 8GB disk, with 1 partition, Linux
 - Created file /home/riddel/valuable.txt, set user to 1002:1002
 - Downloaded NEON devunstable 1022
 - Booted in VM; used "try without install", checked that disk contained files
 - Started Calamares from the desktop; can't install because 8GB is too small (requires 8GB). Ugh.
 - Edited /etc/calamares/modules/welcome.conf to accept 7GB
 - Double-check, Calamares 3.1.5
 - Next, next, next, in partitioning screen choose "manual partitioning", next
 - Click /dev/sda1, click edit, click format, then keep (double-check!), set mount-point to /, leave all flags unset, ok
 - next, fill in user info, next
 - The partition summary bit says manual partitioning, install neon on ext4 system /dev/sda1, boot loader /dev/sda, next
 - Watch unsquash filesystem take a long time .. start a konsole, see that the interesting file is still there, ..
 - .. the file is still there during the mkinitramfs stage, and after the installer is finished, still there

Try it again, this time without checking format, keep .. to check that the default works as intended. Re-used same username as before, also worked.

The only thing I can think of is that maybe there was a non-standard setup (say, symlinking /home/ to /usr/home)? But I really can't reproduce this or come up with a reason why it didn't keep stuff.

**Comment by jriddell** [comment]
tested now, can't recreate, sorry for the hassle, world is safe
