### ISSUE TITLE
Allow selecting  the FS from GUI

### ISSUE THREAD

**Issue by abucodonosor** [calamares/calamares#847]
#### Submission type

  - [X] Feature Request

Right now we have a static 'defaultFileSystemType: ..' value in packages.conf
and fallback to ext4 in PartitionViewStep.

It would be nice to allow selecting the FS from a defined list from the Partition GUI.
I don't think we should force users to use 'Manual Partitioning' just to select the
some other FS.

So Distributors can have something like this:

```
   supportedFileSystems:
            - FS1
            - FS2
            - FS3
            ....
```

First FS would be default one and the user could switch to any supported 
FS from the partition GUI.

**Comment by adriaandegroot** [comment]
This will probably require changes to the partition "bars view" widget, to allow changing the filesystem. I consider it fairly low-priority: it introduces a fair bit of complexity with -- for me -- no visible benefit to distro's. Sure, it empowers a certain kind of power user who knows and wants to set up something specific, but this leads us straight towards supporting nested plausibly-deniable LUKS volumes, which is something we recently refused under "not a goal with Calamares".

**Comment by abucodonosor** [comment]
Well this is not meant for the poweruser but for normal users,

A poweruser won't care about what defauts are he'll go to manual partitioning anyway.

A normal user may want to use ext4 over btrfs ( as example ) but has no clue how to
use the 'manual partitioning' mode.

**Comment by kkofler** [comment]
A normal user should just use `ext4` and not pick some unreliable file system just because he read the buzzword somewhere. (It follows that the distro default should be sane, defaulting to `btrfs` is a very bad idea.)

**Comment by jayarmstrong** [comment]
@adriaandegroot Yes, there is a gradient of popularity for options. Perhaps you'll allow users to vote on feature requests in some manner? It'd be a shame, IMO, to produce another installer that is as equally limited as the other projects. As for the benefit to distros, I'm here today, choosing my distro based on how well its installer works at solving my needs. I gave up on Maui and Neon because of Calamares bugs. That said, I really want to see Calamares flourish, mature, and deliver a better experience for desktop Linux.

@kkofler "should" and "bad" are your opinions. I don't see why you're bringing those into someone else's feature request.

**Comment by adriaandegroot** [comment]
Reopening since the feature is neither implemented-and-merged, nor rejected. It ties in with #901 a bit. As far as I'm concerned, the tricky bit is getting a nice UI for this (preferably in combination with #848) and getting distro's to configure appropriately. Those that feel that FS selection is overkill, should be able to suppress the UI for it.

**Comment by Chrysostomus** [comment]
Is there progress or decision on this? I would like to use this in Manjaro to be able to have easy btrfs setup option without making it the distro default filesystem.

**Comment by adriaandegroot** [comment]
No progress; it's a feature request that for me is low-priority. However, with a nice design to "force my hand" in terms of UI, it'd be a viable item.

**maybe** it'd be interesting to introduce a list of accepable filesystems in `partition.conf` and then make the default partition conf allow `filesystem: "choice"` as a setting, and you could get a drop-down somewhere in the UI.

I'm not really sure where such a thing would go in the existing widgets UI.

**Comment by Chrysostomus** [comment]
Personally I would like just a tick box for one extra filesystem, like Ubuntu does it with ubiquity and zfs. I would label it "Enable snapshotting" or something like that. I would put it on the same row with encryption. 

Alternatively, it could be done with a drop down menu like the swap is done. In that case I would place it on the same row with swap configuration.

Nothing smarter than that comes to mind fight now. Drop down menu would give much more flexibility, but would also make the interface look more busy and less friendly to new users. I would therefore add only one distro configurable tick box.

**Comment by kkofler** [comment]
I wouldn't know at all what an installer is trying to tell me with an "Enable snapshotting" option. I don't think I would guess that it makes it use a completely different file system with its own advantages and disadvantages, let alone know which file system will be picked in either case.

**Comment by Chrysostomus** [comment]
That is also true and a disadvantage. Ubuntu has label "Erase disk and use zfs". The filesystem names are also not very descriptive for users that don't know them, but at least that would give the correct information to somebody. So "Use {filesystem}" would probably be a better label.

**Comment by adriaandegroot** [comment]
@abucodonosor If you tag things as "hacktoberfest" please also take the time to write out some more detailed plans and instructions for what needs doing and where. Hacktoberfest issues (which we'll re-use for Season of KDE) are generally introductory issues with a bit of hand-holding so that the contributor has a pretty good idea of what the workflow is and what will constitute a "good" submission.

**Comment by Chrysostomus** [comment]
![filesystem_chooser](https://user-images.githubusercontent.com/12002226/100139999-0002f580-2e99-11eb-84b2-dddc3b4b4920.png)
Would this be good design for this filesystem chooser?

**Comment by abucodonosor** [comment]
I think so yes

**Comment by arcolinuxz** [comment]
Nice - me like

**Comment by philmmanjaro** [comment]
See here: https://github.com/calamares/calamares/pull/1667

**Comment by demmm** [comment]
Can this be closed?  It is implemented in Erase disk option (only). Is that sufficient?

**Comment by arcolinuxz** [comment]
can be closed for me
