### ISSUE TITLE
Allow to enable / disable Swap from GUI

### ISSUE THREAD

**Issue by abucodonosor** [calamares/calamares#848]
#### Submission type

  - [x] Feature Request

Swap doesn't make any sense for some setups ( eg: Workstations , Servers with a lot RAM etc)
Also users may want to just use swapfile when they needed or simple they don't want swap.

I think having or not having swap is a user choice and should not be forced by Distributors

**Comment by adriaandegroot** [comment]
In which setups does this apply? Only when selecting *erase*? The defaults are there to set up a machine that most-likely works. Anything that switches off swap is going to have effects on suspend / hibernation, for instance -- documenting that and communicating it to users is going to be tricky.

**Comment by abucodonosor** [comment]
Should apply on !manual partitioning.

We already have  ensureSuspendToDisk and neverCreateSwap ( which set to true ignores
ensureSuspendToDisk). We just need a checkbox to control this from UI.

**Comment by nextgenthemes** [comment]
Yes!

* Swap is not needed for system with large amounts of RAM, that nowadays even includes some laptops
* Its a long known fact that a swap file is not in any way slower then a swap partition (anymore).
* May actually be bad for SSD. Digitalocean VPS have no swap enabled by default on Ubuntu AFAIK, I read a article on there about how to enable it on their VPS that sad its bad for the SSD live-span.
* A swap file is way more flexible then a swap partition. If can easily enabled/disabled/resized afterwards even easier then a partition because its basically just a file, no need to adjust other partitions sizes when resizing swap.
* For encrypted systems there is no additional mumbo jumbo needed for encrypt swap, the swap file can just sit on whatever LUKS partition.

So it may make sense not only to allow to disable swap partition but switch to a optional swap file instead. **In fact I think Ubuntu switched from swap partition to swap file in one of their releases.**

[Also a option to change the size of the swap for the automatic installation would be nice.](https://unix.stackexchange.com/questions/402603/how-to-change-the-swap-partition-size-for-the-automatic-delete-disk-installati)

**Comment by kkofler** [comment]
Swap files do not work for hibernation. They are also not supported on all file systems (the file system must allow allocating a contiguous file and locking it in place).

**Comment by abucodonosor** [comment]
@nextgenthemes you can disable swap in any Dstribution using Calamares by editing 
the ``partition.conf`` and setting ``neverCreateSwap`` from true to false.

Not sure manjaro uses /etc/calamares/modules/.. however easy to figure.. check first
whatever the files exists in /etc/calamares/modules , when not look under /usr/share/calamares/modules/..

Hope that helps you until there may be something to control swap from UI

**Comment by abucodonosor** [comment]
@kkofler yes sure however why would I need swap on my 256GB RAM Workstation ?

An when I need swap for sure not the size calamares will calculate :)

**Comment by geckolinux** [comment]
I personally do find suspend-to-disk useful. But a lot of users don't. For example, [this review](https://youtu.be/VIiAMGslHfE?t=664) of my distro installed with Calamares ended up with a massive 34G swap partition. So the simplest solution to me seems to be a checkbox to enable swap or not with automatic partitioning.

**Comment by abucodonosor** [comment]
@geckolinux 

34GB is nothing .. 

Following setup:

 Workastation with 128GB RAM
 Boot disk a 256GB NVMe
 
With swap && ensureSuspendToDisk enabled , the math ends up in having 
swap partition bigger that rootfs .. which is insane.

**Comment by adriaandegroot** [comment]
Reopening, since the feature-request is neither implemented-and-merged, nor rejected. It also ties in with #901, partitioning profiles. Right now, we have the following situation:
 - distro's can enable/disable swap and if enabled, it tunes either for regular use (half-of-memory) or for hibernate (110% of memory).

What is wanted / needed is more tuning possibilities:
 - limiting to some percentage of disk, or some maximum size
 - user control **without** going full-manual partitioning, for large-memory systems

As far as I'm concerned that's still on the table, waiting for a design and/or a PR to show up (or for me to get around to it, but like I said, low-priority for me).

**Comment by adriaandegroot** [comment]
A related change was added in 8ed26e537f73959e295e82b4cc51540478393204 , because the calculated swap size was not limited by the disk size. The regular-use case (e.g. without ensuresuspendtodisk) should top out at 8GiB with up to 16GiB of memory, and then drop to 4GiB for more memory.
