### ISSUE TITLE
eufi partition issue

### ISSUE THREAD

**Issue by joksik** [calamares/calamares#856]
Something's not right when we want install manjaro 17.0.6 with f2fs filesystem so reading arch wiki and testing under clean arch and even gentoo the /boot partition can be used for eufi too and we dont need create /boot/efi and /boot we can create one partition /boot but with esp flag and fat32

https://wiki.archlinux.org/index.php/Talk:EFISTUB#ESP_mount_points
and
quotation from https://wiki.archlinux.org/index.php/EFI_System_Partition
For sake of simplicity, you can also use the ESP as the /boot partition itself instead of a separate /boot partition, for EFISTUB booting. In other words, after creating and formatting the EFI System Partition as instructed above, simply mount it at /boot. 

so in calamres i create 2 partition:

- /boot with fat32 for eufi and two flags boot for grub boot loader and esp for uefi
- / f2fs

and calameres dont detect that i create already esp partition and in next step warning me that i need /boot/efi but this is a litte bug. the bigger bug is that when i reboot my computer manjaro dont boot :/ i read manjaro board i see that not only i have this bug with manjaro installer when we use only /boot with esp and f2fs

https://forum.manjaro.org/t/installing-manjaro-with-f2fs-on-root-partition/32315

so i dont know why but manjaro calmares need to create 3 partition

- /boot with ext4 and boot flag
- /boot/efi fat32 with esp flag for uefi
- / f2fs

after this when i reboot my laptop manjaro works but on small ssd disc like me 120gb i dont want create 3 partition and lost 512 mb free space for one partition /boot/efi that i dont need so please fix this bug ;)

**Comment by abucodonosor** [comment]
@joksik what Wiki's are telling you doesn't matter much. What matters for you is
how your Distribution set up Calamares. And so far I see manjaro need /boot/efi at least
is what the partition.conf have in it. @philmmanjaro right ?

The warning you see is bc your Distributor sets efiSystemPartition to '/boot/efi' , there is
nothing to fix.

That said when you do manual partitioning you are on your own .. you should know what
your Distribution supports and what not.

**Comment by philmmanjaro** [comment]
I didn't test it yet with **f2fs**, however we need at least a **fat32** partition as **/boot/efi** for UEFI.

**Comment by kkofler** [comment]
Reusing `/boot` as the EFI system partition is not really a supported setup, as it cannot be made to work in all situations (especially multiboot ones). The idea is, `/boot/efi` is a unique (per disk or even per system) partition that can support multiple operating systems, `/boot` is the distribution(that you are about to install)'s boot partition that is not shared with the other operating systems.

**Comment by abucodonosor** [comment]
@philmmanjaro can you take care of this one ? you should know 
best what you support and what not..

**Comment by philmmanjaro** [comment]
Well, we go with the standard:

* option A
  * root (includes /boot folder)
  * /boot/efi

* option B
  * root
  * /boot
  * /boot/efi

**Comment by joksik** [comment]
ok i understand in that case if it was a targeted aim i should not suggest that under pure arch we dont need /boot/efi so if this was not installer bug you can close this issue

**Comment by blackcrack** [comment]
@adriaandegroot 
Hi,
sorry if i post again on a closed issue (i don't know if interesting for a new issue), 
but i have installed at last OMLx and i have on one Win7 + EUfi \*g\* 
and on the other harddisk OMLX 3 Partitions, the middle of it a swap, 
would nice if the able to choose the harddisk where it is install grub2 in any case ,
because i have the eurofi in front of Win7 and the bios want boot win7, but
if i use F12 to become the harddisk-bootmanager of the bios, can i use the 2nd
harddisk.
sda1boot sda2(?) sda3Win7,
sdb1omlx,sdb2swap,sdb3cooker
sdc1-1tb-data-ntfs
Now it is so, if i am want install, found Calamares the UEFI and want Calamares now an efi partition and i can not choose the 2nd Harddisk as Grub2-install so the sdb1 or sdb3(ssd) because on sda1 is uefi on it.. :\ only if i disconnect the sda1(ssd) then can i am choose an harddisk.. and this is crap imho, because if some one install a System, should it able to choose efi or plain grub2 on the first harddisk or on the 2nd harddisk grub2 install.
you see what i meant ?
Because the UEFI Partition from Windows fount  the Bios every the f-beep- uefi-partition
and marked as uefi Computer, Calamares use this marked like i think and it is impossible for choose an other harddisk to install a plain grub2 for booting on sdb1 (and not sda1) .. or it is on top wrong translated in german ? Because grubinstall ? on top the 2 screen before partitioning and on partitioning ?

best regards
Blacky

**Comment by abucodonosor** [comment]
@blackcrack I don't really understand what you are saying , sorry 

OMLx = openmandriva ?

You want install 'plain BIOS grub' while booting in UEFI ?

**Comment by blackcrack** [comment]
OpenMandriva, yep :)

on the 1st harddisk it is a Win7 with UEfi and the bios use the uefi at this moment as default,
at the 2nd disk it is openmandriva, but there want i am install grub2, but it have works not, because
Calamares found the uefi and whant install a uefipartition or other say, the Calamares told me, he whant have a /boot/uefi and no change what possible (the bios had recognized the uefi partition and have setting up the uefi boot :\ )

where i disconnected the first sda1 had it works with install a plain /normal grub2 for 
openmandriva on sdb2 ..

hmmm :\ where was connected the uefi partition 
i could not select another boot medium ..
can it be ? 

best regards
Blacky

**Comment by abucodonosor** [comment]
@blackcrack  ``/boot/ef`` is a Distribution configuration option.

**Comment by blackcrack** [comment]
@abucodonosor 
:\ but i had no possible to change it so far the sda1 it is connected.. 
or something fits in the translation not.. and i have something oversee ..
"select the bootdisk for install the bootmanager .." and this in german..
hmm.. calamares becomes every more complex .... 
well.. the bad, i have it already installed.. 
and i want not play around again ..
the time will come if i must install it again..
and this in deadly safety !  \*g\*
but so far.. thank you very much for your effort :)

best regards
Blacky
