### ISSUE TITLE
systemv support/openrc support request

### ISSUE THREAD

**Issue by FrostKnight** [calamares/calamares#867]
There are some arch based distros such as parabola, hyperbola and artix
that would love it, if you would make openrc and sysvinit support
available to your calamares installer.  Even if the support is limited,
it would be nice to make that option open.

I bet even antix or devuan would like this.

I just thought I would ask. That's all.

**Comment by adriaandegroot** [comment]
Can you describe, what would actually be needed for them (those distro's, using sysv init)? While there's some systemd-specific code in Calamares (e.g. the systemd-services module, and it looks like machineid and timezonesetting, maybe), it is either configurable (e.g. the shutdown command) or optional (services configuration).

A better issue would be "I'm trying to use Calamares for <foo-distro> which uses SysV init, and can't do <bar> because <reason>." That's something I can help with.

**Comment by FrostKnight** [comment]
I wouldn't really know how to fully explain it, I know some people who are considering contacting you about this, if you would like, I can email you their name.  If not, within a few days at least I recommend you closing this. Also: I found out recently that hyperbola has this covered. Parabola and atrix are I think a different story.

**Comment by adriaandegroot** [comment]
OK. In any case: there's no special reason I know of why Calamares can't support SysV init (or openrc for that matter). Anything that Calamares does that requires systemd is basically a bug, so do report them. The best way to get in contact is through the GitHub issues, or IRC, If need be, you can mail me directly but that is far more likely to be overlooked than an issue filed here.

**Comment by abucodonosor** [comment]
well the request is somewhat wrong since the inits are supported .. should be:

"Do not assume everyone is using systemd" :)

Hoever in some places we still 'assume' yay systemd which would be right now:

LocalePage.cpp
SetTimezoneJob.cpp
and the whole services modules

For servises one is easy git mv services systemd-services almost 
and change the documatiation. Then openrc/sysV/finit/runit etc can submit
an sinit-services module. Mixing these wold not be a very good ide I think.

( almost nothing to do with that but while @ it networkgfg is about NM only )

Also for Locale we could use the symlink methode I think.

**Comment by philmmanjaro** [comment]
There is a [fork of Artix](https://github.com/artix-linux/calamares) which is designed to work on **openrc**.

**Comment by abucodonosor** [comment]
So solved for Artix :-)

**Comment by adriaandegroot** [comment]
So, I'm going to close this one. We've had some people w/ openrc on IRC, the idea is clear:
-  If there is a need for openrc services configuration, then that can be done in a services-openrc module.
- If some existing code requires systemd, that can be reported as a bug.

As for the list that @abucodonosor mentions above:

 - LocalePage.cpp uses `timedatectl` to immediately set the timezone in the live system when a location is picked. Without that executable, the desktop local time isn't updated when you pick a location. I don't know how to immediately update the local time zone otherwise. Note that the code that sets up the locale in the target system, has a fallback to symlinking the right bits, so non-systemd systems are missing (at most) instant-updates of the local timezone during installation.
 - SetTimeZoneJob.cpp see above -- it has a fallback.
 - Services module can remain; it configures systemd services.

If there are specifics, please file individual issues for them.
