### ISSUE TITLE
[Feature Request] Configure kdesurc depending on setRootPassword

### ISSUE THREAD

**Issue by llelectronics** [calamares/calamares#895]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

#### What do you expect to have happen when Calamares installs?

Depending on if setRootPassword is set in users.conf it should configure kdesurc in /etc/xdg/kdesurc to make sure the correct method su or sudo is used

**Comment by abucodonosor** [comment]
I don't think so ..  how about gksu ? xdg-su  whatever other wrappers ? 

Is up2 your distro to provide 'right' wrappers to start calamares and not
up2 calamares to workaround your Distribution issues.

**Comment by adriaandegroot** [comment]
@abucodonosor I specifically asked @llelectronics to file this **here**. It can be phrased more generally: "*Depending on settings made on the user page, I want to run one script, or another. How can I do that?*"

Well, there's two parts to that:
 - are the settings from the user page available in globalSettings? If not, can they be added there, or can they be inferred from something else in the target system?
 - if the setting can be discovered, **then** it's up to the distro to execute a (distro-specific) script to do the actual setup. Up until recently, you'd write a python jobmodule to do the work, since that has the capability to branch based on the value of a global setting. Now, you may be able to use the contextualprocess to do the same.

Issue is here so that (1) I check if the necessary globalSettings are actually stored and (2) to check that the contextualProcess module can distinguish them correctly.

**Comment by abucodonosor** [comment]
@adriaandegroot 

as long calamares itself doesn't provide any kind support for kdesu,gksu etc
all this is up2 the Distro setting up the 'wrapper' to start calamares.

Even we setup /etc/whatever_files , in this example su or sudo for 'kdesu'
*if* sudo isn't set correcly we still end up on being broken no matter we set it up in
that file or not. ( eg: sudo -E .. etc just won't work )

ofc we can add some 'calamares_su' and hook it up in the globalSettings ,
 or something in 3.2++ and set it to pkexec , but we should not start adding $foo_su implematations files but let Distros use the scripting and  contextual to set up things
for the giving implemenation they use since they know best how the installation
ISO's they provide works best. EG: someone with plasma may want kdesu while Gnome 
/ Gnome derivates may want gksu or maybe noone of these but xdg-su or even
the systemd su impelmetation or maybe something different.. 

We should not start guessing all these and start adding random files.

**Comment by adriaandegroot** [comment]
@llelectronics the value of **setRootPassword** in `users.conf` is under the control of the distro. Nothing changes that value. If you have something (a script, probably, or some application that can write kdesu configuration) that can configure kdesu appropriately, then:

 - use the shellprocess module (an instance) to run appropriate commands 
    ````
instances:
    - id: kdesu
      module: shellprocess
      config: shellprocess_kdesu.conf
```
 - create a new module, with job type process, and configure that to run the appropriate commands
 - since the value of **setRootPassword** is constant, just configure the target image correctly in the first place

.. this makes me think you actually mean something else, and that you want to depend on the value of the checkbox **Use the same password for the administrator account**. Please confirm.

(and then, *if* that is what you want, we can check if the contextualprocess module is strong enough to support that use-case)

**Comment by adriaandegroot** [comment]
@llelectronics FWIW, contextualprocess can handle true / false, so a configuration based on **setRootPassword** is 
```
setRootPassword:
    true:    "/bin/configurethething --thevaluewas=true"
    false:   "/bin/configurethething --thevaluewas=false"
```

**Comment by llelectronics** [comment]
> his makes me think you actually mean something else, and that you want to depend on the value of the checkbox Use the same password for the administrator account. Please confirm.

Yes this is exactly what I meant.
