### ISSUE TITLE
[Feature Request] FS/Partition layout profiles?

### ISSUE THREAD

**Issue by polarathene** [calamares/calamares#901]
I quite like the default one that openSUSE offers with their installer. BTRFS for the system with a rather thought out subvolume layout and XFS for `/home`. Going with the default offering also sets up Snapper integration which was another perk.

It'd be nice if Calamares could have similar "presets" or suggested layout configurations. The distro maintainer could offer these(or just a default one) as a profile, or a user could import/export a layout via Calamares to use with the installer in future installations.

---

I'm not sure what the current situation is for silent/unattended installations, being able to provide profiles for that use-case would also be nice, with constraints like min/max partition size and a % value.

**Comment by abucodonosor** [comment]
dupe #725

**Comment by abucodonosor** [comment]
also #525

**Comment by polarathene** [comment]
@abucodonosor ? How is this a dupe of #725? That issue requests `/home` to be included in an auto partitioner.

Have I misunderstood and missed something about Calamares that allows a user or distro maintainer to have Calamares use or default to a custom partition scheme/layout? Are you familiar with the openSUSE installer and how it presents a rather advanced partition layout of BTRFS with many subvolumes and settings along with the XFS /home?

2ndly does Calamares presently support unattended/silent installs that can define said layouts to use arbitary sizes with min/max constraints and % values instead of only absolute?

#525 for Snapper mention is fine. But I disagree that this issue is a dupe of #725, it's a far more involved request.

**Comment by polarathene** [comment]
I understand if the feature requested however is not something Calamares plans to support. Perhaps it is something that a third party can contribute as a module(assuming that's possible), if so and that doesn't warrant keeping this issue open for visibility, that's fine.

**Comment by abucodonosor** [comment]
@polarathene 

#725 tells about /home only but is about having some sort layout/schemas.

right now only BTRFS does /home  .. also see #815 , #807 , #586

**Comment by polarathene** [comment]
None of the linked issues are related to what this one requests.

I kind of get where you're coming from with #725, as it mentions to add it as a possibility/option. It is rather specific though where as this issue asks for generic partition layout/schema support with import/export(#725 does not mention anything like that, closing this issue therefore will ignore such a request?)

None of the linked issues refer to the request for min/max/% support for said FS/partition presets when doing unattended/silent installs. Closing this issue also buries that request(should I create a separate request for it?)

From the linked issues I am of the understanding that BTRFS support isn't too good/flexible with Calamares right now(I haven't personally tried it yet). It's not clear how much that will improve since the contributors for Calamares are insisting that any FS options be as generic as possible, for some reason whatever dropdowns/flags cannot be filtered lists based on the partition FS type?

**Comment by adriaandegroot** [comment]
Reopening as "interesting feature request". The "auto partitioner" of Calamares applies a single, hardcoded scheme to the disk: / and /home . It would be interesting to have that defined through a JSON document, which basically subsumes settings in the partition module like *defaultFileSystemType*. Getting it right, in the different use cases (new system, existing system; replace alongside or manual), will probably be tricky, which is why I'd love to go over this with a designer and a filesystem person as part of the design (see also all the LVM issues: there's some serious work figuring out what-do-we-actually-want before coding starts).

**Comment by a-wai** [comment]
Hi,

I'm interested in this feature and might be able to implement it. Just to make sure I'm getting things right, here's what I have in mind for a first version:

- add this feature to the existing `partition` module
- use the `partition.conf` file to store a partition scheme
- partition entries would be declared the same way [debos](https://github.com/go-debos/debos) does, ie a list where each entry is a partition and has the following fields: `name`, `filesystem`, `mountPoint`, `start` & `end` (expressed as a fixed size or a % of the available disk space)
- the partition scheme would be applied to the whole disk, erasing any existing data (remember I'm considering a 1st version here)

Once this is working & merged, I could iterate more and add the following features:

- give the user the choice to use only the unused disk space (and use the manual partitioner to make room on the disk if necessary)
- support LVM & encrypted volumes
- allow the selection between several partition schemes

Please let me know if this would be alright or if I'm missing anything, any comment will be appreciated.

**Comment by polarathene** [comment]
> the partition scheme would be applied to the whole disk, erasing any existing data

Just to clarify the partition layout/profile would be presented like existing default layout/scheme is to the user for confirmation?

Being able to modify it after switching to it is also nice. openSUSE can provide a nice BTRFS default(with additional integration of Snapper or Transactional RO root) with XFS for /home, which you can then tweak to preference afterwards.

**Comment by a-wai** [comment]
> Just to clarify the partition layout/profile would be presented like existing default layout/scheme is to the user for confirmation?

Absolutely, this will still be visible to the user, so that he can decide whether to proceed with this or not.
I have a [working PoC](https://github.com/a-wai/calamares/tree/partlayout-poc) if you want to check it out. In this code, the layout is only applied when selecting "Erase disk" in the partition screen.
(CAUTION: this is only a quick & dirty hack I did to understand the way things work and how this could be implemented, it hasn't been thoroughly tested and might break things, and of course, it needs to be fully & properly rewritten for better code quality)

> Being able to modify it after switching to it is also nice. openSUSE can provide a nice BTRFS default(with additional integration of Snapper or Transactional RO root) with XFS for /home, which you can then tweak to preference afterwards.

That would be a nice addition yes, but not for the 1st version, as it would require chaining the "Erase" case with the "Manual partitioning" case, which will likely need huge modifications to the module.

**Comment by abucodonosor** [comment]
Closing, https://github.com/calamares/calamares/pull/1068
