### ISSUE TITLE
The installer slideshow should have forward and back buttons

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#904]
#### Submission type

Feature Request

--------
If there is more than one slide, a forward and back arrow should be displayed, similar to Ubiquity.

**Comment by adriaandegroot** [comment]
The slideshow should do that itself, if it needs them (I'd be open to a pull request adding a file which implements them in the example QML). As far as Calamares is concerned, the "slideshow" is a QML widget that gets a "next" signal every 5 seconds, but there's no other tooling that knows that it's a slideshow in QML that needs such arrows.

Note that the example slideshow does support left- and right- arrow keys.

(And you can use Same Game as the slideshow, where arrows wouldn't make any sense at all since it's a time-wasting game to play during install)

**Comment by demmm** [comment]
An example how you can tell your users to move forward or backward in the slideshow:
https://github.com/KaOSx/calamares/blob/master/src/branding/kaos_branding/show.qml#L47
