### ISSUE TITLE
Please consider making Calamares reproducible

### ISSUE THREAD

**Issue by highvoltage** [calamares/calamares#917]
In the Debian project, we aim to make all our builds reproducible so that users can trust that the binaries they use were built from the source that we make available to them.

For more information about reproducible builds, please refer to: https://reproducible-builds.org/

For more debian-specific information: https://wiki.debian.org/ReproducibleBuilds

Unfortunately, Calamares is not currently reproducible.

Details on unreproducibility for current calamares builds:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/calamares.html

It seems related to build-ids. I'm not sure what the best approach is to solving this, but feedback or investigation by the Calamares team would be great. I'm the maintainer for Calamares in Debian, so feel free to also contact me (highvoltage) on #calamares on freenode.

**Comment by kkofler** [comment]
If the build-id is the only thing changing between build attempts, are you sure that this is an upstream issue?

**Comment by adriaandegroot** [comment]
"Use Clang" and "don't expect debug builds to be reproducible" are my two semi-snarky responses.

See https://tests.reproducible-builds.org/debian/issues/unstable/build_id_differences_only_issue.html .. that seems to be a suitable flag to add to Calamares, but the whole reproducible builds site is really thin on information on fixing the problem (to me it looks like the build id changes randomly, and i have no idea if that's because the inputs are changing or because gcc is stupid).

**Comment by adriaandegroot** [comment]
fwiw,

```
make clean ; make -j4 > /dev/null 2>&1 ; readelf --wide --notes calamares
```

outputs a different build ID each time, in spite of the source being identical. (On a Manjaro / Arch installation)

**Comment by adriaandegroot** [comment]
The object files generated from the C++ code generated by qrc differ; that's because the C++ code differs (in one test just now, a later build has 1 byte more C++ source than an earlier one), in lines that *look* like they might be timestamps. It's hard to tell because of the hex-encoding.

**Comment by adriaandegroot** [comment]
.. at which point you end up with https://tests.reproducible-builds.org/debian/issues/unstable/timestamps_in_source_generated_by_rcc_issue.html
