### ISSUE TITLE
dynamic l10n package listing

### ISSUE THREAD

**Issue by hsitter** [calamares/calamares#924]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

Somewhat related to #923

Currently, when wanting to localize a system you need to semi-hardcode a list of localization-relevant packages in packages.conf. Being hardcoded this is somewhat of a maintenance drag. Namely: if the user switches the language after installation you need to know which localization packages to install on-demand then, so distros have to have a record of fairly dynamic localization mapping outside calamares already. To that end the hardcoded packages in packages.conf can easily go out of date (missing stuff, or installing excess stuff as their app packages get dropped from the installation medium) AND they are ultimately repetitive information from this on-demand information that already exists elsewhere.

To that end I would like to suggest a new system where localization packages are generated by a helper program rather than hardcoded in a conf.

The helper would (maybe?) be run inside the chroot and take a single argument, the posix locale. Additional arguments ought to be ignored in case calamares grows an input-method configuration system which would be passed as an additional argument I suppose. It outputs the packages to install to localize the chroot. Calamares handles the actual installation of the package list.

Internally the helper would be listing all packages installed in the chroot, then map them to l10n package names and applying locale transformation as described in #923 

- exec /bin/helper ca@valencia
- read stdout
- split by `\n`
- install list of packages

The end result is that a distro can programmatically determine which l10n packages need installing based on which software is actually on the system, and at the same time make sure the LOCALE is transformed to whatever format it needs to build the package name.

Conceivably this could somehow be part of the packages module, but I am thinking a separate module might be nicer to use. To be clear: the helper would need writing by the distros themselves. What I am suggesting is the framework around it.

**Comment by demmm** [comment]
In case useful, here is a python module that does part of what is described above, Iterates over every found pkg and put each one in a list, then sets a list of locale packages not used by target system locale (I know not usable in the state, since it relies on a specific package manager, but thought it might be helpful to put this example here):
https://github.com/KaOSx/calamares/blob/master/src/modules/package_removal/main.py#L92

**Comment by adriaandegroot** [comment]
(*Mostly off-topic comments about that KaOS module, @demmm *)

That Python module is interesting (-ish) in how it kind of duplicates a bunch of functionality. Ideally, package removal should be something that the package module can do as **well** as installation. That would make some of this additional package-managery stuff unnecessary.

Using print() in a Calamares Python module is a bit  weird. The user isn't going to see it, and it doesn't get logged properly either.

Are you sure all your locales are 2-characters?

**Comment by adriaandegroot** [comment]
@apachelogger There is a precedent here, which is the netinstall module. It inserts entries into globalstorage, and the package module has logic to pull entries out of that globalstorage **besides** its own configuration. So a module such as proposed here, could use the same mechanism of injecting entries into globalstorage, and things would "magically" work.

It does suggest that there should be an API for handling package injection in Calamares core, rather than something that is just conventional between different modules.
