### ISSUE TITLE
Add support for other geoip providers (xml/json)

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#932]
#### Submission type

  - [ ] Bug report
  - [X] Feature Request

Since the API from freegeoip.net is depreciated by June 2018 we may think about http://ip-api.com support. It also support [**json** and **xml** format](http://ip-api.com/docs/). Only difference is, it uses for json/xml **timezone** instead of **time_zone** and **TimeZone** as freegeoip.net uses. A solution would be to make the search pattern adjustable via `locale.conf`.

**Comment by philmmanjaro** [comment]
Current service, which will end by June 2018:

- http://freegeoip.net/json/ will return `"time_zone":"Europe/Berlin"`

Here some other services we also need some adjustments:

- http://geoip.nekudo.com/api/ will return `time_zone":"Europe\/Berlin"` (The API follows a fair use policy. There are no limits by default but if the service is abused your IP may get blocked.)
- https://ipapi.co/json will return `"timezone": "Europe/Berlin"` (1000 requests per day from same IP)
- http://ip-api.com/json will return `"timezone": "Europe/Berlin"` (system will automatically ban any IP addresses doing over 150 requests per minute)

Services, which work without any adjustment:

- https://geoip.tools/v1/json will return `time_zone":"Europe/Berlin"` (120 requests per minute. Once reached subsequent requests will result in error 503 until your quota is cleared)

**Comment by abucodonosor** [comment]
@philmmanjaro 

you can look at my old patch  I guess you'll need adjust ..  I changed the tzName to tzString 
later .. but since no-one wanted that I dropped it , just found a old cala-git in my backup :-)


http://ftp.frugalware.org/pub/other/people/crazy/51500382cf1225e8648169340e960df7dd9086fc.patch

**Comment by philmmanjaro** [comment]
@abucodonosor: maybe push it as a new PR for this matter. Was it a PR already?

**Comment by philmmanjaro** [comment]
.. also we should find a way to parse also `\/` from `time_zone":"Europe\/Berlin"`

**Comment by abucodonosor** [comment]
@philmmanjaro 

No PR just discuss on IRC.

I really don't have any time now to look at this stuff , however feel free to reuse code
and open some PR yourself.

To remove chars you don't want in a string use QRegularExpression ?

or something like:

```

QString cleanup(QString str)
{
    str.remove("\");
    str.remove("/");
    str = str.trimmed();
    return str;
}  

```

**Comment by philmmanjaro** [comment]
OK, however seems I miss a link to transfer the string value to the handler. Additionally to my first attempt I added these following commits: https://github.com/manjaro/calamares/commit/758fedcb54f838c8785498923617763fe9385159, https://github.com/manjaro/calamares/commit/e4bc2bcb67053b223b18e3ce6f12ed9ab9b8f3a7. However I still have not yet declared the new string value and therefore the build fails:

```
[ 71%] Building CXX object src/modules/locale/CMakeFiles/geoiptest.dir/GeoIPXML.cpp.o
/src/src/modules/locale/GeoIPJSON.cpp: In member function 'virtual GeoIP::RegionZonePair JSONGeoIP::processReply(const QByteArray&)':
/src/src/modules/locale/GeoIPJSON.cpp:43:32: error: 'm_geoipTzJson' was not declared in this scope
             if ( map.contains( m_geoipTzJson ) &&
                                ^
make[2]: *** [src/modules/locale/CMakeFiles/geoiptest.dir/GeoIPJSON.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/modules/locale/CMakeFiles/geoiptest.dir/build.make:110: recipe for target 'src/modules/locale/CMakeFiles/geoiptest.dir/GeoIPJSON.cpp.o' failed
/src/src/modules/locale/GeoIPXML.cpp: In member function 'virtual GeoIP::RegionZonePair XMLGeoIP::processReply(const QByteArray&)':
/src/src/modules/locale/GeoIPXML.cpp:36:56: error: 'm_geoipTzXml' was not declared in this scope
         const auto tzElements = doc.elementsByTagName( m_geoipTzXml );
                                                        ^
src/modules/locale/CMakeFiles/geoiptest.dir/build.make:134: recipe for target 'src/modules/locale/CMakeFiles/geoiptest.dir/GeoIPXML.cpp.o' failed
make[2]: *** [src/modules/locale/CMakeFiles/geoiptest.dir/GeoIPXML.cpp.o] Error 1
CMakeFiles/Makefile2:1338: recipe for target 'src/modules/locale/CMakeFiles/geoiptest.dir/all' failed
Makefile:138: recipe for target 'all' failed
make[1]: *** [src/modules/locale/CMakeFiles/geoiptest.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by guinux** [comment]
You just forgot the quotes in the strings, it should be 
`map.contains( "m_geoipTzJson" )`  and `doc.elementsByTagName( "m_geoipTzXml" )`
and not 
`map.contains( m_geoipTzJson )`  and `doc.elementsByTagName( m_geoipTzXml )`

**Comment by philmmanjaro** [comment]
@guinux: I don't think so, as it is not a string. See here the snippet:

```
@@ -128,14 +128,14 @@ LocaleViewStep::fetchGeoIpTimezone()
                     var.type() == QVariant::Map )
                 {
                     QVariantMap map = var.toMap();
-                    if ( map.contains( "time_zone" ) &&
-                        !map.value( "time_zone" ).toString().isEmpty() )
+                    if ( map.contains( m_geoipTzName ) &&
+                        !map.value( m_geoipTzName ).toString().isEmpty() )
                     {
-                        QString timezoneString = map.value( "time_zone" ).toString();
+                        QString timezoneString = map.value( m_geoipTzName ).toString();
                         QStringList tzParts = timezoneString.split( '/', QString::SkipEmptyParts );
                         if ( tzParts.size() >= 2 )
                         {
-                            cDebug() << "GeoIP reporting" << timezoneString;
+                            cDebug() << "LocaleViewStep: GeoIP is working. Got TimeZone: " << timezoneString;
                             QString region = tzParts.takeFirst();
                             QString zone = tzParts.join( '/' );
                             m_startingTimezone = qMakePair( region, zone );
```
It get defined here:

```
@@ -293,4 +293,16 @@ LocaleViewStep::setConfigurationMap( const QVariantMap& configurationMap )
     {
         m_geoipUrl = configurationMap.value( "geoipUrl" ).toString();
     }
+
+   if ( configurationMap.contains( "geoipTzName" ) &&
+        configurationMap.value( "geoipTzName" ).type() == QVariant::String &&
+        !configurationMap.value( "geoipTzName" ).toString().isEmpty() )
+   {
+       m_geoipTzName = configurationMap.value( "geoipTzName" ).toString();
+   }
+   else
+   {
+       // defaults to freegeoip.net
+       m_geoipTzName = QStringLiteral( "time_zone" );
+   }
 }
```

The old patch was for one file. Now we have several cpp and h files. The element is defined in a config file.

**Comment by abucodonosor** [comment]
@philmmanjaro 

Well the error is clear ? Look at these geoip header files :) , your are missing
the members in the struct.

Not sure why you are changing the include files .. everything can stay as is.
What do you want is 'time_zone' and friends to be set from the configuration
file too. How the files are now called does not matter , really.

@adriaandegroot 

While now more flexible the initial problem still remains.
We still hardcode this values to an service is gone soon.

And while all these GeoIP providers doesn't seem to agree on any kind API
next one may have a string of ' foo ' or whatever they wish for the timezone
string.

So what is our reason to hardcode these ? .. I mean we can hardcode some default
fallback but basically allow any kind string for these , with possible exmaples
in our configuration file.

eg: 
geoipTzString: blubb
geoipUrl: blubb.com

Now if users/Distros want bluub.com , which may have bluub as 'time_zone' string
there we go , use that without the need to patch the code ..

So why not doing that once right and don't really care anymore , since then 
it does not matter how the strings are called , all can be set from .conf ?

**Comment by adriaandegroot** [comment]
[ ] Allow different selector strings (e.g. some services use *time_zone*, some *timezone*). That's done in master -- needed to get the config value (and document how it works) and massage GeoIP and derived classes to take the config value in their constructor, to use when interpreting data.
 [ ] Allow multi-level selection in the JSON handler. (e.g. set the selector string to *location.time_zone*). This is needed for some of the examples @philmmanjaro  provides, since they have nested JSON instead of just top-level.

**Comment by adriaandegroot** [comment]
@abucodonosor Thanks for nudging

Originally I was thinking of using *geoipStyle* to do all of the work in picking variants (JSON variations like you can see in @philmmanjaro 's list, or in XML format), but you're right that having a configuration variable lets us write less code, with more flexibility (in particular when a new scheme shows up).

In master, the GeoIP handlers now can grok *geoipUrl*, *geoipStyle* and *geoipSelector* so that all of the examples Phil provides can be configured. There's a test that tries to HTTP GET each of them (plus a few more I know about) and compares the results.

Unless there's more specifically related to getting the time zone out of GeoIP data, I'm going to close this one; I think we could get more out of the geoIP data (like language data, best-guesses for language, that kind of thing) but that's worth a different issue with some planning first.
