### ISSUE TITLE
Calamares should be able to do a minimal install

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#956]
Calamares should be able to do a minimal install, similar to how Ubuntu does it with Ubiquity.

How it is done right now with Ubiquity is that a specific list of packages is in the seed, and should a checkbox be clicked, that list of packages is removed from the copied squashfs. Canonical Foundations is implementing stacked squashfses in the near future to handle this.

How can we work to do this in Calamares?

**Comment by adriaandegroot** [comment]
>  similar to how Ubuntu does it with Ubiquity.

 - Calamares supports the opposite approach, **adding** packages to the installed system. The netinstall module can be used for that. You can use a local package repository and local netinstall config file, for instance, and allow groups to be defined.
 - Calamares supports multiple filesystem images in the unsquashfs module. There is no mechanism, though, for contextually installing them. That might be something to introduce more generally in Cala, inspired by the way contextualprocess works. Then you could say "unpack this FS if global config **want_krita** is set".

**Comment by blshkv** [comment]
I'm second for this request. For example, a single ```interactiveterminal``` module requires the entire KDE to be build. Please make all modules optional if possible. An installer should not use X packages and should not require ```konsole``` to be present in the system. First of all, this is too heavy, secondly, it glues it to a KDE, i.e. a distro won't be able to use this installer if they provide multiple WM (which all major distros do).

**Comment by philmmanjaro** [comment]
@blshkv Calamares is more or less a KDE friendly project. It has, however focus on QT.

**Comment by blackcrack** [comment]
focus can be on QT, why not, but if it's make able to install
an prompt/server related  environment it's also nothing wrong.
Why ever a "must be a QT and Surface" related Surface
have the KDE/QT the © and TM of the Surface have to be ?!

simethnig make ever bigger and bigger, why not support a slim system design,
why not support task- releated installer and
why the hack not support a prompt only install like @tsimonq2 told ?
many users have the wish to have something without an specific Surface 
install.. prompt only, it is ever shooting up by users where meant "it mus be this or the other one, but kant be something.. i be about really angry because they dump (not bad meant, more "unknowing") users it is not clear, they are make a bad thing to and meant they mus ever setting up theyre bad thing and stop developing on points, where could be a developing of an other was, maybe, yes i told maybe, a better way in the future.. but they tell ever and ever: "no, i want stay this way and whant stay still on this point" insteat to shut his mouth and let it easy enable to let developing in different ways ..
and this is "bäh i want noting else more learning" "i want stay dump and blocking others"

so, why please, not let enable to install prompt only system..

and i want not hear, because this is surely not wished.. STOP TO SPEAK FOR OTHER! 
Support this or support this not and hold you back and bullying it not (don't make it bad) .

regards
Blackcrack

**Comment by kkofler** [comment]
@blshkv:
> I'm second for this request. For example, a single `interactiveterminal` module requires the entire
> KDE to build.

This is a mostly unrelated issue to the feature request at hand, which is about installing a minimal package set, **not** about minimizing the dependencies of Calamares itself.

> Please make all modules optional if possible. An installer should not use X packages and should not
> require konsole to be present in the system.

All modules are already optional:
* They are optional at build time. You can just pass `-DSKIP_MODULES="interactiveterminal"` to compile Calamares without that module. To pass multiple ones, space-separate them, e.g. `-DSKIP_MODULES="interactiveterminal webview"`.
* They are also optional at runtime. All modules are plugins (individual `.so` files). The distribution can easily put modules with problematic dependencies into optional subpackages. In fact, that is exactly what I do with `interactiveterminal` and `webview` in Fedora. (My default configuration does not use those modules, and they both have heavy dependencies, so I do not install them by default. But they are available for derivatives that wish to use them.)

> First of all, this is too heavy, secondly, it glues it to KDE WM, i.e. a distro won't be able to use this
> installer if they provide multiple WM (which all major distros do).

This is also not true. The `interactiveterminal` module depends on a few KDE Frameworks, but not on the KDE Plasma desktop environment.

> You cannot call it "Distribution-independent installer framework" with such dependances.

The dependencies you complain about are already optional.

**Comment by adriaandegroot** [comment]
@kkofler Excellent explanation. I'm a bit torn about this specific issue now (this is meta-issue-discussion): the original request from @tsimonq2 is clear (and we've thought about using netinstall or something similar to make that work). This issue is now cluttered with a bunch of unrelated stuff, and I've got no "sense of procedure" whether to delete the unrelated things (including your excellent answer) or not.

An actually useful issue to report out of these unrelated-issues is "the interactiveterminal module doesn't make itself optional (like e.g. partition, or plasmalnf) when its dependencies are not met at compile time".

**Comment by adriaandegroot** [comment]
@tsimonq2 have you tried the "positive" direction, with netinstall to select packages that are installed from the Live CD?

**Comment by demmm** [comment]
This is implemented with packagechooser (and using the package module for doing the actual removal).

**Comment by abucodonosor** [comment]
How that was even an issue? Doing minimal or any kind of custom installations worked since the netinstall module exists. Yes, this one can be used ad frontend to package modules so you do a local install of 'whatever' with the Netinstall GUI.
