### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by potatogim** [calamares/calamares#985]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> …

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …

#### What do you expect to have happen when Calamares installs?

> …

#### Describe the issue you encountered

> …

#### Steps to reproduce the problem

> …

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> …

Hello, I want to translate calamares for Korean users :)

I did request in transifex and I'm waiting accept for it.

Could you check for that?

**Comment by adriaandegroot** [comment]
Thank you for proposing the Korean translation of Calamares. I was away from my regular development place for a week. I have now accepted the language on Transifex and made you the language coordinator.

The language has also been added to Calamares, but since the translation is at 0% right now, the language is not enabled. So you can't pick it from the user interface **yet**. Once some translations have started the language can be enabled in the interface and you may be able to "live test" the translation.

If you use Transifex's filters to pick strings, you can use the following *occurrence* values to pick strings that show up early in the application, so that it is easy to see if the language works:
 - *Welcome*
 - *Debug*
 - *Finished*

**Comment by adriaandegroot** [comment]
(I have added this "getting started" information to the Calamares wiki as well, thank you for making me write it)
