### ISSUE TITLE
No translation for Python Modules

### ISSUE THREAD

**Issue by NorcuxOS** [calamares/calamares#991]
When the installation is running and a python module with custom description is executed, the status text doesn't have a translation.

1. Start Installation
2. Wait until for example the unpackfs python module is executed
3. There is an english only status text

Expected beahviour:
There should be a translated text / you can translate it.

**Comment by adriaandegroot** [comment]
Most of the Python modules don't use translations at all -- generally because there is only one string to display. The *umount*, *packages* and *machineid* modules show how it can be done, although it doesn't look very nice. Basically it's a matter of doing the drudgework of enabling translations for all the other modules (followed by waiting for the translation teams to deal with it).

**Comment by adriaandegroot** [comment]
Modules and their translation status:
 - [ ] bootloader
 - [X] displaymanager
 - [ ] dracut
 - [X] dummypython
 - [X] dummypythonqt
 - [ ] fstab
 - [ ] grubcfg
 - [ ] hwclock
 - [ ] initcpio
 - [ ] initcpiocfg
 - [ ] initramfs
 - [ ] initramfscfg
 - [ ] localecfg
 - [ ] luksbootkeyfile
 - [ ] luksopenswaphookcfg
 - [X] machineid
 - [ ] mount
 - [ ] networkcfg
 - [ ] openrcdmcryptcfg
 - [X] packages
 - [X] plymouthcfg
 - [X] rawfs
 - [X] removeuser
 - [X] services-openrc
 - [X] services-systemd
 - [X] umount
 - [X] unpackfs
