### ISSUE TITLE
Deciding on openrc management

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#992]
The long discussions in pull requests #966 #974 #975 need to be wrapped up. I locked those discussions because they were getting unpleasant. I hope that, now we've had a week to cool off, we can make a decision one way or another.

So, to begin with, I'm going to state a few guiding principles I think we have for Calamares. They haven't been written down (in the developer's guide), but should be:
 1. Calamares **doesn't set policy**. It claims to be a universal installer framework; that means providing flexibility and configurability **and** allowing distro's to shoot themselves in the foot with a minicannon.
 2. I have some (limited) faith that distro's can and should solve their own problems when it comes to configuration. This is why I've been pushing for more documentation in the `module.desc` and `*.conf` files, so that responses along the lines of *RTFM* become more plausible (and/or *fix your packages*).

For the first point, we provide process modules, and *shellprocess* and *contextualprocess* modules for foot-shooting, not to mention all the different ways unsquash can mess up. Point 2 is a little more difficult; finding the balance between hand-holding and letting distro's figure it out themselves is tricky. I'm inclined to think that Calamares should be discoverable for new distro's, as well .. not just the "old guard" who has been around since the beginning (which, I should point out, does not include me).

So here are questions that need answering. Bear in mind, when answering, that I don't care one bit about openrc. I had runlevels 0, S and 3 in 1991 and that's good enough for me.

 - Does it ever make sense to have named runlevels in openrc?
 - Does it ever make sense to have named runlevels **that are not the default** in openrc?
 - Does it ever make sense to configure a single system with multiple named non-default runlevels?

Related, not openrc-specific:
 - Should services management be part of Calamares at all? That is, is this something that should be entirely managed by the package manager of the target system?

In general, features that support principle 1 (flexibility) and do not raise the support burden too much (interfering with 2), should IMO be upstream. I have answers to the questions above in mind, but I want to hear from the developers of openrc-based distro's in a civil fashion. If possible, include detailed use-cases and/or screenshots of what you already have.

**Comment by adriaandegroot** [comment]
There is a separate suggestion to improve naming of service-management modules, e.g. to rename *services* to *services-systemd* (and allow *services-sysvinit*, for instance).

**Comment by udeved** [comment]
First thing I find important, we should establish a naming schema for init related modules.
eg 

* servrices-systemd
* services-runit
* services-openrc

In terms of services, each module should only enable/disable a gives set of services, any extra stuff eg encrypting should be done in a distro specific module.

**Comment by abucodonosor** [comment]
Quote from V3n3RiX : 

If calamares intends to supply every distro developer with a minicannon in the name of flexibility...well, I'll just have to hope those won't backfire one day

This already happened at least once with plymouthcfg module, recently fixed in : https://github.com/calamares/calamares/commit/0ccca6902bb8a58203e2fd8b7b26225d8d1f8185

Renaming services modules per init makes sense, in the name of same flexibility, and to bring some uniformity. It will allow further modules to be developed in the future. So thumbs up on that one.

Named runlevels, aka custom runlevels are a bit tricky. @udeved patch will indeed allow creation of custom runlevels, but the story doesn't end there. OpenRC boots in default runlevel by default, and it won't boot in any other unless softlevel=runlevel is added to grub cmdline. Unless grubcfg is patched to detect those named runlevels and add the required grub parameters, they are pretty much useless. This means @udeved patch will at least need a rewrite to export those custom runlevels to globalstorage so grubcfg can find them. 

Of course, this may not be the desired implementation and one may say "Let's create them and leave user decide what runlevel boots post-installation. After all, all he must do is edit bootloader configuration file". To me this seems a bit weird, since custom runlevels are usually created by users for a very specific need. E.g. @nofirewall runlevel to boot without a firewall, or whatever. 

I won't even go about multiple custom runlevels, for the same reasons above.

In Redcore Linux we actually have a little need for a service module, our ISO scripts will do everything for us. I would however like to dump some code from our scripts if calamares will support such a module. So I will still support such a module. Our only **must have** module was openrcdmcryptcfg to be able to support encrypted installs.

Btw I've been working on openrcdmcryptcfg lately to export needsDmcrypt to globalstorage, and paired with my services-openrc module to add dmcrypt service to boot runlevel when needed. This can be of course expanded, or a new openrccfg module can be written to export various things to globalstorage, so other modules be it services-openrc or whatever will detect and use them when needed. Lately I discovered the true power of globalstorage. :D But I'm already offtopic, so I'll wrap it up in here.

**Comment by bill-auger** [comment]
i asked the parabola dev who has the most experience with openrc to give his opinion:

> I would go for #974, it keeps it simple and doesn't touch other runlevel than default, which is basically the only runlevel that a common user would use

**Comment by udeved** [comment]
Calamares is not configured by the user however, but by the distro devs.
As in the case of elogind or lvmetad, some distro may require a boot runlevel.

**Comment by abucodonosor** [comment]
> As in the case of elogind or lvmetad, some distro may require a boot runlevel.

While we can discuss LVM* once is in and add special case for it ( a simple exported gs value will do it .. ) , elogind is a Distribution packaging thing.

The only thing you may want to do with elogind ( and Distribution does not matter )
is not to enable but to disable it , say in a Server target. And even there I don't
thing someone want to do that.

**Comment by bill-auger** [comment]
i think his sentiment there was mainly the KISS and YAGNI principles - namely just do the simplest thing that works in 99% of the uses-cases and allow users to customize for extra-ordinary situations

in the context of calamares, the users are distro devs who are presumably quite capable of carrying a patch set if need be

again i have not read either of these implementations yet -  i am just looking at this from a distance i would ask:

* if implementation 'A' is merged, how difficult would it be to patch for the 'B' use-case
* if implementation 'B' is merged, how difficult would it be to patch for the 'A' use-case

blindly speaking, i would be inclined to favor with the one that requires the least delta to support the other
if that is really amounts to no more than a few LOC, then this discussion is a time-bandit

**Comment by udeved** [comment]
Simply speaking, I see absolutely no gain to hardcode a specific runlevel, to the contrary, and the way I implemented it, it simply does not matter since it is a variable read from conf, it is up to the distro devs to decide how the write the conf file. Simple as that.

But what is the pint merging a module, if consuming distros need to patch it? Waste of time in my view.

**Comment by kkofler** [comment]
@bill-auger: The implementation in #966 supports both use cases without patching. The implementation in #974 supports only the "normal" use case (default runlevel) without patching.

**Comment by bill-auger** [comment]
udeved - so you are saying that if your implementation were merged, and if someone wanted the "hard-coded" behavior, they would only need to put the word 'default' in a config file? that sounds to me like no patch would be required at all - surely, that is the purpose of a config file

if it is really that simple, i dont understand why there is any debate about it

**Comment by abucodonosor** [comment]
@bill-auger 

10-15LOC for #974 to kind support what @udev want and 2LOC in the configuration file.

#966 need more work anyway .. error handling and such..

OFC to support kind very custom boot run levels there is 'much' more work to be done.
However I don't see the real use of these other that: 'We do it while is possible some sort'


> in the context of calamares, those "users" are distro devs, who are presumably quite capable  ...

And assuming this is true , those devels should be capable to put a ISO together
or a base system that just works...

Also allowing this kind customization in this case is pure 'users' option and nothing
to do with devels at all. ( and that is true for systemd part also )

For devels only matters: enable or disable a service is impossible to handle in packaging.
The boot levels have to be already well defined in the Distro base system and the 
used init system does not matter here.

Also the other use case is to enable or disable services based on calamares
global storage values , however that is a per 'case usage' and should be hadled 
automatically. EG for things like LVM and RAID ( once implemented ) , CRYPT targets
for some etc.

**Comment by bill-auger** [comment]
ok then i withdraw the vote of my associate - if #966 supports both use cases without patching then that is clearly the superior choice IMHO - just do it and lets move on :)

**Comment by udeved** [comment]
Regarding the error handling, I see absolutely no point to catch errors, because there are none to catch.
rc-update is called in chroot, if a service does not exist in the chroot, rc-update will not be called. If the service exists, it will not fail when rc-update is called. The only thing I could add is logging the rc-update calls.
I just dislike that some seem to define themselves by negation, just because.

**Comment by abucodonosor** [comment]
OMG .. :joy: :joy: :joy:

OK.. 

So we push the implementation of enabling or disabling everything 
with an argument that ' some distros may need to touch services
in boot/critical levels' and then 'not even adding error handling for that?'

Not even making those manadory of any sort , silent fail and possible break
the boot ?

Also note your implementation is by far not done even without error handling.
While someone now may replace boot level with my-boot level how is that
meant to work without grub / systemd-boot knows about it ?

Anyway I'm out of that.. People seems to forget Calamares is an Installer ..

**Comment by kkofler** [comment]
@abucodonosor:
> Also allowing this kind customization in this case is pure 'users' option and nothing
> to do with devels at all. ( and that is true for systemd part also )

`services` as it stands and both the proposed implementations for OpenRC are clearly **not** suitable as end user configuration modules. To be usable as an end user module, a user interface is needed. End users are not going to edit module `.conf` files. If they are going that far, they may as well just run `systemctl` resp. `rc-update` directly after the installation and not bother with configuring Calamares at all.

**Comment by abucodonosor** [comment]
@kkofler 
 
.. ofc not. However there is no real use case for allowing that.. Not for users
nor for developers.

Please show me an real use case of that.
 
Since you are an systemd guy , where 'enabling' / 'disabling' of such targets is
done in systemd ? Calamares or your packaging?

Also if we allo that we need allow that to systemd one too since 'disable' targets is not
yet allowed..

**Comment by abucodonosor** [comment]
@adriaandegroot 

as for #975 , if you or someone want to implemet that ( well it is already just some defaults and log messages need changing ) feel free.. If not just close it.

I'm not going to change anything in that PR bc I think it should not exists in calamares.

**Comment by udeved** [comment]
>Also if we allow that we need allow that to systemd one too since 'disable' targets is not
yet allowed..

Take at least a look at the [systemd module](https://github.com/calamares/calamares/blob/master/src/modules/services/services.conf). This statement is simply wrong, untrue.

It is also not the business of redcore to enforce how distros package their stuff. As previously said, arch linux discourage from enabling services with the package. Not every package you install has to necessarily enable a service.

**Comment by udeved** [comment]
To put these false claims to rest that have been made in the other discussion.
Here is our openrccfg conf file.

```
---
services:
    add:
      - name: acpid
        runlevel: default
      - name: bluetooth
        runlevel: default
      - name: cronie
        runlevel: default
      - name: cupsd
        runlevel: default
      - name: syslog-ng
        runlevel: default
      - name: NetworkManager
        runlevel: default
      - name: xdm
        runlevel: default

```

A use case of different runlevels is actually our netstrap module, which does not unpack the squash image, but pacstraps from online repo.

**Comment by bill-auger** [comment]
> A use case of different runlevels is actually our netstrap module, which does not unpack the squash image, but pacstraps from online repo.

that's also what i do for the current systemd installer - but i honestly dont know how that related to openrc runlevels - if #966 is somehow critical to that use-case then i will be using that implementation whether it is merged into calamres or not

i guess it's time to do some homework :)

**Comment by udeved** [comment]
@bill-auger 

#996 simply allows the distro devs to set whatever runlevel they chose for a given service via the conf file. The module does not enforce any runlevel, it has variables that get initialized from conf file like the one posted. ;)

**Comment by abucodonosor** [comment]
> Take at least a look at the systemd module. This statement is simply wrong, untrue.

So you can disable sysinit and basic target in systemd modules ?
Where can you do that ? 'enable' yes but not disable.

And that is what I recomnaded you already. Alow enable but disable of these.

> It is also not the business of redcore to enforce how distros package their stuff.

No one enforce you do do anything. Thats your problem. Our is to not take your
strage things just beacuse you want so..

> A use case of different runlevels is actually our netstrap module, which does not unpack the squash image, but pacstraps from online repo. It is pacman specific.

.. exactly .. Distribution problem..

> As previously said, arch linux discourage from enabling services with the package. Not every package you install has to necessarily enable a service.

.. again Distribution one .. And what do you have to do with ArchLinux ?
You maintain a different one , right ? 

Also from your confgiuration if you need just that #974  will work just fine.

'So what is the use case for allowing everything then ?'

**Comment by udeved** [comment]
Archlinux is our upstream distro, similar to what debian is for ubuntu, and the rest is not your business.
I would urge you to look at the systemd module, you will find it supports disabling systemd targets.
Frankly, I am done with you going around in circles, and I have no time to waste. I consider what you do a kind of trolling.

**Comment by abucodonosor** [comment]
The opposite .. I'm done with you :joy: 

However is funny to see how f..... s....  you are..

>I would urge you to look at the systemd module, you will find it supports disabling systemd targets.

```
    # enable targets
    for tgt in targets:
        ec = libcalamares.utils.target_env_call(
            ['systemctl', 'enable', '{}.target'.format(tgt['name'])]
            )

        if ec != 0:
            if tgt['mandatory']:
                return ("Cannot enable systemd target {}".format(tgt['name']),
                        "systemctl enable call in chroot returned error code"
                        "{}".format(ec)
                        )
            else:
                libcalamares.utils.debug(
                    "Cannot enable systemd target {}".format(tgt['name'])
                    )
                libcalamares.utils.debug(
                    "systemctl enable call in chroot returned error code "
                    "{}".format(ec)
                    )
```
Pull out your glasses .. Only 'enable' exists for targets ... Also learn to read code..

I get the idea now why you just copy and paste the same code for everything.

**Comment by kkofler** [comment]
Please stop the personal attacks **immediately**!

So, in the `services` module, `disable` exists for services, but is missing for targets. I do not see how this is related to the discussion on whether to allow modifying non-default runlevels for OpenRC.

**Comment by udeved** [comment]
I think there is not gonna be a solution to this, I will just keep patching in modules.
I still do not see one sane reason to hardcode runlevels, instead of letting distro devs decide.
It is also unproductive to constantly claim packaging issues on other distros.

**Comment by bill-auger** [comment]
the last thing i will add here is that the beauty of modules is that they are modular - calamres already contains mutually exclusive or redundant modules such as mkinicpio and initramfs - yes ? - and there are multiple options for sub-classing new modules either in C or python - yes ? so its all good :) - there need not be any conflict

practically speaking, both of these openrc modules could co-exist in the same codebase to be chosen by the distro - they would be redundant but not problematic - conversely, neither of them needs to exist in the upstream calamares codebase in order to be useful - they only need to be available somewhere and freely licensed - perhaps the calamares website could have a section to link to third-party modules - maybe udeved and i could both put our pacstrap modules there - maybe we could merge them -  maybe everyone could be satisfied without any arguments over which workflow to officially endorse or enforce

cant we all just get along lol

**Comment by bill-auger** [comment]
yes - everything in parabola is freely licensed and public - i have a mirror on github also

it is implemented as a core class that modules can sub-class from for multiple pacstrap stages - its also a bit coupled to the JobQueue class because i implemented a fine-grained progress-bar pump for the long running pacstrap procedure

https://github.com/bill-auger/calamares/blob/parabola/src/libcalamares/PacstrapCppJob.cpp
https://github.com/bill-auger/calamares/blob/parabola/src/modules/pacstrap-base/pacstrap-base.cpp

**Comment by udeved** [comment]
Sounds and looks good. Our module is a python module, and it has problems with the fine grained progressbar, ie problem with UI. Its far from perfect and may not work any longer as soon as pacman defaults to the new --sysroot arg.

**Comment by kkofler** [comment]
I would rather not have 2 modules in Calamares where one has a subset of the other's functionality. I don't see why we cannot just have the most flexible implementation. Nobody is forcing anybody to use non-default runlevels, even if the implementation supports them.

**Comment by adriaandegroot** [comment]
There is now one module merged into master.

In the spirit of compromise, which leaves everyone unhappy, the final implementation is this:

 - follows @v3nerix 's suggestion to copy the systemd configuration with separate *services* and *disable* keys (ignoring the other ones available to systemd)
 - follows @udeved 's suggestion to **allow** setting the runlevel; as others have pointed out, that is probably useless on its own, but that's for the distro to decide (and contribute useful patches when using that feature, later)
 - is flexible in how a service is specified: a runlevel is not required; if it isn't named, then "default" is used. you can also use just a name, then runlevel "default" is also assumed
 - allows to use the key *mandatory* for actual error checking (like the systemd one uses)

So you can write a simple list of names for the default case with no error checking (just warnings if things fail), a list of *name* and *mandatory* keys to enjoy error checking, or a list with *name*, *runlevel* for the no-eror-checking-multiple-runlevels case.

I believe this covers all of the use-cases discussed, and encourages the use of the simple configurations (default runlevel) while allowing the minicannon to be aimed at the foot as well.

(And I wrote more extensive documentation for the module, too)
