### ISSUE TITLE
Boost.Python error in job "machineid"

### ISSUE THREAD

**Issue by agaida** [calamares/calamares#994]
**Describe the bug**
Build a new image, debian/sid with latest kpmcore and calamares-git - installation went fine until
```
02:40:11 [6]: Job description from pretty_name "machineid" = "Generiere Computer-ID" 
02:40:11 [6]: Python Error:
 <class 'KeyError'> 
 ('systemd',) 
 File "/usr/lib/x86_64-linux-gnu/calamares/modules/machineid/main.py", line 45, in run
    enable_systemd = libcalamares.job.configuration["systemd"] 
```

**To Reproduce**
1. Get the iso: http://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201806300024.iso
2. Start calamares
3. Try to install

**Expected behavior**
There should be no KeyError

**Comment by agaida** [comment]
I really don't get it right now - the machine-id code wasn't changed lately - so i guess it's in libcalamares. Will try to debug later.

**Comment by adriaandegroot** [comment]
Which Calamares version? What does your config file look like?

**Comment by agaida** [comment]
Hmm - kind of "solved" - running python transition in debian: https://release.debian.org/transitions/html/python3.7.html

**Comment by erikdubois** [comment]
I had this one too - for future reference.
I have changed a lot and maybe it is not the how I solved it but
at some point I added this line to the pkgbuild

`sed -i -e 's/"Install configuration files" OFF/"Install configuration files" ON/' "$srcdir/${_pkgname}-${pkgver}/CMakeLists.txt"`

and calamares installed fine

**Comment by kkofler** [comment]
Well, you definitely need **some** configuration files or Calamares will not work. But the thing is, the defaults are not necessarily correct for your distribution, which is why this flag defaults to OFF. You are supposed to either install your own config files, or patch the default ones and enable this flag (either in the same patch that tweaks your config file defaults, or with `-DINSTALL_CONFIG:BOOL=ON` on the CMake command line – using `sed` is a hack, especially because you match the user description and not the actual name `INSTALL_CONFIG` of the flag).

**Comment by philmmanjaro** [comment]
Default configs are mostly configured for **Manjaro** as most of the original code was from us.

**Comment by erikdubois** [comment]
I have looked in the code and in the website and general google but where can we find a setting like 

> -DINSTALL_CONFIG:BOOL=ON

  and what other settings are there that I am missing now.
Is there a page that lines them all up?

**Comment by kkofler** [comment]
`cmake -LH`

**Comment by erikdubois** [comment]
thanks

**Comment by adriaandegroot** [comment]
Hm, I didn't know about `cmake -LH`. I was going to say, though, that the top-level `CMakeLists.txt` starts with some documentation, then a clearly-labeled section of *OPTIONS* and then a section of *USE_* things (with documentation on how they work). That's not exactly the level of having them documented in the developer or deployer's guides, though -- I'd welcome some PRs there, really.

The release notes for [Calamares 3.2.2](https://calamares.io/calamares-3.2.2-is-out/) though, point out that the option changed and why it changed. Although the defaults are **often** OK for Manjaro, there's no guarantee that they will remain so, or that they are suitable for a default installation of anything. That's why distributions are strongly encouraged to package calamares settings **separately** (or inject them into the ISO image, or whatever).
