### ISSUE TITLE
Feature Request: A Flatpak Installer for Calamares

### ISSUE THREAD

**Issue by subhaniminhas** [calamares/calamares#999]
Installing Calamares in Debain Stretch is not easy, almost impossible, as it requires adding a line to your */etc/apt/sources.list* like this: 
deb http://ftp.de.debian.org/debian sid main
after that you can install it using 
**aptitude install calamares-settings-debian calamares-settings calamares**
aptitude automatically installs and removes packages but end of the day, the system is broken as sid packages replace the stable once and every thing goes unstable. 
I resolved the broken issues using these commands:
**sudo apt-get update --fix-missing**
**sudo dpkg --configure -a**
**sudo apt-get install -f**
If there was a **Flatpak** version of Calamares, its availability would have been much easier. 
I am ready to help if pointed to the right direction.

**Comment by adriaandegroot** [comment]
- Information about flatpak is at https://flatpak.org/
 - Sources for Calamares are at https://github.com/calamares/calamares

I'm not sure what else you're asking for? In any case, why are you trying to install Calamares from packages anyway? If you're a distro, you should package it yourself in the form that you need it; the `deploycala.py` script can help with that. The *Siduction* distro probably has packages, which might be useful for you.

**Comment by abucodonosor** [comment]
Uff.. these again.. 

No,  a flatpak or everything the like, is plain stupid for any system installer
which has to operate from / within the OS and not from within an *isolated container!*

Even someone provides an flatpak calamares won't work right ?

**Comment by adriaandegroot** [comment]
I talked with a knowledgeable Flatpak person this afternoon. Primarily, it's unclear if the sandboxing of a Flatpak would allow the pack to do anything useful. It depends on how available chroot, sudo, mount .. are in the container, and whether /dev is mounted in a way that allows manipulation of disk devices. I may put some time into sorting that out (whether it could possibly work, or not).

It's been suggested that snap or AppImage might be a better fit, because their sandboxing is different (or allows the container to be less-sandboxed). Again, I haven't actually looked at it.

Personally I'm not very interested in figuring this stuff out -- **if** someone creates a flatpak, perferably with either CMake integration or a script in `ci/`, (or some other containerized format, I don't care) then I'd be willing to merge and maintain it. But I don't see it happening from my side.

**Comment by agaida** [comment]
My guess is that an appimage as a kind of black box should do fine - or some kind of a portable container - should have access to the settings and needed files, to the host, when needed and to the target system - and thats it. But right now i don't have the ressources to dig deeper into it. A plus might be that there should be a way to convert the travis builds into an appimage :sunglasses:

**Comment by subhaniminhas** [comment]
I am really grateful to core contributers for so many quick and relevant replies. I will try them in my humble capacity and limited knowledge and report result once i reach somewhere. Again Thanks.
